// Generated declarative data. Review v2/policy.json and project.zeno.
// Regenerate/check with tools/check_template_contracts_v2.py; no runtime mapper.
extern crate alloc;
use alloc::{vec, vec::Vec};
use zeno_fcis_synthesis::finite::{Domain as ScalarDomain, Op, V2ScalarProgram};
use zeno_fcis_synthesis::finite::{
    V2InputField as InputField, V2InputLeaf as InputLeaf, V2InputVariant as InputVariant,
    V2Resource as Resource, canonical_v2::schema as s, v2_authority as authority,
    v2_catalog as catalog, v2_composition as c, v2_laws as l, v2_zero_limits,
};
/// Exact actual original schema bytes.
pub const ORIGINAL_SCHEMA: &[u8] = include_bytes!("../v2/schema.zcve");
/// Complete reviewed library-encoded policy.
pub const ORIGINAL_POLICY: &[u8] = include_bytes!("../v2/policy.zcve");
/// Complete original named schema description.
pub const DESCRIPTION: s::Description<'static> = s::Description {
    profile: b"order_fulfillment",
    version: 1,
    root: 100,
    definitions: &[
        s::Definition {
            id: 100,
            name: b"Order",
            kind: s::Kind::Record(&[
                s::Field {
                    id: 120,
                    name: b"status",
                    type_id: 105,
                },
                s::Field {
                    id: 121,
                    name: b"payment_attempts",
                    type_id: 106,
                },
            ]),
        },
        s::Definition {
            id: 101,
            name: b"OrderCommand",
            kind: s::Kind::Record(&[
                s::Field {
                    id: 125,
                    name: b"action",
                    type_id: 111,
                },
                s::Field {
                    id: 126,
                    name: b"callback_attempt",
                    type_id: 106,
                },
            ]),
        },
        s::Definition {
            id: 102,
            name: b"CallerContext",
            kind: s::Kind::Record(&[s::Field {
                id: 130,
                name: b"caller",
                type_id: 107,
            }]),
        },
        s::Definition {
            id: 103,
            name: b"PaymentDestination",
            kind: s::Kind::Text { min: 1, max: 32 },
        },
        s::Definition {
            id: 104,
            name: b"PaymentRequest",
            kind: s::Kind::Record(&[
                s::Field {
                    id: 140,
                    name: b"request_attempt",
                    type_id: 106,
                },
                s::Field {
                    id: 141,
                    name: b"request_action",
                    type_id: 108,
                },
            ]),
        },
        s::Definition {
            id: 105,
            name: b"OrderStatus",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 160,
                    name: b"Placed",
                },
                s::Variant {
                    id: 161,
                    name: b"AwaitingPayment",
                },
                s::Variant {
                    id: 162,
                    name: b"Paid",
                },
                s::Variant {
                    id: 163,
                    name: b"Shipped",
                },
                s::Variant {
                    id: 164,
                    name: b"Delivered",
                },
                s::Variant {
                    id: 165,
                    name: b"Cancelled",
                },
            ]),
        },
        s::Definition {
            id: 106,
            name: b"Attempts",
            kind: s::Kind::I128 { min: 0, max: 3 },
        },
        s::Definition {
            id: 107,
            name: b"Caller",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 170,
                    name: b"Customer",
                },
                s::Variant {
                    id: 171,
                    name: b"PaymentProvider",
                },
                s::Variant {
                    id: 172,
                    name: b"Carrier",
                },
            ]),
        },
        s::Definition {
            id: 108,
            name: b"PaymentAction",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 175,
                    name: b"Capture",
                },
                s::Variant {
                    id: 176,
                    name: b"Void",
                },
            ]),
        },
        s::Definition {
            id: 109,
            name: b"CarrierDestination",
            kind: s::Kind::Text { min: 1, max: 32 },
        },
        s::Definition {
            id: 110,
            name: b"ShippingRequest",
            kind: s::Kind::Record(&[s::Field {
                id: 145,
                name: b"paid_attempt",
                type_id: 106,
            }]),
        },
        s::Definition {
            id: 111,
            name: b"OrderAction",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 150,
                    name: b"Checkout",
                },
                s::Variant {
                    id: 151,
                    name: b"PaymentCaptured",
                },
                s::Variant {
                    id: 152,
                    name: b"PaymentDeclined",
                },
                s::Variant {
                    id: 153,
                    name: b"ParcelDispatched",
                },
                s::Variant {
                    id: 154,
                    name: b"ParcelDelivered",
                },
                s::Variant {
                    id: 155,
                    name: b"CancelOrder",
                },
            ]),
        },
    ],
};
/// Original root and schema commitments and complete wire-size limits.
pub const FRAMING: c::Framing = c::Framing {
    state: c::FrameBinding {
        root: 100,
        schema: [
            71, 100, 173, 153, 254, 28, 59, 63, 63, 67, 27, 75, 153, 123, 86, 112, 14, 55, 249,
            202, 88, 238, 188, 110, 4, 29, 102, 156, 147, 161, 181, 105,
        ],
        max_bytes: 82,
    },
    command: c::FrameBinding {
        root: 101,
        schema: [
            71, 100, 173, 153, 254, 28, 59, 63, 63, 67, 27, 75, 153, 123, 86, 112, 14, 55, 249,
            202, 88, 238, 188, 110, 4, 29, 102, 156, 147, 161, 181, 105,
        ],
        max_bytes: 82,
    },
    context: c::FrameBinding {
        root: 102,
        schema: [
            71, 100, 173, 153, 254, 28, 59, 63, 63, 67, 27, 75, 153, 123, 86, 112, 14, 55, 249,
            202, 88, 238, 188, 110, 4, 29, 102, 156, 147, 161, 181, 105,
        ],
        max_bytes: 63,
    },
};
/// Exact channel to original destination and payload type links.
pub const CHANNEL_ROOTS: &[(u32, u32, u32)] = &[(300, 103, 104), (301, 109, 110)];
/// Complete ordered decisions selected only by actual graph output.
pub const BRANCHES: &[c::Branch<'static>] = &[
    c::Branch {
        code: 0,
        class: c::Class::Reject,
        reason: Some(200),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 1,
        class: c::Class::Reject,
        reason: Some(201),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 2,
        class: c::Class::Reject,
        reason: Some(202),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 3,
        class: c::Class::Reject,
        reason: Some(203),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 4,
        class: c::Class::Accept,
        reason: None,
        assignments: &[
            c::Assignment {
                field: 120,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 105,
                    variant: 161,
                }),
                domain: c::Domain::Sum {
                    type_id: 105,
                    variants: &[160, 161, 162, 163, 164, 165],
                },
            },
            c::Assignment {
                field: 121,
                value: c::Expr::Output(1),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 300,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"payment-provider")),
            payload: &[
                c::PayloadField {
                    field: 140,
                    value: c::Expr::Output(1),
                },
                c::PayloadField {
                    field: 141,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 108,
                        variant: 175,
                    }),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 5,
        class: c::Class::Accept,
        reason: None,
        assignments: &[
            c::Assignment {
                field: 120,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 105,
                    variant: 162,
                }),
                domain: c::Domain::Sum {
                    type_id: 105,
                    variants: &[160, 161, 162, 163, 164, 165],
                },
            },
            c::Assignment {
                field: 121,
                value: c::Expr::Input(c::Source::State, 121),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 301,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"carrier")),
            payload: &[c::PayloadField {
                field: 145,
                value: c::Expr::Input(c::Source::State, 121),
            }],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 6,
        class: c::Class::CommittedFailure,
        reason: Some(204),
        assignments: &[
            c::Assignment {
                field: 120,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 105,
                    variant: 160,
                }),
                domain: c::Domain::Sum {
                    type_id: 105,
                    variants: &[160, 161, 162, 163, 164, 165],
                },
            },
            c::Assignment {
                field: 121,
                value: c::Expr::Input(c::Source::State, 121),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 7,
        class: c::Class::Accept,
        reason: None,
        assignments: &[
            c::Assignment {
                field: 120,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 105,
                    variant: 163,
                }),
                domain: c::Domain::Sum {
                    type_id: 105,
                    variants: &[160, 161, 162, 163, 164, 165],
                },
            },
            c::Assignment {
                field: 121,
                value: c::Expr::Input(c::Source::State, 121),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 8,
        class: c::Class::Accept,
        reason: None,
        assignments: &[
            c::Assignment {
                field: 120,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 105,
                    variant: 164,
                }),
                domain: c::Domain::Sum {
                    type_id: 105,
                    variants: &[160, 161, 162, 163, 164, 165],
                },
            },
            c::Assignment {
                field: 121,
                value: c::Expr::Input(c::Source::State, 121),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 9,
        class: c::Class::Accept,
        reason: None,
        assignments: &[
            c::Assignment {
                field: 120,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 105,
                    variant: 165,
                }),
                domain: c::Domain::Sum {
                    type_id: 105,
                    variants: &[160, 161, 162, 163, 164, 165],
                },
            },
            c::Assignment {
                field: 121,
                value: c::Expr::Input(c::Source::State, 121),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 10,
        class: c::Class::Accept,
        reason: None,
        assignments: &[
            c::Assignment {
                field: 120,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 105,
                    variant: 165,
                }),
                domain: c::Domain::Sum {
                    type_id: 105,
                    variants: &[160, 161, 162, 163, 164, 165],
                },
            },
            c::Assignment {
                field: 121,
                value: c::Expr::Input(c::Source::State, 121),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 300,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"payment-provider")),
            payload: &[
                c::PayloadField {
                    field: 140,
                    value: c::Expr::Input(c::Source::State, 121),
                },
                c::PayloadField {
                    field: 141,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 108,
                        variant: 176,
                    }),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
];
const LAW_500: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Post(120)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(161)),
    l::Op::Eq(1, 2),
    l::Op::Literal(l::Atom::I128(162)),
    l::Op::Eq(1, 4),
    l::Op::Not(3),
    l::Op::Not(5),
    l::Op::And(6, 7),
    l::Op::Not(8),
    l::Op::Literal(l::Atom::I128(163)),
    l::Op::Eq(1, 10),
    l::Op::Not(9),
    l::Op::Not(11),
    l::Op::And(12, 13),
    l::Op::Not(14),
    l::Op::Literal(l::Atom::I128(164)),
    l::Op::Eq(1, 16),
    l::Op::Not(15),
    l::Op::Not(17),
    l::Op::And(18, 19),
    l::Op::Not(20),
    l::Op::Observe(l::Observation::Post(121)),
    l::Op::ToI128(22),
    l::Op::Literal(l::Atom::I128(1)),
    l::Op::Lt(23, 24),
    l::Op::Not(25),
    l::Op::Not(21),
    l::Op::Not(27),
    l::Op::Not(26),
    l::Op::And(28, 29),
    l::Op::Not(30),
];
const LAW_501: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(125)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(152)),
    l::Op::Eq(1, 2),
    l::Op::Not(3),
    l::Op::Literal(l::Atom::I128(150)),
    l::Op::Eq(1, 5),
    l::Op::Observe(l::Observation::Context(130)),
    l::Op::ToI128(7),
    l::Op::Literal(l::Atom::I128(170)),
    l::Op::Eq(8, 9),
    l::Op::Observe(l::Observation::Pre(120)),
    l::Op::ToI128(11),
    l::Op::Literal(l::Atom::I128(160)),
    l::Op::Eq(12, 13),
    l::Op::And(10, 14),
    l::Op::Observe(l::Observation::Pre(121)),
    l::Op::ToI128(16),
    l::Op::Literal(l::Atom::I128(3)),
    l::Op::Lt(17, 18),
    l::Op::And(15, 19),
    l::Op::Observe(l::Observation::Post(120)),
    l::Op::ToI128(21),
    l::Op::Literal(l::Atom::I128(161)),
    l::Op::Eq(22, 23),
    l::Op::And(20, 24),
    l::Op::Observe(l::Observation::Post(121)),
    l::Op::ToI128(26),
    l::Op::Literal(l::Atom::I128(1)),
    l::Op::Add(17, 28),
    l::Op::Eq(27, 29),
    l::Op::And(25, 30),
    l::Op::Not(6),
    l::Op::Not(32),
    l::Op::Not(31),
    l::Op::And(33, 34),
    l::Op::Not(35),
    l::Op::And(4, 36),
];
const LAW_502: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(125)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(151)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Context(130)),
    l::Op::ToI128(4),
    l::Op::Literal(l::Atom::I128(171)),
    l::Op::Eq(5, 6),
    l::Op::Observe(l::Observation::Pre(120)),
    l::Op::ToI128(8),
    l::Op::Literal(l::Atom::I128(161)),
    l::Op::Eq(9, 10),
    l::Op::And(7, 11),
    l::Op::Observe(l::Observation::Command(126)),
    l::Op::ToI128(13),
    l::Op::Observe(l::Observation::Pre(121)),
    l::Op::ToI128(15),
    l::Op::Eq(14, 16),
    l::Op::And(12, 17),
    l::Op::Observe(l::Observation::Post(120)),
    l::Op::ToI128(19),
    l::Op::Literal(l::Atom::I128(162)),
    l::Op::Eq(20, 21),
    l::Op::And(18, 22),
    l::Op::Observe(l::Observation::Post(121)),
    l::Op::ToI128(24),
    l::Op::Eq(25, 16),
    l::Op::And(23, 26),
    l::Op::Not(3),
    l::Op::Not(28),
    l::Op::Not(27),
    l::Op::And(29, 30),
    l::Op::Not(31),
];
const LAW_503: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(125)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(153)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Context(130)),
    l::Op::ToI128(4),
    l::Op::Literal(l::Atom::I128(172)),
    l::Op::Eq(5, 6),
    l::Op::Observe(l::Observation::Pre(120)),
    l::Op::ToI128(8),
    l::Op::Literal(l::Atom::I128(162)),
    l::Op::Eq(9, 10),
    l::Op::And(7, 11),
    l::Op::Observe(l::Observation::Post(120)),
    l::Op::ToI128(13),
    l::Op::Literal(l::Atom::I128(163)),
    l::Op::Eq(14, 15),
    l::Op::And(12, 16),
    l::Op::Observe(l::Observation::Post(121)),
    l::Op::ToI128(18),
    l::Op::Observe(l::Observation::Pre(121)),
    l::Op::ToI128(20),
    l::Op::Eq(19, 21),
    l::Op::And(17, 22),
    l::Op::Not(3),
    l::Op::Not(24),
    l::Op::Not(23),
    l::Op::And(25, 26),
    l::Op::Not(27),
];
const LAW_504: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(125)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(154)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Context(130)),
    l::Op::ToI128(4),
    l::Op::Literal(l::Atom::I128(172)),
    l::Op::Eq(5, 6),
    l::Op::Observe(l::Observation::Pre(120)),
    l::Op::ToI128(8),
    l::Op::Literal(l::Atom::I128(163)),
    l::Op::Eq(9, 10),
    l::Op::And(7, 11),
    l::Op::Observe(l::Observation::Post(120)),
    l::Op::ToI128(13),
    l::Op::Literal(l::Atom::I128(164)),
    l::Op::Eq(14, 15),
    l::Op::And(12, 16),
    l::Op::Observe(l::Observation::Post(121)),
    l::Op::ToI128(18),
    l::Op::Observe(l::Observation::Pre(121)),
    l::Op::ToI128(20),
    l::Op::Eq(19, 21),
    l::Op::And(17, 22),
    l::Op::Not(3),
    l::Op::Not(24),
    l::Op::Not(23),
    l::Op::And(25, 26),
    l::Op::Not(27),
];
const LAW_505: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(125)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(155)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Context(130)),
    l::Op::ToI128(4),
    l::Op::Literal(l::Atom::I128(170)),
    l::Op::Eq(5, 6),
    l::Op::Observe(l::Observation::Pre(120)),
    l::Op::ToI128(8),
    l::Op::Literal(l::Atom::I128(160)),
    l::Op::Eq(9, 10),
    l::Op::Literal(l::Atom::I128(161)),
    l::Op::Eq(9, 12),
    l::Op::Not(11),
    l::Op::Not(13),
    l::Op::And(14, 15),
    l::Op::Not(16),
    l::Op::And(7, 17),
    l::Op::Observe(l::Observation::Post(120)),
    l::Op::ToI128(19),
    l::Op::Literal(l::Atom::I128(165)),
    l::Op::Eq(20, 21),
    l::Op::And(18, 22),
    l::Op::Observe(l::Observation::Post(121)),
    l::Op::ToI128(24),
    l::Op::Observe(l::Observation::Pre(121)),
    l::Op::ToI128(26),
    l::Op::Eq(25, 27),
    l::Op::And(23, 28),
    l::Op::Not(3),
    l::Op::Not(30),
    l::Op::Not(29),
    l::Op::And(31, 32),
    l::Op::Not(33),
];
const LAW_506: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(125)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(152)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Context(130)),
    l::Op::ToI128(4),
    l::Op::Literal(l::Atom::I128(171)),
    l::Op::Eq(5, 6),
    l::Op::And(3, 7),
    l::Op::Observe(l::Observation::Pre(120)),
    l::Op::ToI128(9),
    l::Op::Literal(l::Atom::I128(161)),
    l::Op::Eq(10, 11),
    l::Op::And(8, 12),
    l::Op::Observe(l::Observation::Command(126)),
    l::Op::ToI128(14),
    l::Op::Observe(l::Observation::Pre(121)),
    l::Op::ToI128(16),
    l::Op::Eq(15, 17),
    l::Op::And(13, 18),
    l::Op::Observe(l::Observation::Post(120)),
    l::Op::ToI128(20),
    l::Op::Literal(l::Atom::I128(160)),
    l::Op::Eq(21, 22),
    l::Op::And(19, 23),
    l::Op::Observe(l::Observation::Post(121)),
    l::Op::ToI128(25),
    l::Op::Eq(26, 17),
    l::Op::And(24, 27),
];
const LAW_909: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::PostLength),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::PatchLength),
    l::Op::ToI128(4),
    l::Op::Eq(5, 2),
    l::Op::Observe(l::Observation::EffectLength),
    l::Op::ToI128(7),
    l::Op::Eq(8, 2),
    l::Op::Observe(l::Observation::OutboxLength),
    l::Op::ToI128(10),
    l::Op::Eq(11, 2),
    l::Op::Literal(l::Atom::Bool(true)),
    l::Op::And(13, 3),
    l::Op::And(14, 6),
    l::Op::And(15, 9),
    l::Op::And(16, 12),
];
const LAW_990: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Initial(120)),
    l::Op::Literal(l::Atom::Sum {
        type_id: 105,
        variant: 160,
    }),
    l::Op::Eq(0, 1),
    l::Op::Observe(l::Observation::Initial(121)),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(3, 4),
    l::Op::Literal(l::Atom::Bool(true)),
    l::Op::And(6, 2),
    l::Op::And(7, 5),
];
const LAW_991: &[l::Op<'static>] = &[
    l::Op::Literal(l::Atom::Bool(true)),
    l::Op::Observe(l::Observation::Context(130)),
    l::Op::ToI128(1),
    l::Op::Observe(l::Observation::Command(125)),
    l::Op::ToI128(3),
    l::Op::Literal(l::Atom::I128(150)),
    l::Op::Eq(4, 5),
    l::Op::Literal(l::Atom::I128(155)),
    l::Op::Eq(4, 7),
    l::Op::Not(6),
    l::Op::Not(8),
    l::Op::And(9, 10),
    l::Op::Not(11),
    l::Op::Literal(l::Atom::I128(170)),
    l::Op::Literal(l::Atom::I128(151)),
    l::Op::Eq(4, 14),
    l::Op::Literal(l::Atom::I128(152)),
    l::Op::Eq(4, 16),
    l::Op::Not(15),
    l::Op::Not(17),
    l::Op::And(18, 19),
    l::Op::Not(20),
    l::Op::Literal(l::Atom::I128(171)),
    l::Op::Literal(l::Atom::I128(172)),
    l::Op::Select(21, 22, 23),
    l::Op::Select(12, 13, 24),
    l::Op::Eq(2, 25),
    l::Op::Not(26),
    l::Op::And(0, 27),
    l::Op::Not(27),
    l::Op::And(0, 29),
    l::Op::Observe(l::Observation::Class),
    l::Op::ToI128(31),
    l::Op::Literal(l::Atom::I128(1)),
    l::Op::Eq(32, 33),
    l::Op::Observe(l::Observation::HasReason),
    l::Op::ObserveWhen(28, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(36),
    l::Op::Literal(l::Atom::I128(200)),
    l::Op::Eq(37, 38),
    l::Op::Observe(l::Observation::EffectLength),
    l::Op::ToI128(40),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(41, 42),
    l::Op::Observe(l::Observation::OutboxLength),
    l::Op::ToI128(44),
    l::Op::Eq(45, 42),
    l::Op::Observe(l::Observation::PostLength),
    l::Op::ToI128(47),
    l::Op::Eq(48, 42),
    l::Op::And(0, 34),
    l::Op::And(50, 35),
    l::Op::And(51, 39),
    l::Op::And(52, 43),
    l::Op::And(53, 46),
    l::Op::And(54, 49),
    l::Op::Select(28, 55, 0),
    l::Op::Observe(l::Observation::Pre(120)),
    l::Op::ToI128(57),
    l::Op::Literal(l::Atom::I128(160)),
    l::Op::Eq(58, 59),
    l::Op::And(6, 60),
    l::Op::Literal(l::Atom::I128(161)),
    l::Op::Eq(58, 62),
    l::Op::And(21, 63),
    l::Op::Not(61),
    l::Op::Not(64),
    l::Op::And(65, 66),
    l::Op::Not(67),
    l::Op::Literal(l::Atom::I128(153)),
    l::Op::Eq(4, 69),
    l::Op::Literal(l::Atom::I128(162)),
    l::Op::Eq(58, 71),
    l::Op::And(70, 72),
    l::Op::Not(68),
    l::Op::Not(73),
    l::Op::And(74, 75),
    l::Op::Not(76),
    l::Op::Literal(l::Atom::I128(154)),
    l::Op::Eq(4, 78),
    l::Op::Literal(l::Atom::I128(163)),
    l::Op::Eq(58, 80),
    l::Op::And(79, 81),
    l::Op::Not(77),
    l::Op::Not(82),
    l::Op::And(83, 84),
    l::Op::Not(85),
    l::Op::Not(60),
    l::Op::Not(63),
    l::Op::And(87, 88),
    l::Op::Not(89),
    l::Op::And(8, 90),
    l::Op::Not(86),
    l::Op::Not(91),
    l::Op::And(92, 93),
    l::Op::Not(94),
    l::Op::Not(95),
    l::Op::And(30, 96),
    l::Op::Not(96),
    l::Op::And(30, 98),
    l::Op::ObserveWhen(97, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(100),
    l::Op::Literal(l::Atom::I128(201)),
    l::Op::Eq(101, 102),
    l::Op::And(51, 103),
    l::Op::And(104, 43),
    l::Op::And(105, 46),
    l::Op::And(106, 49),
    l::Op::Select(97, 107, 0),
    l::Op::Observe(l::Observation::Command(126)),
    l::Op::ToI128(109),
    l::Op::Observe(l::Observation::Pre(121)),
    l::Op::ToI128(111),
    l::Op::Eq(110, 112),
    l::Op::Not(113),
    l::Op::And(21, 114),
    l::Op::And(99, 115),
    l::Op::Not(115),
    l::Op::And(99, 117),
    l::Op::ObserveWhen(116, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(119),
    l::Op::Literal(l::Atom::I128(202)),
    l::Op::Eq(120, 121),
    l::Op::And(51, 122),
    l::Op::And(123, 43),
    l::Op::And(124, 46),
    l::Op::And(125, 49),
    l::Op::Select(116, 126, 0),
    l::Op::Literal(l::Atom::I128(3)),
    l::Op::Eq(112, 128),
    l::Op::And(6, 129),
    l::Op::And(118, 130),
    l::Op::Not(130),
    l::Op::And(118, 132),
    l::Op::ObserveWhen(131, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(134),
    l::Op::Literal(l::Atom::I128(203)),
    l::Op::Eq(135, 136),
    l::Op::And(51, 137),
    l::Op::And(138, 43),
    l::Op::And(139, 46),
    l::Op::And(140, 49),
    l::Op::Select(131, 141, 0),
    l::Op::And(133, 6),
    l::Op::And(133, 9),
    l::Op::Eq(32, 42),
    l::Op::Not(35),
    l::Op::Eq(45, 33),
    l::Op::Literal(l::Atom::I128(2)),
    l::Op::Eq(48, 148),
    l::Op::ObserveWhen(
        143,
        l::Observation::Post(120),
        l::Atom::Sum {
            type_id: 105,
            variant: 160,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 105,
        variant: 161,
    }),
    l::Op::Eq(150, 151),
    l::Op::Select(143, 152, 0),
    l::Op::ObserveWhen(143, l::Observation::Post(121), l::Atom::I128(0)),
    l::Op::ToI128(154),
    l::Op::Add(112, 33),
    l::Op::Eq(155, 156),
    l::Op::Select(143, 157, 0),
    l::Op::ObserveWhen(143, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(159),
    l::Op::Eq(160, 42),
    l::Op::ObserveWhen(143, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(162),
    l::Op::Literal(l::Atom::I128(300)),
    l::Op::Eq(163, 164),
    l::Op::ObserveWhen(
        143,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"payment-provider"),
    ),
    l::Op::Literal(l::Atom::Text(b"payment-provider")),
    l::Op::Eq(166, 167),
    l::Op::ObserveWhen(143, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Literal(l::Atom::U128(0)),
    l::Op::Eq(169, 170),
    l::Op::ObserveWhen(143, l::Observation::OutboxPayload(0, 140), l::Atom::I128(0)),
    l::Op::ToI128(172),
    l::Op::Eq(173, 156),
    l::Op::Select(143, 174, 0),
    l::Op::ObserveWhen(
        143,
        l::Observation::OutboxPayload(0, 141),
        l::Atom::Sum {
            type_id: 108,
            variant: 175,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 108,
        variant: 175,
    }),
    l::Op::Eq(176, 177),
    l::Op::Select(143, 178, 0),
    l::Op::And(0, 145),
    l::Op::And(180, 146),
    l::Op::And(181, 43),
    l::Op::And(182, 147),
    l::Op::And(183, 149),
    l::Op::And(184, 153),
    l::Op::And(185, 158),
    l::Op::And(186, 161),
    l::Op::And(187, 165),
    l::Op::And(188, 168),
    l::Op::And(189, 171),
    l::Op::And(190, 175),
    l::Op::And(191, 179),
    l::Op::Select(143, 192, 0),
    l::Op::And(144, 15),
    l::Op::And(144, 18),
    l::Op::ObserveWhen(
        194,
        l::Observation::Post(120),
        l::Atom::Sum {
            type_id: 105,
            variant: 160,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 105,
        variant: 162,
    }),
    l::Op::Eq(196, 197),
    l::Op::Select(194, 198, 0),
    l::Op::ObserveWhen(194, l::Observation::Post(121), l::Atom::I128(0)),
    l::Op::ToI128(200),
    l::Op::Eq(201, 112),
    l::Op::Select(194, 202, 0),
    l::Op::ObserveWhen(194, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(204),
    l::Op::Eq(205, 42),
    l::Op::ObserveWhen(194, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(207),
    l::Op::Literal(l::Atom::I128(301)),
    l::Op::Eq(208, 209),
    l::Op::ObserveWhen(
        194,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"carrier"),
    ),
    l::Op::Literal(l::Atom::Text(b"carrier")),
    l::Op::Eq(211, 212),
    l::Op::ObserveWhen(194, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(214, 170),
    l::Op::ObserveWhen(194, l::Observation::OutboxPayload(0, 145), l::Atom::I128(0)),
    l::Op::ToI128(216),
    l::Op::Eq(217, 112),
    l::Op::Select(194, 218, 0),
    l::Op::And(184, 199),
    l::Op::And(220, 203),
    l::Op::And(221, 206),
    l::Op::And(222, 210),
    l::Op::And(223, 213),
    l::Op::And(224, 215),
    l::Op::And(225, 219),
    l::Op::Select(194, 226, 0),
    l::Op::And(195, 17),
    l::Op::And(195, 19),
    l::Op::Eq(32, 148),
    l::Op::ObserveWhen(228, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(231),
    l::Op::Literal(l::Atom::I128(204)),
    l::Op::Eq(232, 233),
    l::Op::ObserveWhen(
        228,
        l::Observation::Post(120),
        l::Atom::Sum {
            type_id: 105,
            variant: 160,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 105,
        variant: 160,
    }),
    l::Op::Eq(235, 236),
    l::Op::Select(228, 237, 0),
    l::Op::ObserveWhen(228, l::Observation::Post(121), l::Atom::I128(0)),
    l::Op::ToI128(239),
    l::Op::Eq(240, 112),
    l::Op::Select(228, 241, 0),
    l::Op::And(0, 230),
    l::Op::And(243, 35),
    l::Op::And(244, 234),
    l::Op::And(245, 43),
    l::Op::And(246, 46),
    l::Op::And(247, 149),
    l::Op::And(248, 238),
    l::Op::And(249, 242),
    l::Op::Select(228, 250, 0),
    l::Op::And(229, 70),
    l::Op::Not(70),
    l::Op::And(229, 253),
    l::Op::ObserveWhen(
        252,
        l::Observation::Post(120),
        l::Atom::Sum {
            type_id: 105,
            variant: 160,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 105,
        variant: 163,
    }),
    l::Op::Eq(255, 256),
    l::Op::Select(252, 257, 0),
    l::Op::ObserveWhen(252, l::Observation::Post(121), l::Atom::I128(0)),
    l::Op::ToI128(259),
    l::Op::Eq(260, 112),
    l::Op::Select(252, 261, 0),
    l::Op::And(182, 46),
    l::Op::And(263, 149),
    l::Op::And(264, 258),
    l::Op::And(265, 262),
    l::Op::Select(252, 266, 0),
    l::Op::And(254, 79),
    l::Op::Not(79),
    l::Op::And(254, 269),
    l::Op::ObserveWhen(
        268,
        l::Observation::Post(120),
        l::Atom::Sum {
            type_id: 105,
            variant: 160,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 105,
        variant: 164,
    }),
    l::Op::Eq(271, 272),
    l::Op::Select(268, 273, 0),
    l::Op::ObserveWhen(268, l::Observation::Post(121), l::Atom::I128(0)),
    l::Op::ToI128(275),
    l::Op::Eq(276, 112),
    l::Op::Select(268, 277, 0),
    l::Op::And(264, 274),
    l::Op::And(279, 278),
    l::Op::Select(268, 280, 0),
    l::Op::And(270, 60),
    l::Op::And(270, 87),
    l::Op::ObserveWhen(
        282,
        l::Observation::Post(120),
        l::Atom::Sum {
            type_id: 105,
            variant: 160,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 105,
        variant: 165,
    }),
    l::Op::Eq(284, 285),
    l::Op::Select(282, 286, 0),
    l::Op::ObserveWhen(282, l::Observation::Post(121), l::Atom::I128(0)),
    l::Op::ToI128(288),
    l::Op::Eq(289, 112),
    l::Op::Select(282, 290, 0),
    l::Op::And(264, 287),
    l::Op::And(292, 291),
    l::Op::Select(282, 293, 0),
    l::Op::And(283, 0),
    l::Op::Not(0),
    l::Op::And(283, 296),
    l::Op::ObserveWhen(
        295,
        l::Observation::Post(120),
        l::Atom::Sum {
            type_id: 105,
            variant: 160,
        },
    ),
    l::Op::Eq(298, 285),
    l::Op::Select(295, 299, 0),
    l::Op::ObserveWhen(295, l::Observation::Post(121), l::Atom::I128(0)),
    l::Op::ToI128(301),
    l::Op::Eq(302, 112),
    l::Op::Select(295, 303, 0),
    l::Op::ObserveWhen(295, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(305),
    l::Op::Eq(306, 42),
    l::Op::ObserveWhen(295, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(308),
    l::Op::Eq(309, 164),
    l::Op::ObserveWhen(
        295,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"payment-provider"),
    ),
    l::Op::Eq(311, 167),
    l::Op::ObserveWhen(295, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(313, 170),
    l::Op::ObserveWhen(295, l::Observation::OutboxPayload(0, 140), l::Atom::I128(0)),
    l::Op::ToI128(315),
    l::Op::Eq(316, 112),
    l::Op::Select(295, 317, 0),
    l::Op::ObserveWhen(
        295,
        l::Observation::OutboxPayload(0, 141),
        l::Atom::Sum {
            type_id: 108,
            variant: 175,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 108,
        variant: 176,
    }),
    l::Op::Eq(319, 320),
    l::Op::Select(295, 321, 0),
    l::Op::And(184, 300),
    l::Op::And(323, 304),
    l::Op::And(324, 307),
    l::Op::And(325, 310),
    l::Op::And(326, 312),
    l::Op::And(327, 314),
    l::Op::And(328, 318),
    l::Op::And(329, 322),
    l::Op::Select(295, 330, 0),
    l::Op::Not(297),
    l::Op::And(0, 56),
    l::Op::And(333, 108),
    l::Op::And(334, 127),
    l::Op::And(335, 142),
    l::Op::And(336, 193),
    l::Op::And(337, 227),
    l::Op::And(338, 251),
    l::Op::And(339, 267),
    l::Op::And(340, 281),
    l::Op::And(341, 294),
    l::Op::And(342, 331),
    l::Op::And(343, 332),
];
/// Original scoped laws plus independent structural requirements.
pub const LAWS: &[l::Law<'static>] = &[
    l::Law {
        id: 500,
        kind: l::Kind::StateInvariant,
        scope: l::Scope::Committing,
        genesis: true,
        program: l::Program {
            nodes: LAW_500,
            root: 31,
        },
    },
    l::Law {
        id: 501,
        kind: l::Kind::AuthoritySubjectRecipient,
        scope: l::Scope::Accept,
        genesis: false,
        program: l::Program {
            nodes: LAW_501,
            root: 37,
        },
    },
    l::Law {
        id: 502,
        kind: l::Kind::AuthoritySubjectRecipient,
        scope: l::Scope::Accept,
        genesis: false,
        program: l::Program {
            nodes: LAW_502,
            root: 32,
        },
    },
    l::Law {
        id: 503,
        kind: l::Kind::AuthoritySubjectRecipient,
        scope: l::Scope::Accept,
        genesis: false,
        program: l::Program {
            nodes: LAW_503,
            root: 28,
        },
    },
    l::Law {
        id: 504,
        kind: l::Kind::AuthoritySubjectRecipient,
        scope: l::Scope::Accept,
        genesis: false,
        program: l::Program {
            nodes: LAW_504,
            root: 28,
        },
    },
    l::Law {
        id: 505,
        kind: l::Kind::AuthoritySubjectRecipient,
        scope: l::Scope::Accept,
        genesis: false,
        program: l::Program {
            nodes: LAW_505,
            root: 34,
        },
    },
    l::Law {
        id: 506,
        kind: l::Kind::CommittedFailureEffects,
        scope: l::Scope::CommittedFailure,
        genesis: false,
        program: l::Program {
            nodes: LAW_506,
            root: 28,
        },
    },
    l::Law {
        id: 909,
        kind: l::Kind::RejectNoAuthority,
        scope: l::Scope::Reject,
        genesis: false,
        program: l::Program {
            nodes: LAW_909,
            root: 17,
        },
    },
    l::Law {
        id: 990,
        kind: l::Kind::InitialCondition,
        scope: l::Scope::Always,
        genesis: true,
        program: l::Program {
            nodes: LAW_990,
            root: 8,
        },
    },
    l::Law {
        id: 991,
        kind: l::Kind::DecisionConformance,
        scope: l::Scope::Always,
        genesis: false,
        program: l::Program {
            nodes: LAW_991,
            root: 344,
        },
    },
];
/// No declared law is optional at descriptor admission.
pub const REQUIRED: &[u32] = &[500, 501, 502, 503, 504, 505, 506, 909, 990, 991];
/// Owns declarative input/output type tables; evaluation stays in the library.
pub struct Contract {
    state: Vec<InputField>,
    command: Vec<InputField>,
    context: Vec<InputField>,
    output_types: Vec<InputLeaf>,
}
impl Default for Contract {
    fn default() -> Self {
        Self::new()
    }
}
impl Contract {
    /// Allocate only fixed declarative type tables.
    #[must_use]
    pub fn new() -> Self {
        Self {
            state: vec![
                InputField {
                    id: 120,
                    leaf: InputLeaf::Sum {
                        type_id: 105,
                        min: 160,
                        max: 165,
                        variants: vec![
                            InputVariant { id: 160, code: 160 },
                            InputVariant { id: 161, code: 161 },
                            InputVariant { id: 162, code: 162 },
                            InputVariant { id: 163, code: 163 },
                            InputVariant { id: 164, code: 164 },
                            InputVariant { id: 165, code: 165 },
                        ],
                    },
                },
                InputField {
                    id: 121,
                    leaf: InputLeaf::I128 { min: 0, max: 3 },
                },
            ],
            command: vec![
                InputField {
                    id: 125,
                    leaf: InputLeaf::Sum {
                        type_id: 111,
                        min: 150,
                        max: 155,
                        variants: vec![
                            InputVariant { id: 150, code: 150 },
                            InputVariant { id: 151, code: 151 },
                            InputVariant { id: 152, code: 152 },
                            InputVariant { id: 153, code: 153 },
                            InputVariant { id: 154, code: 154 },
                            InputVariant { id: 155, code: 155 },
                        ],
                    },
                },
                InputField {
                    id: 126,
                    leaf: InputLeaf::I128 { min: 0, max: 3 },
                },
            ],
            context: vec![InputField {
                id: 130,
                leaf: InputLeaf::Sum {
                    type_id: 107,
                    min: 170,
                    max: 172,
                    variants: vec![
                        InputVariant { id: 170, code: 170 },
                        InputVariant { id: 171, code: 171 },
                        InputVariant { id: 172, code: 172 },
                    ],
                },
            }],
            output_types: vec![
                InputLeaf::I128 { min: 0, max: 10 },
                InputLeaf::I128 {
                    min: -9223372036854775808,
                    max: 9223372036854775807,
                },
            ],
        }
    }
    /// Borrow the full raw-input, complete-decision and law contract.
    #[must_use]
    pub fn descriptor(&self) -> c::Descriptor<'_> {
        c::Descriptor {
            producer: c::Producer::Finite,
            state: c::Schema::Record(&self.state),
            command: c::Schema::Record(&self.command),
            context: c::Schema::Record(&self.context),
            program: V2ScalarProgram {
                inputs: &[
                    ScalarDomain::Int { min: 160, max: 165 },
                    ScalarDomain::Int { min: 0, max: 3 },
                    ScalarDomain::Int { min: 150, max: 155 },
                    ScalarDomain::Int { min: 0, max: 3 },
                    ScalarDomain::Int { min: 170, max: 172 },
                ],
                outputs: &[
                    ScalarDomain::Int { min: 0, max: 10 },
                    ScalarDomain::Int {
                        min: -9223372036854775808,
                        max: 9223372036854775807,
                    },
                ],
                nodes: &[
                    Op::Input(4),
                    Op::Input(2),
                    Op::Int(150),
                    Op::Eq(1, 2),
                    Op::Int(155),
                    Op::Eq(1, 4),
                    Op::Not(3),
                    Op::Not(5),
                    Op::And(6, 7),
                    Op::Not(8),
                    Op::Int(170),
                    Op::Int(151),
                    Op::Eq(1, 11),
                    Op::Int(152),
                    Op::Eq(1, 13),
                    Op::Not(12),
                    Op::Not(14),
                    Op::And(15, 16),
                    Op::Not(17),
                    Op::Int(171),
                    Op::Int(172),
                    Op::Select(18, 19, 20),
                    Op::Select(9, 10, 21),
                    Op::Eq(0, 22),
                    Op::Not(23),
                    Op::Int(0),
                    Op::Input(0),
                    Op::Int(160),
                    Op::Eq(26, 27),
                    Op::And(3, 28),
                    Op::Int(161),
                    Op::Eq(26, 30),
                    Op::And(18, 31),
                    Op::Not(29),
                    Op::Not(32),
                    Op::And(33, 34),
                    Op::Not(35),
                    Op::Int(153),
                    Op::Eq(1, 37),
                    Op::Int(162),
                    Op::Eq(26, 39),
                    Op::And(38, 40),
                    Op::Not(36),
                    Op::Not(41),
                    Op::And(42, 43),
                    Op::Not(44),
                    Op::Int(154),
                    Op::Eq(1, 46),
                    Op::Int(163),
                    Op::Eq(26, 48),
                    Op::And(47, 49),
                    Op::Not(45),
                    Op::Not(50),
                    Op::And(51, 52),
                    Op::Not(53),
                    Op::Not(28),
                    Op::Not(31),
                    Op::And(55, 56),
                    Op::Not(57),
                    Op::And(5, 58),
                    Op::Not(54),
                    Op::Not(59),
                    Op::And(60, 61),
                    Op::Not(62),
                    Op::Not(63),
                    Op::Int(1),
                    Op::Input(3),
                    Op::Input(1),
                    Op::Eq(66, 67),
                    Op::Not(68),
                    Op::And(18, 69),
                    Op::Int(2),
                    Op::Int(3),
                    Op::Eq(67, 72),
                    Op::And(3, 73),
                    Op::Int(4),
                    Op::Int(5),
                    Op::Int(6),
                    Op::Int(7),
                    Op::Int(8),
                    Op::Int(9),
                    Op::Int(10),
                    Op::Select(28, 80, 81),
                    Op::Select(47, 79, 82),
                    Op::Select(38, 78, 83),
                    Op::Select(14, 77, 84),
                    Op::Select(12, 76, 85),
                    Op::Select(3, 75, 86),
                    Op::Select(74, 72, 87),
                    Op::Select(70, 71, 88),
                    Op::Select(64, 65, 89),
                    Op::Select(24, 25, 90),
                    Op::Add(67, 65),
                ],
                roots: &[91, 92],
            },
            bindings: &[
                c::Binding {
                    source: c::Source::State,
                    selector: c::Selector::Field(120),
                },
                c::Binding {
                    source: c::Source::State,
                    selector: c::Selector::Field(121),
                },
                c::Binding {
                    source: c::Source::Command,
                    selector: c::Selector::Field(125),
                },
                c::Binding {
                    source: c::Source::Command,
                    selector: c::Selector::Field(126),
                },
                c::Binding {
                    source: c::Source::Context,
                    selector: c::Selector::Field(130),
                },
            ],
            output_types: &self.output_types,
            decision_output: 0,
            branches: BRANCHES,
            reasons: &[
                c::Reason {
                    id: 200,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 201,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 202,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 203,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 204,
                    class: c::Class::CommittedFailure,
                },
            ],
            channels: &[
                c::Channel {
                    id: 300,
                    destination: c::Domain::Text,
                    payload: &[
                        c::TypedField {
                            field: 140,
                            domain: c::Domain::I128 { min: 0, max: 3 },
                        },
                        c::TypedField {
                            field: 141,
                            domain: c::Domain::Sum {
                                type_id: 108,
                                variants: &[175, 176],
                            },
                        },
                    ],
                    idempotency: c::Domain::U128 { min: 0, max: 0 },
                },
                c::Channel {
                    id: 301,
                    destination: c::Domain::Text,
                    payload: &[c::TypedField {
                        field: 145,
                        domain: c::Domain::I128 { min: 0, max: 3 },
                    }],
                    idempotency: c::Domain::U128 { min: 0, max: 0 },
                },
            ],
            laws: LAWS,
            required: REQUIRED,
            limits: v2_zero_limits()
                .with_limit(Resource::Read, 171)
                .with_limit(Resource::Write, 2)
                .with_limit(Resource::Candidate, 1)
                .with_limit(Resource::Effect, 1)
                .with_limit(Resource::Byte, 227)
                .with_limit(Resource::WitnessByte, 0)
                .with_limit(Resource::Depth, 0)
                .with_limit(Resource::Step, 695),
        }
    }
}
/// Exact complete schema/policy correspondence precedes Authority construction.
pub fn checked_catalog<'a>(
    descriptor: &'a c::Descriptor<'a>,
) -> Result<catalog::BoundCatalog<'a>, catalog::Failure> {
    catalog::bind_original(
        ORIGINAL_SCHEMA,
        &DESCRIPTION,
        catalog::Limits {
            schema: s::Limits {
                bytes: ORIGINAL_SCHEMA.len() as u64,
                types: 12,
                fields: 2,
                variants: 6,
            },
            contract_bytes: ORIGINAL_POLICY.len() as u64,
        },
        ORIGINAL_POLICY,
        descriptor,
        &FRAMING,
        CHANNEL_ROOTS,
    )
}
/// Ordered refusal at checked catalog or private Authority construction.
#[derive(Debug)]
pub enum BindFailure {
    /// Complete original schema/policy correspondence refused.
    Catalog(catalog::Failure),
    /// Private library source binding refused.
    Authority(authority::Refusal),
}
/// Sole supplied production constructor; identity comes from the checked library.
pub fn checked_authority<'a>(
    descriptor: &'a c::Descriptor<'a>,
) -> Result<authority::Authority<'a>, BindFailure> {
    let catalog = checked_catalog(descriptor).map_err(BindFailure::Catalog)?;
    authority::bind(&catalog).map_err(BindFailure::Authority)
}
