// Generated declarative data. Review v2/policy.json and project.zeno.
// Regenerate or check with `zeno-fcis generate contract`; no runtime mapper.
extern crate alloc;
use alloc::{vec, vec::Vec};
use zeno_fcis_synthesis::finite::{Domain as ScalarDomain, Op, V2ScalarProgram};
use zeno_fcis_synthesis::finite::{
    V2InputField as InputField, V2InputLeaf as InputLeaf, V2InputVariant as InputVariant,
    V2Resource as Resource, canonical_v2::schema as s, v2_authority as authority,
    v2_catalog as catalog, v2_composition as c, v2_laws as l, v2_zero_limits,
};
/// Exact actual original schema bytes.
pub const ORIGINAL_SCHEMA: &[u8] = include_bytes!("../v2/schema.zcve");
/// Complete reviewed library-encoded policy.
pub const ORIGINAL_POLICY: &[u8] = include_bytes!("../v2/policy.zcve");
/// Complete original named schema description.
pub const DESCRIPTION: s::Description<'static> = s::Description {
    profile: b"compliance_gateway",
    version: 1,
    root: 100,
    definitions: &[
        s::Definition {
            id: 100,
            name: b"Standing",
            kind: s::Kind::Record(&[s::Field {
                id: 120,
                name: b"strikes",
                type_id: 107,
            }]),
        },
        s::Definition {
            id: 101,
            name: b"GatewayCommand",
            kind: s::Kind::Record(&[
                s::Field {
                    id: 130,
                    name: b"action",
                    type_id: 111,
                },
                s::Field {
                    id: 131,
                    name: b"region",
                    type_id: 112,
                },
                s::Field {
                    id: 132,
                    name: b"amount_band",
                    type_id: 109,
                },
                s::Field {
                    id: 133,
                    name: b"counterparty_risk",
                    type_id: 113,
                },
            ]),
        },
        s::Definition {
            id: 102,
            name: b"CallerContext",
            kind: s::Kind::Record(&[
                s::Field {
                    id: 140,
                    name: b"identity_tier",
                    type_id: 108,
                },
                s::Field {
                    id: 141,
                    name: b"reviewer",
                    type_id: 110,
                },
            ]),
        },
        s::Definition {
            id: 103,
            name: b"ReviewDesk",
            kind: s::Kind::Text { min: 1, max: 32 },
        },
        s::Definition {
            id: 104,
            name: b"ReviewTicket",
            kind: s::Kind::Record(&[
                s::Field {
                    id: 145,
                    name: b"ticket_rule",
                    type_id: 114,
                },
                s::Field {
                    id: 146,
                    name: b"ticket_amount_band",
                    type_id: 109,
                },
            ]),
        },
        s::Definition {
            id: 105,
            name: b"ComplianceDesk",
            kind: s::Kind::Text { min: 1, max: 32 },
        },
        s::Definition {
            id: 106,
            name: b"BlockAlert",
            kind: s::Kind::Record(&[
                s::Field {
                    id: 147,
                    name: b"alert_rule",
                    type_id: 114,
                },
                s::Field {
                    id: 148,
                    name: b"alert_strikes",
                    type_id: 107,
                },
            ]),
        },
        s::Definition {
            id: 107,
            name: b"Strikes",
            kind: s::Kind::I128 { min: 0, max: 3 },
        },
        s::Definition {
            id: 108,
            name: b"IdentityTier",
            kind: s::Kind::I128 { min: 0, max: 3 },
        },
        s::Definition {
            id: 109,
            name: b"AmountBand",
            kind: s::Kind::I128 { min: 0, max: 4 },
        },
        s::Definition {
            id: 110,
            name: b"ReviewerFlag",
            kind: s::Kind::Bool,
        },
        s::Definition {
            id: 111,
            name: b"GatewayAction",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 150,
                    name: b"Screen",
                },
                s::Variant {
                    id: 151,
                    name: b"Reinstate",
                },
            ]),
        },
        s::Definition {
            id: 112,
            name: b"Region",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 160,
                    name: b"Allowed",
                },
                s::Variant {
                    id: 161,
                    name: b"Restricted",
                },
                s::Variant {
                    id: 162,
                    name: b"Sanctioned",
                },
            ]),
        },
        s::Definition {
            id: 113,
            name: b"CounterpartyRisk",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 165,
                    name: b"Low",
                },
                s::Variant {
                    id: 166,
                    name: b"Medium",
                },
                s::Variant {
                    id: 167,
                    name: b"High",
                },
            ]),
        },
        s::Definition {
            id: 114,
            name: b"RuleId",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 170,
                    name: b"SanctionedRegion",
                },
                s::Variant {
                    id: 171,
                    name: b"FrozenAccount",
                },
                s::Variant {
                    id: 172,
                    name: b"UnverifiedHighRisk",
                },
                s::Variant {
                    id: 173,
                    name: b"RestrictedLarge",
                },
                s::Variant {
                    id: 174,
                    name: b"UnverifiedLarge",
                },
                s::Variant {
                    id: 175,
                    name: b"HighRiskCounterparty",
                },
                s::Variant {
                    id: 176,
                    name: b"RestrictedRegion",
                },
                s::Variant {
                    id: 177,
                    name: b"UnverifiedTransfer",
                },
                s::Variant {
                    id: 178,
                    name: b"PartiallyVerifiedLarge",
                },
                s::Variant {
                    id: 179,
                    name: b"RepeatOffender",
                },
                s::Variant {
                    id: 180,
                    name: b"MediumRiskLarge",
                },
                s::Variant {
                    id: 181,
                    name: b"DefaultAllow",
                },
            ]),
        },
    ],
};
/// Original root and schema commitments and complete wire-size limits.
pub const FRAMING: c::Framing = c::Framing {
    state: c::FrameBinding {
        root: 100,
        schema: [
            81, 224, 193, 97, 28, 155, 8, 246, 147, 0, 207, 179, 81, 44, 33, 65, 52, 64, 109, 115,
            136, 136, 85, 248, 96, 204, 166, 6, 214, 25, 99, 41,
        ],
        max_bytes: 72,
    },
    command: c::FrameBinding {
        root: 101,
        schema: [
            81, 224, 193, 97, 28, 155, 8, 246, 147, 0, 207, 179, 81, 44, 33, 65, 52, 64, 109, 115,
            136, 136, 85, 248, 96, 204, 166, 6, 214, 25, 99, 41,
        ],
        max_bytes: 102,
    },
    context: c::FrameBinding {
        root: 102,
        schema: [
            81, 224, 193, 97, 28, 155, 8, 246, 147, 0, 207, 179, 81, 44, 33, 65, 52, 64, 109, 115,
            136, 136, 85, 248, 96, 204, 166, 6, 214, 25, 99, 41,
        ],
        max_bytes: 75,
    },
};
/// Exact channel to original destination and payload type links.
pub const CHANNEL_ROOTS: &[(u32, u32, u32)] = &[(300, 103, 104), (301, 105, 106)];
/// The genesis state law 990 requires, field by field.
pub const GENESIS: &[c::Field<'static>] = &[c::Field {
    id: 120,
    value: c::Atom::I128(0),
}];
/// Complete ordered decisions selected only by actual graph output.
pub const BRANCHES: &[c::Branch<'static>] = &[
    c::Branch {
        code: 0,
        class: c::Class::Reject,
        reason: Some(200),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 1,
        class: c::Class::Reject,
        reason: Some(201),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 2,
        class: c::Class::Accept,
        reason: None,
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Constant(c::Atom::I128(0)),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 3,
        class: c::Class::CommittedFailure,
        reason: Some(210),
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Output(1),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 301,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"compliance-team")),
            payload: &[
                c::PayloadField {
                    field: 147,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 114,
                        variant: 170,
                    }),
                },
                c::PayloadField {
                    field: 148,
                    value: c::Expr::Output(1),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 4,
        class: c::Class::CommittedFailure,
        reason: Some(211),
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Output(1),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 301,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"compliance-team")),
            payload: &[
                c::PayloadField {
                    field: 147,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 114,
                        variant: 171,
                    }),
                },
                c::PayloadField {
                    field: 148,
                    value: c::Expr::Output(1),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 5,
        class: c::Class::CommittedFailure,
        reason: Some(212),
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Output(1),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 301,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"compliance-team")),
            payload: &[
                c::PayloadField {
                    field: 147,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 114,
                        variant: 172,
                    }),
                },
                c::PayloadField {
                    field: 148,
                    value: c::Expr::Output(1),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 6,
        class: c::Class::CommittedFailure,
        reason: Some(213),
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Output(1),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 301,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"compliance-team")),
            payload: &[
                c::PayloadField {
                    field: 147,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 114,
                        variant: 173,
                    }),
                },
                c::PayloadField {
                    field: 148,
                    value: c::Expr::Output(1),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 7,
        class: c::Class::CommittedFailure,
        reason: Some(214),
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Output(1),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 301,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"compliance-team")),
            payload: &[
                c::PayloadField {
                    field: 147,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 114,
                        variant: 174,
                    }),
                },
                c::PayloadField {
                    field: 148,
                    value: c::Expr::Output(1),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 8,
        class: c::Class::Accept,
        reason: None,
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Input(c::Source::State, 120),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 300,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"review-queue")),
            payload: &[
                c::PayloadField {
                    field: 145,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 114,
                        variant: 175,
                    }),
                },
                c::PayloadField {
                    field: 146,
                    value: c::Expr::Input(c::Source::Command, 132),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 9,
        class: c::Class::Accept,
        reason: None,
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Input(c::Source::State, 120),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 300,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"review-queue")),
            payload: &[
                c::PayloadField {
                    field: 145,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 114,
                        variant: 176,
                    }),
                },
                c::PayloadField {
                    field: 146,
                    value: c::Expr::Input(c::Source::Command, 132),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 10,
        class: c::Class::Accept,
        reason: None,
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Input(c::Source::State, 120),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 300,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"review-queue")),
            payload: &[
                c::PayloadField {
                    field: 145,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 114,
                        variant: 177,
                    }),
                },
                c::PayloadField {
                    field: 146,
                    value: c::Expr::Input(c::Source::Command, 132),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 11,
        class: c::Class::Accept,
        reason: None,
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Input(c::Source::State, 120),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 300,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"review-queue")),
            payload: &[
                c::PayloadField {
                    field: 145,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 114,
                        variant: 178,
                    }),
                },
                c::PayloadField {
                    field: 146,
                    value: c::Expr::Input(c::Source::Command, 132),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 12,
        class: c::Class::Accept,
        reason: None,
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Input(c::Source::State, 120),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 300,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"review-queue")),
            payload: &[
                c::PayloadField {
                    field: 145,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 114,
                        variant: 179,
                    }),
                },
                c::PayloadField {
                    field: 146,
                    value: c::Expr::Input(c::Source::Command, 132),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 13,
        class: c::Class::Accept,
        reason: None,
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Input(c::Source::State, 120),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 300,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"review-queue")),
            payload: &[
                c::PayloadField {
                    field: 145,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 114,
                        variant: 180,
                    }),
                },
                c::PayloadField {
                    field: 146,
                    value: c::Expr::Input(c::Source::Command, 132),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 14,
        class: c::Class::Accept,
        reason: None,
        assignments: &[c::Assignment {
            field: 120,
            value: c::Expr::Input(c::Source::State, 120),
            domain: c::Domain::I128 { min: 0, max: 3 },
        }],
        effects: &[],
        outbox: &[],
    },
];
const LAW_500: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Post(120)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Lt(1, 2),
    l::Op::Not(3),
    l::Op::Literal(l::Atom::I128(3)),
    l::Op::Lt(5, 1),
    l::Op::Not(6),
    l::Op::And(4, 7),
];
const LAW_501: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(130)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(150)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Command(131)),
    l::Op::ToI128(4),
    l::Op::Literal(l::Atom::I128(162)),
    l::Op::Eq(5, 6),
    l::Op::Not(7),
    l::Op::Observe(l::Observation::Pre(120)),
    l::Op::ToI128(9),
    l::Op::Literal(l::Atom::I128(3)),
    l::Op::Lt(10, 11),
    l::Op::And(8, 12),
    l::Op::Observe(l::Observation::Post(120)),
    l::Op::ToI128(14),
    l::Op::Eq(15, 10),
    l::Op::And(13, 16),
    l::Op::Not(3),
    l::Op::Not(18),
    l::Op::Not(17),
    l::Op::And(19, 20),
    l::Op::Not(21),
];
const LAW_502: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(130)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(151)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Context(141)),
    l::Op::ToI128(4),
    l::Op::Literal(l::Atom::I128(1)),
    l::Op::Eq(5, 6),
    l::Op::Observe(l::Observation::Pre(120)),
    l::Op::ToI128(8),
    l::Op::Lt(9, 6),
    l::Op::Not(10),
    l::Op::And(7, 11),
    l::Op::Observe(l::Observation::Post(120)),
    l::Op::ToI128(13),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(14, 15),
    l::Op::And(12, 16),
    l::Op::Not(3),
    l::Op::Not(18),
    l::Op::Not(17),
    l::Op::And(19, 20),
    l::Op::Not(21),
];
const LAW_503: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(130)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(150)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Pre(120)),
    l::Op::ToI128(4),
    l::Op::Literal(l::Atom::I128(3)),
    l::Op::Lt(5, 6),
    l::Op::Observe(l::Observation::Post(120)),
    l::Op::ToI128(8),
    l::Op::Literal(l::Atom::I128(1)),
    l::Op::Add(5, 10),
    l::Op::Eq(9, 11),
    l::Op::Not(7),
    l::Op::Not(13),
    l::Op::Not(12),
    l::Op::And(14, 15),
    l::Op::Not(16),
    l::Op::And(3, 17),
    l::Op::Eq(5, 6),
    l::Op::Eq(9, 6),
    l::Op::Not(19),
    l::Op::Not(21),
    l::Op::Not(20),
    l::Op::And(22, 23),
    l::Op::Not(24),
    l::Op::And(18, 25),
];
const LAW_509: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::PostLength),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::PatchLength),
    l::Op::ToI128(4),
    l::Op::Eq(5, 2),
    l::Op::Observe(l::Observation::EffectLength),
    l::Op::ToI128(7),
    l::Op::Eq(8, 2),
    l::Op::Observe(l::Observation::OutboxLength),
    l::Op::ToI128(10),
    l::Op::Eq(11, 2),
    l::Op::Literal(l::Atom::Bool(true)),
    l::Op::And(13, 3),
    l::Op::And(14, 6),
    l::Op::And(15, 9),
    l::Op::And(16, 12),
];
const LAW_990: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Initial(120)),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(0, 1),
    l::Op::Literal(l::Atom::Bool(true)),
    l::Op::And(3, 2),
];
const LAW_991: &[l::Op<'static>] = &[
    l::Op::Literal(l::Atom::Bool(true)),
    l::Op::Observe(l::Observation::Command(130)),
    l::Op::ToI128(1),
    l::Op::Literal(l::Atom::I128(151)),
    l::Op::Eq(2, 3),
    l::Op::Observe(l::Observation::Context(141)),
    l::Op::ToI128(5),
    l::Op::Literal(l::Atom::I128(1)),
    l::Op::Eq(6, 7),
    l::Op::Not(8),
    l::Op::And(4, 9),
    l::Op::And(0, 10),
    l::Op::Not(10),
    l::Op::And(0, 12),
    l::Op::Observe(l::Observation::Class),
    l::Op::ToI128(14),
    l::Op::Eq(15, 7),
    l::Op::Observe(l::Observation::HasReason),
    l::Op::ObserveWhen(11, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(18),
    l::Op::Literal(l::Atom::I128(200)),
    l::Op::Eq(19, 20),
    l::Op::Observe(l::Observation::EffectLength),
    l::Op::ToI128(22),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(23, 24),
    l::Op::Observe(l::Observation::OutboxLength),
    l::Op::ToI128(26),
    l::Op::Eq(27, 24),
    l::Op::Observe(l::Observation::PostLength),
    l::Op::ToI128(29),
    l::Op::Eq(30, 24),
    l::Op::And(0, 16),
    l::Op::And(32, 17),
    l::Op::And(33, 21),
    l::Op::And(34, 25),
    l::Op::And(35, 28),
    l::Op::And(36, 31),
    l::Op::Select(11, 37, 0),
    l::Op::Observe(l::Observation::Pre(120)),
    l::Op::ToI128(39),
    l::Op::Eq(40, 24),
    l::Op::And(4, 41),
    l::Op::And(13, 42),
    l::Op::Not(42),
    l::Op::And(13, 44),
    l::Op::ObserveWhen(43, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(46),
    l::Op::Literal(l::Atom::I128(201)),
    l::Op::Eq(47, 48),
    l::Op::And(33, 49),
    l::Op::And(50, 25),
    l::Op::And(51, 28),
    l::Op::And(52, 31),
    l::Op::Select(43, 53, 0),
    l::Op::And(45, 4),
    l::Op::Not(4),
    l::Op::And(45, 56),
    l::Op::Eq(15, 24),
    l::Op::Not(17),
    l::Op::Eq(30, 7),
    l::Op::ObserveWhen(55, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(61, 62),
    l::Op::Select(55, 63, 0),
    l::Op::And(0, 58),
    l::Op::And(65, 59),
    l::Op::And(66, 25),
    l::Op::And(67, 28),
    l::Op::And(68, 60),
    l::Op::And(69, 64),
    l::Op::Select(55, 70, 0),
    l::Op::Observe(l::Observation::Command(131)),
    l::Op::ToI128(72),
    l::Op::Literal(l::Atom::I128(162)),
    l::Op::Eq(73, 74),
    l::Op::And(57, 75),
    l::Op::Not(75),
    l::Op::And(57, 77),
    l::Op::Literal(l::Atom::I128(2)),
    l::Op::Eq(15, 79),
    l::Op::ObserveWhen(76, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(81),
    l::Op::Literal(l::Atom::I128(210)),
    l::Op::Eq(82, 83),
    l::Op::Eq(27, 7),
    l::Op::ObserveWhen(76, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::ToI128(86),
    l::Op::Literal(l::Atom::I128(3)),
    l::Op::Lt(40, 88),
    l::Op::Add(40, 7),
    l::Op::Select(89, 90, 88),
    l::Op::Eq(87, 91),
    l::Op::Select(76, 92, 0),
    l::Op::ObserveWhen(76, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(94),
    l::Op::Eq(95, 24),
    l::Op::ObserveWhen(76, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(97),
    l::Op::Literal(l::Atom::I128(301)),
    l::Op::Eq(98, 99),
    l::Op::ObserveWhen(
        76,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"compliance-team"),
    ),
    l::Op::Literal(l::Atom::Text(b"compliance-team")),
    l::Op::Eq(101, 102),
    l::Op::ObserveWhen(76, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Literal(l::Atom::U128(0)),
    l::Op::Eq(104, 105),
    l::Op::ObserveWhen(
        76,
        l::Observation::OutboxPayload(0, 147),
        l::Atom::Sum {
            type_id: 114,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 114,
        variant: 170,
    }),
    l::Op::Eq(107, 108),
    l::Op::Select(76, 109, 0),
    l::Op::ObserveWhen(76, l::Observation::OutboxPayload(0, 148), l::Atom::I128(0)),
    l::Op::ToI128(111),
    l::Op::Eq(112, 91),
    l::Op::Select(76, 113, 0),
    l::Op::And(0, 80),
    l::Op::And(115, 17),
    l::Op::And(116, 84),
    l::Op::And(117, 25),
    l::Op::And(118, 85),
    l::Op::And(119, 60),
    l::Op::And(120, 93),
    l::Op::And(121, 96),
    l::Op::And(122, 100),
    l::Op::And(123, 103),
    l::Op::And(124, 106),
    l::Op::And(125, 110),
    l::Op::And(126, 114),
    l::Op::Select(76, 127, 0),
    l::Op::Eq(40, 88),
    l::Op::And(78, 129),
    l::Op::Not(129),
    l::Op::And(78, 131),
    l::Op::ObserveWhen(130, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(133),
    l::Op::Literal(l::Atom::I128(211)),
    l::Op::Eq(134, 135),
    l::Op::ObserveWhen(130, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::ToI128(137),
    l::Op::Eq(138, 91),
    l::Op::Select(130, 139, 0),
    l::Op::ObserveWhen(130, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(141),
    l::Op::Eq(142, 24),
    l::Op::ObserveWhen(130, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(144),
    l::Op::Eq(145, 99),
    l::Op::ObserveWhen(
        130,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"compliance-team"),
    ),
    l::Op::Eq(147, 102),
    l::Op::ObserveWhen(130, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(149, 105),
    l::Op::ObserveWhen(
        130,
        l::Observation::OutboxPayload(0, 147),
        l::Atom::Sum {
            type_id: 114,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 114,
        variant: 171,
    }),
    l::Op::Eq(151, 152),
    l::Op::Select(130, 153, 0),
    l::Op::ObserveWhen(130, l::Observation::OutboxPayload(0, 148), l::Atom::I128(0)),
    l::Op::ToI128(155),
    l::Op::Eq(156, 91),
    l::Op::Select(130, 157, 0),
    l::Op::And(116, 136),
    l::Op::And(159, 25),
    l::Op::And(160, 85),
    l::Op::And(161, 60),
    l::Op::And(162, 140),
    l::Op::And(163, 143),
    l::Op::And(164, 146),
    l::Op::And(165, 148),
    l::Op::And(166, 150),
    l::Op::And(167, 154),
    l::Op::And(168, 158),
    l::Op::Select(130, 169, 0),
    l::Op::Observe(l::Observation::Context(140)),
    l::Op::ToI128(171),
    l::Op::Eq(172, 24),
    l::Op::Observe(l::Observation::Command(133)),
    l::Op::ToI128(174),
    l::Op::Literal(l::Atom::I128(167)),
    l::Op::Eq(175, 176),
    l::Op::And(173, 177),
    l::Op::And(132, 178),
    l::Op::Not(178),
    l::Op::And(132, 180),
    l::Op::ObserveWhen(179, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(182),
    l::Op::Literal(l::Atom::I128(212)),
    l::Op::Eq(183, 184),
    l::Op::ObserveWhen(179, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::ToI128(186),
    l::Op::Eq(187, 91),
    l::Op::Select(179, 188, 0),
    l::Op::ObserveWhen(179, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(190),
    l::Op::Eq(191, 24),
    l::Op::ObserveWhen(179, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(193),
    l::Op::Eq(194, 99),
    l::Op::ObserveWhen(
        179,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"compliance-team"),
    ),
    l::Op::Eq(196, 102),
    l::Op::ObserveWhen(179, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(198, 105),
    l::Op::ObserveWhen(
        179,
        l::Observation::OutboxPayload(0, 147),
        l::Atom::Sum {
            type_id: 114,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 114,
        variant: 172,
    }),
    l::Op::Eq(200, 201),
    l::Op::Select(179, 202, 0),
    l::Op::ObserveWhen(179, l::Observation::OutboxPayload(0, 148), l::Atom::I128(0)),
    l::Op::ToI128(204),
    l::Op::Eq(205, 91),
    l::Op::Select(179, 206, 0),
    l::Op::And(116, 185),
    l::Op::And(208, 25),
    l::Op::And(209, 85),
    l::Op::And(210, 60),
    l::Op::And(211, 189),
    l::Op::And(212, 192),
    l::Op::And(213, 195),
    l::Op::And(214, 197),
    l::Op::And(215, 199),
    l::Op::And(216, 203),
    l::Op::And(217, 207),
    l::Op::Select(179, 218, 0),
    l::Op::Literal(l::Atom::I128(161)),
    l::Op::Eq(73, 220),
    l::Op::Observe(l::Observation::Command(132)),
    l::Op::ToI128(222),
    l::Op::Lt(223, 88),
    l::Op::Not(224),
    l::Op::And(221, 225),
    l::Op::And(181, 226),
    l::Op::Not(226),
    l::Op::And(181, 228),
    l::Op::ObserveWhen(227, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(230),
    l::Op::Literal(l::Atom::I128(213)),
    l::Op::Eq(231, 232),
    l::Op::ObserveWhen(227, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::ToI128(234),
    l::Op::Eq(235, 91),
    l::Op::Select(227, 236, 0),
    l::Op::ObserveWhen(227, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(238),
    l::Op::Eq(239, 24),
    l::Op::ObserveWhen(227, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(241),
    l::Op::Eq(242, 99),
    l::Op::ObserveWhen(
        227,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"compliance-team"),
    ),
    l::Op::Eq(244, 102),
    l::Op::ObserveWhen(227, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(246, 105),
    l::Op::ObserveWhen(
        227,
        l::Observation::OutboxPayload(0, 147),
        l::Atom::Sum {
            type_id: 114,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 114,
        variant: 173,
    }),
    l::Op::Eq(248, 249),
    l::Op::Select(227, 250, 0),
    l::Op::ObserveWhen(227, l::Observation::OutboxPayload(0, 148), l::Atom::I128(0)),
    l::Op::ToI128(252),
    l::Op::Eq(253, 91),
    l::Op::Select(227, 254, 0),
    l::Op::And(116, 233),
    l::Op::And(256, 25),
    l::Op::And(257, 85),
    l::Op::And(258, 60),
    l::Op::And(259, 237),
    l::Op::And(260, 240),
    l::Op::And(261, 243),
    l::Op::And(262, 245),
    l::Op::And(263, 247),
    l::Op::And(264, 251),
    l::Op::And(265, 255),
    l::Op::Select(227, 266, 0),
    l::Op::Literal(l::Atom::I128(160)),
    l::Op::Eq(73, 268),
    l::Op::And(269, 173),
    l::Op::And(270, 225),
    l::Op::And(229, 271),
    l::Op::Not(271),
    l::Op::And(229, 273),
    l::Op::ObserveWhen(272, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(275),
    l::Op::Literal(l::Atom::I128(214)),
    l::Op::Eq(276, 277),
    l::Op::ObserveWhen(272, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::ToI128(279),
    l::Op::Eq(280, 91),
    l::Op::Select(272, 281, 0),
    l::Op::ObserveWhen(272, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(283),
    l::Op::Eq(284, 24),
    l::Op::ObserveWhen(272, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(286),
    l::Op::Eq(287, 99),
    l::Op::ObserveWhen(
        272,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"compliance-team"),
    ),
    l::Op::Eq(289, 102),
    l::Op::ObserveWhen(272, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(291, 105),
    l::Op::ObserveWhen(
        272,
        l::Observation::OutboxPayload(0, 147),
        l::Atom::Sum {
            type_id: 114,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 114,
        variant: 174,
    }),
    l::Op::Eq(293, 294),
    l::Op::Select(272, 295, 0),
    l::Op::ObserveWhen(272, l::Observation::OutboxPayload(0, 148), l::Atom::I128(0)),
    l::Op::ToI128(297),
    l::Op::Eq(298, 91),
    l::Op::Select(272, 299, 0),
    l::Op::And(116, 278),
    l::Op::And(301, 25),
    l::Op::And(302, 85),
    l::Op::And(303, 60),
    l::Op::And(304, 282),
    l::Op::And(305, 285),
    l::Op::And(306, 288),
    l::Op::And(307, 290),
    l::Op::And(308, 292),
    l::Op::And(309, 296),
    l::Op::And(310, 300),
    l::Op::Select(272, 311, 0),
    l::Op::And(274, 177),
    l::Op::Not(177),
    l::Op::And(274, 314),
    l::Op::ObserveWhen(313, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::ToI128(316),
    l::Op::Eq(317, 40),
    l::Op::Select(313, 318, 0),
    l::Op::ObserveWhen(313, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(320),
    l::Op::Eq(321, 24),
    l::Op::ObserveWhen(313, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(323),
    l::Op::Literal(l::Atom::I128(300)),
    l::Op::Eq(324, 325),
    l::Op::ObserveWhen(
        313,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"review-queue"),
    ),
    l::Op::Literal(l::Atom::Text(b"review-queue")),
    l::Op::Eq(327, 328),
    l::Op::ObserveWhen(313, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(330, 105),
    l::Op::ObserveWhen(
        313,
        l::Observation::OutboxPayload(0, 145),
        l::Atom::Sum {
            type_id: 114,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 114,
        variant: 175,
    }),
    l::Op::Eq(332, 333),
    l::Op::Select(313, 334, 0),
    l::Op::ObserveWhen(313, l::Observation::OutboxPayload(0, 146), l::Atom::I128(0)),
    l::Op::ToI128(336),
    l::Op::Eq(337, 223),
    l::Op::Select(313, 338, 0),
    l::Op::And(67, 85),
    l::Op::And(340, 60),
    l::Op::And(341, 319),
    l::Op::And(342, 322),
    l::Op::And(343, 326),
    l::Op::And(344, 329),
    l::Op::And(345, 331),
    l::Op::And(346, 335),
    l::Op::And(347, 339),
    l::Op::Select(313, 348, 0),
    l::Op::And(315, 221),
    l::Op::Not(221),
    l::Op::And(315, 351),
    l::Op::ObserveWhen(350, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::ToI128(353),
    l::Op::Eq(354, 40),
    l::Op::Select(350, 355, 0),
    l::Op::ObserveWhen(350, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(357),
    l::Op::Eq(358, 24),
    l::Op::ObserveWhen(350, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(360),
    l::Op::Eq(361, 325),
    l::Op::ObserveWhen(
        350,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"review-queue"),
    ),
    l::Op::Eq(363, 328),
    l::Op::ObserveWhen(350, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(365, 105),
    l::Op::ObserveWhen(
        350,
        l::Observation::OutboxPayload(0, 145),
        l::Atom::Sum {
            type_id: 114,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 114,
        variant: 176,
    }),
    l::Op::Eq(367, 368),
    l::Op::Select(350, 369, 0),
    l::Op::ObserveWhen(350, l::Observation::OutboxPayload(0, 146), l::Atom::I128(0)),
    l::Op::ToI128(371),
    l::Op::Eq(372, 223),
    l::Op::Select(350, 373, 0),
    l::Op::And(341, 356),
    l::Op::And(375, 359),
    l::Op::And(376, 362),
    l::Op::And(377, 364),
    l::Op::And(378, 366),
    l::Op::And(379, 370),
    l::Op::And(380, 374),
    l::Op::Select(350, 381, 0),
    l::Op::Lt(223, 7),
    l::Op::Not(383),
    l::Op::And(173, 384),
    l::Op::And(352, 385),
    l::Op::Not(385),
    l::Op::And(352, 387),
    l::Op::ObserveWhen(386, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::ToI128(389),
    l::Op::Eq(390, 40),
    l::Op::Select(386, 391, 0),
    l::Op::ObserveWhen(386, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(393),
    l::Op::Eq(394, 24),
    l::Op::ObserveWhen(386, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(396),
    l::Op::Eq(397, 325),
    l::Op::ObserveWhen(
        386,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"review-queue"),
    ),
    l::Op::Eq(399, 328),
    l::Op::ObserveWhen(386, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(401, 105),
    l::Op::ObserveWhen(
        386,
        l::Observation::OutboxPayload(0, 145),
        l::Atom::Sum {
            type_id: 114,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 114,
        variant: 177,
    }),
    l::Op::Eq(403, 404),
    l::Op::Select(386, 405, 0),
    l::Op::ObserveWhen(386, l::Observation::OutboxPayload(0, 146), l::Atom::I128(0)),
    l::Op::ToI128(407),
    l::Op::Eq(408, 223),
    l::Op::Select(386, 409, 0),
    l::Op::And(341, 392),
    l::Op::And(411, 395),
    l::Op::And(412, 398),
    l::Op::And(413, 400),
    l::Op::And(414, 402),
    l::Op::And(415, 406),
    l::Op::And(416, 410),
    l::Op::Select(386, 417, 0),
    l::Op::Eq(172, 7),
    l::Op::And(419, 225),
    l::Op::And(388, 420),
    l::Op::Not(420),
    l::Op::And(388, 422),
    l::Op::ObserveWhen(421, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::ToI128(424),
    l::Op::Eq(425, 40),
    l::Op::Select(421, 426, 0),
    l::Op::ObserveWhen(421, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(428),
    l::Op::Eq(429, 24),
    l::Op::ObserveWhen(421, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(431),
    l::Op::Eq(432, 325),
    l::Op::ObserveWhen(
        421,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"review-queue"),
    ),
    l::Op::Eq(434, 328),
    l::Op::ObserveWhen(421, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(436, 105),
    l::Op::ObserveWhen(
        421,
        l::Observation::OutboxPayload(0, 145),
        l::Atom::Sum {
            type_id: 114,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 114,
        variant: 178,
    }),
    l::Op::Eq(438, 439),
    l::Op::Select(421, 440, 0),
    l::Op::ObserveWhen(421, l::Observation::OutboxPayload(0, 146), l::Atom::I128(0)),
    l::Op::ToI128(442),
    l::Op::Eq(443, 223),
    l::Op::Select(421, 444, 0),
    l::Op::And(341, 427),
    l::Op::And(446, 430),
    l::Op::And(447, 433),
    l::Op::And(448, 435),
    l::Op::And(449, 437),
    l::Op::And(450, 441),
    l::Op::And(451, 445),
    l::Op::Select(421, 452, 0),
    l::Op::Lt(40, 79),
    l::Op::Not(454),
    l::Op::Lt(223, 79),
    l::Op::Not(456),
    l::Op::And(455, 457),
    l::Op::And(423, 458),
    l::Op::Not(458),
    l::Op::And(423, 460),
    l::Op::ObserveWhen(459, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::ToI128(462),
    l::Op::Eq(463, 40),
    l::Op::Select(459, 464, 0),
    l::Op::ObserveWhen(459, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(466),
    l::Op::Eq(467, 24),
    l::Op::ObserveWhen(459, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(469),
    l::Op::Eq(470, 325),
    l::Op::ObserveWhen(
        459,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"review-queue"),
    ),
    l::Op::Eq(472, 328),
    l::Op::ObserveWhen(459, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(474, 105),
    l::Op::ObserveWhen(
        459,
        l::Observation::OutboxPayload(0, 145),
        l::Atom::Sum {
            type_id: 114,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 114,
        variant: 179,
    }),
    l::Op::Eq(476, 477),
    l::Op::Select(459, 478, 0),
    l::Op::ObserveWhen(459, l::Observation::OutboxPayload(0, 146), l::Atom::I128(0)),
    l::Op::ToI128(480),
    l::Op::Eq(481, 223),
    l::Op::Select(459, 482, 0),
    l::Op::And(341, 465),
    l::Op::And(484, 468),
    l::Op::And(485, 471),
    l::Op::And(486, 473),
    l::Op::And(487, 475),
    l::Op::And(488, 479),
    l::Op::And(489, 483),
    l::Op::Select(459, 490, 0),
    l::Op::Literal(l::Atom::I128(166)),
    l::Op::Eq(175, 492),
    l::Op::Literal(l::Atom::I128(4)),
    l::Op::Eq(223, 494),
    l::Op::And(493, 495),
    l::Op::And(461, 496),
    l::Op::Not(496),
    l::Op::And(461, 498),
    l::Op::ObserveWhen(497, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::ToI128(500),
    l::Op::Eq(501, 40),
    l::Op::Select(497, 502, 0),
    l::Op::ObserveWhen(497, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(504),
    l::Op::Eq(505, 24),
    l::Op::ObserveWhen(497, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(507),
    l::Op::Eq(508, 325),
    l::Op::ObserveWhen(
        497,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"review-queue"),
    ),
    l::Op::Eq(510, 328),
    l::Op::ObserveWhen(497, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(512, 105),
    l::Op::ObserveWhen(
        497,
        l::Observation::OutboxPayload(0, 145),
        l::Atom::Sum {
            type_id: 114,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 114,
        variant: 180,
    }),
    l::Op::Eq(514, 515),
    l::Op::Select(497, 516, 0),
    l::Op::ObserveWhen(497, l::Observation::OutboxPayload(0, 146), l::Atom::I128(0)),
    l::Op::ToI128(518),
    l::Op::Eq(519, 223),
    l::Op::Select(497, 520, 0),
    l::Op::And(341, 503),
    l::Op::And(522, 506),
    l::Op::And(523, 509),
    l::Op::And(524, 511),
    l::Op::And(525, 513),
    l::Op::And(526, 517),
    l::Op::And(527, 521),
    l::Op::Select(497, 528, 0),
    l::Op::And(499, 0),
    l::Op::Not(0),
    l::Op::And(499, 531),
    l::Op::ObserveWhen(530, l::Observation::Post(120), l::Atom::I128(0)),
    l::Op::ToI128(533),
    l::Op::Eq(534, 40),
    l::Op::Select(530, 535, 0),
    l::Op::And(69, 536),
    l::Op::Select(530, 537, 0),
    l::Op::Not(532),
    l::Op::And(0, 38),
    l::Op::And(540, 54),
    l::Op::And(541, 71),
    l::Op::And(542, 128),
    l::Op::And(543, 170),
    l::Op::And(544, 219),
    l::Op::And(545, 267),
    l::Op::And(546, 312),
    l::Op::And(547, 349),
    l::Op::And(548, 382),
    l::Op::And(549, 418),
    l::Op::And(550, 453),
    l::Op::And(551, 491),
    l::Op::And(552, 529),
    l::Op::And(553, 538),
    l::Op::And(554, 539),
];
/// Original scoped laws plus independent structural requirements.
pub const LAWS: &[l::Law<'static>] = &[
    l::Law {
        id: 500,
        kind: l::Kind::StateInvariant,
        scope: l::Scope::Committing,
        genesis: true,
        program: l::Program {
            nodes: LAW_500,
            root: 8,
        },
    },
    l::Law {
        id: 501,
        kind: l::Kind::AuthoritySubjectRecipient,
        scope: l::Scope::Accept,
        genesis: false,
        program: l::Program {
            nodes: LAW_501,
            root: 22,
        },
    },
    l::Law {
        id: 502,
        kind: l::Kind::AuthoritySubjectRecipient,
        scope: l::Scope::Accept,
        genesis: false,
        program: l::Program {
            nodes: LAW_502,
            root: 22,
        },
    },
    l::Law {
        id: 503,
        kind: l::Kind::CommittedFailureEffects,
        scope: l::Scope::CommittedFailure,
        genesis: false,
        program: l::Program {
            nodes: LAW_503,
            root: 26,
        },
    },
    l::Law {
        id: 509,
        kind: l::Kind::RejectNoAuthority,
        scope: l::Scope::Reject,
        genesis: false,
        program: l::Program {
            nodes: LAW_509,
            root: 17,
        },
    },
    l::Law {
        id: 990,
        kind: l::Kind::InitialCondition,
        scope: l::Scope::Always,
        genesis: true,
        program: l::Program {
            nodes: LAW_990,
            root: 4,
        },
    },
    l::Law {
        id: 991,
        kind: l::Kind::DecisionConformance,
        scope: l::Scope::Always,
        genesis: false,
        program: l::Program {
            nodes: LAW_991,
            root: 555,
        },
    },
];
/// No declared law is optional at descriptor admission.
pub const REQUIRED: &[u32] = &[500, 501, 502, 503, 509, 990, 991];
/// Owns declarative input/output type tables; evaluation stays in the library.
pub struct Contract {
    state: Vec<InputField>,
    command: Vec<InputField>,
    context: Vec<InputField>,
    output_types: Vec<InputLeaf>,
}
impl Default for Contract {
    fn default() -> Self {
        Self::new()
    }
}
impl Contract {
    /// Allocate only fixed declarative type tables.
    #[must_use]
    pub fn new() -> Self {
        Self {
            state: vec![InputField {
                id: 120,
                leaf: InputLeaf::I128 { min: 0, max: 3 },
            }],
            command: vec![
                InputField {
                    id: 130,
                    leaf: InputLeaf::Sum {
                        type_id: 111,
                        min: 150,
                        max: 151,
                        variants: vec![
                            InputVariant { id: 150, code: 150 },
                            InputVariant { id: 151, code: 151 },
                        ],
                    },
                },
                InputField {
                    id: 131,
                    leaf: InputLeaf::Sum {
                        type_id: 112,
                        min: 160,
                        max: 162,
                        variants: vec![
                            InputVariant { id: 160, code: 160 },
                            InputVariant { id: 161, code: 161 },
                            InputVariant { id: 162, code: 162 },
                        ],
                    },
                },
                InputField {
                    id: 132,
                    leaf: InputLeaf::I128 { min: 0, max: 4 },
                },
                InputField {
                    id: 133,
                    leaf: InputLeaf::Sum {
                        type_id: 113,
                        min: 165,
                        max: 167,
                        variants: vec![
                            InputVariant { id: 165, code: 165 },
                            InputVariant { id: 166, code: 166 },
                            InputVariant { id: 167, code: 167 },
                        ],
                    },
                },
            ],
            context: vec![
                InputField {
                    id: 140,
                    leaf: InputLeaf::I128 { min: 0, max: 3 },
                },
                InputField {
                    id: 141,
                    leaf: InputLeaf::Bool,
                },
            ],
            output_types: vec![
                InputLeaf::I128 { min: 0, max: 14 },
                InputLeaf::I128 {
                    min: -9223372036854775808,
                    max: 9223372036854775807,
                },
            ],
        }
    }
    /// Borrow the full raw-input, complete-decision and law contract.
    #[must_use]
    pub fn descriptor(&self) -> c::Descriptor<'_> {
        c::Descriptor {
            state: c::Schema::Record(&self.state),
            command: c::Schema::Record(&self.command),
            context: c::Schema::Record(&self.context),
            program: V2ScalarProgram {
                inputs: &[
                    ScalarDomain::Int { min: 0, max: 3 },
                    ScalarDomain::Int { min: 150, max: 151 },
                    ScalarDomain::Int { min: 160, max: 162 },
                    ScalarDomain::Int { min: 0, max: 4 },
                    ScalarDomain::Int { min: 165, max: 167 },
                    ScalarDomain::Int { min: 0, max: 3 },
                    ScalarDomain::Bool,
                ],
                outputs: &[
                    ScalarDomain::Int { min: 0, max: 14 },
                    ScalarDomain::Int {
                        min: -9223372036854775808,
                        max: 9223372036854775807,
                    },
                ],
                nodes: &[
                    Op::Input(1),
                    Op::Int(151),
                    Op::Eq(0, 1),
                    Op::Input(6),
                    Op::Not(3),
                    Op::And(2, 4),
                    Op::Int(0),
                    Op::Input(0),
                    Op::Eq(7, 6),
                    Op::And(2, 8),
                    Op::Int(1),
                    Op::Int(2),
                    Op::Input(2),
                    Op::Int(162),
                    Op::Eq(12, 13),
                    Op::Int(3),
                    Op::Eq(7, 15),
                    Op::Int(4),
                    Op::Input(5),
                    Op::Eq(18, 6),
                    Op::Input(4),
                    Op::Int(167),
                    Op::Eq(20, 21),
                    Op::And(19, 22),
                    Op::Int(5),
                    Op::Int(161),
                    Op::Eq(12, 25),
                    Op::Input(3),
                    Op::Lt(27, 15),
                    Op::Not(28),
                    Op::And(26, 29),
                    Op::Int(6),
                    Op::Int(160),
                    Op::Eq(12, 32),
                    Op::And(33, 19),
                    Op::And(34, 29),
                    Op::Int(7),
                    Op::Int(8),
                    Op::Int(9),
                    Op::Lt(27, 10),
                    Op::Not(39),
                    Op::And(19, 40),
                    Op::Int(10),
                    Op::Eq(18, 10),
                    Op::And(43, 29),
                    Op::Int(11),
                    Op::Lt(7, 11),
                    Op::Not(46),
                    Op::Lt(27, 11),
                    Op::Not(48),
                    Op::And(47, 49),
                    Op::Int(12),
                    Op::Int(166),
                    Op::Eq(20, 52),
                    Op::Eq(27, 17),
                    Op::And(53, 54),
                    Op::Int(13),
                    Op::Int(14),
                    Op::Select(55, 56, 57),
                    Op::Select(50, 51, 58),
                    Op::Select(44, 45, 59),
                    Op::Select(41, 42, 60),
                    Op::Select(26, 38, 61),
                    Op::Select(22, 37, 62),
                    Op::Select(35, 36, 63),
                    Op::Select(30, 31, 64),
                    Op::Select(23, 24, 65),
                    Op::Select(16, 17, 66),
                    Op::Select(14, 15, 67),
                    Op::Select(2, 11, 68),
                    Op::Select(9, 10, 69),
                    Op::Select(5, 6, 70),
                    Op::Lt(7, 15),
                    Op::Add(7, 10),
                    Op::Select(72, 73, 15),
                ],
                roots: &[71, 74],
            },
            bindings: &[
                c::Binding {
                    source: c::Source::State,
                    selector: c::Selector::Field(120),
                },
                c::Binding {
                    source: c::Source::Command,
                    selector: c::Selector::Field(130),
                },
                c::Binding {
                    source: c::Source::Command,
                    selector: c::Selector::Field(131),
                },
                c::Binding {
                    source: c::Source::Command,
                    selector: c::Selector::Field(132),
                },
                c::Binding {
                    source: c::Source::Command,
                    selector: c::Selector::Field(133),
                },
                c::Binding {
                    source: c::Source::Context,
                    selector: c::Selector::Field(140),
                },
                c::Binding {
                    source: c::Source::Context,
                    selector: c::Selector::Field(141),
                },
            ],
            output_types: &self.output_types,
            decision_output: 0,
            branches: BRANCHES,
            reasons: &[
                c::Reason {
                    id: 200,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 201,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 210,
                    class: c::Class::CommittedFailure,
                },
                c::Reason {
                    id: 211,
                    class: c::Class::CommittedFailure,
                },
                c::Reason {
                    id: 212,
                    class: c::Class::CommittedFailure,
                },
                c::Reason {
                    id: 213,
                    class: c::Class::CommittedFailure,
                },
                c::Reason {
                    id: 214,
                    class: c::Class::CommittedFailure,
                },
            ],
            channels: &[
                c::Channel {
                    id: 300,
                    destination: c::Domain::Text,
                    payload: &[
                        c::TypedField {
                            field: 145,
                            domain: c::Domain::Sum {
                                type_id: 114,
                                variants: &[
                                    170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
                                ],
                            },
                        },
                        c::TypedField {
                            field: 146,
                            domain: c::Domain::I128 { min: 0, max: 4 },
                        },
                    ],
                    idempotency: c::Domain::U128 { min: 0, max: 0 },
                },
                c::Channel {
                    id: 301,
                    destination: c::Domain::Text,
                    payload: &[
                        c::TypedField {
                            field: 147,
                            domain: c::Domain::Sum {
                                type_id: 114,
                                variants: &[
                                    170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
                                ],
                            },
                        },
                        c::TypedField {
                            field: 148,
                            domain: c::Domain::I128 { min: 0, max: 3 },
                        },
                    ],
                    idempotency: c::Domain::U128 { min: 0, max: 0 },
                },
            ],
            laws: LAWS,
            required: REQUIRED,
            limits: v2_zero_limits()
                .with_limit(Resource::Read, 200)
                .with_limit(Resource::Write, 1)
                .with_limit(Resource::Candidate, 1)
                .with_limit(Resource::Effect, 1)
                .with_limit(Resource::Byte, 249)
                .with_limit(Resource::WitnessByte, 0)
                .with_limit(Resource::Depth, 0)
                .with_limit(Resource::Step, 741),
        }
    }
}
/// Exact complete schema/policy correspondence precedes Authority construction.
pub fn checked_catalog<'a>(
    descriptor: &'a c::Descriptor<'a>,
) -> Result<catalog::BoundCatalog<'a>, catalog::Failure> {
    catalog::bind_original(
        ORIGINAL_SCHEMA,
        &DESCRIPTION,
        catalog::Limits {
            schema: s::Limits {
                bytes: ORIGINAL_SCHEMA.len() as u64,
                types: 15,
                fields: 4,
                variants: 12,
            },
            contract_bytes: ORIGINAL_POLICY.len() as u64,
        },
        ORIGINAL_POLICY,
        descriptor,
        &FRAMING,
        CHANNEL_ROOTS,
    )
}
/// Ordered refusal at checked catalog or private Authority construction.
#[derive(Debug)]
#[non_exhaustive]
pub enum BindFailure {
    /// Complete original schema/policy correspondence refused.
    Catalog(catalog::Failure),
    /// Private library source binding refused.
    Authority(authority::Refusal),
}
/// Sole supplied production constructor; identity comes from the checked library.
pub fn checked_authority<'a>(
    descriptor: &'a c::Descriptor<'a>,
) -> Result<authority::Authority<'a>, BindFailure> {
    let catalog = checked_catalog(descriptor).map_err(BindFailure::Catalog)?;
    authority::bind(&catalog).map_err(BindFailure::Authority)
}
