// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity 0.8.36;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";

/// @notice Generated by zeno-fcis-solidity/2.
/// @dev Regenerate this base. Derived contracts implement only the pure hooks.
abstract contract TreasuryMachineFcis {
    using SafeERC20 for IERC20;

    bytes32 public constant MACHINE_HASH = 0xbd5c612ad6484fa025e8f2b6dee9a868a9a54bd7beb8c2904760011b854039de;
    uint16 public constant MACHINE_VERSION = 1;
    uint8 private constant MAX_EVENT_SLOTS = 1;
    uint8 private constant MAX_EFFECT_SLOTS = 1;

    enum DecisionKind { Accept, Reject }

    struct State {
        bytes32 owner;
        uint128 balance;
    }

    struct Command {
        bytes32 recipient;
        uint128 amount;
    }

    struct Context {
        bytes32 actor;
        bytes32 chainDomain;
        uint64 sequence;
        uint64 blockNumber;
        uint64 timestamp;
    }

    struct EventPlan {
        uint16 code;
        uint8 fieldCount;
        bytes32[8] data;
    }

    struct EffectPlan {
        uint16 capability;
        bytes32 assetId;
        bytes32 recipient;
        uint128 amount;
    }

    struct Decision {
        DecisionKind kind;
        uint16 reasonCode;
        State nextState;
        uint8 eventCount;
        EventPlan[1] events;
        uint8 effectCount;
        EffectPlan[1] effects;
    }

    address private immutable _initializationAuthority;
    bool private _initialized;
    uint256 private _gate;
    uint64 private _sequence;
    bytes32 private _stateHash;
    bytes32 private _state_owner;
    uint128 private _state_balance;

    error UnauthorizedInitializer(address expected, address actual);
    error AlreadyInitialized();
    error NotInitialized();
    error Reentrancy();
    error StaleState(bytes32 expectedHash, bytes32 actualHash, uint64 expectedSequence, uint64 actualSequence);
    error StateRootCorrupted(bytes32 committed, bytes32 actual);
    error CommandNotAdmissible();
    error InvariantViolation();
    error InvalidDecision(uint16 reasonCode);
    error TransitionRejected(uint16 reasonCode);
    error InvalidPlan();
    error InvalidCapability(uint16 capability);
    error AssetBindingChanged(uint16 capability, bytes32 expected, bytes32 actual);

    event Initialized(bytes32 indexed stateHash, address indexed authority);
    event DomainEvent(uint16 indexed code, bytes32 indexed payloadHash, bytes32[8] data, uint8 fieldCount);
    event TransitionCommitted(uint64 indexed sequence, bytes32 indexed preStateHash, bytes32 indexed postStateHash, bytes32 candidateHash, bytes32 commandHash, bytes32 contextHash);

    constructor() {
        _initializationAuthority = msg.sender;
        _gate = 1;
    }

    function initializationAuthority() external view returns (address) { return _initializationAuthority; }
    function currentStateHash() external view returns (bytes32) { if (!_initialized) revert NotInitialized(); return _stateHash; }
    function currentSequence() external view returns (uint64) { if (!_initialized) revert NotInitialized(); return _sequence; }
    function currentState() external view returns (State memory) { if (!_initialized) revert NotInitialized(); return _readState(); }

    function initialize(State calldata initialState) external {
        if (msg.sender != _initializationAuthority) revert UnauthorizedInitializer(_initializationAuthority, msg.sender);
        if (_initialized) revert AlreadyInitialized();
        State memory admitted = initialState;
        if (!_invariant(admitted)) revert InvariantViolation();
        _writeState(admitted);
        _stateHash = _hashState(admitted);
        _initialized = true;
        emit Initialized(_stateHash, msg.sender);
    }

    function execute(Command calldata command, bytes32 expectedStateHash, uint64 expectedSequence) external returns (bytes32 postStateHash) {
        if (!_initialized) revert NotInitialized();
        if (_gate != 1) revert Reentrancy();
        _gate = 2;
        State memory beforeState = _readState();
        bytes32 actualStateHash = _hashState(beforeState);
        if (actualStateHash != _stateHash) revert StateRootCorrupted(_stateHash, actualStateHash);
        if (actualStateHash != expectedStateHash || _sequence != expectedSequence) revert StaleState(expectedStateHash, actualStateHash, expectedSequence, _sequence);
        Command memory admittedCommand = command;
        Context memory context = Context({ actor: bytes32(uint256(uint160(msg.sender))), chainDomain: sha256(abi.encode(block.chainid, address(this), MACHINE_HASH)), sequence: _sequence, blockNumber: uint64(block.number), timestamp: uint64(block.timestamp) });
        if (!_commandAdmissible(admittedCommand, context)) revert CommandNotAdmissible();
        Decision memory decision = _decide(beforeState, admittedCommand, context);
        if (decision.kind == DecisionKind.Reject) {
            if (!_knownReason(decision.reasonCode)) revert InvalidDecision(decision.reasonCode);
            revert TransitionRejected(decision.reasonCode);
        }
        if (decision.reasonCode != 0) revert InvalidDecision(decision.reasonCode);
        if (!_invariant(decision.nextState)) revert InvariantViolation();
        _validatePlans(decision, beforeState, admittedCommand, context);
        postStateHash = _hashState(decision.nextState);
        bytes32 commandHash = _hashCommand(admittedCommand);
        bytes32 contextHash = _hashContext(context);
        bytes32 eventPlanHash = _hashEventPlan(decision);
        bytes32 effectPlanHash = _hashEffectPlan(decision);
        bytes32 candidateHash = sha256(abi.encode(MACHINE_HASH, actualStateHash, postStateHash, commandHash, contextHash, eventPlanHash, effectPlanHash));
        _writeState(decision.nextState);
        _stateHash = postStateHash;
        _sequence += 1;
        for (uint256 index = 0; index < decision.eventCount; ++index) {
            EventPlan memory plannedEvent = decision.events[index];
            emit DomainEvent(plannedEvent.code, _hashEvent(plannedEvent), plannedEvent.data, plannedEvent.fieldCount);
        }
        for (uint256 index = 0; index < decision.effectCount; ++index) { _applyEffect(decision.effects[index]); }
        emit TransitionCommitted(_sequence, actualStateHash, postStateHash, candidateHash, commandHash, contextHash);
        _gate = 1;
    }

    function _readState() private view returns (State memory current) {
        current.owner = _state_owner;
        current.balance = _state_balance;
    }

    function _writeState(State memory nextState) private {
        _state_owner = nextState.owner;
        _state_balance = nextState.balance;
    }

    function _hashState(State memory value) private pure returns (bytes32) { return sha256(abi.encode(MACHINE_HASH, uint16(1), value.owner, uint16(2), value.balance)); }
    function _hashCommand(Command memory value) private pure returns (bytes32) { return sha256(abi.encode(MACHINE_HASH, uint16(1), value.recipient, uint16(2), value.amount)); }
    function _hashContext(Context memory value) private pure returns (bytes32) { return sha256(abi.encode(MACHINE_HASH, value.actor, value.chainDomain, value.sequence, value.blockNumber, value.timestamp)); }
    function _hashEvent(EventPlan memory value) private pure returns (bytes32) { return sha256(abi.encode(MACHINE_HASH, value.code, value.fieldCount, value.data)); }
    function _hashEffect(EffectPlan memory value) private pure returns (bytes32) { return sha256(abi.encode(MACHINE_HASH, value.capability, value.assetId, value.recipient, value.amount)); }
    function _hashEventPlan(Decision memory value) private pure returns (bytes32 result) { result = sha256(abi.encode(MACHINE_HASH, value.eventCount)); for (uint256 index = 0; index < value.eventCount; ++index) result = sha256(abi.encode(result, _hashEvent(value.events[index]))); }
    function _hashEffectPlan(Decision memory value) private pure returns (bytes32 result) { result = sha256(abi.encode(MACHINE_HASH, value.effectCount)); for (uint256 index = 0; index < value.effectCount; ++index) result = sha256(abi.encode(result, _hashEffect(value.effects[index]))); }

    function _validatePlans(Decision memory decision, State memory beforeState, Command memory command, Context memory context) private view {
        if (decision.eventCount > MAX_EVENT_SLOTS || decision.effectCount > MAX_EFFECT_SLOTS) revert InvalidPlan();
        bytes32 prior;
        for (uint256 index = 0; index < decision.eventCount; ++index) { EventPlan memory planned = decision.events[index]; if (_eventFieldCount(planned.code) != planned.fieldCount) revert InvalidPlan(); bytes32 digest = _hashEvent(planned); if (index != 0 && uint256(digest) < uint256(prior)) revert InvalidPlan(); prior = digest; }
        for (uint256 index = decision.eventCount; index < 1; ++index) if (!_zeroEvent(decision.events[index])) revert InvalidPlan();
        prior = bytes32(0);
        for (uint256 index = 0; index < decision.effectCount; ++index) { EffectPlan memory planned = decision.effects[index]; _validateEffect(planned, beforeState, command, context); bytes32 digest = _hashEffect(planned); if (index != 0 && uint256(digest) < uint256(prior)) revert InvalidPlan(); prior = digest; uint8 uses; for (uint256 inner = 0; inner <= index; ++inner) if (decision.effects[inner].capability == planned.capability) ++uses; if (uses > _capabilityMaxUses(planned.capability)) revert InvalidPlan(); }
        for (uint256 index = decision.effectCount; index < 1; ++index) if (!_zeroEffect(decision.effects[index])) revert InvalidPlan();
    }

    function _validateEffect(EffectPlan memory planned, State memory beforeState, Command memory command, Context memory context) private view {
        if (!_knownCapability(planned.capability) || planned.amount == 0 || planned.amount > _capabilityMaxAmount(planned.capability)) revert InvalidCapability(planned.capability);
        if (planned.assetId != _capabilityAsset(planned.capability) || planned.recipient != _expectedRecipient(planned.capability, beforeState, command, context) || uint256(planned.recipient) > type(uint160).max) revert InvalidCapability(planned.capability);
        address token = _tokenAddress(planned.capability); bytes32 actualCodeHash = token.codehash; bytes32 expectedCodeHash = _tokenCodeHash(planned.capability); if (actualCodeHash != expectedCodeHash) revert AssetBindingChanged(planned.capability, expectedCodeHash, actualCodeHash);
    }

    function _zeroEvent(EventPlan memory value) private pure returns (bool) { if (value.code != 0 || value.fieldCount != 0) return false; for (uint256 index = 0; index < 8; ++index) if (value.data[index] != bytes32(0)) return false; return true; }
    function _zeroEffect(EffectPlan memory value) private pure returns (bool) { return value.capability == 0 && value.assetId == bytes32(0) && value.recipient == bytes32(0) && value.amount == 0; }
    function _applyEffect(EffectPlan memory planned) private { IERC20(_tokenAddress(planned.capability)).safeTransfer(address(uint160(uint256(planned.recipient))), uint256(planned.amount)); }

    function _eventPaid(bytes32 recipient, uint128 amount) internal pure returns (EventPlan memory planned) {
        planned.code = 1;
        planned.fieldCount = 2;
        planned.data[0] = recipient;
        planned.data[1] = bytes32(uint256(amount));
    }

    function _effectPayout(uint128 amount, State memory beforeState, Command memory command, Context memory context) internal pure returns (EffectPlan memory planned) {
        planned.capability = 7;
        planned.assetId = 0x0808080808080808080808080808080808080808080808080808080808080808;
        planned.recipient = command.recipient;
        planned.amount = amount;
    }

    function _knownReason(uint16 code) private pure returns (bool) { return code == 1 || code == 2; }
    function _knownCapability(uint16 code) private pure returns (bool) { return code == 7; }
    function _eventFieldCount(uint16 code) private pure returns (uint8) {
        if (code == 1) return 2;
        revert InvalidPlan();
    }
    function _capabilityAsset(uint16 code) private pure returns (bytes32) {
        if (code == 7) return 0x0808080808080808080808080808080808080808080808080808080808080808;
        revert InvalidCapability(code);
    }
    function _capabilityMaxAmount(uint16 code) private pure returns (uint128) {
        if (code == 7) return 1000000;
        revert InvalidCapability(code);
    }
    function _capabilityMaxUses(uint16 code) private pure returns (uint8) {
        if (code == 7) return 1;
        revert InvalidCapability(code);
    }
    function _expectedRecipient(uint16 code, State memory beforeState, Command memory command, Context memory context) private pure returns (bytes32) {
        if (code == 7) return command.recipient;
        revert InvalidCapability(code);
    }
    function _tokenAddress(uint16 code) private pure returns (address) {
        if (code == 7) return 0x0303030303030303030303030303030303030303;
        revert InvalidCapability(code);
    }
    function _tokenCodeHash(uint16 code) private pure returns (bytes32) {
        if (code == 7) return 0x0404040404040404040404040404040404040404040404040404040404040404;
        revert InvalidCapability(code);
    }

    function _commandAdmissible(Command memory command, Context memory context) internal pure virtual returns (bool);

    function _invariant(State memory stateValue) internal pure virtual returns (bool);

    function _decide(State memory stateValue, Command memory command, Context memory context) internal pure virtual returns (Decision memory);
}
