//! Closed, package-local file set for the account-lockout example.

pub(crate) const FILES: &[(&str, &[u8])] = &[
    (
        "project.zeno",
        include_bytes!("../templates/account-lockout/project.zeno"),
    ),
    (
        "README.md",
        include_bytes!("../templates/account-lockout/README.md"),
    ),
    (
        "Cargo.toml",
        include_bytes!("../templates/account-lockout/Cargo.toml.in"),
    ),
    (
        "build.rs",
        include_bytes!("../templates/account-lockout/build.rs"),
    ),
    (
        "profile.rs",
        include_bytes!("../templates/account-lockout/profile.rs"),
    ),
    (
        "src/delivery.rs",
        include_bytes!("../templates/account-lockout/src/delivery.rs"),
    ),
    (
        "src/laws.rs",
        include_bytes!("../templates/account-lockout/src/laws.rs"),
    ),
    (
        "src/lib.rs",
        include_bytes!("../templates/account-lockout/src/lib.rs"),
    ),
    (
        "src/main.rs",
        include_bytes!("../templates/account-lockout/src/main.rs"),
    ),
    (
        "src/program.rs",
        include_bytes!("../templates/account-lockout/src/program.rs"),
    ),
    (
        "tests/claims.rs",
        include_bytes!("../templates/account-lockout/tests/claims.rs"),
    ),
    (
        "tests/conformance.rs",
        include_bytes!("../templates/account-lockout/tests/conformance.rs"),
    ),
    (
        "tests/decision-examples.txt",
        include_bytes!("../templates/account-lockout/tests/decision-examples.txt"),
    ),
    (
        "tests/determinism.rs",
        include_bytes!("../templates/account-lockout/tests/determinism.rs"),
    ),
    (
        "tests/laws.rs",
        include_bytes!("../templates/account-lockout/tests/laws.rs"),
    ),
    (
        "tests/lifecycle.rs",
        include_bytes!("../templates/account-lockout/tests/lifecycle.rs"),
    ),
];
