//! Closed, package-local file set for the agent-treasury-guard example.

pub(crate) const FILES: &[(&str, &[u8])] = &[
    (
        "project.zeno",
        include_bytes!("../templates/agent-treasury-guard/project.zeno"),
    ),
    (
        "README.md",
        include_bytes!("../templates/agent-treasury-guard/README.md"),
    ),
    (
        "Cargo.toml",
        include_bytes!("../templates/agent-treasury-guard/Cargo.toml.in"),
    ),
    (
        "build.rs",
        include_bytes!("../templates/agent-treasury-guard/build.rs"),
    ),
    (
        "profile.rs",
        include_bytes!("../templates/agent-treasury-guard/profile.rs"),
    ),
    (
        "src/delivery.rs",
        include_bytes!("../templates/agent-treasury-guard/src/delivery.rs"),
    ),
    (
        "src/laws.rs",
        include_bytes!("../templates/agent-treasury-guard/src/laws.rs"),
    ),
    (
        "src/lib.rs",
        include_bytes!("../templates/agent-treasury-guard/src/lib.rs"),
    ),
    (
        "src/main.rs",
        include_bytes!("../templates/agent-treasury-guard/src/main.rs"),
    ),
    (
        "src/program.rs",
        include_bytes!("../templates/agent-treasury-guard/src/program.rs"),
    ),
    (
        "synthesis.json",
        include_bytes!("../templates/agent-treasury-guard/synthesis.json"),
    ),
    (
        "synthesized/manifest.json",
        include_bytes!("../templates/agent-treasury-guard/synthesized/manifest.json"),
    ),
    (
        "synthesized/problem.json",
        include_bytes!("../templates/agent-treasury-guard/synthesized/problem.json"),
    ),
    (
        "synthesized/program.zcve",
        include_bytes!("../templates/agent-treasury-guard/synthesized/program.zcve"),
    ),
    (
        "synthesized/transition.rs",
        include_bytes!("../templates/agent-treasury-guard/synthesized/transition.rs"),
    ),
    (
        "synthesized/vectors.json",
        include_bytes!("../templates/agent-treasury-guard/synthesized/vectors.json"),
    ),
    (
        "tests/claims.rs",
        include_bytes!("../templates/agent-treasury-guard/tests/claims.rs"),
    ),
    (
        "tests/conformance.rs",
        include_bytes!("../templates/agent-treasury-guard/tests/conformance.rs"),
    ),
    (
        "tests/decision-examples.txt",
        include_bytes!("../templates/agent-treasury-guard/tests/decision-examples.txt"),
    ),
    (
        "tests/determinism.rs",
        include_bytes!("../templates/agent-treasury-guard/tests/determinism.rs"),
    ),
    (
        "tests/laws.rs",
        include_bytes!("../templates/agent-treasury-guard/tests/laws.rs"),
    ),
    (
        "tests/lifecycle.rs",
        include_bytes!("../templates/agent-treasury-guard/tests/lifecycle.rs"),
    ),
];
