//! Closed, package-local file set for the compliance-gateway example.

pub(crate) const FILES: &[(&str, &[u8])] = &[
    (
        "project.zeno",
        include_bytes!("../templates/compliance-gateway/project.zeno"),
    ),
    (
        "README.md",
        include_bytes!("../templates/compliance-gateway/README.md"),
    ),
    (
        "Cargo.toml",
        include_bytes!("../templates/compliance-gateway/Cargo.toml.in"),
    ),
    (
        "build.rs",
        include_bytes!("../templates/compliance-gateway/build.rs"),
    ),
    (
        "profile.rs",
        include_bytes!("../templates/compliance-gateway/profile.rs"),
    ),
    (
        "rules.txt",
        include_bytes!("../templates/compliance-gateway/rules.txt"),
    ),
    (
        "rules_to_synthesis.py",
        include_bytes!("../templates/compliance-gateway/rules_to_synthesis.py"),
    ),
    (
        "src/delivery.rs",
        include_bytes!("../templates/compliance-gateway/src/delivery.rs"),
    ),
    (
        "src/laws.rs",
        include_bytes!("../templates/compliance-gateway/src/laws.rs"),
    ),
    (
        "src/lib.rs",
        include_bytes!("../templates/compliance-gateway/src/lib.rs"),
    ),
    (
        "src/main.rs",
        include_bytes!("../templates/compliance-gateway/src/main.rs"),
    ),
    (
        "src/program.rs",
        include_bytes!("../templates/compliance-gateway/src/program.rs"),
    ),
    (
        "src/rules.rs",
        include_bytes!("../templates/compliance-gateway/src/rules.rs"),
    ),
    (
        "synthesis.json",
        include_bytes!("../templates/compliance-gateway/synthesis.json"),
    ),
    (
        "synthesized/manifest.json",
        include_bytes!("../templates/compliance-gateway/synthesized/manifest.json"),
    ),
    (
        "synthesized/problem.json",
        include_bytes!("../templates/compliance-gateway/synthesized/problem.json"),
    ),
    (
        "synthesized/program.zcve",
        include_bytes!("../templates/compliance-gateway/synthesized/program.zcve"),
    ),
    (
        "synthesized/transition.rs",
        include_bytes!("../templates/compliance-gateway/synthesized/transition.rs"),
    ),
    (
        "synthesized/vectors.json",
        include_bytes!("../templates/compliance-gateway/synthesized/vectors.json"),
    ),
    (
        "tau/check.py",
        include_bytes!("../templates/compliance-gateway/tau/check.py"),
    ),
    (
        "tau/rule-base.tau",
        include_bytes!("../templates/compliance-gateway/tau/rule-base.tau"),
    ),
    (
        "tests/claims.rs",
        include_bytes!("../templates/compliance-gateway/tests/claims.rs"),
    ),
    (
        "tests/conformance.rs",
        include_bytes!("../templates/compliance-gateway/tests/conformance.rs"),
    ),
    (
        "tests/decision-examples.txt",
        include_bytes!("../templates/compliance-gateway/tests/decision-examples.txt"),
    ),
    (
        "tests/determinism.rs",
        include_bytes!("../templates/compliance-gateway/tests/determinism.rs"),
    ),
    (
        "tests/laws.rs",
        include_bytes!("../templates/compliance-gateway/tests/laws.rs"),
    ),
    (
        "tests/lifecycle.rs",
        include_bytes!("../templates/compliance-gateway/tests/lifecycle.rs"),
    ),
    (
        "tests/rule_base.rs",
        include_bytes!("../templates/compliance-gateway/tests/rule_base.rs"),
    ),
];
