//! Closed, package-local file set for the runnable development example.

pub(crate) const FILES: &[(&str, &[u8])] = &[
    (
        "project.zeno",
        include_bytes!("../templates/durable-counter/project.zeno"),
    ),
    (
        "README.md",
        include_bytes!("../templates/durable-counter/README.md"),
    ),
    (
        "Cargo.toml",
        include_bytes!("../templates/durable-counter/Cargo.toml.in"),
    ),
    (
        "build.rs",
        include_bytes!("../templates/durable-counter/build.rs"),
    ),
    (
        "profile.rs",
        include_bytes!("../templates/durable-counter/profile.rs"),
    ),
    (
        "src/lib.rs",
        include_bytes!("../templates/durable-counter/src/lib.rs"),
    ),
    (
        "src/main.rs",
        include_bytes!("../templates/durable-counter/src/main.rs"),
    ),
    (
        "src/program.rs",
        include_bytes!("../templates/durable-counter/src/program.rs"),
    ),
    (
        "src/laws.rs",
        include_bytes!("../templates/durable-counter/src/laws.rs"),
    ),
    (
        "src/delivery.rs",
        include_bytes!("../templates/durable-counter/src/delivery.rs"),
    ),
    (
        "tests/lifecycle.rs",
        include_bytes!("../templates/durable-counter/tests/lifecycle.rs"),
    ),
    (
        "tests/laws.rs",
        include_bytes!("../templates/durable-counter/tests/laws.rs"),
    ),
    (
        "synthesis.json",
        include_bytes!("../templates/durable-counter/synthesis.json"),
    ),
    (
        "synthesized/problem.json",
        include_bytes!("../templates/durable-counter/synthesized/problem.json"),
    ),
    (
        "synthesized/manifest.json",
        include_bytes!("../templates/durable-counter/synthesized/manifest.json"),
    ),
    (
        "synthesized/vectors.json",
        include_bytes!("../templates/durable-counter/synthesized/vectors.json"),
    ),
    (
        "synthesized/transition.rs",
        include_bytes!("../templates/durable-counter/synthesized/transition.rs"),
    ),
    (
        "synthesized/program.zcve",
        include_bytes!("../templates/durable-counter/synthesized/program.zcve"),
    ),
];
