//! Closed, package-local file set for the inventory-reservation example.

pub(crate) const FILES: &[(&str, &[u8])] = &[
    (
        "project.zeno",
        include_bytes!("../templates/inventory-reservation/project.zeno"),
    ),
    (
        "README.md",
        include_bytes!("../templates/inventory-reservation/README.md"),
    ),
    (
        "Cargo.toml",
        include_bytes!("../templates/inventory-reservation/Cargo.toml.in"),
    ),
    (
        "build.rs",
        include_bytes!("../templates/inventory-reservation/build.rs"),
    ),
    (
        "profile.rs",
        include_bytes!("../templates/inventory-reservation/profile.rs"),
    ),
    (
        "src/delivery.rs",
        include_bytes!("../templates/inventory-reservation/src/delivery.rs"),
    ),
    (
        "src/laws.rs",
        include_bytes!("../templates/inventory-reservation/src/laws.rs"),
    ),
    (
        "src/lib.rs",
        include_bytes!("../templates/inventory-reservation/src/lib.rs"),
    ),
    (
        "src/main.rs",
        include_bytes!("../templates/inventory-reservation/src/main.rs"),
    ),
    (
        "src/program.rs",
        include_bytes!("../templates/inventory-reservation/src/program.rs"),
    ),
    (
        "synthesis.json",
        include_bytes!("../templates/inventory-reservation/synthesis.json"),
    ),
    (
        "synthesized/manifest.json",
        include_bytes!("../templates/inventory-reservation/synthesized/manifest.json"),
    ),
    (
        "synthesized/problem.json",
        include_bytes!("../templates/inventory-reservation/synthesized/problem.json"),
    ),
    (
        "synthesized/program.zcve",
        include_bytes!("../templates/inventory-reservation/synthesized/program.zcve"),
    ),
    (
        "synthesized/transition.rs",
        include_bytes!("../templates/inventory-reservation/synthesized/transition.rs"),
    ),
    (
        "synthesized/vectors.json",
        include_bytes!("../templates/inventory-reservation/synthesized/vectors.json"),
    ),
    (
        "tests/conformance.rs",
        include_bytes!("../templates/inventory-reservation/tests/conformance.rs"),
    ),
    (
        "tests/decision-examples.txt",
        include_bytes!("../templates/inventory-reservation/tests/decision-examples.txt"),
    ),
    (
        "tests/determinism.rs",
        include_bytes!("../templates/inventory-reservation/tests/determinism.rs"),
    ),
    (
        "tests/laws.rs",
        include_bytes!("../templates/inventory-reservation/tests/laws.rs"),
    ),
    (
        "tests/lifecycle.rs",
        include_bytes!("../templates/inventory-reservation/tests/lifecycle.rs"),
    ),
];
