//! Closed, package-local file set for the order-fulfillment example.

pub(crate) const FILES: &[(&str, &[u8])] = &[
    (
        "project.zeno",
        include_bytes!("../templates/order-fulfillment/project.zeno"),
    ),
    (
        "README.md",
        include_bytes!("../templates/order-fulfillment/README.md"),
    ),
    (
        "Cargo.toml",
        include_bytes!("../templates/order-fulfillment/Cargo.toml.in"),
    ),
    (
        "build.rs",
        include_bytes!("../templates/order-fulfillment/build.rs"),
    ),
    (
        "profile.rs",
        include_bytes!("../templates/order-fulfillment/profile.rs"),
    ),
    (
        "src/delivery.rs",
        include_bytes!("../templates/order-fulfillment/src/delivery.rs"),
    ),
    (
        "src/laws.rs",
        include_bytes!("../templates/order-fulfillment/src/laws.rs"),
    ),
    (
        "src/lib.rs",
        include_bytes!("../templates/order-fulfillment/src/lib.rs"),
    ),
    (
        "src/main.rs",
        include_bytes!("../templates/order-fulfillment/src/main.rs"),
    ),
    (
        "src/program.rs",
        include_bytes!("../templates/order-fulfillment/src/program.rs"),
    ),
    (
        "tests/conformance.rs",
        include_bytes!("../templates/order-fulfillment/tests/conformance.rs"),
    ),
    (
        "tests/decision-examples.txt",
        include_bytes!("../templates/order-fulfillment/tests/decision-examples.txt"),
    ),
    (
        "tests/determinism.rs",
        include_bytes!("../templates/order-fulfillment/tests/determinism.rs"),
    ),
    (
        "tests/laws.rs",
        include_bytes!("../templates/order-fulfillment/tests/laws.rs"),
    ),
    (
        "tests/lifecycle.rs",
        include_bytes!("../templates/order-fulfillment/tests/lifecycle.rs"),
    ),
];
