//! Closed, package-local file set for the withdrawal-queue example.

pub(crate) const FILES: &[(&str, &[u8])] = &[
    (
        "project.zeno",
        include_bytes!("../templates/withdrawal-queue/project.zeno"),
    ),
    (
        "README.md",
        include_bytes!("../templates/withdrawal-queue/README.md"),
    ),
    (
        "Cargo.toml",
        include_bytes!("../templates/withdrawal-queue/Cargo.toml.in"),
    ),
    (
        "build.rs",
        include_bytes!("../templates/withdrawal-queue/build.rs"),
    ),
    (
        "profile.rs",
        include_bytes!("../templates/withdrawal-queue/profile.rs"),
    ),
    (
        "synthesis.json",
        include_bytes!("../templates/withdrawal-queue/synthesis.json"),
    ),
    (
        "controller/contract.json",
        include_bytes!("../templates/withdrawal-queue/controller/contract.json"),
    ),
    (
        "controller/contract.sha256",
        include_bytes!("../templates/withdrawal-queue/controller/contract.sha256"),
    ),
    (
        "controller/model.py",
        include_bytes!("../templates/withdrawal-queue/controller/model.py"),
    ),
    (
        "controller/rejected/alarm-deferential.strategy.json",
        include_bytes!(
            "../templates/withdrawal-queue/controller/rejected/alarm-deferential.strategy.json"
        ),
    ),
    (
        "controller/rejected/fixed-priority.strategy.json",
        include_bytes!(
            "../templates/withdrawal-queue/controller/rejected/fixed-priority.strategy.json"
        ),
    ),
    (
        "controller/strategy.json",
        include_bytes!("../templates/withdrawal-queue/controller/strategy.json"),
    ),
    (
        "src/controller.rs",
        include_bytes!("../templates/withdrawal-queue/src/controller.rs"),
    ),
    (
        "src/delivery.rs",
        include_bytes!("../templates/withdrawal-queue/src/delivery.rs"),
    ),
    (
        "src/laws.rs",
        include_bytes!("../templates/withdrawal-queue/src/laws.rs"),
    ),
    (
        "src/lib.rs",
        include_bytes!("../templates/withdrawal-queue/src/lib.rs"),
    ),
    (
        "src/main.rs",
        include_bytes!("../templates/withdrawal-queue/src/main.rs"),
    ),
    (
        "src/program.rs",
        include_bytes!("../templates/withdrawal-queue/src/program.rs"),
    ),
    (
        "synthesized/manifest.json",
        include_bytes!("../templates/withdrawal-queue/synthesized/manifest.json"),
    ),
    (
        "synthesized/problem.json",
        include_bytes!("../templates/withdrawal-queue/synthesized/problem.json"),
    ),
    (
        "synthesized/program.zcve",
        include_bytes!("../templates/withdrawal-queue/synthesized/program.zcve"),
    ),
    (
        "synthesized/transition.rs",
        include_bytes!("../templates/withdrawal-queue/synthesized/transition.rs"),
    ),
    (
        "synthesized/vectors.json",
        include_bytes!("../templates/withdrawal-queue/synthesized/vectors.json"),
    ),
    (
        "tests/claims.rs",
        include_bytes!("../templates/withdrawal-queue/tests/claims.rs"),
    ),
    (
        "tests/conformance.rs",
        include_bytes!("../templates/withdrawal-queue/tests/conformance.rs"),
    ),
    (
        "tests/controller.rs",
        include_bytes!("../templates/withdrawal-queue/tests/controller.rs"),
    ),
    (
        "tests/decision-examples.txt",
        include_bytes!("../templates/withdrawal-queue/tests/decision-examples.txt"),
    ),
    (
        "tests/determinism.rs",
        include_bytes!("../templates/withdrawal-queue/tests/determinism.rs"),
    ),
    (
        "tests/laws.rs",
        include_bytes!("../templates/withdrawal-queue/tests/laws.rs"),
    ),
    (
        "tests/lifecycle.rs",
        include_bytes!("../templates/withdrawal-queue/tests/lifecycle.rs"),
    ),
];
