// Generated declarative data. Review v2/policy.json and project.zeno.
// Regenerate/check with tools/check_template_contracts_v2.py; no runtime mapper.
extern crate alloc;
use alloc::{vec, vec::Vec};
use zeno_fcis_synthesis::finite::{Domain as ScalarDomain, Op, V2ScalarProgram};
use zeno_fcis_synthesis::finite::{
    V2InputField as InputField, V2InputLeaf as InputLeaf, V2InputVariant as InputVariant,
    V2Resource as Resource, canonical_v2::schema as s, v2_authority as authority,
    v2_catalog as catalog, v2_composition as c, v2_laws as l, v2_zero_limits,
};
/// Exact actual original schema bytes.
pub const ORIGINAL_SCHEMA: &[u8] = include_bytes!("../v2/schema.zcve");
/// Complete reviewed library-encoded policy.
pub const ORIGINAL_POLICY: &[u8] = include_bytes!("../v2/policy.zcve");
/// Complete original named schema description.
pub const DESCRIPTION: s::Description<'static> = s::Description {
    profile: b"agent_treasury_guard",
    version: 1,
    root: 100,
    definitions: &[
        s::Definition {
            id: 100,
            name: b"Treasury",
            kind: s::Kind::Record(&[
                s::Field {
                    id: 130,
                    name: b"quote",
                    type_id: 105,
                },
                s::Field {
                    id: 131,
                    name: b"base",
                    type_id: 106,
                },
                s::Field {
                    id: 132,
                    name: b"spent_today",
                    type_id: 107,
                },
                s::Field {
                    id: 133,
                    name: b"last_seen",
                    type_id: 108,
                },
                s::Field {
                    id: 134,
                    name: b"pending",
                    type_id: 109,
                },
                s::Field {
                    id: 135,
                    name: b"pending_amount",
                    type_id: 111,
                },
                s::Field {
                    id: 136,
                    name: b"pending_min_out",
                    type_id: 113,
                },
            ]),
        },
        s::Definition {
            id: 101,
            name: b"TreasuryCommand",
            kind: s::Kind::Record(&[
                s::Field {
                    id: 140,
                    name: b"action",
                    type_id: 115,
                },
                s::Field {
                    id: 141,
                    name: b"direction",
                    type_id: 110,
                },
                s::Field {
                    id: 142,
                    name: b"amount",
                    type_id: 112,
                },
                s::Field {
                    id: 143,
                    name: b"min_out",
                    type_id: 113,
                },
                s::Field {
                    id: 144,
                    name: b"intent",
                    type_id: 108,
                },
                s::Field {
                    id: 145,
                    name: b"amount_out",
                    type_id: 114,
                },
            ]),
        },
        s::Definition {
            id: 102,
            name: b"GuardContext",
            kind: s::Kind::Record(&[
                s::Field {
                    id: 150,
                    name: b"caller",
                    type_id: 116,
                },
                s::Field {
                    id: 151,
                    name: b"now",
                    type_id: 108,
                },
                s::Field {
                    id: 152,
                    name: b"price",
                    type_id: 117,
                },
                s::Field {
                    id: 153,
                    name: b"price_time",
                    type_id: 108,
                },
                s::Field {
                    id: 154,
                    name: b"model",
                    type_id: 118,
                },
            ]),
        },
        s::Definition {
            id: 103,
            name: b"DexDestination",
            kind: s::Kind::Text { min: 1, max: 32 },
        },
        s::Definition {
            id: 104,
            name: b"SwapRequest",
            kind: s::Kind::Record(&[
                s::Field {
                    id: 160,
                    name: b"intent_number",
                    type_id: 108,
                },
                s::Field {
                    id: 161,
                    name: b"asset_in",
                    type_id: 120,
                },
                s::Field {
                    id: 162,
                    name: b"asset_out",
                    type_id: 120,
                },
                s::Field {
                    id: 163,
                    name: b"amount_in",
                    type_id: 112,
                },
                s::Field {
                    id: 164,
                    name: b"min_amount_out",
                    type_id: 113,
                },
                s::Field {
                    id: 165,
                    name: b"deadline",
                    type_id: 119,
                },
            ]),
        },
        s::Definition {
            id: 105,
            name: b"QuoteUnits",
            kind: s::Kind::I128 { min: 0, max: 20 },
        },
        s::Definition {
            id: 106,
            name: b"BaseUnits",
            kind: s::Kind::I128 { min: 0, max: 20 },
        },
        s::Definition {
            id: 107,
            name: b"SpentUnits",
            kind: s::Kind::I128 { min: 0, max: 4 },
        },
        s::Definition {
            id: 108,
            name: b"Tick",
            kind: s::Kind::I128 { min: 0, max: 11 },
        },
        s::Definition {
            id: 109,
            name: b"PendingSwap",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 170,
                    name: b"NoSwap",
                },
                s::Variant {
                    id: 171,
                    name: b"PendingBuy",
                },
                s::Variant {
                    id: 172,
                    name: b"PendingSell",
                },
            ]),
        },
        s::Definition {
            id: 110,
            name: b"Direction",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 173,
                    name: b"BuyBase",
                },
                s::Variant {
                    id: 174,
                    name: b"SellBase",
                },
            ]),
        },
        s::Definition {
            id: 111,
            name: b"HeldAmount",
            kind: s::Kind::I128 { min: 0, max: 3 },
        },
        s::Definition {
            id: 112,
            name: b"TradeAmount",
            kind: s::Kind::I128 { min: 1, max: 3 },
        },
        s::Definition {
            id: 113,
            name: b"MinOut",
            kind: s::Kind::I128 { min: 0, max: 3 },
        },
        s::Definition {
            id: 114,
            name: b"AmountOut",
            kind: s::Kind::I128 { min: 0, max: 3 },
        },
        s::Definition {
            id: 115,
            name: b"TreasuryAction",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 175,
                    name: b"ProposeSwap",
                },
                s::Variant {
                    id: 176,
                    name: b"SwapSettled",
                },
                s::Variant {
                    id: 177,
                    name: b"SwapFailed",
                },
            ]),
        },
        s::Definition {
            id: 116,
            name: b"Caller",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 178,
                    name: b"Agent",
                },
                s::Variant {
                    id: 179,
                    name: b"Dex",
                },
            ]),
        },
        s::Definition {
            id: 117,
            name: b"Price",
            kind: s::Kind::I128 { min: 1, max: 2 },
        },
        s::Definition {
            id: 118,
            name: b"ModelId",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 180,
                    name: b"TreasuryAgentV2",
                },
                s::Variant {
                    id: 181,
                    name: b"TreasuryAgentV1",
                },
                s::Variant {
                    id: 182,
                    name: b"UnlistedModel",
                },
            ]),
        },
        s::Definition {
            id: 119,
            name: b"Deadline",
            kind: s::Kind::I128 { min: 0, max: 13 },
        },
        s::Definition {
            id: 120,
            name: b"Asset",
            kind: s::Kind::Sum(&[
                s::Variant {
                    id: 183,
                    name: b"Quote",
                },
                s::Variant {
                    id: 184,
                    name: b"Base",
                },
            ]),
        },
    ],
};
/// Original root and schema commitments and complete wire-size limits.
pub const FRAMING: c::Framing = c::Framing {
    state: c::FrameBinding {
        root: 100,
        schema: [
            215, 50, 2, 108, 226, 91, 41, 1, 56, 205, 10, 152, 75, 247, 197, 74, 197, 80, 3, 128,
            20, 138, 10, 213, 2, 139, 169, 233, 20, 118, 100, 51,
        ],
        max_bytes: 177,
    },
    command: c::FrameBinding {
        root: 101,
        schema: [
            215, 50, 2, 108, 226, 91, 41, 1, 56, 205, 10, 152, 75, 247, 197, 74, 197, 80, 3, 128,
            20, 138, 10, 213, 2, 139, 169, 233, 20, 118, 100, 51,
        ],
        max_bytes: 149,
    },
    context: c::FrameBinding {
        root: 102,
        schema: [
            215, 50, 2, 108, 226, 91, 41, 1, 56, 205, 10, 152, 75, 247, 197, 74, 197, 80, 3, 128,
            20, 138, 10, 213, 2, 139, 169, 233, 20, 118, 100, 51,
        ],
        max_bytes: 130,
    },
};
/// Exact channel to original destination and payload type links.
pub const CHANNEL_ROOTS: &[(u32, u32, u32)] = &[(300, 103, 104)];
/// Complete ordered decisions selected only by actual graph output.
pub const BRANCHES: &[c::Branch<'static>] = &[
    c::Branch {
        code: 0,
        class: c::Class::Reject,
        reason: Some(200),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 1,
        class: c::Class::Reject,
        reason: Some(201),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 2,
        class: c::Class::Reject,
        reason: Some(202),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 3,
        class: c::Class::Reject,
        reason: Some(203),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 4,
        class: c::Class::Reject,
        reason: Some(204),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 5,
        class: c::Class::Reject,
        reason: Some(205),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 6,
        class: c::Class::Reject,
        reason: Some(206),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 7,
        class: c::Class::Reject,
        reason: Some(207),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 8,
        class: c::Class::Reject,
        reason: Some(208),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 9,
        class: c::Class::Reject,
        reason: Some(209),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 10,
        class: c::Class::Reject,
        reason: Some(210),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 11,
        class: c::Class::Reject,
        reason: Some(211),
        assignments: &[],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 12,
        class: c::Class::Accept,
        reason: None,
        assignments: &[
            c::Assignment {
                field: 130,
                value: c::Expr::Output(1),
                domain: c::Domain::I128 { min: 0, max: 20 },
            },
            c::Assignment {
                field: 131,
                value: c::Expr::Input(c::Source::State, 131),
                domain: c::Domain::I128 { min: 0, max: 20 },
            },
            c::Assignment {
                field: 132,
                value: c::Expr::Output(2),
                domain: c::Domain::I128 { min: 0, max: 4 },
            },
            c::Assignment {
                field: 133,
                value: c::Expr::Input(c::Source::Context, 151),
                domain: c::Domain::I128 { min: 0, max: 11 },
            },
            c::Assignment {
                field: 134,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 109,
                    variant: 171,
                }),
                domain: c::Domain::Sum {
                    type_id: 109,
                    variants: &[170, 171, 172],
                },
            },
            c::Assignment {
                field: 135,
                value: c::Expr::Input(c::Source::Command, 142),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
            c::Assignment {
                field: 136,
                value: c::Expr::Input(c::Source::Command, 143),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 300,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"zenodex")),
            payload: &[
                c::PayloadField {
                    field: 160,
                    value: c::Expr::Input(c::Source::Context, 151),
                },
                c::PayloadField {
                    field: 161,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 120,
                        variant: 183,
                    }),
                },
                c::PayloadField {
                    field: 162,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 120,
                        variant: 184,
                    }),
                },
                c::PayloadField {
                    field: 163,
                    value: c::Expr::Input(c::Source::Command, 142),
                },
                c::PayloadField {
                    field: 164,
                    value: c::Expr::Input(c::Source::Command, 143),
                },
                c::PayloadField {
                    field: 165,
                    value: c::Expr::Output(3),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 13,
        class: c::Class::Accept,
        reason: None,
        assignments: &[
            c::Assignment {
                field: 130,
                value: c::Expr::Input(c::Source::State, 130),
                domain: c::Domain::I128 { min: 0, max: 20 },
            },
            c::Assignment {
                field: 131,
                value: c::Expr::Output(4),
                domain: c::Domain::I128 { min: 0, max: 20 },
            },
            c::Assignment {
                field: 132,
                value: c::Expr::Output(2),
                domain: c::Domain::I128 { min: 0, max: 4 },
            },
            c::Assignment {
                field: 133,
                value: c::Expr::Input(c::Source::Context, 151),
                domain: c::Domain::I128 { min: 0, max: 11 },
            },
            c::Assignment {
                field: 134,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 109,
                    variant: 172,
                }),
                domain: c::Domain::Sum {
                    type_id: 109,
                    variants: &[170, 171, 172],
                },
            },
            c::Assignment {
                field: 135,
                value: c::Expr::Input(c::Source::Command, 142),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
            c::Assignment {
                field: 136,
                value: c::Expr::Input(c::Source::Command, 143),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[c::DeliveryPlan {
            ordinal: 0,
            channel: 300,
            when: c::Expr::Constant(c::Atom::Bool(true)),
            destination: c::Expr::Constant(c::Atom::Text(b"zenodex")),
            payload: &[
                c::PayloadField {
                    field: 160,
                    value: c::Expr::Input(c::Source::Context, 151),
                },
                c::PayloadField {
                    field: 161,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 120,
                        variant: 184,
                    }),
                },
                c::PayloadField {
                    field: 162,
                    value: c::Expr::Constant(c::Atom::Sum {
                        type_id: 120,
                        variant: 183,
                    }),
                },
                c::PayloadField {
                    field: 163,
                    value: c::Expr::Input(c::Source::Command, 142),
                },
                c::PayloadField {
                    field: 164,
                    value: c::Expr::Input(c::Source::Command, 143),
                },
                c::PayloadField {
                    field: 165,
                    value: c::Expr::Output(3),
                },
            ],
            idempotency: c::Expr::Constant(c::Atom::U128(0)),
        }],
    },
    c::Branch {
        code: 14,
        class: c::Class::Accept,
        reason: None,
        assignments: &[
            c::Assignment {
                field: 130,
                value: c::Expr::Input(c::Source::State, 130),
                domain: c::Domain::I128 { min: 0, max: 20 },
            },
            c::Assignment {
                field: 131,
                value: c::Expr::Output(5),
                domain: c::Domain::I128 { min: 0, max: 20 },
            },
            c::Assignment {
                field: 132,
                value: c::Expr::Output(6),
                domain: c::Domain::I128 { min: 0, max: 4 },
            },
            c::Assignment {
                field: 133,
                value: c::Expr::Input(c::Source::Context, 151),
                domain: c::Domain::I128 { min: 0, max: 11 },
            },
            c::Assignment {
                field: 134,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 109,
                    variant: 170,
                }),
                domain: c::Domain::Sum {
                    type_id: 109,
                    variants: &[170, 171, 172],
                },
            },
            c::Assignment {
                field: 135,
                value: c::Expr::Constant(c::Atom::I128(0)),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
            c::Assignment {
                field: 136,
                value: c::Expr::Constant(c::Atom::I128(0)),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 15,
        class: c::Class::Accept,
        reason: None,
        assignments: &[
            c::Assignment {
                field: 130,
                value: c::Expr::Output(7),
                domain: c::Domain::I128 { min: 0, max: 20 },
            },
            c::Assignment {
                field: 131,
                value: c::Expr::Input(c::Source::State, 131),
                domain: c::Domain::I128 { min: 0, max: 20 },
            },
            c::Assignment {
                field: 132,
                value: c::Expr::Output(6),
                domain: c::Domain::I128 { min: 0, max: 4 },
            },
            c::Assignment {
                field: 133,
                value: c::Expr::Input(c::Source::Context, 151),
                domain: c::Domain::I128 { min: 0, max: 11 },
            },
            c::Assignment {
                field: 134,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 109,
                    variant: 170,
                }),
                domain: c::Domain::Sum {
                    type_id: 109,
                    variants: &[170, 171, 172],
                },
            },
            c::Assignment {
                field: 135,
                value: c::Expr::Constant(c::Atom::I128(0)),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
            c::Assignment {
                field: 136,
                value: c::Expr::Constant(c::Atom::I128(0)),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 16,
        class: c::Class::CommittedFailure,
        reason: Some(212),
        assignments: &[
            c::Assignment {
                field: 130,
                value: c::Expr::Output(8),
                domain: c::Domain::I128 { min: 0, max: 20 },
            },
            c::Assignment {
                field: 131,
                value: c::Expr::Input(c::Source::State, 131),
                domain: c::Domain::I128 { min: 0, max: 20 },
            },
            c::Assignment {
                field: 132,
                value: c::Expr::Output(6),
                domain: c::Domain::I128 { min: 0, max: 4 },
            },
            c::Assignment {
                field: 133,
                value: c::Expr::Input(c::Source::Context, 151),
                domain: c::Domain::I128 { min: 0, max: 11 },
            },
            c::Assignment {
                field: 134,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 109,
                    variant: 170,
                }),
                domain: c::Domain::Sum {
                    type_id: 109,
                    variants: &[170, 171, 172],
                },
            },
            c::Assignment {
                field: 135,
                value: c::Expr::Constant(c::Atom::I128(0)),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
            c::Assignment {
                field: 136,
                value: c::Expr::Constant(c::Atom::I128(0)),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[],
    },
    c::Branch {
        code: 17,
        class: c::Class::CommittedFailure,
        reason: Some(212),
        assignments: &[
            c::Assignment {
                field: 130,
                value: c::Expr::Input(c::Source::State, 130),
                domain: c::Domain::I128 { min: 0, max: 20 },
            },
            c::Assignment {
                field: 131,
                value: c::Expr::Output(9),
                domain: c::Domain::I128 { min: 0, max: 20 },
            },
            c::Assignment {
                field: 132,
                value: c::Expr::Output(6),
                domain: c::Domain::I128 { min: 0, max: 4 },
            },
            c::Assignment {
                field: 133,
                value: c::Expr::Input(c::Source::Context, 151),
                domain: c::Domain::I128 { min: 0, max: 11 },
            },
            c::Assignment {
                field: 134,
                value: c::Expr::Constant(c::Atom::Sum {
                    type_id: 109,
                    variant: 170,
                }),
                domain: c::Domain::Sum {
                    type_id: 109,
                    variants: &[170, 171, 172],
                },
            },
            c::Assignment {
                field: 135,
                value: c::Expr::Constant(c::Atom::I128(0)),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
            c::Assignment {
                field: 136,
                value: c::Expr::Constant(c::Atom::I128(0)),
                domain: c::Domain::I128 { min: 0, max: 3 },
            },
        ],
        effects: &[],
        outbox: &[],
    },
];
const LAW_500: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Post(130)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(2)),
    l::Op::Lt(1, 2),
    l::Op::Not(3),
    l::Op::Observe(l::Observation::Post(131)),
    l::Op::ToI128(5),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Lt(6, 7),
    l::Op::Not(8),
    l::Op::And(4, 9),
    l::Op::Observe(l::Observation::Post(132)),
    l::Op::ToI128(11),
    l::Op::Lt(12, 7),
    l::Op::Not(13),
    l::Op::And(10, 14),
    l::Op::Literal(l::Atom::I128(4)),
    l::Op::Lt(16, 12),
    l::Op::Not(17),
    l::Op::And(15, 18),
    l::Op::Observe(l::Observation::Post(134)),
    l::Op::ToI128(20),
    l::Op::Literal(l::Atom::I128(170)),
    l::Op::Eq(21, 22),
    l::Op::Observe(l::Observation::Post(135)),
    l::Op::ToI128(24),
    l::Op::Eq(25, 7),
    l::Op::Observe(l::Observation::Post(136)),
    l::Op::ToI128(27),
    l::Op::Eq(28, 7),
    l::Op::And(26, 29),
    l::Op::Not(23),
    l::Op::Not(31),
    l::Op::Not(30),
    l::Op::And(32, 33),
    l::Op::Not(34),
    l::Op::And(19, 35),
    l::Op::Literal(l::Atom::I128(1)),
    l::Op::Lt(25, 37),
    l::Op::Not(38),
    l::Op::Lt(28, 7),
    l::Op::Not(40),
    l::Op::And(39, 41),
    l::Op::Not(32),
    l::Op::Not(42),
    l::Op::And(43, 44),
    l::Op::Not(45),
    l::Op::And(36, 46),
];
const LAW_501: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Context(151)),
    l::Op::ToI128(0),
    l::Op::Observe(l::Observation::Pre(133)),
    l::Op::ToI128(2),
    l::Op::Lt(3, 1),
    l::Op::Observe(l::Observation::Post(133)),
    l::Op::ToI128(5),
    l::Op::Eq(6, 1),
    l::Op::And(4, 7),
];
const LAW_502: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Context(151)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(4)),
    l::Op::Div(l::Division::Floor, 1, 2),
    l::Op::Observe(l::Observation::Pre(133)),
    l::Op::ToI128(4),
    l::Op::Div(l::Division::Floor, 5, 2),
    l::Op::Lt(6, 3),
    l::Op::Observe(l::Observation::Command(140)),
    l::Op::ToI128(8),
    l::Op::Literal(l::Atom::I128(175)),
    l::Op::Eq(9, 10),
    l::Op::Not(11),
    l::Op::Observe(l::Observation::Post(132)),
    l::Op::ToI128(13),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(14, 15),
    l::Op::Not(12),
    l::Op::Not(17),
    l::Op::Not(16),
    l::Op::And(18, 19),
    l::Op::Not(20),
    l::Op::Observe(l::Observation::Command(141)),
    l::Op::ToI128(22),
    l::Op::Literal(l::Atom::I128(173)),
    l::Op::Eq(23, 24),
    l::Op::And(11, 25),
    l::Op::Observe(l::Observation::Command(142)),
    l::Op::ToI128(27),
    l::Op::Eq(14, 28),
    l::Op::Not(26),
    l::Op::Not(30),
    l::Op::Not(29),
    l::Op::And(31, 32),
    l::Op::Not(33),
    l::Op::And(21, 34),
    l::Op::Literal(l::Atom::I128(174)),
    l::Op::Eq(23, 36),
    l::Op::And(11, 37),
    l::Op::Observe(l::Observation::Context(152)),
    l::Op::ToI128(39),
    l::Op::Mul(28, 40),
    l::Op::Eq(14, 41),
    l::Op::Not(38),
    l::Op::Not(43),
    l::Op::Not(42),
    l::Op::And(44, 45),
    l::Op::Not(46),
    l::Op::And(35, 47),
    l::Op::Not(7),
    l::Op::Not(49),
    l::Op::Not(48),
    l::Op::And(50, 51),
    l::Op::Not(52),
    l::Op::Eq(3, 6),
    l::Op::Observe(l::Observation::Pre(132)),
    l::Op::ToI128(55),
    l::Op::Eq(14, 56),
    l::Op::Not(57),
    l::Op::And(18, 58),
    l::Op::Not(59),
    l::Op::Add(56, 28),
    l::Op::Eq(14, 61),
    l::Op::Not(62),
    l::Op::And(31, 63),
    l::Op::Not(64),
    l::Op::And(60, 65),
    l::Op::Add(56, 41),
    l::Op::Eq(14, 67),
    l::Op::Not(68),
    l::Op::And(44, 69),
    l::Op::Not(70),
    l::Op::And(66, 71),
    l::Op::Not(54),
    l::Op::Not(73),
    l::Op::Not(72),
    l::Op::And(74, 75),
    l::Op::Not(76),
    l::Op::And(53, 77),
];
const LAW_503: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(140)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(175)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Context(150)),
    l::Op::ToI128(4),
    l::Op::Literal(l::Atom::I128(178)),
    l::Op::Eq(5, 6),
    l::Op::Observe(l::Observation::Context(154)),
    l::Op::ToI128(8),
    l::Op::Literal(l::Atom::I128(180)),
    l::Op::Eq(9, 10),
    l::Op::And(7, 11),
    l::Op::Observe(l::Observation::Context(153)),
    l::Op::ToI128(13),
    l::Op::Observe(l::Observation::Context(151)),
    l::Op::ToI128(15),
    l::Op::Lt(16, 14),
    l::Op::Not(17),
    l::Op::And(12, 18),
    l::Op::Sub(16, 14),
    l::Op::Literal(l::Atom::I128(1)),
    l::Op::Lt(21, 20),
    l::Op::Not(22),
    l::Op::And(19, 23),
    l::Op::Observe(l::Observation::Pre(134)),
    l::Op::ToI128(25),
    l::Op::Literal(l::Atom::I128(170)),
    l::Op::Eq(26, 27),
    l::Op::And(24, 28),
    l::Op::Observe(l::Observation::Post(134)),
    l::Op::ToI128(30),
    l::Op::Eq(31, 27),
    l::Op::Not(32),
    l::Op::And(29, 33),
    l::Op::Not(3),
    l::Op::Not(35),
    l::Op::Not(34),
    l::Op::And(36, 37),
    l::Op::Not(38),
    l::Op::Literal(l::Atom::I128(176)),
    l::Op::Eq(1, 40),
    l::Op::Literal(l::Atom::I128(179)),
    l::Op::Eq(5, 42),
    l::Op::Not(28),
    l::Op::And(43, 44),
    l::Op::Observe(l::Observation::Command(144)),
    l::Op::ToI128(46),
    l::Op::Observe(l::Observation::Pre(133)),
    l::Op::ToI128(48),
    l::Op::Eq(47, 49),
    l::Op::And(45, 50),
    l::Op::And(51, 32),
    l::Op::Not(41),
    l::Op::Not(53),
    l::Op::Not(52),
    l::Op::And(54, 55),
    l::Op::Not(56),
    l::Op::And(39, 57),
    l::Op::Literal(l::Atom::I128(177)),
    l::Op::Eq(1, 59),
    l::Op::Not(60),
    l::Op::And(58, 61),
];
const LAW_504: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(140)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(176)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Command(145)),
    l::Op::ToI128(4),
    l::Op::Observe(l::Observation::Pre(136)),
    l::Op::ToI128(6),
    l::Op::Lt(5, 7),
    l::Op::Not(8),
    l::Op::Observe(l::Observation::Post(134)),
    l::Op::ToI128(10),
    l::Op::Literal(l::Atom::I128(170)),
    l::Op::Eq(11, 12),
    l::Op::And(9, 13),
    l::Op::Observe(l::Observation::Post(135)),
    l::Op::ToI128(15),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(16, 17),
    l::Op::And(14, 18),
    l::Op::Observe(l::Observation::Post(136)),
    l::Op::ToI128(20),
    l::Op::Eq(21, 17),
    l::Op::And(19, 22),
    l::Op::Observe(l::Observation::Pre(134)),
    l::Op::ToI128(24),
    l::Op::Literal(l::Atom::I128(171)),
    l::Op::Eq(25, 26),
    l::Op::Observe(l::Observation::Post(131)),
    l::Op::ToI128(28),
    l::Op::Observe(l::Observation::Pre(131)),
    l::Op::ToI128(30),
    l::Op::Add(31, 5),
    l::Op::Eq(29, 32),
    l::Op::Observe(l::Observation::Post(130)),
    l::Op::ToI128(34),
    l::Op::Observe(l::Observation::Pre(130)),
    l::Op::ToI128(36),
    l::Op::Eq(35, 37),
    l::Op::And(33, 38),
    l::Op::Not(27),
    l::Op::Not(40),
    l::Op::Not(39),
    l::Op::And(41, 42),
    l::Op::Not(43),
    l::Op::And(23, 44),
    l::Op::Literal(l::Atom::I128(172)),
    l::Op::Eq(25, 46),
    l::Op::Add(37, 5),
    l::Op::Eq(35, 48),
    l::Op::Eq(29, 31),
    l::Op::And(49, 50),
    l::Op::Not(47),
    l::Op::Not(52),
    l::Op::Not(51),
    l::Op::And(53, 54),
    l::Op::Not(55),
    l::Op::And(45, 56),
    l::Op::Not(3),
    l::Op::Not(58),
    l::Op::Not(57),
    l::Op::And(59, 60),
    l::Op::Not(61),
];
const LAW_505: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(140)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(175)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Command(142)),
    l::Op::ToI128(4),
    l::Op::Literal(l::Atom::I128(1)),
    l::Op::Lt(5, 6),
    l::Op::Not(7),
    l::Op::Observe(l::Observation::Command(141)),
    l::Op::ToI128(9),
    l::Op::Literal(l::Atom::I128(173)),
    l::Op::Eq(10, 11),
    l::Op::Observe(l::Observation::Post(130)),
    l::Op::ToI128(13),
    l::Op::Add(14, 5),
    l::Op::Observe(l::Observation::Pre(130)),
    l::Op::ToI128(16),
    l::Op::Eq(15, 17),
    l::Op::Literal(l::Atom::I128(2)),
    l::Op::Lt(14, 19),
    l::Op::Not(20),
    l::Op::And(18, 21),
    l::Op::Observe(l::Observation::Post(131)),
    l::Op::ToI128(23),
    l::Op::Observe(l::Observation::Pre(131)),
    l::Op::ToI128(25),
    l::Op::Eq(24, 26),
    l::Op::And(22, 27),
    l::Op::Not(12),
    l::Op::Not(29),
    l::Op::Not(28),
    l::Op::And(30, 31),
    l::Op::Not(32),
    l::Op::And(8, 33),
    l::Op::Literal(l::Atom::I128(174)),
    l::Op::Eq(10, 35),
    l::Op::Add(24, 5),
    l::Op::Eq(37, 26),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Lt(24, 39),
    l::Op::Not(40),
    l::Op::And(38, 41),
    l::Op::Eq(14, 17),
    l::Op::And(42, 43),
    l::Op::Not(36),
    l::Op::Not(45),
    l::Op::Not(44),
    l::Op::And(46, 47),
    l::Op::Not(48),
    l::Op::And(34, 49),
    l::Op::Not(3),
    l::Op::Not(51),
    l::Op::Not(50),
    l::Op::And(52, 53),
    l::Op::Not(54),
];
const LAW_506: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(140)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(175)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Post(135)),
    l::Op::ToI128(4),
    l::Op::Observe(l::Observation::Command(142)),
    l::Op::ToI128(6),
    l::Op::Eq(5, 7),
    l::Op::Observe(l::Observation::Post(136)),
    l::Op::ToI128(9),
    l::Op::Observe(l::Observation::Command(143)),
    l::Op::ToI128(11),
    l::Op::Eq(10, 12),
    l::Op::And(8, 13),
    l::Op::Observe(l::Observation::Command(141)),
    l::Op::ToI128(15),
    l::Op::Literal(l::Atom::I128(173)),
    l::Op::Eq(16, 17),
    l::Op::Observe(l::Observation::Post(134)),
    l::Op::ToI128(19),
    l::Op::Literal(l::Atom::I128(171)),
    l::Op::Eq(20, 21),
    l::Op::Not(18),
    l::Op::Not(23),
    l::Op::Not(22),
    l::Op::And(24, 25),
    l::Op::Not(26),
    l::Op::And(14, 27),
    l::Op::Literal(l::Atom::I128(174)),
    l::Op::Eq(16, 29),
    l::Op::Literal(l::Atom::I128(172)),
    l::Op::Eq(20, 31),
    l::Op::Not(30),
    l::Op::Not(33),
    l::Op::Not(32),
    l::Op::And(34, 35),
    l::Op::Not(36),
    l::Op::And(28, 37),
    l::Op::Not(3),
    l::Op::Not(39),
    l::Op::Not(38),
    l::Op::And(40, 41),
    l::Op::Not(42),
];
const LAW_507: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(140)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(175)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Context(152)),
    l::Op::ToI128(4),
    l::Op::Literal(l::Atom::I128(1)),
    l::Op::Lt(5, 6),
    l::Op::Not(7),
    l::Op::Observe(l::Observation::Post(132)),
    l::Op::ToI128(9),
    l::Op::Literal(l::Atom::I128(4)),
    l::Op::Lt(11, 10),
    l::Op::Not(12),
    l::Op::And(8, 13),
    l::Op::Observe(l::Observation::Command(141)),
    l::Op::ToI128(15),
    l::Op::Literal(l::Atom::I128(173)),
    l::Op::Eq(16, 17),
    l::Op::Observe(l::Observation::Post(135)),
    l::Op::ToI128(19),
    l::Op::Literal(l::Atom::I128(3)),
    l::Op::Lt(21, 20),
    l::Op::Not(22),
    l::Op::Observe(l::Observation::Post(136)),
    l::Op::ToI128(24),
    l::Op::Mul(20, 21),
    l::Op::Mul(11, 5),
    l::Op::Div(l::Division::Ceil, 26, 27),
    l::Op::Lt(25, 28),
    l::Op::Not(29),
    l::Op::And(23, 30),
    l::Op::Not(18),
    l::Op::Not(32),
    l::Op::Not(31),
    l::Op::And(33, 34),
    l::Op::Not(35),
    l::Op::And(14, 36),
    l::Op::Literal(l::Atom::I128(174)),
    l::Op::Eq(16, 38),
    l::Op::Mul(20, 5),
    l::Op::Lt(21, 40),
    l::Op::Not(41),
    l::Op::Mul(40, 21),
    l::Op::Div(l::Division::Ceil, 43, 11),
    l::Op::Lt(25, 44),
    l::Op::Not(45),
    l::Op::And(42, 46),
    l::Op::Not(39),
    l::Op::Not(48),
    l::Op::Not(47),
    l::Op::And(49, 50),
    l::Op::Not(51),
    l::Op::And(37, 52),
    l::Op::Not(3),
    l::Op::Not(54),
    l::Op::Not(53),
    l::Op::And(55, 56),
    l::Op::Not(57),
];
const LAW_508: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Command(140)),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(177)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::Context(150)),
    l::Op::ToI128(4),
    l::Op::Literal(l::Atom::I128(179)),
    l::Op::Eq(5, 6),
    l::Op::And(3, 7),
    l::Op::Observe(l::Observation::Pre(134)),
    l::Op::ToI128(9),
    l::Op::Literal(l::Atom::I128(170)),
    l::Op::Eq(10, 11),
    l::Op::Not(12),
    l::Op::And(8, 13),
    l::Op::Observe(l::Observation::Command(144)),
    l::Op::ToI128(15),
    l::Op::Observe(l::Observation::Pre(133)),
    l::Op::ToI128(17),
    l::Op::Eq(16, 18),
    l::Op::And(14, 19),
    l::Op::Observe(l::Observation::Post(134)),
    l::Op::ToI128(21),
    l::Op::Eq(22, 11),
    l::Op::And(20, 23),
    l::Op::Observe(l::Observation::Post(135)),
    l::Op::ToI128(25),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(26, 27),
    l::Op::And(24, 28),
    l::Op::Observe(l::Observation::Post(136)),
    l::Op::ToI128(30),
    l::Op::Eq(31, 27),
    l::Op::And(29, 32),
    l::Op::Literal(l::Atom::I128(171)),
    l::Op::Eq(10, 34),
    l::Op::Observe(l::Observation::Post(130)),
    l::Op::ToI128(36),
    l::Op::Observe(l::Observation::Pre(130)),
    l::Op::ToI128(38),
    l::Op::Observe(l::Observation::Pre(135)),
    l::Op::ToI128(40),
    l::Op::Add(39, 41),
    l::Op::Eq(37, 42),
    l::Op::Observe(l::Observation::Post(131)),
    l::Op::ToI128(44),
    l::Op::Observe(l::Observation::Pre(131)),
    l::Op::ToI128(46),
    l::Op::Eq(45, 47),
    l::Op::And(43, 48),
    l::Op::Not(35),
    l::Op::Not(50),
    l::Op::Not(49),
    l::Op::And(51, 52),
    l::Op::Not(53),
    l::Op::And(33, 54),
    l::Op::Literal(l::Atom::I128(172)),
    l::Op::Eq(10, 56),
    l::Op::Add(47, 41),
    l::Op::Eq(45, 58),
    l::Op::Eq(37, 39),
    l::Op::And(59, 60),
    l::Op::Not(57),
    l::Op::Not(62),
    l::Op::Not(61),
    l::Op::And(63, 64),
    l::Op::Not(65),
    l::Op::And(55, 66),
];
const LAW_509: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::PostLength),
    l::Op::ToI128(0),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(1, 2),
    l::Op::Observe(l::Observation::PatchLength),
    l::Op::ToI128(4),
    l::Op::Eq(5, 2),
    l::Op::Observe(l::Observation::EffectLength),
    l::Op::ToI128(7),
    l::Op::Eq(8, 2),
    l::Op::Observe(l::Observation::OutboxLength),
    l::Op::ToI128(10),
    l::Op::Eq(11, 2),
    l::Op::Literal(l::Atom::Bool(true)),
    l::Op::And(13, 3),
    l::Op::And(14, 6),
    l::Op::And(15, 9),
    l::Op::And(16, 12),
];
const LAW_990: &[l::Op<'static>] = &[
    l::Op::Observe(l::Observation::Initial(130)),
    l::Op::Literal(l::Atom::I128(6)),
    l::Op::Eq(0, 1),
    l::Op::Observe(l::Observation::Initial(131)),
    l::Op::Literal(l::Atom::I128(1)),
    l::Op::Eq(3, 4),
    l::Op::Observe(l::Observation::Initial(132)),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(6, 7),
    l::Op::Observe(l::Observation::Initial(133)),
    l::Op::Eq(9, 7),
    l::Op::Observe(l::Observation::Initial(134)),
    l::Op::Literal(l::Atom::Sum {
        type_id: 109,
        variant: 170,
    }),
    l::Op::Eq(11, 12),
    l::Op::Observe(l::Observation::Initial(135)),
    l::Op::Eq(14, 7),
    l::Op::Observe(l::Observation::Initial(136)),
    l::Op::Eq(16, 7),
    l::Op::Literal(l::Atom::Bool(true)),
    l::Op::And(18, 2),
    l::Op::And(19, 5),
    l::Op::And(20, 8),
    l::Op::And(21, 10),
    l::Op::And(22, 13),
    l::Op::And(23, 15),
    l::Op::And(24, 17),
];
const LAW_991: &[l::Op<'static>] = &[
    l::Op::Literal(l::Atom::Bool(true)),
    l::Op::Observe(l::Observation::Context(150)),
    l::Op::ToI128(1),
    l::Op::Observe(l::Observation::Command(140)),
    l::Op::ToI128(3),
    l::Op::Literal(l::Atom::I128(175)),
    l::Op::Eq(4, 5),
    l::Op::Literal(l::Atom::I128(178)),
    l::Op::Literal(l::Atom::I128(179)),
    l::Op::Select(6, 7, 8),
    l::Op::Eq(2, 9),
    l::Op::Not(10),
    l::Op::And(0, 11),
    l::Op::Not(11),
    l::Op::And(0, 13),
    l::Op::Observe(l::Observation::Class),
    l::Op::ToI128(15),
    l::Op::Literal(l::Atom::I128(1)),
    l::Op::Eq(16, 17),
    l::Op::Observe(l::Observation::HasReason),
    l::Op::ObserveWhen(12, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(20),
    l::Op::Literal(l::Atom::I128(200)),
    l::Op::Eq(21, 22),
    l::Op::Observe(l::Observation::EffectLength),
    l::Op::ToI128(24),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(25, 26),
    l::Op::Observe(l::Observation::OutboxLength),
    l::Op::ToI128(28),
    l::Op::Eq(29, 26),
    l::Op::Observe(l::Observation::PostLength),
    l::Op::ToI128(31),
    l::Op::Eq(32, 26),
    l::Op::And(0, 18),
    l::Op::And(34, 19),
    l::Op::And(35, 23),
    l::Op::And(36, 27),
    l::Op::And(37, 30),
    l::Op::And(38, 33),
    l::Op::Select(12, 39, 0),
    l::Op::Observe(l::Observation::Context(151)),
    l::Op::ToI128(41),
    l::Op::Observe(l::Observation::Pre(133)),
    l::Op::ToI128(43),
    l::Op::Lt(44, 42),
    l::Op::Not(45),
    l::Op::And(14, 46),
    l::Op::Not(46),
    l::Op::And(14, 48),
    l::Op::ObserveWhen(47, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(50),
    l::Op::Literal(l::Atom::I128(201)),
    l::Op::Eq(51, 52),
    l::Op::And(35, 53),
    l::Op::And(54, 27),
    l::Op::And(55, 30),
    l::Op::And(56, 33),
    l::Op::Select(47, 57, 0),
    l::Op::Observe(l::Observation::Context(154)),
    l::Op::ToI128(59),
    l::Op::Literal(l::Atom::I128(180)),
    l::Op::Eq(60, 61),
    l::Op::Not(62),
    l::Op::And(6, 63),
    l::Op::And(49, 64),
    l::Op::Not(64),
    l::Op::And(49, 66),
    l::Op::ObserveWhen(65, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(68),
    l::Op::Literal(l::Atom::I128(202)),
    l::Op::Eq(69, 70),
    l::Op::And(35, 71),
    l::Op::And(72, 27),
    l::Op::And(73, 30),
    l::Op::And(74, 33),
    l::Op::Select(65, 75, 0),
    l::Op::Observe(l::Observation::Context(153)),
    l::Op::ToI128(77),
    l::Op::Lt(42, 78),
    l::Op::Sub(42, 78),
    l::Op::Lt(17, 80),
    l::Op::Not(79),
    l::Op::Not(81),
    l::Op::And(82, 83),
    l::Op::Not(84),
    l::Op::And(6, 85),
    l::Op::And(67, 86),
    l::Op::Not(86),
    l::Op::And(67, 88),
    l::Op::ObserveWhen(87, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(90),
    l::Op::Literal(l::Atom::I128(203)),
    l::Op::Eq(91, 92),
    l::Op::And(35, 93),
    l::Op::And(94, 27),
    l::Op::And(95, 30),
    l::Op::And(96, 33),
    l::Op::Select(87, 97, 0),
    l::Op::Observe(l::Observation::Pre(134)),
    l::Op::ToI128(99),
    l::Op::Literal(l::Atom::I128(170)),
    l::Op::Eq(100, 101),
    l::Op::Not(102),
    l::Op::And(6, 103),
    l::Op::And(89, 104),
    l::Op::Not(104),
    l::Op::And(89, 106),
    l::Op::ObserveWhen(105, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(108),
    l::Op::Literal(l::Atom::I128(204)),
    l::Op::Eq(109, 110),
    l::Op::And(35, 111),
    l::Op::And(112, 27),
    l::Op::And(113, 30),
    l::Op::And(114, 33),
    l::Op::Select(105, 115, 0),
    l::Op::Not(6),
    l::Op::And(117, 102),
    l::Op::And(107, 118),
    l::Op::Not(118),
    l::Op::And(107, 120),
    l::Op::ObserveWhen(119, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(122),
    l::Op::Literal(l::Atom::I128(205)),
    l::Op::Eq(123, 124),
    l::Op::And(35, 125),
    l::Op::And(126, 27),
    l::Op::And(127, 30),
    l::Op::And(128, 33),
    l::Op::Select(119, 129, 0),
    l::Op::Observe(l::Observation::Command(144)),
    l::Op::ToI128(131),
    l::Op::Eq(132, 44),
    l::Op::Not(133),
    l::Op::And(117, 134),
    l::Op::And(121, 135),
    l::Op::Not(135),
    l::Op::And(121, 137),
    l::Op::ObserveWhen(136, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(139),
    l::Op::Literal(l::Atom::I128(206)),
    l::Op::Eq(140, 141),
    l::Op::And(35, 142),
    l::Op::And(143, 27),
    l::Op::And(144, 30),
    l::Op::And(145, 33),
    l::Op::Select(136, 146, 0),
    l::Op::Literal(l::Atom::I128(176)),
    l::Op::Eq(4, 148),
    l::Op::Observe(l::Observation::Command(145)),
    l::Op::ToI128(150),
    l::Op::Observe(l::Observation::Pre(136)),
    l::Op::ToI128(152),
    l::Op::Lt(151, 153),
    l::Op::And(149, 154),
    l::Op::And(138, 155),
    l::Op::Not(155),
    l::Op::And(138, 157),
    l::Op::ObserveWhen(156, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(159),
    l::Op::Literal(l::Atom::I128(207)),
    l::Op::Eq(160, 161),
    l::Op::And(35, 162),
    l::Op::And(163, 27),
    l::Op::And(164, 30),
    l::Op::And(165, 33),
    l::Op::Select(156, 166, 0),
    l::Op::Observe(l::Observation::Command(141)),
    l::Op::ToI128(168),
    l::Op::Literal(l::Atom::I128(173)),
    l::Op::Eq(169, 170),
    l::Op::Observe(l::Observation::Context(152)),
    l::Op::ToI128(172),
    l::Op::Eq(173, 17),
    l::Op::Not(171),
    l::Op::Not(174),
    l::Op::And(175, 176),
    l::Op::Not(177),
    l::Op::Observe(l::Observation::Command(142)),
    l::Op::ToI128(179),
    l::Op::Add(180, 180),
    l::Op::Select(178, 180, 181),
    l::Op::Literal(l::Atom::I128(3)),
    l::Op::Lt(183, 182),
    l::Op::And(6, 184),
    l::Op::And(158, 185),
    l::Op::Not(185),
    l::Op::And(158, 187),
    l::Op::ObserveWhen(186, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(189),
    l::Op::Literal(l::Atom::I128(208)),
    l::Op::Eq(190, 191),
    l::Op::And(35, 192),
    l::Op::And(193, 27),
    l::Op::And(194, 30),
    l::Op::And(195, 33),
    l::Op::Select(186, 196, 0),
    l::Op::Literal(l::Atom::I128(4)),
    l::Op::Lt(42, 198),
    l::Op::Literal(l::Atom::I128(8)),
    l::Op::Lt(42, 200),
    l::Op::Literal(l::Atom::I128(2)),
    l::Op::Select(201, 17, 202),
    l::Op::Select(199, 26, 203),
    l::Op::Lt(44, 198),
    l::Op::Lt(44, 200),
    l::Op::Select(206, 17, 202),
    l::Op::Select(205, 26, 207),
    l::Op::Lt(208, 204),
    l::Op::Observe(l::Observation::Pre(132)),
    l::Op::ToI128(210),
    l::Op::Select(209, 26, 211),
    l::Op::Add(212, 182),
    l::Op::Lt(198, 213),
    l::Op::And(6, 214),
    l::Op::And(188, 215),
    l::Op::Not(215),
    l::Op::And(188, 217),
    l::Op::ObserveWhen(216, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(219),
    l::Op::Literal(l::Atom::I128(209)),
    l::Op::Eq(220, 221),
    l::Op::And(35, 222),
    l::Op::And(223, 27),
    l::Op::And(224, 30),
    l::Op::And(225, 33),
    l::Op::Select(216, 226, 0),
    l::Op::Observe(l::Observation::Command(143)),
    l::Op::ToI128(228),
    l::Op::Eq(180, 183),
    l::Op::Select(230, 202, 17),
    l::Op::Select(174, 180, 231),
    l::Op::Eq(180, 17),
    l::Op::Eq(180, 202),
    l::Op::Literal(l::Atom::I128(5)),
    l::Op::Select(234, 183, 235),
    l::Op::Select(233, 202, 236),
    l::Op::Select(174, 180, 237),
    l::Op::Select(171, 232, 238),
    l::Op::Lt(229, 239),
    l::Op::And(6, 240),
    l::Op::And(218, 241),
    l::Op::Not(241),
    l::Op::And(218, 243),
    l::Op::ObserveWhen(242, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(245),
    l::Op::Literal(l::Atom::I128(210)),
    l::Op::Eq(246, 247),
    l::Op::And(35, 248),
    l::Op::And(249, 27),
    l::Op::And(250, 30),
    l::Op::And(251, 33),
    l::Op::Select(242, 252, 0),
    l::Op::Observe(l::Observation::Pre(130)),
    l::Op::ToI128(254),
    l::Op::Sub(255, 180),
    l::Op::Lt(256, 202),
    l::Op::Not(257),
    l::Op::Observe(l::Observation::Pre(131)),
    l::Op::ToI128(259),
    l::Op::Sub(260, 180),
    l::Op::Lt(261, 26),
    l::Op::Not(262),
    l::Op::Select(171, 258, 263),
    l::Op::Not(264),
    l::Op::And(6, 265),
    l::Op::And(244, 266),
    l::Op::Not(266),
    l::Op::And(244, 268),
    l::Op::ObserveWhen(267, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(270),
    l::Op::Literal(l::Atom::I128(211)),
    l::Op::Eq(271, 272),
    l::Op::And(35, 273),
    l::Op::And(274, 27),
    l::Op::And(275, 30),
    l::Op::And(276, 33),
    l::Op::Select(267, 277, 0),
    l::Op::And(6, 171),
    l::Op::And(269, 279),
    l::Op::Not(279),
    l::Op::And(269, 281),
    l::Op::Eq(16, 26),
    l::Op::Not(19),
    l::Op::Eq(29, 17),
    l::Op::Literal(l::Atom::I128(7)),
    l::Op::Eq(32, 286),
    l::Op::ObserveWhen(280, l::Observation::Post(130), l::Atom::I128(6)),
    l::Op::ToI128(288),
    l::Op::Eq(289, 256),
    l::Op::Select(280, 290, 0),
    l::Op::ObserveWhen(280, l::Observation::Post(131), l::Atom::I128(1)),
    l::Op::ToI128(292),
    l::Op::Eq(293, 260),
    l::Op::Select(280, 294, 0),
    l::Op::ObserveWhen(280, l::Observation::Post(132), l::Atom::I128(0)),
    l::Op::ToI128(296),
    l::Op::Eq(297, 213),
    l::Op::Select(280, 298, 0),
    l::Op::ObserveWhen(280, l::Observation::Post(133), l::Atom::I128(0)),
    l::Op::ToI128(300),
    l::Op::Eq(301, 42),
    l::Op::Select(280, 302, 0),
    l::Op::ObserveWhen(
        280,
        l::Observation::Post(134),
        l::Atom::Sum {
            type_id: 109,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 109,
        variant: 171,
    }),
    l::Op::Eq(304, 305),
    l::Op::Select(280, 306, 0),
    l::Op::ObserveWhen(280, l::Observation::Post(135), l::Atom::I128(0)),
    l::Op::ToI128(308),
    l::Op::Eq(309, 180),
    l::Op::Select(280, 310, 0),
    l::Op::ObserveWhen(280, l::Observation::Post(136), l::Atom::I128(0)),
    l::Op::ToI128(312),
    l::Op::Eq(313, 229),
    l::Op::Select(280, 314, 0),
    l::Op::ObserveWhen(280, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(316),
    l::Op::Eq(317, 26),
    l::Op::ObserveWhen(280, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(319),
    l::Op::Literal(l::Atom::I128(300)),
    l::Op::Eq(320, 321),
    l::Op::ObserveWhen(
        280,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"zenodex"),
    ),
    l::Op::Literal(l::Atom::Text(b"zenodex")),
    l::Op::Eq(323, 324),
    l::Op::ObserveWhen(280, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Literal(l::Atom::U128(0)),
    l::Op::Eq(326, 327),
    l::Op::ObserveWhen(280, l::Observation::OutboxPayload(0, 160), l::Atom::I128(0)),
    l::Op::ToI128(329),
    l::Op::Eq(330, 42),
    l::Op::Select(280, 331, 0),
    l::Op::ObserveWhen(
        280,
        l::Observation::OutboxPayload(0, 161),
        l::Atom::Sum {
            type_id: 120,
            variant: 183,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 120,
        variant: 183,
    }),
    l::Op::Eq(333, 334),
    l::Op::Select(280, 335, 0),
    l::Op::ObserveWhen(
        280,
        l::Observation::OutboxPayload(0, 162),
        l::Atom::Sum {
            type_id: 120,
            variant: 183,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 120,
        variant: 184,
    }),
    l::Op::Eq(337, 338),
    l::Op::Select(280, 339, 0),
    l::Op::ObserveWhen(280, l::Observation::OutboxPayload(0, 163), l::Atom::I128(0)),
    l::Op::ToI128(341),
    l::Op::Eq(342, 180),
    l::Op::Select(280, 343, 0),
    l::Op::ObserveWhen(280, l::Observation::OutboxPayload(0, 164), l::Atom::I128(0)),
    l::Op::ToI128(345),
    l::Op::Eq(346, 229),
    l::Op::Select(280, 347, 0),
    l::Op::ObserveWhen(280, l::Observation::OutboxPayload(0, 165), l::Atom::I128(0)),
    l::Op::ToI128(349),
    l::Op::Add(42, 202),
    l::Op::Eq(350, 351),
    l::Op::Select(280, 352, 0),
    l::Op::And(0, 283),
    l::Op::And(354, 284),
    l::Op::And(355, 27),
    l::Op::And(356, 285),
    l::Op::And(357, 287),
    l::Op::And(358, 291),
    l::Op::And(359, 295),
    l::Op::And(360, 299),
    l::Op::And(361, 303),
    l::Op::And(362, 307),
    l::Op::And(363, 311),
    l::Op::And(364, 315),
    l::Op::And(365, 318),
    l::Op::And(366, 322),
    l::Op::And(367, 325),
    l::Op::And(368, 328),
    l::Op::And(369, 332),
    l::Op::And(370, 336),
    l::Op::And(371, 340),
    l::Op::And(372, 344),
    l::Op::And(373, 348),
    l::Op::And(374, 353),
    l::Op::Select(280, 375, 0),
    l::Op::And(282, 6),
    l::Op::And(282, 117),
    l::Op::ObserveWhen(377, l::Observation::Post(130), l::Atom::I128(6)),
    l::Op::ToI128(379),
    l::Op::Eq(380, 255),
    l::Op::Select(377, 381, 0),
    l::Op::ObserveWhen(377, l::Observation::Post(131), l::Atom::I128(1)),
    l::Op::ToI128(383),
    l::Op::Eq(384, 261),
    l::Op::Select(377, 385, 0),
    l::Op::ObserveWhen(377, l::Observation::Post(132), l::Atom::I128(0)),
    l::Op::ToI128(387),
    l::Op::Eq(388, 213),
    l::Op::Select(377, 389, 0),
    l::Op::ObserveWhen(377, l::Observation::Post(133), l::Atom::I128(0)),
    l::Op::ToI128(391),
    l::Op::Eq(392, 42),
    l::Op::Select(377, 393, 0),
    l::Op::ObserveWhen(
        377,
        l::Observation::Post(134),
        l::Atom::Sum {
            type_id: 109,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 109,
        variant: 172,
    }),
    l::Op::Eq(395, 396),
    l::Op::Select(377, 397, 0),
    l::Op::ObserveWhen(377, l::Observation::Post(135), l::Atom::I128(0)),
    l::Op::ToI128(399),
    l::Op::Eq(400, 180),
    l::Op::Select(377, 401, 0),
    l::Op::ObserveWhen(377, l::Observation::Post(136), l::Atom::I128(0)),
    l::Op::ToI128(403),
    l::Op::Eq(404, 229),
    l::Op::Select(377, 405, 0),
    l::Op::ObserveWhen(377, l::Observation::OutboxOrdinal(0), l::Atom::I128(0)),
    l::Op::ToI128(407),
    l::Op::Eq(408, 26),
    l::Op::ObserveWhen(377, l::Observation::OutboxChannel(0), l::Atom::I128(0)),
    l::Op::ToI128(410),
    l::Op::Eq(411, 321),
    l::Op::ObserveWhen(
        377,
        l::Observation::OutboxDestination(0),
        l::Atom::Text(b"zenodex"),
    ),
    l::Op::Eq(413, 324),
    l::Op::ObserveWhen(377, l::Observation::OutboxIdempotency(0), l::Atom::U128(0)),
    l::Op::Eq(415, 327),
    l::Op::ObserveWhen(377, l::Observation::OutboxPayload(0, 160), l::Atom::I128(0)),
    l::Op::ToI128(417),
    l::Op::Eq(418, 42),
    l::Op::Select(377, 419, 0),
    l::Op::ObserveWhen(
        377,
        l::Observation::OutboxPayload(0, 161),
        l::Atom::Sum {
            type_id: 120,
            variant: 183,
        },
    ),
    l::Op::Eq(421, 338),
    l::Op::Select(377, 422, 0),
    l::Op::ObserveWhen(
        377,
        l::Observation::OutboxPayload(0, 162),
        l::Atom::Sum {
            type_id: 120,
            variant: 183,
        },
    ),
    l::Op::Eq(424, 334),
    l::Op::Select(377, 425, 0),
    l::Op::ObserveWhen(377, l::Observation::OutboxPayload(0, 163), l::Atom::I128(0)),
    l::Op::ToI128(427),
    l::Op::Eq(428, 180),
    l::Op::Select(377, 429, 0),
    l::Op::ObserveWhen(377, l::Observation::OutboxPayload(0, 164), l::Atom::I128(0)),
    l::Op::ToI128(431),
    l::Op::Eq(432, 229),
    l::Op::Select(377, 433, 0),
    l::Op::ObserveWhen(377, l::Observation::OutboxPayload(0, 165), l::Atom::I128(0)),
    l::Op::ToI128(435),
    l::Op::Eq(436, 351),
    l::Op::Select(377, 437, 0),
    l::Op::And(358, 382),
    l::Op::And(439, 386),
    l::Op::And(440, 390),
    l::Op::And(441, 394),
    l::Op::And(442, 398),
    l::Op::And(443, 402),
    l::Op::And(444, 406),
    l::Op::And(445, 409),
    l::Op::And(446, 412),
    l::Op::And(447, 414),
    l::Op::And(448, 416),
    l::Op::And(449, 420),
    l::Op::And(450, 423),
    l::Op::And(451, 426),
    l::Op::And(452, 430),
    l::Op::And(453, 434),
    l::Op::And(454, 438),
    l::Op::Select(377, 455, 0),
    l::Op::Literal(l::Atom::I128(171)),
    l::Op::Eq(100, 457),
    l::Op::And(149, 458),
    l::Op::And(378, 459),
    l::Op::Not(459),
    l::Op::And(378, 461),
    l::Op::ObserveWhen(460, l::Observation::Post(130), l::Atom::I128(6)),
    l::Op::ToI128(463),
    l::Op::Eq(464, 255),
    l::Op::Select(460, 465, 0),
    l::Op::ObserveWhen(460, l::Observation::Post(131), l::Atom::I128(1)),
    l::Op::ToI128(467),
    l::Op::Add(260, 151),
    l::Op::Eq(468, 469),
    l::Op::Select(460, 470, 0),
    l::Op::ObserveWhen(460, l::Observation::Post(132), l::Atom::I128(0)),
    l::Op::ToI128(472),
    l::Op::Eq(473, 212),
    l::Op::Select(460, 474, 0),
    l::Op::ObserveWhen(460, l::Observation::Post(133), l::Atom::I128(0)),
    l::Op::ToI128(476),
    l::Op::Eq(477, 42),
    l::Op::Select(460, 478, 0),
    l::Op::ObserveWhen(
        460,
        l::Observation::Post(134),
        l::Atom::Sum {
            type_id: 109,
            variant: 170,
        },
    ),
    l::Op::Literal(l::Atom::Sum {
        type_id: 109,
        variant: 170,
    }),
    l::Op::Eq(480, 481),
    l::Op::Select(460, 482, 0),
    l::Op::ObserveWhen(460, l::Observation::Post(135), l::Atom::I128(0)),
    l::Op::Literal(l::Atom::I128(0)),
    l::Op::Eq(484, 485),
    l::Op::Select(460, 486, 0),
    l::Op::ObserveWhen(460, l::Observation::Post(136), l::Atom::I128(0)),
    l::Op::Eq(488, 485),
    l::Op::Select(460, 489, 0),
    l::Op::And(356, 30),
    l::Op::And(491, 287),
    l::Op::And(492, 466),
    l::Op::And(493, 471),
    l::Op::And(494, 475),
    l::Op::And(495, 479),
    l::Op::And(496, 483),
    l::Op::And(497, 487),
    l::Op::And(498, 490),
    l::Op::Select(460, 499, 0),
    l::Op::And(462, 149),
    l::Op::Not(149),
    l::Op::And(462, 502),
    l::Op::ObserveWhen(501, l::Observation::Post(130), l::Atom::I128(6)),
    l::Op::ToI128(504),
    l::Op::Add(255, 151),
    l::Op::Eq(505, 506),
    l::Op::Select(501, 507, 0),
    l::Op::ObserveWhen(501, l::Observation::Post(131), l::Atom::I128(1)),
    l::Op::ToI128(509),
    l::Op::Eq(510, 260),
    l::Op::Select(501, 511, 0),
    l::Op::ObserveWhen(501, l::Observation::Post(132), l::Atom::I128(0)),
    l::Op::ToI128(513),
    l::Op::Eq(514, 212),
    l::Op::Select(501, 515, 0),
    l::Op::ObserveWhen(501, l::Observation::Post(133), l::Atom::I128(0)),
    l::Op::ToI128(517),
    l::Op::Eq(518, 42),
    l::Op::Select(501, 519, 0),
    l::Op::ObserveWhen(
        501,
        l::Observation::Post(134),
        l::Atom::Sum {
            type_id: 109,
            variant: 170,
        },
    ),
    l::Op::Eq(521, 481),
    l::Op::Select(501, 522, 0),
    l::Op::ObserveWhen(501, l::Observation::Post(135), l::Atom::I128(0)),
    l::Op::Eq(524, 485),
    l::Op::Select(501, 525, 0),
    l::Op::ObserveWhen(501, l::Observation::Post(136), l::Atom::I128(0)),
    l::Op::Eq(527, 485),
    l::Op::Select(501, 528, 0),
    l::Op::And(492, 508),
    l::Op::And(530, 512),
    l::Op::And(531, 516),
    l::Op::And(532, 520),
    l::Op::And(533, 523),
    l::Op::And(534, 526),
    l::Op::And(535, 529),
    l::Op::Select(501, 536, 0),
    l::Op::And(503, 458),
    l::Op::Not(458),
    l::Op::And(503, 539),
    l::Op::Eq(16, 202),
    l::Op::ObserveWhen(538, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(542),
    l::Op::Literal(l::Atom::I128(212)),
    l::Op::Eq(543, 544),
    l::Op::ObserveWhen(538, l::Observation::Post(130), l::Atom::I128(6)),
    l::Op::ToI128(546),
    l::Op::Observe(l::Observation::Pre(135)),
    l::Op::ToI128(548),
    l::Op::Add(255, 549),
    l::Op::Eq(547, 550),
    l::Op::Select(538, 551, 0),
    l::Op::ObserveWhen(538, l::Observation::Post(131), l::Atom::I128(1)),
    l::Op::ToI128(553),
    l::Op::Eq(554, 260),
    l::Op::Select(538, 555, 0),
    l::Op::ObserveWhen(538, l::Observation::Post(132), l::Atom::I128(0)),
    l::Op::ToI128(557),
    l::Op::Eq(558, 212),
    l::Op::Select(538, 559, 0),
    l::Op::ObserveWhen(538, l::Observation::Post(133), l::Atom::I128(0)),
    l::Op::ToI128(561),
    l::Op::Eq(562, 42),
    l::Op::Select(538, 563, 0),
    l::Op::ObserveWhen(
        538,
        l::Observation::Post(134),
        l::Atom::Sum {
            type_id: 109,
            variant: 170,
        },
    ),
    l::Op::Eq(565, 481),
    l::Op::Select(538, 566, 0),
    l::Op::ObserveWhen(538, l::Observation::Post(135), l::Atom::I128(0)),
    l::Op::Eq(568, 485),
    l::Op::Select(538, 569, 0),
    l::Op::ObserveWhen(538, l::Observation::Post(136), l::Atom::I128(0)),
    l::Op::Eq(571, 485),
    l::Op::Select(538, 572, 0),
    l::Op::And(0, 541),
    l::Op::And(574, 19),
    l::Op::And(575, 545),
    l::Op::And(576, 27),
    l::Op::And(577, 30),
    l::Op::And(578, 287),
    l::Op::And(579, 552),
    l::Op::And(580, 556),
    l::Op::And(581, 560),
    l::Op::And(582, 564),
    l::Op::And(583, 567),
    l::Op::And(584, 570),
    l::Op::And(585, 573),
    l::Op::Select(538, 586, 0),
    l::Op::And(540, 0),
    l::Op::Not(0),
    l::Op::And(540, 589),
    l::Op::ObserveWhen(588, l::Observation::Reason, l::Atom::I128(0)),
    l::Op::ToI128(591),
    l::Op::Eq(592, 544),
    l::Op::ObserveWhen(588, l::Observation::Post(130), l::Atom::I128(6)),
    l::Op::ToI128(594),
    l::Op::Eq(595, 255),
    l::Op::Select(588, 596, 0),
    l::Op::ObserveWhen(588, l::Observation::Post(131), l::Atom::I128(1)),
    l::Op::ToI128(598),
    l::Op::Add(260, 549),
    l::Op::Eq(599, 600),
    l::Op::Select(588, 601, 0),
    l::Op::ObserveWhen(588, l::Observation::Post(132), l::Atom::I128(0)),
    l::Op::ToI128(603),
    l::Op::Eq(604, 212),
    l::Op::Select(588, 605, 0),
    l::Op::ObserveWhen(588, l::Observation::Post(133), l::Atom::I128(0)),
    l::Op::ToI128(607),
    l::Op::Eq(608, 42),
    l::Op::Select(588, 609, 0),
    l::Op::ObserveWhen(
        588,
        l::Observation::Post(134),
        l::Atom::Sum {
            type_id: 109,
            variant: 170,
        },
    ),
    l::Op::Eq(611, 481),
    l::Op::Select(588, 612, 0),
    l::Op::ObserveWhen(588, l::Observation::Post(135), l::Atom::I128(0)),
    l::Op::Eq(614, 485),
    l::Op::Select(588, 615, 0),
    l::Op::ObserveWhen(588, l::Observation::Post(136), l::Atom::I128(0)),
    l::Op::Eq(617, 485),
    l::Op::Select(588, 618, 0),
    l::Op::And(575, 593),
    l::Op::And(620, 27),
    l::Op::And(621, 30),
    l::Op::And(622, 287),
    l::Op::And(623, 597),
    l::Op::And(624, 602),
    l::Op::And(625, 606),
    l::Op::And(626, 610),
    l::Op::And(627, 613),
    l::Op::And(628, 616),
    l::Op::And(629, 619),
    l::Op::Select(588, 630, 0),
    l::Op::Not(590),
    l::Op::And(0, 40),
    l::Op::And(633, 58),
    l::Op::And(634, 76),
    l::Op::And(635, 98),
    l::Op::And(636, 116),
    l::Op::And(637, 130),
    l::Op::And(638, 147),
    l::Op::And(639, 167),
    l::Op::And(640, 197),
    l::Op::And(641, 227),
    l::Op::And(642, 253),
    l::Op::And(643, 278),
    l::Op::And(644, 376),
    l::Op::And(645, 456),
    l::Op::And(646, 500),
    l::Op::And(647, 537),
    l::Op::And(648, 587),
    l::Op::And(649, 631),
    l::Op::And(650, 632),
];
/// Original scoped laws plus independent structural requirements.
pub const LAWS: &[l::Law<'static>] = &[
    l::Law {
        id: 500,
        kind: l::Kind::StateInvariant,
        scope: l::Scope::Committing,
        genesis: true,
        program: l::Program {
            nodes: LAW_500,
            root: 47,
        },
    },
    l::Law {
        id: 501,
        kind: l::Kind::AuthoritySubjectRecipient,
        scope: l::Scope::Committing,
        genesis: false,
        program: l::Program {
            nodes: LAW_501,
            root: 8,
        },
    },
    l::Law {
        id: 502,
        kind: l::Kind::AssetConservation,
        scope: l::Scope::Committing,
        genesis: false,
        program: l::Program {
            nodes: LAW_502,
            root: 78,
        },
    },
    l::Law {
        id: 503,
        kind: l::Kind::AuthoritySubjectRecipient,
        scope: l::Scope::Accept,
        genesis: false,
        program: l::Program {
            nodes: LAW_503,
            root: 62,
        },
    },
    l::Law {
        id: 504,
        kind: l::Kind::AssetConservation,
        scope: l::Scope::Accept,
        genesis: false,
        program: l::Program {
            nodes: LAW_504,
            root: 62,
        },
    },
    l::Law {
        id: 505,
        kind: l::Kind::AssetConservation,
        scope: l::Scope::Accept,
        genesis: false,
        program: l::Program {
            nodes: LAW_505,
            root: 55,
        },
    },
    l::Law {
        id: 506,
        kind: l::Kind::DebitCreditEffectEquality,
        scope: l::Scope::Accept,
        genesis: false,
        program: l::Program {
            nodes: LAW_506,
            root: 43,
        },
    },
    l::Law {
        id: 507,
        kind: l::Kind::FeeAndRounding,
        scope: l::Scope::Accept,
        genesis: false,
        program: l::Program {
            nodes: LAW_507,
            root: 58,
        },
    },
    l::Law {
        id: 508,
        kind: l::Kind::CommittedFailureEffects,
        scope: l::Scope::CommittedFailure,
        genesis: false,
        program: l::Program {
            nodes: LAW_508,
            root: 67,
        },
    },
    l::Law {
        id: 509,
        kind: l::Kind::RejectNoAuthority,
        scope: l::Scope::Reject,
        genesis: false,
        program: l::Program {
            nodes: LAW_509,
            root: 17,
        },
    },
    l::Law {
        id: 990,
        kind: l::Kind::InitialCondition,
        scope: l::Scope::Always,
        genesis: true,
        program: l::Program {
            nodes: LAW_990,
            root: 25,
        },
    },
    l::Law {
        id: 991,
        kind: l::Kind::DecisionConformance,
        scope: l::Scope::Always,
        genesis: false,
        program: l::Program {
            nodes: LAW_991,
            root: 651,
        },
    },
];
/// No declared law is optional at descriptor admission.
pub const REQUIRED: &[u32] = &[500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 990, 991];
/// Owns declarative input/output type tables; evaluation stays in the library.
pub struct Contract {
    state: Vec<InputField>,
    command: Vec<InputField>,
    context: Vec<InputField>,
    output_types: Vec<InputLeaf>,
}
impl Default for Contract {
    fn default() -> Self {
        Self::new()
    }
}
impl Contract {
    /// Allocate only fixed declarative type tables.
    #[must_use]
    pub fn new() -> Self {
        Self {
            state: vec![
                InputField {
                    id: 130,
                    leaf: InputLeaf::I128 { min: 0, max: 20 },
                },
                InputField {
                    id: 131,
                    leaf: InputLeaf::I128 { min: 0, max: 20 },
                },
                InputField {
                    id: 132,
                    leaf: InputLeaf::I128 { min: 0, max: 4 },
                },
                InputField {
                    id: 133,
                    leaf: InputLeaf::I128 { min: 0, max: 11 },
                },
                InputField {
                    id: 134,
                    leaf: InputLeaf::Sum {
                        type_id: 109,
                        min: 170,
                        max: 172,
                        variants: vec![
                            InputVariant { id: 170, code: 170 },
                            InputVariant { id: 171, code: 171 },
                            InputVariant { id: 172, code: 172 },
                        ],
                    },
                },
                InputField {
                    id: 135,
                    leaf: InputLeaf::I128 { min: 0, max: 3 },
                },
                InputField {
                    id: 136,
                    leaf: InputLeaf::I128 { min: 0, max: 3 },
                },
            ],
            command: vec![
                InputField {
                    id: 140,
                    leaf: InputLeaf::Sum {
                        type_id: 115,
                        min: 175,
                        max: 177,
                        variants: vec![
                            InputVariant { id: 175, code: 175 },
                            InputVariant { id: 176, code: 176 },
                            InputVariant { id: 177, code: 177 },
                        ],
                    },
                },
                InputField {
                    id: 141,
                    leaf: InputLeaf::Sum {
                        type_id: 110,
                        min: 173,
                        max: 174,
                        variants: vec![
                            InputVariant { id: 173, code: 173 },
                            InputVariant { id: 174, code: 174 },
                        ],
                    },
                },
                InputField {
                    id: 142,
                    leaf: InputLeaf::I128 { min: 1, max: 3 },
                },
                InputField {
                    id: 143,
                    leaf: InputLeaf::I128 { min: 0, max: 3 },
                },
                InputField {
                    id: 144,
                    leaf: InputLeaf::I128 { min: 0, max: 11 },
                },
                InputField {
                    id: 145,
                    leaf: InputLeaf::I128 { min: 0, max: 3 },
                },
            ],
            context: vec![
                InputField {
                    id: 150,
                    leaf: InputLeaf::Sum {
                        type_id: 116,
                        min: 178,
                        max: 179,
                        variants: vec![
                            InputVariant { id: 178, code: 178 },
                            InputVariant { id: 179, code: 179 },
                        ],
                    },
                },
                InputField {
                    id: 151,
                    leaf: InputLeaf::I128 { min: 0, max: 11 },
                },
                InputField {
                    id: 152,
                    leaf: InputLeaf::I128 { min: 1, max: 2 },
                },
                InputField {
                    id: 153,
                    leaf: InputLeaf::I128 { min: 0, max: 11 },
                },
                InputField {
                    id: 154,
                    leaf: InputLeaf::Sum {
                        type_id: 118,
                        min: 180,
                        max: 182,
                        variants: vec![
                            InputVariant { id: 180, code: 180 },
                            InputVariant { id: 181, code: 181 },
                            InputVariant { id: 182, code: 182 },
                        ],
                    },
                },
            ],
            output_types: vec![
                InputLeaf::I128 { min: 0, max: 17 },
                InputLeaf::I128 {
                    min: -9223372036854775808,
                    max: 9223372036854775807,
                },
                InputLeaf::I128 {
                    min: -9223372036854775808,
                    max: 9223372036854775807,
                },
                InputLeaf::I128 {
                    min: -9223372036854775808,
                    max: 9223372036854775807,
                },
                InputLeaf::I128 {
                    min: -9223372036854775808,
                    max: 9223372036854775807,
                },
                InputLeaf::I128 {
                    min: -9223372036854775808,
                    max: 9223372036854775807,
                },
                InputLeaf::I128 {
                    min: -9223372036854775808,
                    max: 9223372036854775807,
                },
                InputLeaf::I128 {
                    min: -9223372036854775808,
                    max: 9223372036854775807,
                },
                InputLeaf::I128 {
                    min: -9223372036854775808,
                    max: 9223372036854775807,
                },
                InputLeaf::I128 {
                    min: -9223372036854775808,
                    max: 9223372036854775807,
                },
            ],
        }
    }
    /// Borrow the full raw-input, complete-decision and law contract.
    #[must_use]
    pub fn descriptor(&self) -> c::Descriptor<'_> {
        c::Descriptor {
            state: c::Schema::Record(&self.state),
            command: c::Schema::Record(&self.command),
            context: c::Schema::Record(&self.context),
            program: V2ScalarProgram {
                inputs: &[
                    ScalarDomain::Int { min: 0, max: 20 },
                    ScalarDomain::Int { min: 0, max: 20 },
                    ScalarDomain::Int { min: 0, max: 4 },
                    ScalarDomain::Int { min: 0, max: 11 },
                    ScalarDomain::Int { min: 170, max: 172 },
                    ScalarDomain::Int { min: 0, max: 3 },
                    ScalarDomain::Int { min: 0, max: 3 },
                    ScalarDomain::Int { min: 175, max: 177 },
                    ScalarDomain::Int { min: 173, max: 174 },
                    ScalarDomain::Int { min: 1, max: 3 },
                    ScalarDomain::Int { min: 0, max: 3 },
                    ScalarDomain::Int { min: 0, max: 11 },
                    ScalarDomain::Int { min: 0, max: 3 },
                    ScalarDomain::Int { min: 178, max: 179 },
                    ScalarDomain::Int { min: 0, max: 11 },
                    ScalarDomain::Int { min: 1, max: 2 },
                    ScalarDomain::Int { min: 0, max: 11 },
                    ScalarDomain::Int { min: 180, max: 182 },
                ],
                outputs: &[
                    ScalarDomain::Int { min: 0, max: 17 },
                    ScalarDomain::Int {
                        min: -9223372036854775808,
                        max: 9223372036854775807,
                    },
                    ScalarDomain::Int {
                        min: -9223372036854775808,
                        max: 9223372036854775807,
                    },
                    ScalarDomain::Int {
                        min: -9223372036854775808,
                        max: 9223372036854775807,
                    },
                    ScalarDomain::Int {
                        min: -9223372036854775808,
                        max: 9223372036854775807,
                    },
                    ScalarDomain::Int {
                        min: -9223372036854775808,
                        max: 9223372036854775807,
                    },
                    ScalarDomain::Int {
                        min: -9223372036854775808,
                        max: 9223372036854775807,
                    },
                    ScalarDomain::Int {
                        min: -9223372036854775808,
                        max: 9223372036854775807,
                    },
                    ScalarDomain::Int {
                        min: -9223372036854775808,
                        max: 9223372036854775807,
                    },
                    ScalarDomain::Int {
                        min: -9223372036854775808,
                        max: 9223372036854775807,
                    },
                ],
                nodes: &[
                    Op::Input(13),
                    Op::Input(7),
                    Op::Int(175),
                    Op::Eq(1, 2),
                    Op::Int(178),
                    Op::Int(179),
                    Op::Select(3, 4, 5),
                    Op::Eq(0, 6),
                    Op::Not(7),
                    Op::Int(0),
                    Op::Input(14),
                    Op::Input(3),
                    Op::Lt(11, 10),
                    Op::Not(12),
                    Op::Int(1),
                    Op::Input(17),
                    Op::Int(180),
                    Op::Eq(15, 16),
                    Op::Not(17),
                    Op::And(3, 18),
                    Op::Int(2),
                    Op::Input(16),
                    Op::Lt(10, 21),
                    Op::Sub(10, 21),
                    Op::Lt(14, 23),
                    Op::Not(22),
                    Op::Not(24),
                    Op::And(25, 26),
                    Op::Not(27),
                    Op::And(3, 28),
                    Op::Int(3),
                    Op::Input(4),
                    Op::Int(170),
                    Op::Eq(31, 32),
                    Op::Not(33),
                    Op::And(3, 34),
                    Op::Int(4),
                    Op::Not(3),
                    Op::And(37, 33),
                    Op::Int(5),
                    Op::Input(11),
                    Op::Eq(40, 11),
                    Op::Not(41),
                    Op::And(37, 42),
                    Op::Int(6),
                    Op::Int(176),
                    Op::Eq(1, 45),
                    Op::Input(12),
                    Op::Input(6),
                    Op::Lt(47, 48),
                    Op::And(46, 49),
                    Op::Int(7),
                    Op::Input(8),
                    Op::Int(173),
                    Op::Eq(52, 53),
                    Op::Input(15),
                    Op::Eq(55, 14),
                    Op::Not(54),
                    Op::Not(56),
                    Op::And(57, 58),
                    Op::Not(59),
                    Op::Input(9),
                    Op::Add(61, 61),
                    Op::Select(60, 61, 62),
                    Op::Lt(30, 63),
                    Op::And(3, 64),
                    Op::Int(8),
                    Op::Lt(10, 36),
                    Op::Lt(10, 66),
                    Op::Select(68, 14, 20),
                    Op::Select(67, 9, 69),
                    Op::Lt(11, 36),
                    Op::Lt(11, 66),
                    Op::Select(72, 14, 20),
                    Op::Select(71, 9, 73),
                    Op::Lt(74, 70),
                    Op::Input(2),
                    Op::Select(75, 9, 76),
                    Op::Add(77, 63),
                    Op::Lt(36, 78),
                    Op::And(3, 79),
                    Op::Int(9),
                    Op::Input(10),
                    Op::Eq(61, 30),
                    Op::Select(83, 20, 14),
                    Op::Select(56, 61, 84),
                    Op::Eq(61, 14),
                    Op::Eq(61, 20),
                    Op::Select(87, 30, 39),
                    Op::Select(86, 20, 88),
                    Op::Select(56, 61, 89),
                    Op::Select(54, 85, 90),
                    Op::Lt(82, 91),
                    Op::And(3, 92),
                    Op::Int(10),
                    Op::Input(0),
                    Op::Sub(95, 61),
                    Op::Lt(96, 20),
                    Op::Not(97),
                    Op::Input(1),
                    Op::Sub(99, 61),
                    Op::Lt(100, 9),
                    Op::Not(101),
                    Op::Select(54, 98, 102),
                    Op::Not(103),
                    Op::And(3, 104),
                    Op::Int(11),
                    Op::And(3, 54),
                    Op::Int(12),
                    Op::Int(13),
                    Op::Int(171),
                    Op::Eq(31, 110),
                    Op::And(46, 111),
                    Op::Int(14),
                    Op::Int(15),
                    Op::Int(16),
                    Op::Int(17),
                    Op::Select(111, 115, 116),
                    Op::Select(46, 114, 117),
                    Op::Select(112, 113, 118),
                    Op::Select(3, 109, 119),
                    Op::Select(107, 108, 120),
                    Op::Select(105, 106, 121),
                    Op::Select(93, 94, 122),
                    Op::Select(80, 81, 123),
                    Op::Select(65, 66, 124),
                    Op::Select(50, 51, 125),
                    Op::Select(43, 44, 126),
                    Op::Select(38, 39, 127),
                    Op::Select(35, 36, 128),
                    Op::Select(29, 30, 129),
                    Op::Select(19, 20, 130),
                    Op::Select(13, 14, 131),
                    Op::Select(8, 9, 132),
                    Op::Add(10, 20),
                    Op::Add(99, 47),
                    Op::Add(95, 47),
                    Op::Input(5),
                    Op::Add(95, 137),
                    Op::Add(99, 137),
                ],
                roots: &[133, 96, 78, 134, 100, 135, 77, 136, 138, 139],
            },
            bindings: &[
                c::Binding {
                    source: c::Source::State,
                    selector: c::Selector::Field(130),
                },
                c::Binding {
                    source: c::Source::State,
                    selector: c::Selector::Field(131),
                },
                c::Binding {
                    source: c::Source::State,
                    selector: c::Selector::Field(132),
                },
                c::Binding {
                    source: c::Source::State,
                    selector: c::Selector::Field(133),
                },
                c::Binding {
                    source: c::Source::State,
                    selector: c::Selector::Field(134),
                },
                c::Binding {
                    source: c::Source::State,
                    selector: c::Selector::Field(135),
                },
                c::Binding {
                    source: c::Source::State,
                    selector: c::Selector::Field(136),
                },
                c::Binding {
                    source: c::Source::Command,
                    selector: c::Selector::Field(140),
                },
                c::Binding {
                    source: c::Source::Command,
                    selector: c::Selector::Field(141),
                },
                c::Binding {
                    source: c::Source::Command,
                    selector: c::Selector::Field(142),
                },
                c::Binding {
                    source: c::Source::Command,
                    selector: c::Selector::Field(143),
                },
                c::Binding {
                    source: c::Source::Command,
                    selector: c::Selector::Field(144),
                },
                c::Binding {
                    source: c::Source::Command,
                    selector: c::Selector::Field(145),
                },
                c::Binding {
                    source: c::Source::Context,
                    selector: c::Selector::Field(150),
                },
                c::Binding {
                    source: c::Source::Context,
                    selector: c::Selector::Field(151),
                },
                c::Binding {
                    source: c::Source::Context,
                    selector: c::Selector::Field(152),
                },
                c::Binding {
                    source: c::Source::Context,
                    selector: c::Selector::Field(153),
                },
                c::Binding {
                    source: c::Source::Context,
                    selector: c::Selector::Field(154),
                },
            ],
            output_types: &self.output_types,
            decision_output: 0,
            branches: BRANCHES,
            reasons: &[
                c::Reason {
                    id: 200,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 201,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 202,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 203,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 204,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 205,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 206,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 207,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 208,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 209,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 210,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 211,
                    class: c::Class::Reject,
                },
                c::Reason {
                    id: 212,
                    class: c::Class::CommittedFailure,
                },
            ],
            channels: &[c::Channel {
                id: 300,
                destination: c::Domain::Text,
                payload: &[
                    c::TypedField {
                        field: 160,
                        domain: c::Domain::I128 { min: 0, max: 11 },
                    },
                    c::TypedField {
                        field: 161,
                        domain: c::Domain::Sum {
                            type_id: 120,
                            variants: &[183, 184],
                        },
                    },
                    c::TypedField {
                        field: 162,
                        domain: c::Domain::Sum {
                            type_id: 120,
                            variants: &[183, 184],
                        },
                    },
                    c::TypedField {
                        field: 163,
                        domain: c::Domain::I128 { min: 1, max: 3 },
                    },
                    c::TypedField {
                        field: 164,
                        domain: c::Domain::I128 { min: 0, max: 3 },
                    },
                    c::TypedField {
                        field: 165,
                        domain: c::Domain::I128 { min: 0, max: 13 },
                    },
                ],
                idempotency: c::Domain::U128 { min: 0, max: 0 },
            }],
            laws: LAWS,
            required: REQUIRED,
            limits: v2_zero_limits()
                .with_limit(Resource::Read, 298)
                .with_limit(Resource::Write, 7)
                .with_limit(Resource::Candidate, 1)
                .with_limit(Resource::Effect, 1)
                .with_limit(Resource::Byte, 456)
                .with_limit(Resource::WitnessByte, 0)
                .with_limit(Resource::Depth, 0)
                .with_limit(Resource::Step, 1330),
        }
    }
}
/// Exact complete schema/policy correspondence precedes Authority construction.
pub fn checked_catalog<'a>(
    descriptor: &'a c::Descriptor<'a>,
) -> Result<catalog::BoundCatalog<'a>, catalog::Failure> {
    catalog::bind_original(
        ORIGINAL_SCHEMA,
        &DESCRIPTION,
        catalog::Limits {
            schema: s::Limits {
                bytes: ORIGINAL_SCHEMA.len() as u64,
                types: 21,
                fields: 7,
                variants: 3,
            },
            contract_bytes: ORIGINAL_POLICY.len() as u64,
        },
        ORIGINAL_POLICY,
        descriptor,
        &FRAMING,
        CHANNEL_ROOTS,
    )
}
/// Ordered refusal at checked catalog or private Authority construction.
#[derive(Debug)]
#[non_exhaustive]
pub enum BindFailure {
    /// Complete original schema/policy correspondence refused.
    Catalog(catalog::Failure),
    /// Private library source binding refused.
    Authority(authority::Refusal),
}
/// Sole supplied production constructor; identity comes from the checked library.
pub fn checked_authority<'a>(
    descriptor: &'a c::Descriptor<'a>,
) -> Result<authority::Authority<'a>, BindFailure> {
    let catalog = checked_catalog(descriptor).map_err(BindFailure::Catalog)?;
    authority::bind(&catalog).map_err(BindFailure::Authority)
}
