[package]
name = "zeno-fcis-spec"
description = "Bounded .zeno parser, typed project AST, logic, and authoring builders for ZenoFCIS"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
readme.workspace = true

[features]
default = ["std"]
std = ["zeno-fcis-codec/std"]

[dependencies]
zeno-fcis-codec = { version = "=1.0.0-rc.3", path = "../zeno-fcis-codec", default-features = false }

[dev-dependencies]
zeno-fcis-crypto = { version = "=1.0.0-rc.3", path = "../zeno-fcis-crypto", features = ["rustcrypto"] }

[lints]
workspace = true
