//! Typed Python domain adapter and ZCVE/1 replay rendering.
//!
//! Emits ordinary Python classes with strict `to_value`/`try_from_value`
//! conversions, a fixed ZCVE/1 encoder/decoder module used for replay, and the
//! vector evidence list. Stable numeric identifiers drive every emitted
//! reference.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use zeno_fcis_schema::{FieldDef, Schema, TypeDef, TypeId, TypeKind};

use crate::vectors::VectorCase;
use crate::{CodegenError, GenerationSpec};

/// Renders the fixed ZCVE/1 Python codec module (`zcve.py`).
pub(crate) fn render_codec_module() -> String {
    ZCVE_PY.to_owned()
}

/// Renders the typed Python adapter module (`<python_module>.py`).
pub(crate) fn render_adapter_module(
    schema: &Schema,
    spec: &GenerationSpec,
    cases: &[VectorCase],
) -> Result<String, CodegenError> {
    validate_python_names(schema, spec)?;
    let mut output = String::new();
    output.push_str("# @generated by zeno-fcis-codegen/1; do not edit.\n");
    let _ = writeln!(output, "from zcve import encode, decode, DecodeError\n");
    let _ = writeln!(output, "GENERATOR_ID = \"{}\"", crate::render::GENERATOR_ID);
    let _ = writeln!(output, "PYTHON_MODULE = \"{}\"", spec.python_module());
    let _ = writeln!(output, "PROFILE_NAME = \"{}\"", schema.profile().as_str());
    let _ = writeln!(output, "PROFILE_VERSION = {}", schema.version());
    let _ = writeln!(output, "ROOT_TYPE_ID = {}\n", schema.root_type().get());
    emit_constants(&mut output, schema);
    emit_adapter_error(&mut output);
    for definition in schema.types() {
        emit_type(&mut output, schema, definition)?;
    }
    output.push_str("class VectorCase:\n");
    output.push_str(
        "    def __init__(self, name, kind, bytes, expect_kind, expect_label, validate_type):\n",
    );
    output.push_str("        self.name = name; self.kind = kind; self.bytes = bytes\n");
    output.push_str("        self.expect_kind = expect_kind; self.expect_label = expect_label\n");
    output.push_str("        self.validate_type = validate_type\n\n");
    output.push_str(crate::vectors::render_python(cases).as_str());
    emit_replay(&mut output);
    Ok(output)
}

fn emit_constants(output: &mut String, schema: &Schema) {
    for definition in schema.types() {
        let type_name = definition.name().as_str().to_ascii_uppercase();
        let _ = writeln!(output, "TYPE_{type_name} = {}", definition.id().get());
        match definition.kind() {
            TypeKind::Record { fields } => {
                for field in fields.iter() {
                    let field_name = field.name().as_str().to_ascii_uppercase();
                    let _ = writeln!(
                        output,
                        "FIELD_{type_name}_{field_name} = {}",
                        field.id().get()
                    );
                }
            }
            TypeKind::Enum { .. } | TypeKind::Sum { .. } => {
                emit_variant_constants(output, definition, &type_name);
            }
            _ => {}
        }
    }
    output.push('\n');
}

fn emit_variant_constants(output: &mut String, definition: &TypeDef, type_name: &str) {
    let variants: Box<dyn Iterator<Item = (u16, &str)>> = match definition.kind() {
        TypeKind::Enum { variants } => {
            Box::new(variants.iter().map(|v| (v.id().get(), v.name().as_str())))
        }
        TypeKind::Sum { variants } => {
            Box::new(variants.iter().map(|v| (v.id().get(), v.name().as_str())))
        }
        _ => Box::new(core::iter::empty()),
    };
    for (id, name) in variants {
        let upper = name.to_ascii_uppercase();
        let _ = writeln!(output, "VARIANT_{type_name}_{upper} = {id}");
    }
}

fn emit_adapter_error(output: &mut String) {
    output.push_str("class AdapterError(Exception):\n");
    output.push_str("    def __init__(self, kind):\n");
    output.push_str("        super().__init__(kind)\n");
    output.push_str("        self.kind = kind\n\n");
    output.push_str("def _is_tuple(value, size):\n");
    output.push_str("    return type(value) is tuple and len(value) == size\n\n");
    output.push_str("def _is_tagged(value, tag, size):\n");
    output.push_str(
        "    return _is_tuple(value, size) and type(value[0]) is str and value[0] == tag\n\n",
    );
    output.push_str("def _child_value(child, expected):\n");
    output.push_str("    if type(child) is not expected: raise AdapterError(\"type_mismatch\")\n");
    output.push_str("    return child.to_value()\n\n");
}

/// Renders the incoming check that `v` is exactly a `size`-element value
/// tuple carrying `tag`; short, extra, and non-tuple values are rejected
/// before any element is indexed.
fn tagged_check(tag: &str, size: usize) -> String {
    format!("if not _is_tagged(v, \"{tag}\", {size}): raise AdapterError(\"type_mismatch\")")
}

fn emit_type(
    output: &mut String,
    schema: &Schema,
    definition: &TypeDef,
) -> Result<(), CodegenError> {
    let name = definition.name().as_str();
    match definition.kind() {
        TypeKind::Unit => emit_unit(output, name),
        TypeKind::Bool => emit_bool(output, name),
        TypeKind::U128 { min, max } => emit_u128(output, name, *min, *max),
        TypeKind::I128 { min, max } => emit_i128(output, name, *min, *max),
        TypeKind::Bytes { min_len, max_len } => emit_bytes(output, name, *min_len, *max_len),
        TypeKind::Text { min_len, max_len } => emit_text(output, name, *min_len, *max_len),
        TypeKind::Enum { variants } => emit_enum(output, definition, name, variants),
        TypeKind::Tuple { items } => emit_tuple(output, schema, definition, name, items),
        TypeKind::Record { fields } => emit_record(output, schema, definition, name, fields)?,
        TypeKind::Sum { variants } => emit_sum(output, schema, definition, name, variants),
        TypeKind::Vector {
            element,
            min_len,
            max_len,
        } => emit_vector(output, schema, name, element, *min_len, *max_len),
        TypeKind::Map {
            key,
            value,
            min_len,
            max_len,
        } => emit_map(output, schema, name, key, value, *min_len, *max_len),
    }
    Ok(())
}

fn emit_unit(output: &mut String, name: &str) {
    let _ = writeln!(output, "class {name}:");
    let _ = writeln!(output, "    def to_value(self): return (\"unit\",)");
    let _ = writeln!(output, "    @classmethod");
    let _ = writeln!(output, "    def try_from_value(cls, v):");
    let _ = writeln!(output, "        {}", tagged_check("unit", 1));
    let _ = writeln!(output, "        return cls()\n");
}

fn emit_bool(output: &mut String, name: &str) {
    let _ = writeln!(output, "class {name}:");
    let _ = writeln!(output, "    def __init__(self, value): self.value = value");
    let _ = writeln!(output, "    def to_value(self):");
    let _ = writeln!(output, "        {}", exact_type_check("self.value", "bool"));
    let _ = writeln!(output, "        return (\"bool\", self.value)");
    let _ = writeln!(output, "    @classmethod");
    let _ = writeln!(output, "    def try_from_value(cls, v):");
    let _ = writeln!(output, "        {}", tagged_check("bool", 2));
    let _ = writeln!(output, "        {}", exact_type_check("v[1]", "bool"));
    let _ = writeln!(output, "        return cls(v[1])\n");
}

/// Renders a Python statement rejecting anything but the exact built-in type.
///
/// `type(x) is T` deliberately excludes subclasses: `bool` is an `int`
/// subclass, and subclasses can override comparison or `encode` to bypass the
/// range, length, and ASCII checks that follow.
fn exact_type_check(expression: &str, python_type: &str) -> String {
    format!("if type({expression}) is not {python_type}: raise AdapterError(\"type_mismatch\")")
}

/// Emits the outgoing enum/sum check that `self.variant` is a generated
/// variant name (a plain `str` key of `_BY_NAME`).
fn emit_variant_name_check(output: &mut String) {
    let _ = writeln!(
        output,
        "        {}",
        exact_type_check("self.variant", "str")
    );
    let _ = writeln!(
        output,
        "        if self.variant not in self._BY_NAME: raise AdapterError(\"unknown_variant\")"
    );
}

fn emit_u128(output: &mut String, name: &str, min: u128, max: u128) {
    let _ = writeln!(output, "class {name}:");
    let _ = writeln!(output, "    MIN = {min}");
    let _ = writeln!(output, "    MAX = {max}");
    let _ = writeln!(output, "    def __init__(self, value): self.value = value");
    let _ = writeln!(output, "    def to_value(self):");
    let _ = writeln!(output, "        x = self.value");
    let _ = writeln!(output, "        {}", exact_type_check("x", "int"));
    let _ = writeln!(
        output,
        "        if not (self.MIN <= x <= self.MAX): raise AdapterError(\"integer_range\")"
    );
    let _ = writeln!(output, "        return (\"u128\", x)");
    let _ = writeln!(output, "    @classmethod");
    let _ = writeln!(output, "    def try_from_value(cls, v):");
    let _ = writeln!(output, "        {}", tagged_check("u128", 2));
    let _ = writeln!(output, "        x = v[1]");
    let _ = writeln!(output, "        {}", exact_type_check("x", "int"));
    let _ = writeln!(
        output,
        "        if not (cls.MIN <= x <= cls.MAX): raise AdapterError(\"integer_range\")"
    );
    let _ = writeln!(output, "        return cls(x)\n");
}

fn emit_i128(output: &mut String, name: &str, min: i128, max: i128) {
    let _ = writeln!(output, "class {name}:");
    let _ = writeln!(output, "    MIN = {min}");
    let _ = writeln!(output, "    MAX = {max}");
    let _ = writeln!(output, "    def __init__(self, value): self.value = value");
    let _ = writeln!(output, "    def to_value(self):");
    let _ = writeln!(output, "        x = self.value");
    let _ = writeln!(output, "        {}", exact_type_check("x", "int"));
    let _ = writeln!(
        output,
        "        if not (self.MIN <= x <= self.MAX): raise AdapterError(\"integer_range\")"
    );
    let _ = writeln!(output, "        return (\"i128\", x)");
    let _ = writeln!(output, "    @classmethod");
    let _ = writeln!(output, "    def try_from_value(cls, v):");
    let _ = writeln!(output, "        {}", tagged_check("i128", 2));
    let _ = writeln!(output, "        x = v[1]");
    let _ = writeln!(output, "        {}", exact_type_check("x", "int"));
    let _ = writeln!(
        output,
        "        if not (cls.MIN <= x <= cls.MAX): raise AdapterError(\"integer_range\")"
    );
    let _ = writeln!(output, "        return cls(x)\n");
}

fn emit_bytes(output: &mut String, name: &str, min_len: u32, max_len: u32) {
    let _ = writeln!(output, "class {name}:");
    let _ = writeln!(output, "    MIN_LEN = {min_len}");
    let _ = writeln!(output, "    MAX_LEN = {max_len}");
    let _ = writeln!(output, "    def __init__(self, value): self.value = value");
    let _ = writeln!(output, "    def to_value(self):");
    let _ = writeln!(output, "        b = self.value");
    let _ = writeln!(output, "        {}", exact_type_check("b", "bytes"));
    let _ = writeln!(output, "        n = len(b)");
    let _ = writeln!(
        output,
        "        if not (self.MIN_LEN <= n <= self.MAX_LEN): raise AdapterError(\"length\")"
    );
    let _ = writeln!(output, "        return (\"bytes\", b)");
    let _ = writeln!(output, "    @classmethod");
    let _ = writeln!(output, "    def try_from_value(cls, v):");
    let _ = writeln!(output, "        {}", tagged_check("bytes", 2));
    let _ = writeln!(output, "        b = v[1]");
    let _ = writeln!(output, "        {}", exact_type_check("b", "bytes"));
    let _ = writeln!(output, "        n = len(b)");
    let _ = writeln!(
        output,
        "        if not (cls.MIN_LEN <= n <= cls.MAX_LEN): raise AdapterError(\"length\")"
    );
    let _ = writeln!(output, "        return cls(b)\n");
}

fn emit_text(output: &mut String, name: &str, min_len: u32, max_len: u32) {
    let _ = writeln!(output, "class {name}:");
    let _ = writeln!(output, "    MIN_LEN = {min_len}");
    let _ = writeln!(output, "    MAX_LEN = {max_len}");
    let _ = writeln!(output, "    def __init__(self, value): self.value = value");
    let _ = writeln!(output, "    def to_value(self):");
    let _ = writeln!(output, "        s = self.value");
    let _ = writeln!(output, "        {}", exact_type_check("s", "str"));
    let _ = writeln!(output, "        try: s.encode(\"ascii\")");
    let _ = writeln!(
        output,
        "        except UnicodeEncodeError: raise AdapterError(\"non_ascii_text\")"
    );
    let _ = writeln!(output, "        n = len(s)");
    let _ = writeln!(
        output,
        "        if not (self.MIN_LEN <= n <= self.MAX_LEN): raise AdapterError(\"length\")"
    );
    let _ = writeln!(output, "        return (\"text\", s)");
    let _ = writeln!(output, "    @classmethod");
    let _ = writeln!(output, "    def try_from_value(cls, v):");
    let _ = writeln!(output, "        {}", tagged_check("text", 2));
    let _ = writeln!(output, "        s = v[1]");
    let _ = writeln!(output, "        {}", exact_type_check("s", "str"));
    let _ = writeln!(output, "        try: s.encode(\"ascii\")");
    let _ = writeln!(
        output,
        "        except UnicodeEncodeError: raise AdapterError(\"non_ascii_text\")"
    );
    let _ = writeln!(output, "        n = len(s)");
    let _ = writeln!(
        output,
        "        if not (cls.MIN_LEN <= n <= cls.MAX_LEN): raise AdapterError(\"length\")"
    );
    let _ = writeln!(output, "        return cls(s)\n");
}

fn emit_enum(
    output: &mut String,
    definition: &TypeDef,
    name: &str,
    variants: &[zeno_fcis_schema::EnumVariantDef],
) {
    let type_const = format!("TYPE_{}", name.to_ascii_uppercase());
    let _ = writeln!(output, "class {name}:");
    let _ = writeln!(output, "    _BY_NAME = {{}}");
    let _ = writeln!(output, "    _BY_ORD = {{}}");
    let _ = writeln!(
        output,
        "    def __init__(self, variant): self.variant = variant"
    );
    let _ = writeln!(output, "    def to_value(self):");
    emit_variant_name_check(output);
    let _ = writeln!(
        output,
        "        return (\"enum\", {type_const}, self._BY_NAME[self.variant])"
    );
    let _ = writeln!(output, "    @classmethod");
    let _ = writeln!(output, "    def try_from_value(cls, v):");
    let _ = writeln!(
        output,
        "        if not (_is_tagged(v, \"enum\", 3) and type(v[1]) is int and v[1] == {type_const}): raise AdapterError(\"type_mismatch\")"
    );
    let _ = writeln!(output, "        ord_ = v[2]");
    let _ = writeln!(output, "        {}", exact_type_check("ord_", "int"));
    let _ = writeln!(
        output,
        "        if ord_ not in cls._BY_ORD: raise AdapterError(\"unknown_variant\")"
    );
    let _ = writeln!(output, "        return cls(cls._BY_ORD[ord_])\n");
    for variant in variants {
        let vname = variant.name().as_str();
        let vconst = format!(
            "VARIANT_{}_{}",
            name.to_ascii_uppercase(),
            vname.to_ascii_uppercase()
        );
        let _ = writeln!(output, "{name}._BY_NAME[\"{vname}\"] = {vconst}");
        let _ = writeln!(output, "{name}._BY_ORD[{vconst}] = \"{vname}\"");
    }
    output.push('\n');
    let _ = definition;
}

fn emit_tuple(
    output: &mut String,
    schema: &Schema,
    _definition: &TypeDef,
    name: &str,
    items: &[TypeId],
) {
    let _ = writeln!(output, "class {name}:");
    let _ = writeln!(output, "    def __init__(self, {}):", tuple_fields(items));
    for (index, _item) in items.iter().enumerate() {
        let _ = writeln!(output, "        self.field_{index} = field_{index}");
    }
    let _ = writeln!(output, "    def to_value(self):");
    let _ = writeln!(
        output,
        "        return (\"tuple\", [{}])",
        tuple_to_value(schema, items)
    );
    let _ = writeln!(output, "    @classmethod");
    let _ = writeln!(output, "    def try_from_value(cls, v):");
    let _ = writeln!(output, "        {}", tagged_check("tuple", 2));
    let _ = writeln!(output, "        items = v[1]");
    let _ = writeln!(output, "        {}", exact_type_check("items", "list"));
    let _ = writeln!(
        output,
        "        if len(items) != {}: raise AdapterError(\"record_shape\")",
        items.len()
    );
    let mut calls = Vec::new();
    for (index, item) in items.iter().enumerate() {
        let item_name = resolve_type_name(schema, *item);
        calls.push(format!("{item_name}.try_from_value(items[{index}])"));
    }
    let _ = writeln!(output, "        return cls({})", calls.join(", "));
    output.push('\n');
}

fn emit_record(
    output: &mut String,
    schema: &Schema,
    definition: &TypeDef,
    name: &str,
    fields: &[FieldDef],
) -> Result<(), CodegenError> {
    let _ = writeln!(output, "class {name}:");
    let _ = writeln!(
        output,
        "    def __init__(self, {}):",
        record_fields(fields)?
    );
    for field in fields {
        let fname = field.name().as_str();
        let _ = writeln!(output, "        self.{fname} = {fname}");
    }
    let _ = writeln!(output, "    def to_value(self):");
    let type_upper = name.to_ascii_uppercase();
    let mut to_value_parts = Vec::new();
    for field in fields {
        let fname = field.name().as_str();
        let fconst = format!("FIELD_{type_upper}_{}", fname.to_ascii_uppercase());
        let ftype = resolve_type_name(schema, field.type_id());
        to_value_parts.push(format!("({fconst}, _child_value(self.{fname}, {ftype}))"));
    }
    let _ = writeln!(
        output,
        "        return (\"record\", [{}])",
        to_value_parts.join(", ")
    );
    let _ = writeln!(output, "    @classmethod");
    let _ = writeln!(output, "    def try_from_value(cls, v):");
    let _ = writeln!(output, "        {}", tagged_check("record", 2));
    let _ = writeln!(output, "        fields = v[1]");
    let _ = writeln!(output, "        {}", exact_type_check("fields", "list"));
    let _ = writeln!(
        output,
        "        if len(fields) != {}: raise AdapterError(\"record_shape\")",
        fields.len()
    );
    // Decoded children are collected positionally so schema field names are
    // never bound as locals that could shadow generated or builtin names.
    let _ = writeln!(output, "        values = []");
    for (index, field) in fields.iter().enumerate() {
        let fname = field.name().as_str();
        let fconst = format!("FIELD_{type_upper}_{}", fname.to_ascii_uppercase());
        let _ = writeln!(output, "        field = fields[{index}]");
        let _ = writeln!(
            output,
            "        if not _is_tuple(field, 2): raise AdapterError(\"type_mismatch\")"
        );
        let _ = writeln!(output, "        {}", exact_type_check("field[0]", "int"));
        let _ = writeln!(
            output,
            "        if field[0] != {fconst}: raise AdapterError(\"record_shape\")"
        );
        let ftype = resolve_type_name(schema, field.type_id());
        let _ = writeln!(
            output,
            "        values.append({ftype}.try_from_value(field[1]))"
        );
    }
    let _ = writeln!(output, "        return cls(*values)");
    output.push('\n');
    let _ = definition;
    Ok(())
}

fn emit_sum(
    output: &mut String,
    schema: &Schema,
    _definition: &TypeDef,
    name: &str,
    variants: &[zeno_fcis_schema::SumVariantDef],
) {
    let type_const = format!("TYPE_{}", name.to_ascii_uppercase());
    let _ = writeln!(output, "class {name}:");
    let _ = writeln!(output, "    _PAYLOAD = {{}}");
    let _ = writeln!(output, "    _BY_NAME = {{}}");
    let _ = writeln!(output, "    _BY_ORD = {{}}");
    let _ = writeln!(
        output,
        "    def __init__(self, variant, payload=None): self.variant = variant; self.payload = payload"
    );
    let _ = writeln!(output, "    def to_value(self):");
    emit_variant_name_check(output);
    let _ = writeln!(output, "        ord_ = self._BY_NAME[self.variant]");
    let _ = writeln!(output, "        ptype = self._PAYLOAD.get(self.variant)");
    let _ = writeln!(output, "        if ptype is None:");
    let _ = writeln!(
        output,
        "            if self.payload is not None: raise AdapterError(\"unexpected_payload\")"
    );
    let _ = writeln!(
        output,
        "            return (\"sum\", {type_const}, ord_, None)"
    );
    let _ = writeln!(
        output,
        "        if self.payload is None: raise AdapterError(\"missing_payload\")"
    );
    let _ = writeln!(
        output,
        "        return (\"sum\", {type_const}, ord_, _child_value(self.payload, ptype))"
    );
    let _ = writeln!(output, "    @classmethod");
    let _ = writeln!(output, "    def try_from_value(cls, v):");
    let _ = writeln!(
        output,
        "        if not (_is_tagged(v, \"sum\", 4) and type(v[1]) is int and v[1] == {type_const}): raise AdapterError(\"type_mismatch\")"
    );
    let _ = writeln!(output, "        ord_ = v[2]; payload = v[3]");
    let _ = writeln!(output, "        {}", exact_type_check("ord_", "int"));
    let _ = writeln!(
        output,
        "        if ord_ not in cls._BY_ORD: raise AdapterError(\"unknown_variant\")"
    );
    let _ = writeln!(output, "        variant = cls._BY_ORD[ord_]");
    let _ = writeln!(output, "        ptype = cls._PAYLOAD.get(variant)");
    let _ = writeln!(output, "        if ptype is None:");
    let _ = writeln!(
        output,
        "            if payload is not None: raise AdapterError(\"unexpected_payload\")"
    );
    let _ = writeln!(output, "            return cls(variant)");
    let _ = writeln!(
        output,
        "        if payload is None: raise AdapterError(\"missing_payload\")"
    );
    let _ = writeln!(
        output,
        "        return cls(variant, ptype.try_from_value(payload))\n"
    );
    for variant in variants {
        let vname = variant.name().as_str();
        let vconst = format!(
            "VARIANT_{}_{}",
            name.to_ascii_uppercase(),
            vname.to_ascii_uppercase()
        );
        let _ = writeln!(output, "{name}._BY_NAME[\"{vname}\"] = {vconst}");
        let _ = writeln!(output, "{name}._BY_ORD[{vconst}] = \"{vname}\"");
        match variant.payload() {
            None => {
                let _ = writeln!(output, "{name}._PAYLOAD[\"{vname}\"] = None");
            }
            Some(payload) => {
                let payload_name = resolve_type_name(schema, payload);
                let _ = writeln!(output, "{name}._PAYLOAD[\"{vname}\"] = {payload_name}");
            }
        }
    }
    output.push('\n');
}

fn emit_vector(
    output: &mut String,
    schema: &Schema,
    name: &str,
    element: &TypeId,
    min_len: u32,
    max_len: u32,
) {
    let element_name = resolve_type_name(schema, *element);
    let _ = writeln!(output, "class {name}:");
    let _ = writeln!(output, "    MIN_LEN = {min_len}");
    let _ = writeln!(output, "    MAX_LEN = {max_len}");
    let _ = writeln!(
        output,
        "    def __init__(self, value): self.value = list(value)"
    );
    let _ = writeln!(output, "    def to_value(self):");
    let _ = writeln!(output, "        n = len(self.value)");
    let _ = writeln!(
        output,
        "        if not (self.MIN_LEN <= n <= self.MAX_LEN): raise AdapterError(\"length\")"
    );
    let _ = writeln!(
        output,
        "        return (\"vector\", [_child_value(x, {element_name}) for x in self.value])"
    );
    let _ = writeln!(output, "    @classmethod");
    let _ = writeln!(output, "    def try_from_value(cls, v):");
    let _ = writeln!(output, "        {}", tagged_check("vector", 2));
    let _ = writeln!(output, "        items = v[1]");
    let _ = writeln!(output, "        {}", exact_type_check("items", "list"));
    let _ = writeln!(output, "        n = len(items)");
    let _ = writeln!(
        output,
        "        if not (cls.MIN_LEN <= n <= cls.MAX_LEN): raise AdapterError(\"length\")"
    );
    let _ = writeln!(
        output,
        "        return cls([{element_name}.try_from_value(x) for x in items])\n"
    );
}

fn emit_map(
    output: &mut String,
    schema: &Schema,
    name: &str,
    key: &TypeId,
    value: &TypeId,
    min_len: u32,
    max_len: u32,
) {
    let key_name = resolve_type_name(schema, *key);
    let value_name = resolve_type_name(schema, *value);
    let entry_name = format!("{name}Entry");
    let _ = writeln!(output, "class {entry_name}:");
    let _ = writeln!(
        output,
        "    def __init__(self, key, value): self.key = key; self.value = value"
    );
    let _ = writeln!(output, "    def to_entry(self):");
    let _ = writeln!(output, "        kv = _child_value(self.key, {key_name})");
    let _ = writeln!(
        output,
        "        return (encode(kv), kv, _child_value(self.value, {value_name}))\n"
    );
    let _ = writeln!(output, "class {name}:");
    let _ = writeln!(output, "    MIN_LEN = {min_len}");
    let _ = writeln!(output, "    MAX_LEN = {max_len}");
    let _ = writeln!(
        output,
        "    def __init__(self, value): self.value = list(value)"
    );
    let _ = writeln!(output, "    def to_value(self):");
    let _ = writeln!(output, "        n = len(self.value)");
    let _ = writeln!(
        output,
        "        if not (self.MIN_LEN <= n <= self.MAX_LEN): raise AdapterError(\"length\")"
    );
    let _ = writeln!(output, "        entries = []");
    let _ = writeln!(output, "        for e in self.value:");
    let _ = writeln!(output, "            {}", exact_type_check("e", &entry_name));
    let _ = writeln!(output, "            entries.append(e.to_entry())");
    let _ = writeln!(output, "        entries.sort(key=lambda t: t[0])");
    let _ = writeln!(output, "        previous = None");
    let _ = writeln!(output, "        for e in entries:");
    let _ = writeln!(
        output,
        "            if previous == e[0]: raise AdapterError(\"non_canonical_map\")"
    );
    let _ = writeln!(output, "            previous = e[0]");
    let _ = writeln!(output, "        return (\"map\", entries)");
    let _ = writeln!(output, "    @classmethod");
    let _ = writeln!(output, "    def try_from_value(cls, v):");
    let _ = writeln!(output, "        {}", tagged_check("map", 2));
    let _ = writeln!(output, "        entries = v[1]");
    let _ = writeln!(output, "        {}", exact_type_check("entries", "list"));
    let _ = writeln!(output, "        n = len(entries)");
    let _ = writeln!(
        output,
        "        if not (cls.MIN_LEN <= n <= cls.MAX_LEN): raise AdapterError(\"length\")"
    );
    let _ = writeln!(output, "        values = []");
    let _ = writeln!(output, "        previous = None");
    let _ = writeln!(output, "        for e in entries:");
    let _ = writeln!(
        output,
        "            if not _is_tuple(e, 3): raise AdapterError(\"type_mismatch\")"
    );
    let _ = writeln!(
        output,
        "            values.append({entry_name}({key_name}.try_from_value(e[1]), {value_name}.try_from_value(e[2])))"
    );
    let _ = writeln!(output, "            {}", exact_type_check("e[0]", "bytes"));
    let _ = writeln!(
        output,
        "            if e[0] != encode(e[1]) or (previous is not None and previous >= e[0]): raise AdapterError(\"non_canonical_map\")"
    );
    let _ = writeln!(output, "            previous = e[0]");
    let _ = writeln!(output, "        return cls(values)\n");
}

fn emit_replay(output: &mut String) {
    output.push_str("def replay():\n");
    output.push_str("    failures = []\n");
    output.push_str("    for case in VECTORS:\n");
    output.push_str("        try:\n");
    output.push_str("            decode(case.bytes)\n");
    output.push_str("            decoded_ok = True; kind = None\n");
    output.push_str("        except DecodeError as exc:\n");
    output.push_str("            decoded_ok = False; kind = exc.kind\n");
    output.push_str(
        "        if case.expect_kind == \"accept\" or case.expect_kind == \"validate_reject\":\n",
    );
    output.push_str("            if not decoded_ok:\n");
    output.push_str("                failures.append((case.name, \"expected decode ok\", kind))\n");
    output.push_str("        elif case.expect_kind == \"decode_reject\":\n");
    output.push_str("            if decoded_ok or kind != case.expect_label:\n");
    output.push_str(
        "                failures.append((case.name, \"expected \" + case.expect_label, kind))\n",
    );
    output.push_str("    if failures:\n");
    output.push_str("        for name, expected, got in failures:\n");
    output.push_str("            print(\"vector \" + name + \" failed: expected \" + str(expected) + \" got \" + str(got))\n");
    output.push_str("        raise SystemExit(1)\n");
    output.push_str("    print(\"vectors replayed: \" + str(len(VECTORS)))\n\n");
    output.push_str("if __name__ == \"__main__\":\n");
    output.push_str("    replay()\n");
}

fn tuple_fields(items: &[TypeId]) -> String {
    let mut parts = Vec::new();
    for index in 0..items.len() {
        parts.push(format!("field_{index}"));
    }
    parts.join(", ")
}

fn tuple_to_value(schema: &Schema, items: &[TypeId]) -> String {
    let mut parts = Vec::new();
    for (index, item) in items.iter().enumerate() {
        let item_name = resolve_type_name(schema, *item);
        parts.push(format!("_child_value(self.field_{index}, {item_name})"));
    }
    parts.join(", ")
}

fn record_fields(fields: &[FieldDef]) -> Result<String, CodegenError> {
    let mut parts = Vec::new();
    for field in fields {
        parts.push(field.name().as_str().to_owned());
    }
    Ok(parts.join(", "))
}

fn resolve_type_name(schema: &Schema, id: TypeId) -> String {
    match schema.type_by_id(id) {
        Some(definition) => definition.name().as_str().to_owned(),
        None => "Unresolved".to_owned(),
    }
}

/// Module-level names the adapter module defines or imports independent of
/// the schema.
const PYTHON_MODULE_NAMES: &[&str] = &[
    "encode",
    "decode",
    "DecodeError",
    "GENERATOR_ID",
    "PYTHON_MODULE",
    "PROFILE_NAME",
    "PROFILE_VERSION",
    "ROOT_TYPE_ID",
    "AdapterError",
    "_is_tuple",
    "_is_tagged",
    "_child_value",
    "VectorCase",
    "VECTORS",
    "replay",
];

/// Builtins referenced by the adapter module, plus locals bound inside
/// generated methods that also reference class names. A class with one of
/// these names would be shadowed where it is used.
const PYTHON_SHADOWED_NAMES: &[&str] = &[
    "type",
    "int",
    "bool",
    "bytes",
    "str",
    "tuple",
    "list",
    "len",
    "super",
    "classmethod",
    "Exception",
    "UnicodeEncodeError",
    "SystemExit",
    "print",
    "self",
    "cls",
    "v",
    "x",
    "n",
    "e",
    "t",
    "kv",
    "items",
    "fields",
    "field",
    "values",
    "entries",
    "previous",
];

/// Rejects schema names that would not be distinct, unshadowed Python names in
/// the generated module.
///
/// Type names become module globals (with `<Map>Entry` companions and
/// `TYPE_`/`FIELD_`/`VARIANT_` constants); record field names become
/// `__init__` parameters and instance attributes; variant names appear only in
/// string literals and constants.
fn validate_python_names(schema: &Schema, spec: &GenerationSpec) -> Result<(), CodegenError> {
    // The adapter imports the sibling `zcve` codec module.
    if spec.python_module() == "zcve" {
        return Err(CodegenError::InvalidModuleName);
    }
    let mut globals: BTreeSet<String> = PYTHON_MODULE_NAMES
        .iter()
        .map(|name| (*name).to_owned())
        .collect();
    for definition in schema.types() {
        let name = python_name(definition.name().as_str())?;
        // Leading `__` names are mangled when referenced inside class bodies.
        if name.starts_with("__") || PYTHON_SHADOWED_NAMES.contains(&name.as_str()) {
            return Err(CodegenError::InvalidIdentifier);
        }
        let upper = name.to_ascii_uppercase();
        let mut generated = vec![format!("TYPE_{upper}")];
        match definition.kind() {
            TypeKind::Record { fields } => {
                for field in fields.iter() {
                    let field_name = python_name(field.name().as_str())?;
                    // `self` is the `__init__` receiver; the method names would
                    // be shadowed by instance attributes; `__` names are mangled
                    // or special.
                    if field_name.starts_with("__")
                        || ["self", "to_value", "try_from_value"].contains(&field_name.as_str())
                    {
                        return Err(CodegenError::InvalidIdentifier);
                    }
                    generated.push(format!("FIELD_{upper}_{}", field_name.to_ascii_uppercase()));
                }
            }
            TypeKind::Enum { variants } => {
                for variant in variants.iter() {
                    let variant_name = python_name(variant.name().as_str())?;
                    generated.push(format!(
                        "VARIANT_{upper}_{}",
                        variant_name.to_ascii_uppercase()
                    ));
                }
            }
            TypeKind::Sum { variants } => {
                for variant in variants.iter() {
                    let variant_name = python_name(variant.name().as_str())?;
                    generated.push(format!(
                        "VARIANT_{upper}_{}",
                        variant_name.to_ascii_uppercase()
                    ));
                }
            }
            TypeKind::Map { .. } => generated.push(format!("{name}Entry")),
            _ => {}
        }
        generated.push(name);
        for global in generated {
            if !globals.insert(global) {
                return Err(CodegenError::InvalidIdentifier);
            }
        }
    }
    Ok(())
}

fn python_name(value: &str) -> Result<String, CodegenError> {
    const RESERVED: &[&str] = &[
        "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class",
        "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global",
        "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return",
        "try", "while", "with", "yield",
    ];
    if RESERVED.contains(&value) {
        return Err(CodegenError::InvalidIdentifier);
    }
    Ok(value.to_owned())
}

const ZCVE_PY: &str = r#"# @generated by zeno-fcis-codegen/1; do not edit.
# ZCVE/1 canonical encoder/decoder used for vector replay parity.

TAG_UNIT = 0x00
TAG_BOOL_FALSE = 0x01
TAG_BOOL_TRUE = 0x02
TAG_U128 = 0x03
TAG_I128 = 0x04
TAG_BYTES = 0x05
TAG_TEXT = 0x06
TAG_ENUM = 0x07
TAG_TUPLE = 0x08
TAG_RECORD = 0x09
TAG_SUM = 0x0a
TAG_VECTOR = 0x0b
TAG_MAP = 0x0c


class DecodeError(Exception):
    def __init__(self, kind):
        super().__init__(kind)
        self.kind = kind


def _u32(b):
    return int.from_bytes(b, "big")


def encode(v):
    out = bytearray()
    _encode(v, out)
    return bytes(out)


def _encode(v, out):
    tag = v[0]
    if tag == "unit":
        out.append(TAG_UNIT)
    elif tag == "bool":
        out.append(TAG_BOOL_TRUE if v[1] else TAG_BOOL_FALSE)
    elif tag == "u128":
        out.append(TAG_U128); out.extend(int(v[1]).to_bytes(16, "big"))
    elif tag == "i128":
        out.append(TAG_I128); out.extend(int(v[1]).to_bytes(16, "big", signed=True))
    elif tag == "bytes":
        out.append(TAG_BYTES); _put_blob(out, v[1])
    elif tag == "text":
        out.append(TAG_TEXT); _put_blob(out, v[1].encode("ascii"))
    elif tag == "enum":
        out.append(TAG_ENUM); out.extend(int(v[1]).to_bytes(4, "big")); out.extend(int(v[2]).to_bytes(2, "big"))
    elif tag == "tuple":
        out.append(TAG_TUPLE); _put_u32(out, len(v[1]))
        for item in v[1]:
            _encode(item, out)
    elif tag == "record":
        out.append(TAG_RECORD); _put_u32(out, len(v[1]))
        prev = None
        for fid, fv in v[1]:
            if prev is not None and prev >= fid:
                raise DecodeError("non_canonical_record")
            prev = fid
            out.extend(int(fid).to_bytes(2, "big")); _encode(fv, out)
    elif tag == "sum":
        out.append(TAG_SUM); out.extend(int(v[1]).to_bytes(4, "big")); out.extend(int(v[2]).to_bytes(2, "big"))
        if v[3] is None:
            out.append(0)
        else:
            out.append(1); _encode(v[3], out)
    elif tag == "vector":
        out.append(TAG_VECTOR); _put_u32(out, len(v[1]))
        for item in v[1]:
            _encode(item, out)
    elif tag == "map":
        out.append(TAG_MAP); _put_u32(out, len(v[1]))
        prev = None
        for ek, k, val in v[1]:
            if prev is not None and prev >= ek:
                raise DecodeError("non_canonical_map")
            prev = ek
            _put_blob(out, ek); _put_blob(out, encode(val))
    else:
        raise DecodeError("unknown_tag")


def _put_u32(out, n):
    out.extend(int(n).to_bytes(4, "big"))


def _put_blob(out, b):
    _put_u32(out, len(b)); out.extend(b)


class _Cursor:
    def __init__(self, b):
        self.b = b; self.i = 0

    def take(self, n):
        if self.i + n > len(self.b):
            raise DecodeError("unexpected_end")
        chunk = self.b[self.i:self.i + n]
        self.i += n
        return chunk


def decode(b):
    c = _Cursor(b)
    v = _decode(c, 0)
    if c.i != len(b):
        raise DecodeError("trailing_bytes")
    if encode(v) != b:
        raise DecodeError("non_canonical")
    return v


def _decode(c, depth):
    if depth > 64:
        raise DecodeError("unexpected_end")
    tag = c.take(1)[0]
    if tag == TAG_UNIT:
        return ("unit",)
    if tag == TAG_BOOL_FALSE:
        return ("bool", False)
    if tag == TAG_BOOL_TRUE:
        return ("bool", True)
    if tag == TAG_U128:
        return ("u128", int.from_bytes(c.take(16), "big"))
    if tag == TAG_I128:
        return ("i128", int.from_bytes(c.take(16), "big", signed=True))
    if tag == TAG_BYTES:
        return ("bytes", bytes(_take_blob(c)))
    if tag == TAG_TEXT:
        raw = _take_blob(c)
        try:
            s = raw.decode("ascii")
        except UnicodeDecodeError:
            raise DecodeError("non_ascii_text")
        return ("text", s)
    if tag == TAG_ENUM:
        tid = int.from_bytes(c.take(4), "big"); ord_ = int.from_bytes(c.take(2), "big")
        return ("enum", tid, ord_)
    if tag == TAG_TUPLE or tag == TAG_VECTOR:
        n = _u32(c.take(4))
        items = [_decode(c, depth + 1) for _ in range(n)]
        return ("tuple" if tag == TAG_TUPLE else "vector", items)
    if tag == TAG_RECORD:
        n = _u32(c.take(4)); prev = None; fields = []
        for _ in range(n):
            fid = int.from_bytes(c.take(2), "big")
            if prev is not None and prev >= fid:
                raise DecodeError("non_canonical_record")
            prev = fid
            fields.append((fid, _decode(c, depth + 1)))
        return ("record", fields)
    if tag == TAG_SUM:
        tid = int.from_bytes(c.take(4), "big"); ord_ = int.from_bytes(c.take(2), "big")
        flag = c.take(1)[0]
        if flag == 0:
            payload = None
        elif flag == 1:
            payload = _decode(c, depth + 1)
        else:
            raise DecodeError("invalid_sum_flag")
        return ("sum", tid, ord_, payload)
    if tag == TAG_MAP:
        n = _u32(c.take(4)); prev = None; entries = []
        for _ in range(n):
            ek = bytes(_take_blob(c))
            if prev is not None and prev >= ek:
                raise DecodeError("non_canonical_map")
            prev = ek
            val = _decode(_Cursor(_take_blob(c)), depth + 1)
            kc = _Cursor(ek)
            k = _decode(kc, depth + 1)
            if kc.i != len(ek):
                raise DecodeError("trailing_bytes")
            if encode(k) != ek:
                raise DecodeError("non_canonical")
            entries.append((ek, k, val))
        return ("map", entries)
    raise DecodeError("unknown_tag")


def _take_blob(c):
    n = _u32(c.take(4))
    return c.take(n)
"#;
