//! Public bootstrap request, output, and bounded failure values.

use core::fmt;

use zeno_fcis_catalog::CatalogError;
use zeno_fcis_codec::{EncodeError, Hash32};
use zeno_fcis_codegen::{CodegenError, GenerationSpec};
use zeno_fcis_schema::TypeId;

/// Canonical bootstrap artifact format version.
pub const BOOTSTRAP_FORMAT_VERSION: u16 = 1;
/// Stable project-bootstrap generator identity.
pub const BOOTSTRAP_GENERATOR_ID: &str = "zeno-fcis-bootstrap/1";
/// Hard maximum generated file count.
pub const MAX_BOOTSTRAP_FILES: u32 = 256;
/// Hard maximum bytes in one generated file.
pub const MAX_BOOTSTRAP_FILE_BYTES: u64 = 16 * 1024 * 1024;
/// Hard maximum aggregate generated bytes.
pub const MAX_BOOTSTRAP_TOTAL_BYTES: u64 = 128 * 1024 * 1024;

/// Explicit deterministic resource envelope for one bootstrap result.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BootstrapLimits {
    max_files: u32,
    max_file_bytes: u64,
    max_total_bytes: u64,
}

impl BootstrapLimits {
    /// Creates limits under the hard generator maxima.
    pub fn try_new(
        max_files: u32,
        max_file_bytes: u64,
        max_total_bytes: u64,
    ) -> Result<Self, BootstrapError> {
        let limits = Self {
            max_files,
            max_file_bytes,
            max_total_bytes,
        };
        limits.validate()?;
        Ok(limits)
    }

    pub(crate) fn validate(self) -> Result<(), BootstrapError> {
        if self.max_files == 0
            || self.max_files > MAX_BOOTSTRAP_FILES
            || self.max_file_bytes == 0
            || self.max_file_bytes > MAX_BOOTSTRAP_FILE_BYTES
            || self.max_total_bytes < self.max_file_bytes
            || self.max_total_bytes > MAX_BOOTSTRAP_TOTAL_BYTES
        {
            Err(BootstrapError::InvalidLimits)
        } else {
            Ok(())
        }
    }

    /// Returns the generated file-count bound.
    #[must_use]
    pub const fn max_files(self) -> u32 {
        self.max_files
    }

    /// Returns the per-file byte bound.
    #[must_use]
    pub const fn max_file_bytes(self) -> u64 {
        self.max_file_bytes
    }

    /// Returns the aggregate byte bound.
    #[must_use]
    pub const fn max_total_bytes(self) -> u64 {
        self.max_total_bytes
    }
}

impl Default for BootstrapLimits {
    fn default() -> Self {
        Self {
            max_files: 128,
            max_file_bytes: 8 * 1024 * 1024,
            max_total_bytes: 64 * 1024 * 1024,
        }
    }
}

/// Validated project-bootstrap request.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BootstrapSpec {
    package_name: String,
    generation: GenerationSpec,
    limits: BootstrapLimits,
}

impl BootstrapSpec {
    /// Creates a request from a Cargo-style package name and generated module names.
    pub fn try_new(
        package_name: impl Into<String>,
        rust_module: impl Into<String>,
        python_module: impl Into<String>,
        limits: BootstrapLimits,
    ) -> Result<Self, BootstrapError> {
        limits.validate()?;
        let package_name = package_name.into();
        if !valid_package_name(&package_name) {
            return Err(BootstrapError::InvalidPackageName);
        }
        let generation = GenerationSpec::try_new(rust_module, python_module)?;
        Ok(Self {
            package_name,
            generation,
            limits,
        })
    }

    /// Returns the generated package name.
    #[must_use]
    pub fn package_name(&self) -> &str {
        &self.package_name
    }

    /// Returns the underlying schema-generation request.
    #[must_use]
    pub const fn generation(&self) -> &GenerationSpec {
        &self.generation
    }

    /// Returns the exact deterministic output envelope.
    #[must_use]
    pub const fn limits(&self) -> BootstrapLimits {
        self.limits
    }
}

/// One generated bootstrap file with a portable relative path.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BootstrapFile {
    path: String,
    bytes: Vec<u8>,
}

impl BootstrapFile {
    pub(crate) fn new(path: String, bytes: Vec<u8>) -> Self {
        Self { path, bytes }
    }

    /// Returns the portable forward-slash path.
    #[must_use]
    pub fn path(&self) -> &str {
        &self.path
    }

    /// Returns exact generated bytes.
    #[must_use]
    pub fn bytes(&self) -> &[u8] {
        &self.bytes
    }

    /// Consumes the file and returns its path and bytes.
    #[must_use]
    pub fn into_parts(self) -> (String, Vec<u8>) {
        (self.path, self.bytes)
    }
}

/// Complete content-addressed project starter.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BootstrapBundle {
    hash_algorithm_id: String,
    catalog_hash: Hash32,
    profile_hash: Hash32,
    schema_hash: Hash32,
    schema_manifest_hash: Hash32,
    schema_vector_set_hash: Hash32,
    manifest_hash: Hash32,
    total_bytes: u64,
    files: Vec<BootstrapFile>,
}

impl BootstrapBundle {
    #[allow(clippy::too_many_arguments)]
    pub(crate) fn new(
        hash_algorithm_id: String,
        catalog_hash: Hash32,
        profile_hash: Hash32,
        schema_hash: Hash32,
        schema_manifest_hash: Hash32,
        schema_vector_set_hash: Hash32,
        manifest_hash: Hash32,
        total_bytes: u64,
        files: Vec<BootstrapFile>,
    ) -> Self {
        Self {
            hash_algorithm_id,
            catalog_hash,
            profile_hash,
            schema_hash,
            schema_manifest_hash,
            schema_vector_set_hash,
            manifest_hash,
            total_bytes,
            files,
        }
    }

    /// Returns the commitment-provider identity used by the catalog and bootstrap manifest.
    #[must_use]
    pub fn hash_algorithm_id(&self) -> &str {
        &self.hash_algorithm_id
    }

    /// Returns the commitment to the complete input catalog.
    #[must_use]
    pub const fn catalog_hash(&self) -> Hash32 {
        self.catalog_hash
    }

    /// Returns the exact profile commitment carried by the catalog.
    #[must_use]
    pub const fn profile_hash(&self) -> Hash32 {
        self.profile_hash
    }

    /// Returns the catalog-bound closed-schema commitment.
    #[must_use]
    pub const fn schema_hash(&self) -> Hash32 {
        self.schema_hash
    }

    /// Returns the existing schema-generation manifest commitment.
    #[must_use]
    pub const fn schema_manifest_hash(&self) -> Hash32 {
        self.schema_manifest_hash
    }

    /// Returns the schema generator's ordered codec-vector commitment.
    #[must_use]
    pub const fn schema_vector_set_hash(&self) -> Hash32 {
        self.schema_vector_set_hash
    }

    /// Returns the bootstrap manifest commitment.
    #[must_use]
    pub const fn manifest_hash(&self) -> Hash32 {
        self.manifest_hash
    }

    /// Returns exact aggregate generated bytes, including the bootstrap manifest.
    #[must_use]
    pub const fn total_bytes(&self) -> u64 {
        self.total_bytes
    }

    /// Returns files in strictly increasing portable path order.
    #[must_use]
    pub fn files(&self) -> &[BootstrapFile] {
        &self.files
    }
}

/// Deterministic project-bootstrap failure.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum BootstrapError {
    /// The requested package name was not a bounded lowercase identifier.
    InvalidPackageName,
    /// The requested resource envelope was zero, inconsistent, or above a hard maximum.
    InvalidLimits,
    /// Generated file count exceeded the request bound.
    FileCountExceeded {
        /// Configured maximum.
        limit: u32,
        /// Attempted file count.
        actual: u32,
    },
    /// One generated file exceeded its byte bound.
    FileBytesExceeded {
        /// Generated path.
        path: String,
        /// Configured maximum.
        limit: u64,
        /// Actual bytes.
        actual: u64,
    },
    /// Aggregate generated bytes exceeded the request bound.
    TotalBytesExceeded {
        /// Configured maximum.
        limit: u64,
        /// Actual aggregate bytes.
        actual: u64,
    },
    /// Two renderers attempted to produce the same path.
    DuplicatePath(String),
    /// A renderer produced a nonportable or unsafe relative path.
    InvalidPath(String),
    /// Resource-accounting arithmetic exceeded its representation.
    LengthOverflow,
    /// A selected commitment provider returned the reserved zero sentinel.
    ZeroDerivedCommitment,
    /// A catalog definition referenced a schema type that was unavailable during rendering.
    UnknownSchemaType(TypeId),
    /// An in-memory source renderer failed while writing into its owned string.
    Render,
    /// Existing schema generation failed.
    Codegen(CodegenError),
    /// Catalog identity validation failed.
    Catalog(CatalogError),
    /// Canonical encoding or commitment construction failed.
    Encode(EncodeError),
}

impl From<CodegenError> for BootstrapError {
    fn from(error: CodegenError) -> Self {
        Self::Codegen(error)
    }
}

impl From<CatalogError> for BootstrapError {
    fn from(error: CatalogError) -> Self {
        Self::Catalog(error)
    }
}

impl From<EncodeError> for BootstrapError {
    fn from(error: EncodeError) -> Self {
        Self::Encode(error)
    }
}

impl fmt::Display for BootstrapError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidPackageName => formatter.write_str("invalid bootstrap package name"),
            Self::InvalidLimits => formatter.write_str("invalid bootstrap resource limits"),
            Self::FileCountExceeded { limit, actual } => {
                write!(formatter, "generated file count {actual} exceeds {limit}")
            }
            Self::FileBytesExceeded {
                path,
                limit,
                actual,
            } => write!(
                formatter,
                "generated file {path} has {actual} bytes, exceeding {limit}"
            ),
            Self::TotalBytesExceeded { limit, actual } => write!(
                formatter,
                "aggregate generated bytes {actual} exceed {limit}"
            ),
            Self::DuplicatePath(path) => write!(formatter, "duplicate generated path {path}"),
            Self::InvalidPath(path) => write!(formatter, "invalid generated path {path}"),
            Self::LengthOverflow => formatter.write_str("bootstrap length accounting overflowed"),
            Self::ZeroDerivedCommitment => {
                formatter.write_str("bootstrap commitment unexpectedly used the zero sentinel")
            }
            Self::UnknownSchemaType(id) => write!(formatter, "unknown generated schema type {id}"),
            Self::Render => formatter.write_str("project bootstrap rendering failed"),
            Self::Codegen(error) => write!(formatter, "schema generation failed: {error}"),
            Self::Catalog(error) => write!(formatter, "catalog validation failed: {error}"),
            Self::Encode(error) => write!(formatter, "bootstrap encoding failed: {error}"),
        }
    }
}

impl std::error::Error for BootstrapError {}

fn valid_package_name(value: &str) -> bool {
    if value.is_empty() || value.len() > 96 {
        return false;
    }
    let bytes = value.as_bytes();
    if !bytes[0].is_ascii_lowercase() && !bytes[0].is_ascii_digit() {
        return false;
    }
    bytes.iter().copied().all(|byte| {
        byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'-' | b'_')
    })
}
