//! Inspectable project-starter templates derived from one reviewed catalog.

use std::fmt::Write as _;

use zeno_fcis_catalog::{
    HashRequirement, OperationSemantics, ProjectCatalog, ReasonDisposition, ValueFlowKind,
};
use zeno_fcis_codec::Hash32;
use zeno_fcis_project::{ProfileBindings, RegistryKind};
use zeno_fcis_schema::TypeKind;

use crate::{BOOTSTRAP_GENERATOR_ID, BootstrapError, BootstrapSpec};

pub(crate) fn render_rust_project(
    catalog: &ProjectCatalog,
    _spec: &BootstrapSpec,
    catalog_hash: Hash32,
    profile_hash: Hash32,
    schema_hash: Hash32,
) -> Result<String, BootstrapError> {
    let profile = catalog.profile();
    let root_type = schema_type_name(catalog, catalog.schema().root_type())?;
    let command_type = schema_type_name(
        catalog,
        zeno_fcis_schema::TypeId::new(profile.command_type().get()),
    )?;
    let context_type = schema_type_name(
        catalog,
        zeno_fcis_schema::TypeId::new(profile.context_type().get()),
    )?;
    let mut output = String::new();
    writeln!(
        output,
        "// Typed catalog bindings generated by `{BOOTSTRAP_GENERATOR_ID}`."
    )
    .map_err(|_| BootstrapError::Render)?;
    output.push_str(
        "//\n// The private generated project reconstructs the exact reviewed catalog.\n",
    );
    output.push_str("// Declarations and typed adapters are proposals; checked library binding grants capabilities.\n\n");
    output.push_str("extern crate alloc;\n\n");
    output.push_str("use alloc::vec;\n");
    output.push_str("use core::fmt;\n");
    output.push_str("use zeno_fcis_catalog::{\n");
    output.push_str("    CatalogError, CatalogLimits, CatalogManifest, ChannelDefinition,\n");
    output.push_str("    EffectDefinition, HashRequirement, OperationSemantics, ProjectCatalog,\n");
    output.push_str("    ReasonDefinition, ReasonDisposition,\n");
    output.push_str("};\n");
    output.push_str(
        "use zeno_fcis_codec::{CanonicalEncode, CommitmentHasher, Domain, EncodeError, Hash32, commitment};\n",
    );
    output.push_str("use zeno_fcis_synthesis::finite::{canonical_v2::schema as checked_schema, v2_authority as checked_authority, v2_catalog as checked_catalog, v2_composition as checked};\n");
    output.push_str("use checked::{Assignment, Binding as DeclaredBinding, Class as DecisionClass, Domain as DeclaredDomain, Expr, Reason, Selector, Source};\n");
    output.push_str("use zeno_fcis_plan::{Effect, OutboxEntry};\n");
    output.push_str("use zeno_fcis_project::{\n");
    output.push_str(
        "    DomainPrefix, ProfileBindings, ProfileError, ProjectProfile, RegistryEntry,\n",
    );
    output.push_str("    RegistryKind, SemanticId, StableName,\n");
    output.push_str("};\n");
    output.push_str("use zeno_fcis_schema::{\n");
    output.push_str(
        "    SchemaAdmittedEnvelope, SchemaAdmittedTypeEnvelope, SchemaEnvelopeError, SchemaError,\n",
    );
    output.push_str("    TypeId, ValidationLimits, ValidationReport,\n");
    output.push_str("};\n");
    output.push('\n');
    writeln!(
        output,
        "pub const PROJECT: &str = {:?};",
        profile.project().as_str()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const SUBSYSTEM: &str = {:?};",
        profile.subsystem().as_str()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const PROFILE_ID: u32 = {};",
        profile.profile_id().get()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const PROFILE_VERSION: u32 = {};",
        profile.version()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const STATE_TYPE_ID: u32 = {};",
        profile.state_type().get()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const COMMAND_TYPE_ID: u32 = {};",
        profile.command_type().get()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const CONTEXT_TYPE_ID: u32 = {};",
        profile.context_type().get()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const DOMAIN_PREFIX: &str = {:?};\n",
        profile.domain_prefix().as_str()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const HASH_ALGORITHM_ID: &str = {:?};",
        catalog.manifest().hash_algorithm_id()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const CATALOG_HASH: Hash32 = {};",
        hash_expression(catalog_hash)
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const PROFILE_HASH: Hash32 = {};",
        hash_expression(profile_hash)
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const SCHEMA_HASH: Hash32 = {};\n",
        hash_expression(schema_hash)
    )
    .map_err(|_| BootstrapError::Render)?;
    output.push_str("/// Generated command/context commitment-domain format version.\n");
    output.push_str("pub const INPUT_COMMITMENT_FORMAT_VERSION: u16 = 1;\n");
    writeln!(
        output,
        "pub const COMMAND_DOMAIN: &str = {:?};",
        format!("{}/command", profile.domain_prefix().as_str())
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const CONTEXT_DOMAIN: &str = {:?};\n",
        format!("{}/context", profile.domain_prefix().as_str())
    )
    .map_err(|_| BootstrapError::Render)?;

    output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n");
    output.push_str("#[non_exhaustive]\n");
    output.push_str("pub enum ReasonClass { Reject, CommittedFailure }\n\n");
    render_reason_enum(&mut output, catalog)?;
    render_effect_enum(&mut output, catalog)?;
    render_channel_enum(&mut output, catalog)?;
    render_effect_helpers(&mut output, catalog)?;
    render_channel_helpers(&mut output, catalog)?;
    render_generated_project(&mut output, catalog, root_type, command_type, context_type)?;

    Ok(output)
}

fn render_id_attributes(output: &mut String, empty: bool) {
    output.push_str("/// Closed identifiers for this exact versioned catalog, not extensible library diagnostics.\n");
    output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n");
    if !empty {
        output.push_str("#[repr(u32)]\n");
    }
}

fn render_id_get(output: &mut String, empty: bool) {
    output.push_str(if empty {
        "    pub const fn get(self) -> u32 { match self {} }\n"
    } else {
        "    pub const fn get(self) -> u32 { self as u32 }\n"
    });
}

fn render_reason_enum(output: &mut String, catalog: &ProjectCatalog) -> Result<(), BootstrapError> {
    output.push_str("/// Stable catalogued reason identifiers.\n");
    render_id_attributes(output, catalog.manifest().reasons().is_empty());
    output.push_str("pub enum ReasonId {\n");
    for reason in catalog.manifest().reasons() {
        writeln!(
            output,
            "    /// `{}` at precedence {}.\n    Reason{} = {},",
            reason.name().as_str(),
            reason.precedence(),
            reason.id().get(),
            reason.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("}\n\nimpl ReasonId {\n");
    render_id_get(output, catalog.manifest().reasons().is_empty());
    output.push_str("    pub fn try_semantic_id(self) -> Result<SemanticId, ProfileError> {\n");
    output.push_str("        SemanticId::try_new(self.get())\n    }\n");
    output.push_str("    pub const fn class(self) -> ReasonClass {\n        match self {\n");
    for reason in catalog.manifest().reasons() {
        let class = match reason.disposition() {
            ReasonDisposition::Reject => "ReasonClass::Reject",
            ReasonDisposition::CommittedFailure => "ReasonClass::CommittedFailure",
            _ => return Err(BootstrapError::UnsupportedReasonDisposition),
        };
        writeln!(
            output,
            "            Self::Reason{} => {class},",
            reason.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("        }\n    }\n}\n\n");
    render_typed_reason_enum(output, catalog, ReasonDisposition::Reject, "RejectReasonId")?;
    render_typed_reason_enum(
        output,
        catalog,
        ReasonDisposition::CommittedFailure,
        "CommittedFailureReasonId",
    )?;
    Ok(())
}

fn render_typed_reason_enum(
    output: &mut String,
    catalog: &ProjectCatalog,
    disposition: ReasonDisposition,
    type_name: &str,
) -> Result<(), BootstrapError> {
    let class = match disposition {
        ReasonDisposition::Reject => "ordinary rejection",
        ReasonDisposition::CommittedFailure => "committed failure",
        _ => return Err(BootstrapError::UnsupportedReasonDisposition),
    };
    writeln!(output, "/// Stable catalogued {class} identifiers.")
        .map_err(|_| BootstrapError::Render)?;
    output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n");
    writeln!(output, "pub enum {type_name} {{").map_err(|_| BootstrapError::Render)?;
    for reason in catalog
        .manifest()
        .reasons()
        .iter()
        .filter(|reason| reason.disposition() == disposition)
    {
        writeln!(
            output,
            "    /// `{}` at precedence {}.\n    Reason{},",
            reason.name().as_str(),
            reason.precedence(),
            reason.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    writeln!(output, "}}\n\nimpl {type_name} {{").map_err(|_| BootstrapError::Render)?;
    output.push_str("    /// Returns the corresponding general generated reason.\n");
    output.push_str("    pub const fn reason_id(self) -> ReasonId {\n        match self {\n");
    for reason in catalog
        .manifest()
        .reasons()
        .iter()
        .filter(|reason| reason.disposition() == disposition)
    {
        writeln!(
            output,
            "            Self::Reason{} => ReasonId::Reason{},",
            reason.id().get(),
            reason.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("        }\n    }\n");
    output.push_str("    /// Reconstructs the reviewed nonzero semantic identifier.\n");
    output.push_str("    pub fn try_semantic_id(self) -> Result<SemanticId, ProfileError> {\n");
    output.push_str("        self.reason_id().try_semantic_id()\n    }\n");
    output.push_str("}\n\n");
    Ok(())
}

fn render_effect_enum(output: &mut String, catalog: &ProjectCatalog) -> Result<(), BootstrapError> {
    output.push_str("/// Stable identifiers for non-executable commit evidence.\n");
    render_id_attributes(output, catalog.manifest().effects().is_empty());
    output.push_str("pub enum EffectKind {\n");
    for effect in catalog.manifest().effects() {
        writeln!(
            output,
            "    /// `{}`.\n    Effect{} = {},",
            effect.name().as_str(),
            effect.id().get(),
            effect.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("}\n\nimpl EffectKind {\n");
    render_id_get(output, catalog.manifest().effects().is_empty());
    output.push_str("}\n\n");
    Ok(())
}

fn render_channel_enum(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    output.push_str("/// Stable external-delivery channel identifiers.\n");
    render_id_attributes(output, catalog.manifest().channels().is_empty());
    output.push_str("pub enum ChannelKind {\n");
    for channel in catalog.manifest().channels() {
        writeln!(
            output,
            "    /// `{}`.\n    Channel{} = {},",
            channel.name().as_str(),
            channel.id().get(),
            channel.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("}\n\nimpl ChannelKind {\n");
    render_id_get(output, catalog.manifest().channels().is_empty());
    output.push_str("}\n\n");
    Ok(())
}

fn render_effect_helpers(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    for effect in catalog.manifest().effects() {
        let payload = schema_type_name(catalog, effect.payload_type())?;
        let mut parameters = vec!["ordinal: u32".to_owned()];
        push_hash_requirement_parameter(
            &mut parameters,
            "authority",
            effect.authority_requirement(),
        );
        push_hash_requirement_parameter(&mut parameters, "subject", effect.subject_requirement());
        parameters.push(format!("payload: &crate::generated::{payload}"));
        let authority = hash_requirement_argument("authority", effect.authority_requirement());
        let subject = hash_requirement_argument("subject", effect.subject_requirement());
        writeln!(
            output,
            "/// Constructs inert catalog effect `{}`; this is not a Publication.\npub fn effect_{}(\n    {},\n) -> Result<Effect, crate::generated::AdapterError> {{\n    Ok(Effect::new(\n        ordinal,\n        EffectKind::Effect{}.get(),\n        {authority},\n        {subject},\n        payload.to_value()?,\n    ))\n}}\n",
            effect.name().as_str(), effect.id().get(), parameters.join(",\n    "), effect.id().get(),
        ).map_err(|_| BootstrapError::Render)?;
    }
    Ok(())
}

fn render_channel_helpers(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    for channel in catalog.manifest().channels() {
        let destination = schema_type_name(catalog, channel.destination_type())?;
        let payload = schema_type_name(catalog, channel.payload_type())?;
        writeln!(
            output,
            "/// Constructs inert catalog channel entry `{}`; this is not a Publication.\npub fn channel_{}(\n    ordinal: u32,\n    destination: &crate::generated::{destination},\n    payload: &crate::generated::{payload},\n) -> Result<OutboxEntry, crate::generated::AdapterError> {{\n    Ok(OutboxEntry::new(\n        ordinal,\n        ChannelKind::Channel{}.get(),\n        destination.to_value()?,\n        payload.to_value()?,\n    ))\n}}\n",
            channel.name().as_str(),
            channel.id().get(),
            channel.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    Ok(())
}

fn render_generated_input_envelopes(output: &mut String) {
    output.push_str("/// Generated input role used only by local admission diagnostics.\n");
    output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n");
    output.push_str("#[non_exhaustive]\n");
    output.push_str("pub enum GeneratedInputKind { Command, Context }\n\n");
    output.push_str("/// Schema-admitted generated command plus its derived commitment.\n");
    output.push_str("#[derive(Clone, Debug, Eq, PartialEq)]\n");
    output.push_str("pub struct GeneratedCommandEnvelope {\n");
    output.push_str("    admitted: SchemaAdmittedTypeEnvelope,\n");
    output.push_str("    commitment: Hash32,\n");
    output.push_str("}\n\n");
    output.push_str("impl GeneratedCommandEnvelope {\n");
    output.push_str("    /// Returns the exact schema-admitted command.\n");
    output.push_str(
        "    pub const fn admitted(&self) -> &SchemaAdmittedTypeEnvelope { &self.admitted }\n",
    );
    output.push_str("    /// Returns the derived domain-separated command commitment.\n");
    output.push_str("    pub const fn commitment(&self) -> Hash32 { self.commitment }\n");
    output.push_str("    /// Returns the exact successful schema-validation report.\n");
    output.push_str("    pub const fn validation_report(&self) -> ValidationReport { self.admitted.validation_report() }\n");
    output.push_str("}\n\n");
    output.push_str("/// Schema-admitted generated context plus its derived commitment.\n");
    output.push_str("#[derive(Clone, Debug, Eq, PartialEq)]\n");
    output.push_str("pub struct GeneratedContextEnvelope {\n");
    output.push_str("    admitted: SchemaAdmittedTypeEnvelope,\n");
    output.push_str("    commitment: Hash32,\n");
    output.push_str("}\n\n");
    output.push_str("impl GeneratedContextEnvelope {\n");
    output.push_str("    /// Returns the exact schema-admitted authenticated context.\n");
    output.push_str(
        "    pub const fn admitted(&self) -> &SchemaAdmittedTypeEnvelope { &self.admitted }\n",
    );
    output.push_str("    /// Returns the derived domain-separated context commitment.\n");
    output.push_str("    pub const fn commitment(&self) -> Hash32 { self.commitment }\n");
    output.push_str("    /// Returns the exact successful schema-validation report.\n");
    output.push_str("    pub const fn validation_report(&self) -> ValidationReport { self.admitted.validation_report() }\n");
    output.push_str("}\n\n");
}

fn render_generated_declarations(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    output.push_str("/// Original-field declaration helpers. Only library evaluation records actual reads/writes.\n");
    output.push_str("pub struct GeneratedDeclarations;\n\nimpl GeneratedDeclarations {\n");
    let root = catalog
        .schema()
        .type_by_id(catalog.schema().root_type())
        .ok_or(BootstrapError::UnknownSchemaType(
            catalog.schema().root_type(),
        ))?;
    if let TypeKind::Record { fields } = root.kind() {
        for field in fields {
            let name = field.name().as_str();
            let id = field.id().get();
            let ty = catalog
                .schema()
                .type_by_id(field.type_id())
                .ok_or(BootstrapError::UnknownSchemaType(field.type_id()))?;
            writeln!(output, "    /// Proposes the exact original state field `{name}`.\n    pub fn read_{name}() -> Result<Expr<'static>, GeneratedProjectError> {{\n        Ok(Expr::Input(Source::State, {id}))\n    }}\n")
                .map_err(|_| BootstrapError::Render)?;
            let body = declaration_domain_expression(ty.kind(), ty.id().get()).map_or_else(
                || {
                    format!(
                        "let _ = value; Err(GeneratedProjectError::UnsupportedStateField({id}))"
                    )
                },
                |domain| format!("Ok(Assignment {{ field: {id}, value, domain: {domain} }})"),
            );
            writeln!(output, "    /// Proposes a successor for `{name}`; admission/evaluation check the complete schema.\n    pub fn update_{name}<'a>(value: Expr<'a>) -> Result<Assignment<'a>, GeneratedProjectError> {{\n        {body}\n    }}\n")
                .map_err(|_| BootstrapError::Render)?;
        }
    }
    let context_id = zeno_fcis_schema::TypeId::new(catalog.profile().context_type().get());
    let context = catalog
        .schema()
        .type_by_id(context_id)
        .ok_or(BootstrapError::UnknownSchemaType(context_id))?;
    if let TypeKind::Record { fields } = context.kind() {
        for field in fields {
            let name = field.name().as_str();
            let id = field.id().get();
            writeln!(output, "    /// Proposes observation of original context field `{name}`.\n    pub const fn context_{name}_binding() -> DeclaredBinding {{\n        DeclaredBinding {{ source: Source::Context, selector: Selector::Field({id}) }}\n    }}\n")
                .map_err(|_| BootstrapError::Render)?;
        }
    } else {
        output.push_str("    /// Proposes observation of the original scalar context root.\n    pub const fn context_root_binding() -> DeclaredBinding {\n        DeclaredBinding { source: Source::Context, selector: Selector::Root }\n    }\n\n");
    }
    output.push_str("    /// Declares a catalogued ordinary rejection reason.\n    pub const fn reject_reason(reason: RejectReasonId) -> Reason {\n        Reason { id: reason.reason_id().get(), class: DecisionClass::Reject }\n    }\n\n");
    output.push_str("    /// Declares a catalogued committing failure reason.\n    pub const fn committed_failure_reason(reason: CommittedFailureReasonId) -> Reason {\n        Reason { id: reason.reason_id().get(), class: DecisionClass::CommittedFailure }\n    }\n}\n\n");
    Ok(())
}

fn declaration_domain_expression(kind: &TypeKind, type_id: u32) -> Option<String> {
    Some(match kind {
        TypeKind::Bool => "DeclaredDomain::Bool".to_owned(),
        TypeKind::I128 { min, max } => {
            format!("DeclaredDomain::I128 {{ min: {min}i128, max: {max}i128 }}")
        }
        TypeKind::U128 { min, max } => {
            format!("DeclaredDomain::U128 {{ min: {min}u128, max: {max}u128 }}")
        }
        TypeKind::Bytes { .. } => "DeclaredDomain::Bytes".to_owned(),
        TypeKind::Text { .. } => "DeclaredDomain::Text".to_owned(),
        TypeKind::Enum { variants } => {
            let ids = variants
                .iter()
                .map(|v| v.id().get().to_string())
                .collect::<Vec<_>>()
                .join(", ");
            format!("DeclaredDomain::Enum {{ type_id: {type_id}, variants: &[{ids}] }}")
        }
        TypeKind::Sum { variants } if variants.iter().all(|v| v.payload().is_none()) => {
            let ids = variants
                .iter()
                .map(|v| v.id().get().to_string())
                .collect::<Vec<_>>()
                .join(", ");
            format!("DeclaredDomain::Sum {{ type_id: {type_id}, variants: &[{ids}] }}")
        }
        _ => return None,
    })
}

fn push_hash_requirement_parameter(
    parameters: &mut Vec<String>,
    name: &str,
    requirement: HashRequirement,
) {
    match requirement {
        HashRequirement::Any => parameters.push(format!("{name}: Hash32")),
        HashRequirement::Present => {
            parameters.push(format!("{name}: zeno_fcis_catalog::NonZeroHash"));
        }
        HashRequirement::Absent | HashRequirement::Exact(_) => {}
    }
}

fn hash_requirement_argument(name: &str, requirement: HashRequirement) -> String {
    match requirement {
        HashRequirement::Any => name.to_owned(),
        HashRequirement::Absent => "Hash32::ZERO".to_owned(),
        HashRequirement::Present => format!("{name}.get()"),
        HashRequirement::Exact(expected) => hash_expression(expected.get()),
    }
}

fn render_program_proposal(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    output.push_str(r#"/// Complete borrowed proposal. Public fields are declaration data, never capabilities.
#[derive(Debug)]
pub struct GeneratedProgramProposal<'a> {
    /// Exact retained original named schema bytes.
    pub original_schema: &'a [u8],
    /// Complete original schema description, including unused definitions.
    pub description: &'a checked_schema::Description<'a>,
    /// Construction limits, separate from the private invocation meter.
    pub catalog_limits: checked_catalog::Limits,
    /// Exact retained complete policy bytes; serialization alone grants no authority.
    pub original_policy: &'a [u8],
    /// Complete closed control, decision, input and required law declarations.
    pub definition: &'a checked::Descriptor<'a>,
    /// Exact original state/command/context frame links.
    pub framing: &'a checked::Framing,
    /// Every original channel/destination/payload root link.
    pub channel_roots: &'a [(u32, u32, u32)],
}

/// Owned complete original input envelopes. This grants no publication authority.
#[derive(Debug)]
pub struct GeneratedInvocation { state: alloc::vec::Vec<u8>, command: alloc::vec::Vec<u8>, context: alloc::vec::Vec<u8> }

impl GeneratedInvocation {
    /// Borrows the complete envelopes for actual library-owned evaluation/publication.
    pub fn original(&self) -> checked::Raw<'_> {
        checked::Raw { state: &self.state, command: &self.command, context: &self.context }
    }
}

"#);
    output.push_str("const DECLARED_REASONS: &[(u32, DecisionClass)] = &[\n");
    for reason in catalog.manifest().reasons() {
        let class = match reason.disposition() {
            ReasonDisposition::Reject => "DecisionClass::Reject",
            ReasonDisposition::CommittedFailure => "DecisionClass::CommittedFailure",
            _ => return Err(BootstrapError::UnsupportedReasonDisposition),
        };
        writeln!(output, "    ({}, {class}),", reason.id().get())
            .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("];\n\nconst DECLARED_CHANNEL_ROOTS: &[(u32, u32, u32)] = &[\n");
    for channel in catalog.manifest().channels() {
        writeln!(
            output,
            "    ({}, {}, {}),",
            channel.id().get(),
            channel.destination_type().get(),
            channel.payload_type().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("];\n\n");
    Ok(())
}

#[allow(clippy::too_many_lines)]
fn render_generated_project(
    output: &mut String,
    catalog: &ProjectCatalog,
    root_type: &str,
    command_type: &str,
    context_type: &str,
) -> Result<(), BootstrapError> {
    render_generated_input_envelopes(output);
    render_generated_declarations(output, catalog)?;
    render_program_proposal(output, catalog)?;
    output.push_str("/// Local generated-binding construction or admission failure.\n");
    output.push_str("///\n");
    output.push_str("/// This diagnostic order is not application rejection precedence.\n");
    output.push_str("#[derive(Clone, Debug, Eq, PartialEq)]\n");
    output.push_str("#[non_exhaustive]\n");
    output.push_str("pub enum GeneratedProjectError {\n");
    output.push_str("    HashAlgorithmMismatch,\n");
    output.push_str("    SchemaHashMismatch { expected: Hash32, actual: Hash32 },\n");
    output.push_str("    ProfileHashMismatch { expected: Hash32, actual: Hash32 },\n");
    output.push_str("    CatalogHashMismatch { expected: Hash32, actual: Hash32 },\n");
    output.push_str("    RootTypeMismatch { expected: u32, actual: u32 },\n");
    output.push_str("    InputSchemaHashMismatch { kind: GeneratedInputKind, expected: Hash32, actual: Hash32 },\n");
    output.push_str(
        "    InputTypeMismatch { kind: GeneratedInputKind, expected: u32, actual: u32 },\n",
    );
    output.push_str("    InputCommitmentMismatch { kind: GeneratedInputKind, expected: Hash32, actual: Hash32 },\n");
    output.push_str("    ZeroInputCommitment(GeneratedInputKind),\n");
    output.push_str("    Catalog(CatalogError),\n");
    output.push_str("    Adapter(crate::generated::AdapterError),\n");
    output.push_str("    Encode(EncodeError),\n");
    output.push_str("    Envelope(SchemaEnvelopeError),\n");
    output.push_str("    Profile(ProfileError),\n");
    output.push_str("    Schema(SchemaError),\n");
    output.push_str("    OriginalSchemaMismatch,\n");
    output.push_str("    FramingMismatch,\n");
    output.push_str("    ReasonSetMismatch,\n");
    output.push_str("    ChannelSetMismatch,\n");
    output.push_str("    UnsupportedStateField(u16),\n");
    output.push_str("    CheckedCatalog(checked_catalog::Failure),\n");
    output.push_str("    Program(checked_authority::Refusal),\n");
    output.push_str("}\n\n");
    output.push_str("impl From<CatalogError> for GeneratedProjectError {\n");
    output.push_str("    fn from(error: CatalogError) -> Self { Self::Catalog(error) }\n");
    output.push_str("}\n\n");
    output.push_str("impl From<crate::generated::AdapterError> for GeneratedProjectError {\n");
    output.push_str(
        "    fn from(error: crate::generated::AdapterError) -> Self { Self::Adapter(error) }\n",
    );
    output.push_str("}\n\n");
    output.push_str("impl From<EncodeError> for GeneratedProjectError {\n");
    output.push_str("    fn from(error: EncodeError) -> Self { Self::Encode(error) }\n");
    output.push_str("}\n\n");
    output.push_str("impl From<SchemaEnvelopeError> for GeneratedProjectError {\n");
    output.push_str("    fn from(error: SchemaEnvelopeError) -> Self { Self::Envelope(error) }\n");
    output.push_str("}\n\n");
    output.push_str("impl From<ProfileError> for GeneratedProjectError {\n");
    output.push_str("    fn from(error: ProfileError) -> Self { Self::Profile(error) }\n");
    output.push_str("}\n\n");
    output.push_str("impl From<SchemaError> for GeneratedProjectError {\n");
    output.push_str("    fn from(error: SchemaError) -> Self { Self::Schema(error) }\n");
    output.push_str("}\n\n");
    output.push_str("impl fmt::Display for GeneratedProjectError {\n");
    output.push_str("    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {\n");
    output.push_str("        match self {\n");
    output.push_str("            Self::HashAlgorithmMismatch => formatter.write_str(\"generated project hash algorithm mismatch\"),\n");
    output.push_str("            Self::SchemaHashMismatch { expected, actual } => write!(formatter, \"generated project schema hash mismatch: expected {expected}, actual {actual}\"),\n");
    output.push_str("            Self::ProfileHashMismatch { expected, actual } => write!(formatter, \"generated project profile hash mismatch: expected {expected}, actual {actual}\"),\n");
    output.push_str("            Self::CatalogHashMismatch { expected, actual } => write!(formatter, \"generated project catalog hash mismatch: expected {expected}, actual {actual}\"),\n");
    output.push_str("            Self::RootTypeMismatch { expected, actual } => write!(formatter, \"generated project root type mismatch: expected {expected}, actual {actual}\"),\n");
    output.push_str("            Self::InputSchemaHashMismatch { kind, expected, actual } => write!(formatter, \"generated {kind:?} schema hash mismatch: expected {expected}, actual {actual}\"),\n");
    output.push_str("            Self::InputTypeMismatch { kind, expected, actual } => write!(formatter, \"generated {kind:?} type mismatch: expected {expected}, actual {actual}\"),\n");
    output.push_str("            Self::InputCommitmentMismatch { kind, expected, actual } => write!(formatter, \"generated {kind:?} commitment mismatch: expected {expected}, actual {actual}\"),\n");
    output.push_str("            Self::ZeroInputCommitment(kind) => write!(formatter, \"generated {kind:?} commitment used the zero sentinel\"),\n");
    output.push_str("            Self::Catalog(error) => write!(formatter, \"generated catalog rejected: {error}\"),\n");
    output.push_str("            Self::Adapter(error) => write!(formatter, \"generated typed adapter rejected: {error:?}\"),\n");
    output.push_str("            Self::Encode(error) => write!(formatter, \"generated input commitment failed: {error}\"),\n");
    output.push_str("            Self::Envelope(error) => write!(formatter, \"generated schema envelope rejected: {error}\"),\n");
    output.push_str("            Self::Profile(error) => write!(formatter, \"generated profile rejected: {error}\"),\n");
    output.push_str("            Self::Schema(error) => write!(formatter, \"generated schema rejected: {error}\"),\n");
    output.push_str("            Self::OriginalSchemaMismatch => formatter.write_str(\"generated project original schema differs\"),\n");
    output.push_str("            Self::FramingMismatch => formatter.write_str(\"generated project original frame links differ\"),\n");
    output.push_str("            Self::ReasonSetMismatch => formatter.write_str(\"generated project complete reason set differs\"),\n");
    output.push_str("            Self::ChannelSetMismatch => formatter.write_str(\"generated project complete channel links differ\"),\n");
    output.push_str("            Self::UnsupportedStateField(id) => write!(formatter, \"unsupported checked state field {id}\"),\n");
    output.push_str("            Self::CheckedCatalog(error) => write!(formatter, \"checked catalog: {error:?}\"),\n");
    output.push_str(
        "            Self::Program(error) => write!(formatter, \"checked program: {error:?}\"),\n",
    );
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str("/// Exact generated project bindings with no caller-supplied catalog.\n");
    output.push_str("#[derive(Clone, Debug, Eq, PartialEq)]\n");
    output.push_str("pub struct GeneratedProject { catalog: ProjectCatalog }\n\n");
    output.push_str("impl GeneratedProject {\n");
    output.push_str("    /// Reconstructs and revalidates the exact generation-time catalog.\n");
    output.push_str(
        "    pub fn try_new<H: CommitmentHasher>() -> Result<Self, GeneratedProjectError> {\n",
    );
    output.push_str("        if H::ALGORITHM_ID != HASH_ALGORITHM_ID {\n");
    output.push_str("            return Err(GeneratedProjectError::HashAlgorithmMismatch);\n");
    output.push_str("        }\n");
    writeln!(
        output,
        "        let schema = crate::generated::{root_type}::zfcis_schema()?;"
    )
    .map_err(|_| BootstrapError::Render)?;
    output.push_str("        let actual_schema_hash = schema.schema_hash::<H>()?;\n");
    output.push_str("        if actual_schema_hash != SCHEMA_HASH {\n");
    output.push_str("            return Err(GeneratedProjectError::SchemaHashMismatch { expected: SCHEMA_HASH, actual: actual_schema_hash });\n");
    output.push_str("        }\n");
    render_catalog_manifest_construction(output, catalog)?;
    render_profile_construction(output, catalog)?;
    let limits = catalog.limits();
    writeln!(
        output,
        "        let limits = CatalogLimits::try_new({}, {}, {}, {}, {}, {}, {})?;",
        limits.max_effects(),
        limits.max_outbox_entries(),
        limits.max_value_depth(),
        limits.max_value_nodes(),
        limits.max_total_value_nodes(),
        limits.max_total_payload_bytes(),
        limits.max_collection_len()
    )
    .map_err(|_| BootstrapError::Render)?;
    output.push_str(
        "        let catalog = ProjectCatalog::try_new::<H>(profile, schema, manifest, limits)?;\n",
    );
    output.push_str("        let project = Self { catalog };\n");
    output.push_str("        project.validate_catalog::<H>()?;\n");
    output.push_str("        Ok(project)\n");
    output.push_str("    }\n\n");
    output.push_str("    /// Returns the reconstructed exact catalog.\n");
    output.push_str("    pub const fn catalog(&self) -> &ProjectCatalog { &self.catalog }\n\n");
    output.push_str("    /// Admits the typed root under the exact catalog provider and schema.\n");
    output.push_str("    pub fn admit_root<H: CommitmentHasher>(\n");
    output.push_str("        &self,\n");
    writeln!(output, "        root: &crate::generated::{root_type},")
        .map_err(|_| BootstrapError::Render)?;
    output.push_str("        limits: ValidationLimits,\n");
    output.push_str("    ) -> Result<SchemaAdmittedEnvelope, GeneratedProjectError> {\n");
    output.push_str("        self.validate_catalog::<H>()?;\n");
    output.push_str("        let value = root.to_value()?;\n");
    output.push_str(
        "        Ok(SchemaAdmittedEnvelope::try_new::<H>(self.catalog.schema(), value, limits)?)\n",
    );
    output.push_str("    }\n\n");
    output.push_str("    /// Admits a typed command and derives its exact commitment.\n");
    output.push_str("    pub fn admit_command<H: CommitmentHasher>(\n");
    output.push_str("        &self,\n");
    writeln!(
        output,
        "        command: &crate::generated::{command_type},"
    )
    .map_err(|_| BootstrapError::Render)?;
    output.push_str("        limits: ValidationLimits,\n");
    output.push_str("    ) -> Result<GeneratedCommandEnvelope, GeneratedProjectError> {\n");
    output.push_str("        self.validate_catalog::<H>()?;\n");
    output.push_str("        let value = command.to_value()?;\n");
    output.push_str("        let admitted = SchemaAdmittedTypeEnvelope::try_new::<H>(\n");
    output.push_str(
        "            self.catalog.schema(), TypeId::new(COMMAND_TYPE_ID), value, limits,\n",
    );
    output.push_str("        )?;\n");
    output.push_str("        let commitment = Self::input_commitment::<H>(GeneratedInputKind::Command, &admitted)?;\n");
    output.push_str("        Ok(GeneratedCommandEnvelope { admitted, commitment })\n");
    output.push_str("    }\n\n");
    output.push_str(
        "    /// Admits a typed authenticated context and derives its exact commitment.\n",
    );
    output.push_str("    pub fn admit_context<H: CommitmentHasher>(\n");
    output.push_str("        &self,\n");
    writeln!(
        output,
        "        context: &crate::generated::{context_type},"
    )
    .map_err(|_| BootstrapError::Render)?;
    output.push_str("        limits: ValidationLimits,\n");
    output.push_str("    ) -> Result<GeneratedContextEnvelope, GeneratedProjectError> {\n");
    output.push_str("        self.validate_catalog::<H>()?;\n");
    output.push_str("        let value = context.to_value()?;\n");
    output.push_str("        let admitted = SchemaAdmittedTypeEnvelope::try_new::<H>(\n");
    output.push_str(
        "            self.catalog.schema(), TypeId::new(CONTEXT_TYPE_ID), value, limits,\n",
    );
    output.push_str("        )?;\n");
    output.push_str("        let commitment = Self::input_commitment::<H>(GeneratedInputKind::Context, &admitted)?;\n");
    output.push_str("        Ok(GeneratedContextEnvelope { admitted, commitment })\n");
    output.push_str("    }\n\n");
    output.push_str(r#"    /// Binds a complete untrusted proposal through the actual library constructors.
    /// Catalog metadata alone cannot supply branches, footprints, laws or policy adequacy.
    pub fn bind_program<'a, H: CommitmentHasher>(
        &self,
        proposal: GeneratedProgramProposal<'a>,
    ) -> Result<checked_authority::Authority<'a>, GeneratedProjectError> {
        self.validate_catalog::<H>()?;
        if self.catalog.schema().canonical_bytes()?.as_slice() != proposal.original_schema {
            return Err(GeneratedProjectError::OriginalSchemaMismatch);
        }
        let framing = proposal.framing;
        if framing.state.root != STATE_TYPE_ID || framing.command.root != COMMAND_TYPE_ID
            || framing.context.root != CONTEXT_TYPE_ID
            || framing.state.schema != *SCHEMA_HASH.as_bytes()
            || framing.command.schema != *SCHEMA_HASH.as_bytes()
            || framing.context.schema != *SCHEMA_HASH.as_bytes()
        {
            return Err(GeneratedProjectError::FramingMismatch);
        }
        if proposal.definition.reasons.len() != DECLARED_REASONS.len()
            || !DECLARED_REASONS.iter().all(|(id, class)| proposal.definition.reasons.iter()
                .any(|actual| actual.id == *id && actual.class == *class))
        {
            return Err(GeneratedProjectError::ReasonSetMismatch);
        }
        if proposal.channel_roots != DECLARED_CHANNEL_ROOTS {
            return Err(GeneratedProjectError::ChannelSetMismatch);
        }
        let catalog = checked_catalog::bind_original(
            proposal.original_schema, proposal.description, proposal.catalog_limits,
            proposal.original_policy, proposal.definition, framing, proposal.channel_roots,
        ).map_err(GeneratedProjectError::CheckedCatalog)?;
        checked_authority::bind(&catalog).map_err(GeneratedProjectError::Program)
    }

    /// Retains complete original envelopes; the library independently admits them on execution.
    /// Authentication, version/replay selection and physical effects remain host responsibilities.
    pub fn invocation<H: CommitmentHasher>(
        &self,
        pre_state: &SchemaAdmittedEnvelope,
        command: &GeneratedCommandEnvelope,
        context: &GeneratedContextEnvelope,
    ) -> Result<GeneratedInvocation, GeneratedProjectError> {
        self.validate_catalog::<H>()?;
        Self::validate_root_binding(pre_state.schema_hash(), pre_state.root_type())?;
        Self::validate_input::<H>(GeneratedInputKind::Command, command.admitted(), command.commitment())?;
        Self::validate_input::<H>(GeneratedInputKind::Context, context.admitted(), context.commitment())?;
        Ok(GeneratedInvocation {
            state: pre_state.envelope().canonical_bytes()?,
            command: command.admitted().envelope().canonical_bytes()?,
            context: context.admitted().envelope().canonical_bytes()?,
        })
    }

"#);
    output.push_str("    fn validate_root_binding(schema_hash: Hash32, root_type: TypeId) -> Result<(), GeneratedProjectError> {\n");
    output.push_str("        if schema_hash != SCHEMA_HASH {\n");
    output.push_str("            return Err(GeneratedProjectError::SchemaHashMismatch { expected: SCHEMA_HASH, actual: schema_hash });\n");
    output.push_str("        }\n");
    output.push_str("        if root_type != TypeId::new(STATE_TYPE_ID) {\n");
    output.push_str("            return Err(GeneratedProjectError::RootTypeMismatch { expected: STATE_TYPE_ID, actual: root_type.get() });\n");
    output.push_str("        }\n");
    output.push_str("        Ok(())\n");
    output.push_str("    }\n\n");
    output.push_str("    fn validate_input<H: CommitmentHasher>(\n");
    output.push_str("        kind: GeneratedInputKind,\n");
    output.push_str("        admitted: &SchemaAdmittedTypeEnvelope,\n");
    output.push_str("        expected_commitment: Hash32,\n");
    output.push_str("    ) -> Result<(), GeneratedProjectError> {\n");
    output.push_str("        let expected_type = match kind {\n");
    output.push_str("            GeneratedInputKind::Command => COMMAND_TYPE_ID,\n");
    output.push_str("            GeneratedInputKind::Context => CONTEXT_TYPE_ID,\n");
    output.push_str("        };\n");
    output.push_str("        if admitted.schema_hash() != SCHEMA_HASH {\n");
    output.push_str("            return Err(GeneratedProjectError::InputSchemaHashMismatch { kind, expected: SCHEMA_HASH, actual: admitted.schema_hash() });\n");
    output.push_str("        }\n");
    output.push_str("        if admitted.type_id() != TypeId::new(expected_type) {\n");
    output.push_str("            return Err(GeneratedProjectError::InputTypeMismatch { kind, expected: expected_type, actual: admitted.type_id().get() });\n");
    output.push_str("        }\n");
    output.push_str("        let actual = Self::input_commitment::<H>(kind, admitted)?;\n");
    output.push_str("        if actual != expected_commitment {\n");
    output.push_str("            return Err(GeneratedProjectError::InputCommitmentMismatch { kind, expected: expected_commitment, actual });\n");
    output.push_str("        }\n");
    output.push_str("        Ok(())\n");
    output.push_str("    }\n\n");
    output.push_str("    fn input_commitment<H: CommitmentHasher>(\n");
    output.push_str("        kind: GeneratedInputKind,\n");
    output.push_str("        admitted: &SchemaAdmittedTypeEnvelope,\n");
    output.push_str("    ) -> Result<Hash32, GeneratedProjectError> {\n");
    output.push_str("        let domain_name = match kind {\n");
    output.push_str("            GeneratedInputKind::Command => COMMAND_DOMAIN,\n");
    output.push_str("            GeneratedInputKind::Context => CONTEXT_DOMAIN,\n");
    output.push_str("        };\n");
    output.push_str(
        "        let domain = Domain::new(domain_name, INPUT_COMMITMENT_FORMAT_VERSION)?;\n",
    );
    output.push_str("        let bytes = admitted.canonical_bytes()?;\n");
    output.push_str("        let value = commitment::<H>(domain, &bytes)?;\n");
    output.push_str("        if value == Hash32::ZERO {\n");
    output.push_str("            return Err(GeneratedProjectError::ZeroInputCommitment(kind));\n");
    output.push_str("        }\n");
    output.push_str("        Ok(value)\n");
    output.push_str("    }\n\n");
    output.push_str("    fn validate_catalog<H: CommitmentHasher>(&self) -> Result<(), GeneratedProjectError> {\n");
    output.push_str("        if H::ALGORITHM_ID != HASH_ALGORITHM_ID {\n");
    output.push_str("            return Err(GeneratedProjectError::HashAlgorithmMismatch);\n");
    output.push_str("        }\n");
    output.push_str("        let actual_schema_hash = self.catalog.schema_hash();\n");
    output.push_str("        if actual_schema_hash != SCHEMA_HASH {\n");
    output.push_str("            return Err(GeneratedProjectError::SchemaHashMismatch { expected: SCHEMA_HASH, actual: actual_schema_hash });\n");
    output.push_str("        }\n");
    output.push_str("        let actual_profile_hash = self.catalog.profile_hash();\n");
    output.push_str("        if actual_profile_hash != PROFILE_HASH {\n");
    output.push_str("            return Err(GeneratedProjectError::ProfileHashMismatch { expected: PROFILE_HASH, actual: actual_profile_hash });\n");
    output.push_str("        }\n");
    output.push_str("        let actual_catalog_hash = self.catalog.commitment::<H>()?;\n");
    output.push_str("        if actual_catalog_hash != CATALOG_HASH {\n");
    output.push_str("            return Err(GeneratedProjectError::CatalogHashMismatch { expected: CATALOG_HASH, actual: actual_catalog_hash });\n");
    output.push_str("        }\n");
    output.push_str("        Ok(())\n");
    output.push_str("    }\n");
    output.push_str("}\n");

    Ok(())
}

fn render_catalog_manifest_construction(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    output.push_str("        let reasons = vec![\n");
    for reason in catalog.manifest().reasons() {
        let disposition = match reason.disposition() {
            ReasonDisposition::Reject => "ReasonDisposition::Reject",
            ReasonDisposition::CommittedFailure => "ReasonDisposition::CommittedFailure",
            _ => return Err(BootstrapError::UnsupportedReasonDisposition),
        };
        writeln!(
            output,
            "            ReasonDefinition::try_new(SemanticId::try_new({})?, StableName::try_new({:?})?, {disposition}, {}, {})?,",
            reason.id().get(),
            reason.name().as_str(),
            reason.precedence(),
            hash_expression(reason.predicate_hash())
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("        ];\n");
    output.push_str("        let effects = vec![\n");
    for effect in catalog.manifest().effects() {
        writeln!(
            output,
            "            EffectDefinition::try_new(SemanticId::try_new({})?, StableName::try_new({:?})?, TypeId::new({}), {}, {}, {}, {})?,",
            effect.id().get(),
            effect.name().as_str(),
            effect.payload_type().get(),
            hash_requirement_expression(effect.authority_requirement()),
            hash_requirement_expression(effect.subject_requirement()),
            operation_semantics_expression(effect.semantics()),
            hash_expression(effect.policy_hash())
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("        ];\n");
    output.push_str("        let channels = vec![\n");
    for channel in catalog.manifest().channels() {
        writeln!(
            output,
            "            ChannelDefinition::try_new(SemanticId::try_new({})?, StableName::try_new({:?})?, TypeId::new({}), TypeId::new({}), {}, {})?,",
            channel.id().get(),
            channel.name().as_str(),
            channel.destination_type().get(),
            channel.payload_type().get(),
            operation_semantics_expression(channel.semantics()),
            hash_expression(channel.delivery_policy_hash())
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("        ];\n");
    output.push_str(
        "        let manifest = CatalogManifest::try_new::<H>(reasons, effects, channels)?;\n",
    );
    Ok(())
}

fn render_profile_construction(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    let profile = catalog.profile();
    let bindings = profile.bindings();
    output.push_str("        let entries = vec![\n");
    for entry in profile.entries() {
        writeln!(
            output,
            "            RegistryEntry::try_new({}, SemanticId::try_new({})?, StableName::try_new({:?})?, {})?,",
            registry_kind_expression(entry.kind()),
            entry.id().get(),
            entry.name().as_str(),
            hash_expression(entry.definition_hash())
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("        ];\n");
    writeln!(
        output,
        "        let profile = ProjectProfile::try_new(StableName::try_new({:?})?, StableName::try_new({:?})?, SemanticId::try_new({})?, {}, SemanticId::try_new({})?, SemanticId::try_new({})?, SemanticId::try_new({})?, DomainPrefix::try_new({:?})?,",
        profile.project().as_str(),
        profile.subsystem().as_str(),
        profile.profile_id().get(),
        profile.version(),
        profile.state_type().get(),
        profile.command_type().get(),
        profile.context_type().get(),
        profile.domain_prefix().as_str()
    )
    .map_err(|_| BootstrapError::Render)?;
    render_profile_bindings(output, bindings)?;
    output.push_str("            entries,\n");
    output.push_str("        )?;\n");
    Ok(())
}

fn render_profile_bindings(
    output: &mut String,
    bindings: ProfileBindings,
) -> Result<(), BootstrapError> {
    output.push_str("            ProfileBindings {\n");
    for (field, hash) in [
        ("schema_hash", bindings.schema_hash),
        ("precedence_hash", bindings.precedence_hash),
        ("algorithm_hash", bindings.algorithm_hash),
        ("codec_hash", bindings.codec_hash),
        ("effect_registry_hash", bindings.effect_registry_hash),
        ("channel_registry_hash", bindings.channel_registry_hash),
        ("policy_hash", bindings.policy_hash),
    ] {
        writeln!(
            output,
            "                {field}: {},",
            hash_expression(hash)
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("            },\n");
    Ok(())
}

fn hash_expression(hash: Hash32) -> String {
    format!("Hash32::new({:?})", hash.as_bytes())
}

fn hash_requirement_expression(requirement: HashRequirement) -> String {
    match requirement {
        HashRequirement::Any => "HashRequirement::Any".to_owned(),
        HashRequirement::Absent => "HashRequirement::Absent".to_owned(),
        HashRequirement::Present => "HashRequirement::Present".to_owned(),
        HashRequirement::Exact(expected) => {
            format!(
                "HashRequirement::exact({})?",
                hash_expression(expected.get())
            )
        }
    }
}

fn operation_semantics_expression(semantics: &OperationSemantics) -> String {
    if !semantics.is_value_moving() {
        format!(
            "OperationSemantics::non_value({})?",
            hash_expression(semantics.classification_hash())
        )
    } else {
        let flows = semantics
            .flows()
            .iter()
            .map(|flow| match flow.custom_claim() {
                Some((claim_id, claim_hash)) => format!(
                    "zeno_fcis_catalog::ValueFlow::custom({}, SemanticId::try_new({})?, {})?",
                    hash_expression(flow.asset_domain()),
                    claim_id.get(),
                    hash_expression(claim_hash)
                ),
                None => format!(
                    "zeno_fcis_catalog::ValueFlow::standard({}, {})?",
                    value_flow_kind_expression(flow.kind()),
                    hash_expression(flow.asset_domain())
                ),
            })
            .collect::<Vec<_>>()
            .join(", ");
        format!(
            "OperationSemantics::value(vec![{flows}], {})?",
            hash_expression(semantics.classification_hash())
        )
    }
}

const fn value_flow_kind_expression(kind: ValueFlowKind) -> &'static str {
    match kind {
        ValueFlowKind::Transfer => "zeno_fcis_catalog::ValueFlowKind::Transfer",
        ValueFlowKind::Mint => "zeno_fcis_catalog::ValueFlowKind::Mint",
        ValueFlowKind::Burn => "zeno_fcis_catalog::ValueFlowKind::Burn",
        ValueFlowKind::EscrowLock => "zeno_fcis_catalog::ValueFlowKind::EscrowLock",
        ValueFlowKind::EscrowRelease => "zeno_fcis_catalog::ValueFlowKind::EscrowRelease",
        ValueFlowKind::FeeCharge => "zeno_fcis_catalog::ValueFlowKind::FeeCharge",
        ValueFlowKind::Settlement => "zeno_fcis_catalog::ValueFlowKind::Settlement",
        ValueFlowKind::ExternalValueDelivery => {
            "zeno_fcis_catalog::ValueFlowKind::ExternalValueDelivery"
        }
        ValueFlowKind::Custom => "zeno_fcis_catalog::ValueFlowKind::Custom",
    }
}

fn registry_kind_expression(kind: RegistryKind) -> &'static str {
    match kind {
        RegistryKind::StateType => "RegistryKind::StateType",
        RegistryKind::CommandType => "RegistryKind::CommandType",
        RegistryKind::ContextType => "RegistryKind::ContextType",
        RegistryKind::Reason => "RegistryKind::Reason",
        RegistryKind::Effect => "RegistryKind::Effect",
        RegistryKind::Channel => "RegistryKind::Channel",
        RegistryKind::Evidence => "RegistryKind::Evidence",
        RegistryKind::Capability => "RegistryKind::Capability",
        RegistryKind::Event => "RegistryKind::Event",
        RegistryKind::Claim => "RegistryKind::Claim",
        RegistryKind::Migration => "RegistryKind::Migration",
    }
}

fn schema_type_name(
    catalog: &ProjectCatalog,
    id: zeno_fcis_schema::TypeId,
) -> Result<&str, BootstrapError> {
    catalog
        .schema()
        .type_by_id(id)
        .map(|definition| definition.name().as_str())
        .ok_or(BootstrapError::UnknownSchemaType(id))
}

pub(crate) fn render_registry(catalog: &ProjectCatalog) -> Result<String, BootstrapError> {
    let mut output = String::from("kind\tid\tname\tdefinition_hash\n");
    for entry in catalog.profile().entries() {
        writeln!(
            output,
            "{}\t{}\t{}\t{}",
            registry_kind_name(entry.kind()),
            entry.id().get(),
            entry.name().as_str(),
            entry.definition_hash()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    Ok(output)
}

pub(crate) fn render_rust_runtime(spec: &BootstrapSpec) -> String {
    format!(
        "// Mounted-runtime adapter skeleton for `{}`.\n//\n// No runtime is mounted by generation. Implement\n// `zeno_fcis_adapter::CallableRuntime` or\n// `zeno_fcis_adapter::JsonLineRuntime`, then require complete normalized-\n// decision parity.\n\n// Intentionally no implementation: runtime authority requires project review.\n",
        spec.package_name()
    )
}

pub(crate) fn render_python_runtime(spec: &BootstrapSpec) -> String {
    format!(
        "\"\"\"Mounted-runtime protocol skeleton for {}.\n\nGeneration does not claim runtime refinement.\n\"\"\"\n\nfrom typing import Protocol\n\n\nclass MountedRuntime(Protocol):\n    def evaluate(self, request_line: str) -> str:\n        \"\"\"Return one strict complete normalized-decision JSON line.\"\"\"\n        ...\n",
        spec.package_name()
    )
}

pub(crate) fn render_migration(catalog: &ProjectCatalog) -> String {
    format!(
        "format = zeno-fcis-migration-stub/1\nproject = {}\nsubsystem = {}\nfrom_profile_version = {}\nstatus = not-specified\nmigration_hash = absent\nactivation = absent\nrollback = absent\nclaim = no-migration-authority\n",
        catalog.profile().project().as_str(),
        catalog.profile().subsystem().as_str(),
        catalog.profile().version()
    )
}

pub(crate) fn render_evidence(catalog: &ProjectCatalog) -> String {
    format!(
        "format = zeno-fcis-evidence-requirements/1\nproject = {}\nsubsystem = {}\ncodec_vectors = required-not-provided\nruntime_refinement = required-not-provided\nproof_checker = required-not-provided\ncounterexamples = required-not-provided\ntoolchain_identity = required-not-provided\npromotion_status = denied\n",
        catalog.profile().project().as_str(),
        catalog.profile().subsystem().as_str()
    )
}

pub(crate) fn render_ci(spec: &BootstrapSpec) -> String {
    format!(
        "name: generated-project-ci\n\non:\n  pull_request:\n  push:\n    branches: [main]\n\npermissions:\n  contents: read\n\nconcurrency:\n  group: generated-project-ci-${{{{ github.ref }}}}\n  cancel-in-progress: true\n\njobs:\n  rust:\n    runs-on: ubuntu-24.04\n    timeout-minutes: 30\n    steps:\n      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10\n        with:\n          persist-credentials: false\n      - run: rustup toolchain install 1.97.1 --profile minimal\n      - run: cargo +1.97.1 fmt --all -- --check\n      - run: cargo +1.97.1 clippy --workspace --all-targets --all-features --locked -- -D warnings\n      - run: cargo +1.97.1 test --workspace --all-features --locked\n      - run: cargo +1.97.1 test --workspace --doc --all-features --locked\n      - run: RUSTDOCFLAGS='-D warnings' cargo +1.97.1 doc --workspace --all-features --locked --no-deps\n# Package identity: {}\n",
        spec.package_name()
    )
}

pub(crate) fn render_architecture(catalog: &ProjectCatalog, spec: &BootstrapSpec) -> String {
    format!(
        "# {} bootstrap architecture\n\nGenerated by `{}` from the `{}/{}` catalog.\n\n## Authority boundary\n\nThe schema, profile, catalog, stable identifiers, policies, and resource limits are inputs. Generation renders inspectable starter artifacts; it does not admit business intent or authorize execution, migration, proof acceptance, promotion or release.\n\nThe private-field `GeneratedProject` reconstructs the exact catalog and rechecks its schema, profile, complete catalog and provider commitments. Typed input helpers retain complete original envelopes and derive command/context commitments in explicit profile-separated domains. Inert effect/channel helpers cannot authorize a decision.\n\n## Checked program path\n\n```text\ncomplete original schema + policy + ProgramDefinition + original frame/channel links\n  -> exact catalog correspondence\n  -> library bind_catalog\n  -> library bind_program (derived identity)\n  -> actual original envelope admission, private meter, complete decision and required laws\n  -> Accept | Reject | CommittedFailure | technical refusal\n  -> private Publication for committing outcomes\n  -> trusted host persistence and physical delivery\n```\n\n`GeneratedDeclarations` supplies untrusted original-field proposals. The catalog does not contain a complete business policy: callers must supply the full supported closed control graph, branches, footprints, required laws and genuine genesis declarations. Unsupported schema/profile combinations return named refusals and grant no publication capability.\n\n## Explicit nonclaims\n\n- The runtime skeleton is not a mounted runtime.\n- The migration stub authorizes no migration.\n- The evidence manifest contains no satisfied evidence.\n- Exact catalog reconstruction does not prove business-policy correctness.\n- Schema admission does not authenticate context provenance.\n- Generation is not a proof or production-readiness claim.\n\n## Deterministic output bounds\n\n- Files: at most {}.\n- Bytes per file: at most {}.\n- Aggregate bytes: at most {}.\n",
        spec.package_name(),
        BOOTSTRAP_GENERATOR_ID,
        catalog.profile().project().as_str(),
        catalog.profile().subsystem().as_str(),
        spec.limits().max_files(),
        spec.limits().max_file_bytes(),
        spec.limits().max_total_bytes()
    )
}

fn registry_kind_name(kind: RegistryKind) -> &'static str {
    match kind {
        RegistryKind::StateType => "state-type",
        RegistryKind::CommandType => "command-type",
        RegistryKind::ContextType => "context-type",
        RegistryKind::Reason => "reason",
        RegistryKind::Effect => "effect",
        RegistryKind::Channel => "channel",
        RegistryKind::Evidence => "evidence",
        RegistryKind::Capability => "capability",
        RegistryKind::Event => "event",
        RegistryKind::Claim => "claim",
        RegistryKind::Migration => "migration",
    }
}
