//! Inspectable project-starter templates derived from one reviewed catalog.

use std::fmt::Write as _;

use zeno_fcis_catalog::{HashRequirement, ProjectCatalog, ReasonDisposition};
use zeno_fcis_codec::Hash32;
use zeno_fcis_project::{ProfileBindings, RegistryKind};

use crate::{BOOTSTRAP_GENERATOR_ID, BootstrapError, BootstrapSpec};

pub(crate) fn render_rust_project(
    catalog: &ProjectCatalog,
    _spec: &BootstrapSpec,
    catalog_hash: Hash32,
    profile_hash: Hash32,
    schema_hash: Hash32,
) -> Result<String, BootstrapError> {
    let profile = catalog.profile();
    let root_type = schema_type_name(catalog, catalog.schema().root_type())?;
    let mut output = String::new();
    writeln!(
        output,
        "// Typed catalog bindings generated by `{BOOTSTRAP_GENERATOR_ID}`."
    )
    .map_err(|_| BootstrapError::Render)?;
    output.push_str(
        "//\n// The private generated project reconstructs the exact reviewed catalog.\n",
    );
    output.push_str("// Catalog validation and candidate sealing remain authoritative.\n\n");
    output.push_str("extern crate alloc;\n\n");
    output.push_str("use alloc::vec;\n");
    output.push_str("use core::fmt;\n");
    output.push_str("use zeno_fcis_catalog::{\n");
    output.push_str("    CatalogError, CatalogLimits, CatalogManifest, ChannelDefinition,\n");
    output.push_str("    EffectDefinition, HashRequirement, ProjectCatalog, ReasonDefinition,\n");
    output.push_str("    ReasonDisposition,\n");
    output.push_str("};\n");
    output.push_str("use zeno_fcis_codec::{CommitmentHasher, Domain, Hash32};\n");
    output.push_str("use zeno_fcis_core::BudgetUsed;\n");
    output.push_str("use zeno_fcis_plan::{Effect, OutboxEntry};\n");
    output.push_str("use zeno_fcis_project::{\n");
    output.push_str(
        "    DomainPrefix, ProfileBindings, ProfileError, ProjectProfile, RegistryEntry,\n",
    );
    output.push_str("    RegistryKind, SemanticId, StableName,\n");
    output.push_str("};\n");
    output.push_str("use zeno_fcis_schema::{\n");
    output.push_str(
        "    SchemaAdmittedEnvelope, SchemaEnvelopeError, SchemaError, TypeId, ValidationLimits,\n",
    );
    output.push_str("};\n");
    output.push_str("use zeno_fcis_transition::{CataloguedTransitionBuilder, TransitionError, TransitionLimits};\n");
    output.push('\n');
    writeln!(
        output,
        "pub const PROJECT: &str = {:?};",
        profile.project().as_str()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const SUBSYSTEM: &str = {:?};",
        profile.subsystem().as_str()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const PROFILE_ID: u32 = {};",
        profile.profile_id().get()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const PROFILE_VERSION: u32 = {};",
        profile.version()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const STATE_TYPE_ID: u32 = {};",
        profile.state_type().get()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const COMMAND_TYPE_ID: u32 = {};",
        profile.command_type().get()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const CONTEXT_TYPE_ID: u32 = {};",
        profile.context_type().get()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const DOMAIN_PREFIX: &str = {:?};\n",
        profile.domain_prefix().as_str()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const HASH_ALGORITHM_ID: &str = {:?};",
        catalog.manifest().hash_algorithm_id()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const CATALOG_HASH: Hash32 = {};",
        hash_expression(catalog_hash)
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const PROFILE_HASH: Hash32 = {};",
        hash_expression(profile_hash)
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const SCHEMA_HASH: Hash32 = {};\n",
        hash_expression(schema_hash)
    )
    .map_err(|_| BootstrapError::Render)?;

    output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n");
    output.push_str("pub enum ReasonClass { Reject, CommittedFailure }\n\n");
    render_reason_enum(&mut output, catalog)?;
    render_effect_enum(&mut output, catalog)?;
    render_channel_enum(&mut output, catalog)?;
    render_effect_helpers(&mut output, catalog)?;
    render_channel_helpers(&mut output, catalog)?;
    render_generated_project(&mut output, catalog, root_type)?;

    Ok(output)
}

fn render_reason_enum(output: &mut String, catalog: &ProjectCatalog) -> Result<(), BootstrapError> {
    output.push_str("/// Stable catalogued reason identifiers.\n");
    output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n#[repr(u32)]\n");
    output.push_str("pub enum ReasonId {\n");
    for reason in catalog.manifest().reasons() {
        writeln!(
            output,
            "    /// `{}` at precedence {}.\n    Reason{} = {},",
            reason.name().as_str(),
            reason.precedence(),
            reason.id().get(),
            reason.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("}\n\nimpl ReasonId {\n");
    output.push_str("    pub const fn get(self) -> u32 { self as u32 }\n");
    output.push_str("    pub fn try_semantic_id(self) -> Result<SemanticId, ProfileError> {\n");
    output.push_str("        SemanticId::try_new(self.get())\n    }\n");
    output.push_str("    pub const fn class(self) -> ReasonClass {\n        match self {\n");
    for reason in catalog.manifest().reasons() {
        let class = match reason.disposition() {
            ReasonDisposition::Reject => "ReasonClass::Reject",
            ReasonDisposition::CommittedFailure => "ReasonClass::CommittedFailure",
        };
        writeln!(
            output,
            "            Self::Reason{} => {class},",
            reason.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("        }\n    }\n}\n\n");
    Ok(())
}

fn render_effect_enum(output: &mut String, catalog: &ProjectCatalog) -> Result<(), BootstrapError> {
    output.push_str("/// Stable authoritative-effect identifiers.\n");
    output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n#[repr(u32)]\n");
    output.push_str("pub enum EffectKind {\n");
    for effect in catalog.manifest().effects() {
        writeln!(
            output,
            "    /// `{}`.\n    Effect{} = {},",
            effect.name().as_str(),
            effect.id().get(),
            effect.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("}\n\nimpl EffectKind {\n");
    output.push_str("    pub const fn get(self) -> u32 { self as u32 }\n}\n\n");
    Ok(())
}

fn render_channel_enum(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    output.push_str("/// Stable external-delivery channel identifiers.\n");
    output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n#[repr(u32)]\n");
    output.push_str("pub enum ChannelKind {\n");
    for channel in catalog.manifest().channels() {
        writeln!(
            output,
            "    /// `{}`.\n    Channel{} = {},",
            channel.name().as_str(),
            channel.id().get(),
            channel.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("}\n\nimpl ChannelKind {\n");
    output.push_str("    pub const fn get(self) -> u32 { self as u32 }\n}\n\n");
    Ok(())
}

fn render_effect_helpers(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    for effect in catalog.manifest().effects() {
        let payload = schema_type_name(catalog, effect.payload_type())?;
        writeln!(
            output,
            "/// Constructs catalog effect `{}`.\npub fn effect_{}(\n    ordinal: u32,\n    authority: Hash32,\n    subject: Hash32,\n    payload: &crate::generated::{payload},\n) -> Result<Effect, crate::generated::AdapterError> {{\n    Ok(Effect::new(\n        ordinal,\n        EffectKind::Effect{}.get(),\n        authority,\n        subject,\n        payload.to_value()?,\n    ))\n}}\n",
            effect.name().as_str(),
            effect.id().get(),
            effect.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    Ok(())
}

fn render_channel_helpers(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    for channel in catalog.manifest().channels() {
        let destination = schema_type_name(catalog, channel.destination_type())?;
        let payload = schema_type_name(catalog, channel.payload_type())?;
        writeln!(
            output,
            "/// Constructs catalog channel entry `{}`.\npub fn channel_{}(\n    ordinal: u32,\n    destination: &crate::generated::{destination},\n    payload: &crate::generated::{payload},\n) -> Result<OutboxEntry, crate::generated::AdapterError> {{\n    Ok(OutboxEntry::new(\n        ordinal,\n        ChannelKind::Channel{}.get(),\n        destination.to_value()?,\n        payload.to_value()?,\n    ))\n}}\n",
            channel.name().as_str(),
            channel.id().get(),
            channel.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    Ok(())
}

#[allow(clippy::too_many_lines)]
fn render_generated_project(
    output: &mut String,
    catalog: &ProjectCatalog,
    root_type: &str,
) -> Result<(), BootstrapError> {
    output.push_str("/// Local generated-binding construction or admission failure.\n");
    output.push_str("///\n");
    output.push_str("/// This diagnostic order is not application rejection precedence.\n");
    output.push_str("#[derive(Clone, Debug, Eq, PartialEq)]\n");
    output.push_str("pub enum GeneratedProjectError {\n");
    output.push_str("    HashAlgorithmMismatch,\n");
    output.push_str("    SchemaHashMismatch { expected: Hash32, actual: Hash32 },\n");
    output.push_str("    ProfileHashMismatch { expected: Hash32, actual: Hash32 },\n");
    output.push_str("    CatalogHashMismatch { expected: Hash32, actual: Hash32 },\n");
    output.push_str("    RootTypeMismatch { expected: u32, actual: u32 },\n");
    output.push_str("    Catalog(CatalogError),\n");
    output.push_str("    Adapter(crate::generated::AdapterError),\n");
    output.push_str("    Envelope(SchemaEnvelopeError),\n");
    output.push_str("    Profile(ProfileError),\n");
    output.push_str("    Schema(SchemaError),\n");
    output.push_str("    Transition(TransitionError),\n");
    output.push_str("}\n\n");
    output.push_str("impl From<CatalogError> for GeneratedProjectError {\n");
    output.push_str("    fn from(error: CatalogError) -> Self { Self::Catalog(error) }\n");
    output.push_str("}\n\n");
    output.push_str("impl From<crate::generated::AdapterError> for GeneratedProjectError {\n");
    output.push_str(
        "    fn from(error: crate::generated::AdapterError) -> Self { Self::Adapter(error) }\n",
    );
    output.push_str("}\n\n");
    output.push_str("impl From<SchemaEnvelopeError> for GeneratedProjectError {\n");
    output.push_str("    fn from(error: SchemaEnvelopeError) -> Self { Self::Envelope(error) }\n");
    output.push_str("}\n\n");
    output.push_str("impl From<ProfileError> for GeneratedProjectError {\n");
    output.push_str("    fn from(error: ProfileError) -> Self { Self::Profile(error) }\n");
    output.push_str("}\n\n");
    output.push_str("impl From<SchemaError> for GeneratedProjectError {\n");
    output.push_str("    fn from(error: SchemaError) -> Self { Self::Schema(error) }\n");
    output.push_str("}\n\n");
    output.push_str("impl From<TransitionError> for GeneratedProjectError {\n");
    output.push_str("    fn from(error: TransitionError) -> Self { Self::Transition(error) }\n");
    output.push_str("}\n\n");
    output.push_str("impl fmt::Display for GeneratedProjectError {\n");
    output.push_str("    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {\n");
    output.push_str("        match self {\n");
    output.push_str("            Self::HashAlgorithmMismatch => formatter.write_str(\"generated project hash algorithm mismatch\"),\n");
    output.push_str("            Self::SchemaHashMismatch { expected, actual } => write!(formatter, \"generated project schema hash mismatch: expected {expected}, actual {actual}\"),\n");
    output.push_str("            Self::ProfileHashMismatch { expected, actual } => write!(formatter, \"generated project profile hash mismatch: expected {expected}, actual {actual}\"),\n");
    output.push_str("            Self::CatalogHashMismatch { expected, actual } => write!(formatter, \"generated project catalog hash mismatch: expected {expected}, actual {actual}\"),\n");
    output.push_str("            Self::RootTypeMismatch { expected, actual } => write!(formatter, \"generated project root type mismatch: expected {expected}, actual {actual}\"),\n");
    output.push_str("            Self::Catalog(error) => write!(formatter, \"generated catalog rejected: {error}\"),\n");
    output.push_str("            Self::Adapter(error) => write!(formatter, \"generated root adapter rejected: {error:?}\"),\n");
    output.push_str("            Self::Envelope(error) => write!(formatter, \"generated root envelope rejected: {error}\"),\n");
    output.push_str("            Self::Profile(error) => write!(formatter, \"generated profile rejected: {error}\"),\n");
    output.push_str("            Self::Schema(error) => write!(formatter, \"generated schema rejected: {error}\"),\n");
    output.push_str("            Self::Transition(error) => write!(formatter, \"generated transition rejected: {error}\"),\n");
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str("/// Exact generated project bindings with no caller-supplied catalog.\n");
    output.push_str("#[derive(Clone, Debug, Eq, PartialEq)]\n");
    output.push_str("pub struct GeneratedProject { catalog: ProjectCatalog }\n\n");
    output.push_str("impl GeneratedProject {\n");
    output.push_str("    /// Reconstructs and revalidates the exact generation-time catalog.\n");
    output.push_str(
        "    pub fn try_new<H: CommitmentHasher>() -> Result<Self, GeneratedProjectError> {\n",
    );
    output.push_str("        if H::ALGORITHM_ID != HASH_ALGORITHM_ID {\n");
    output.push_str("            return Err(GeneratedProjectError::HashAlgorithmMismatch);\n");
    output.push_str("        }\n");
    writeln!(
        output,
        "        let schema = crate::generated::{root_type}::zfcis_schema()?;"
    )
    .map_err(|_| BootstrapError::Render)?;
    output.push_str("        let actual_schema_hash = schema.schema_hash::<H>()?;\n");
    output.push_str("        if actual_schema_hash != SCHEMA_HASH {\n");
    output.push_str("            return Err(GeneratedProjectError::SchemaHashMismatch { expected: SCHEMA_HASH, actual: actual_schema_hash });\n");
    output.push_str("        }\n");
    render_catalog_manifest_construction(output, catalog)?;
    render_profile_construction(output, catalog)?;
    let limits = catalog.limits();
    writeln!(
        output,
        "        let limits = CatalogLimits::try_new({}, {}, {}, {}, {}, {}, {})?;",
        limits.max_effects(),
        limits.max_outbox_entries(),
        limits.max_value_depth(),
        limits.max_value_nodes(),
        limits.max_total_value_nodes(),
        limits.max_total_payload_bytes(),
        limits.max_collection_len()
    )
    .map_err(|_| BootstrapError::Render)?;
    output.push_str(
        "        let catalog = ProjectCatalog::try_new::<H>(profile, schema, manifest, limits)?;\n",
    );
    output.push_str("        let project = Self { catalog };\n");
    output.push_str("        project.validate_catalog::<H>()?;\n");
    output.push_str("        Ok(project)\n");
    output.push_str("    }\n\n");
    output.push_str("    /// Returns the reconstructed exact catalog.\n");
    output.push_str("    pub const fn catalog(&self) -> &ProjectCatalog { &self.catalog }\n\n");
    output.push_str("    /// Admits the typed root under the exact catalog provider and schema.\n");
    output.push_str("    pub fn admit_root<H: CommitmentHasher>(\n");
    output.push_str("        &self,\n");
    writeln!(output, "        root: &crate::generated::{root_type},")
        .map_err(|_| BootstrapError::Render)?;
    output.push_str("        limits: ValidationLimits,\n");
    output.push_str("    ) -> Result<SchemaAdmittedEnvelope, GeneratedProjectError> {\n");
    output.push_str("        self.validate_catalog::<H>()?;\n");
    output.push_str("        let value = root.to_value()?;\n");
    output.push_str(
        "        Ok(SchemaAdmittedEnvelope::try_new::<H>(self.catalog.schema(), value, limits)?)\n",
    );
    output.push_str("    }\n\n");
    output.push_str("    /// Starts a catalog-aware transition from one schema-admitted root.\n");
    output.push_str("    pub fn begin_transition<'a, H: CommitmentHasher>(\n");
    output.push_str("        &'a self,\n");
    output.push_str("        pre_state: &'a SchemaAdmittedEnvelope,\n");
    output.push_str("        state_domain: Domain<'a>,\n");
    output.push_str("        command_hash: Hash32,\n");
    output.push_str("        context_hash: Hash32,\n");
    output.push_str("        budget_used: BudgetUsed,\n");
    output.push_str("        limits: TransitionLimits,\n");
    output
        .push_str("    ) -> Result<CataloguedTransitionBuilder<'a, H>, GeneratedProjectError> {\n");
    output.push_str("        self.validate_catalog::<H>()?;\n");
    output.push_str("        if pre_state.schema_hash() != SCHEMA_HASH {\n");
    output.push_str("            return Err(GeneratedProjectError::SchemaHashMismatch { expected: SCHEMA_HASH, actual: pre_state.schema_hash() });\n");
    output.push_str("        }\n");
    output.push_str("        if pre_state.root_type() != TypeId::new(STATE_TYPE_ID) {\n");
    output.push_str("            return Err(GeneratedProjectError::RootTypeMismatch { expected: STATE_TYPE_ID, actual: pre_state.root_type().get() });\n");
    output.push_str("        }\n");
    output.push_str("        Ok(CataloguedTransitionBuilder::try_new(\n");
    output.push_str(
        "            &self.catalog, pre_state.value().value(), state_domain, command_hash,\n",
    );
    output.push_str("            context_hash, budget_used, limits,\n");
    output.push_str("        )?)\n");
    output.push_str("    }\n\n");
    output.push_str("    fn validate_catalog<H: CommitmentHasher>(&self) -> Result<(), GeneratedProjectError> {\n");
    output.push_str("        if H::ALGORITHM_ID != HASH_ALGORITHM_ID {\n");
    output.push_str("            return Err(GeneratedProjectError::HashAlgorithmMismatch);\n");
    output.push_str("        }\n");
    output.push_str("        let actual_schema_hash = self.catalog.schema_hash();\n");
    output.push_str("        if actual_schema_hash != SCHEMA_HASH {\n");
    output.push_str("            return Err(GeneratedProjectError::SchemaHashMismatch { expected: SCHEMA_HASH, actual: actual_schema_hash });\n");
    output.push_str("        }\n");
    output.push_str("        let actual_profile_hash = self.catalog.profile_hash();\n");
    output.push_str("        if actual_profile_hash != PROFILE_HASH {\n");
    output.push_str("            return Err(GeneratedProjectError::ProfileHashMismatch { expected: PROFILE_HASH, actual: actual_profile_hash });\n");
    output.push_str("        }\n");
    output.push_str("        let actual_catalog_hash = self.catalog.commitment::<H>()?;\n");
    output.push_str("        if actual_catalog_hash != CATALOG_HASH {\n");
    output.push_str("            return Err(GeneratedProjectError::CatalogHashMismatch { expected: CATALOG_HASH, actual: actual_catalog_hash });\n");
    output.push_str("        }\n");
    output.push_str("        Ok(())\n");
    output.push_str("    }\n");
    output.push_str("}\n");

    Ok(())
}

fn render_catalog_manifest_construction(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    output.push_str("        let reasons = vec![\n");
    for reason in catalog.manifest().reasons() {
        let disposition = match reason.disposition() {
            ReasonDisposition::Reject => "ReasonDisposition::Reject",
            ReasonDisposition::CommittedFailure => "ReasonDisposition::CommittedFailure",
        };
        writeln!(
            output,
            "            ReasonDefinition::try_new(SemanticId::try_new({})?, StableName::try_new({:?})?, {disposition}, {}, {})?,",
            reason.id().get(),
            reason.name().as_str(),
            reason.precedence(),
            hash_expression(reason.predicate_hash())
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("        ];\n");
    output.push_str("        let effects = vec![\n");
    for effect in catalog.manifest().effects() {
        writeln!(
            output,
            "            EffectDefinition::try_new(SemanticId::try_new({})?, StableName::try_new({:?})?, TypeId::new({}), {}, {}, {})?,",
            effect.id().get(),
            effect.name().as_str(),
            effect.payload_type().get(),
            hash_requirement_expression(effect.authority_requirement()),
            hash_requirement_expression(effect.subject_requirement()),
            hash_expression(effect.policy_hash())
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("        ];\n");
    output.push_str("        let channels = vec![\n");
    for channel in catalog.manifest().channels() {
        writeln!(
            output,
            "            ChannelDefinition::try_new(SemanticId::try_new({})?, StableName::try_new({:?})?, TypeId::new({}), TypeId::new({}), {})?,",
            channel.id().get(),
            channel.name().as_str(),
            channel.destination_type().get(),
            channel.payload_type().get(),
            hash_expression(channel.delivery_policy_hash())
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("        ];\n");
    output.push_str(
        "        let manifest = CatalogManifest::try_new::<H>(reasons, effects, channels)?;\n",
    );
    Ok(())
}

fn render_profile_construction(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    let profile = catalog.profile();
    let bindings = profile.bindings();
    output.push_str("        let entries = vec![\n");
    for entry in profile.entries() {
        writeln!(
            output,
            "            RegistryEntry::try_new({}, SemanticId::try_new({})?, StableName::try_new({:?})?, {})?,",
            registry_kind_expression(entry.kind()),
            entry.id().get(),
            entry.name().as_str(),
            hash_expression(entry.definition_hash())
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("        ];\n");
    writeln!(
        output,
        "        let profile = ProjectProfile::try_new(StableName::try_new({:?})?, StableName::try_new({:?})?, SemanticId::try_new({})?, {}, SemanticId::try_new({})?, SemanticId::try_new({})?, SemanticId::try_new({})?, DomainPrefix::try_new({:?})?,",
        profile.project().as_str(),
        profile.subsystem().as_str(),
        profile.profile_id().get(),
        profile.version(),
        profile.state_type().get(),
        profile.command_type().get(),
        profile.context_type().get(),
        profile.domain_prefix().as_str()
    )
    .map_err(|_| BootstrapError::Render)?;
    render_profile_bindings(output, bindings)?;
    output.push_str("            entries,\n");
    output.push_str("        )?;\n");
    Ok(())
}

fn render_profile_bindings(
    output: &mut String,
    bindings: ProfileBindings,
) -> Result<(), BootstrapError> {
    output.push_str("            ProfileBindings {\n");
    for (field, hash) in [
        ("schema_hash", bindings.schema_hash),
        ("precedence_hash", bindings.precedence_hash),
        ("algorithm_hash", bindings.algorithm_hash),
        ("codec_hash", bindings.codec_hash),
        ("effect_registry_hash", bindings.effect_registry_hash),
        ("channel_registry_hash", bindings.channel_registry_hash),
        ("policy_hash", bindings.policy_hash),
    ] {
        writeln!(
            output,
            "                {field}: {},",
            hash_expression(hash)
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("            },\n");
    Ok(())
}

fn hash_expression(hash: Hash32) -> String {
    format!("Hash32::new({:?})", hash.as_bytes())
}

fn hash_requirement_expression(requirement: HashRequirement) -> String {
    match requirement {
        HashRequirement::Any => "HashRequirement::Any".to_owned(),
        HashRequirement::Absent => "HashRequirement::Absent".to_owned(),
        HashRequirement::Present => "HashRequirement::Present".to_owned(),
        HashRequirement::Exact(expected) => {
            format!(
                "HashRequirement::exact({})?",
                hash_expression(expected.get())
            )
        }
    }
}

fn registry_kind_expression(kind: RegistryKind) -> &'static str {
    match kind {
        RegistryKind::StateType => "RegistryKind::StateType",
        RegistryKind::CommandType => "RegistryKind::CommandType",
        RegistryKind::ContextType => "RegistryKind::ContextType",
        RegistryKind::Reason => "RegistryKind::Reason",
        RegistryKind::Effect => "RegistryKind::Effect",
        RegistryKind::Channel => "RegistryKind::Channel",
        RegistryKind::Evidence => "RegistryKind::Evidence",
        RegistryKind::Capability => "RegistryKind::Capability",
        RegistryKind::Event => "RegistryKind::Event",
        RegistryKind::Claim => "RegistryKind::Claim",
        RegistryKind::Migration => "RegistryKind::Migration",
    }
}

fn schema_type_name(
    catalog: &ProjectCatalog,
    id: zeno_fcis_schema::TypeId,
) -> Result<&str, BootstrapError> {
    catalog
        .schema()
        .type_by_id(id)
        .map(|definition| definition.name().as_str())
        .ok_or(BootstrapError::UnknownSchemaType(id))
}

pub(crate) fn render_registry(catalog: &ProjectCatalog) -> Result<String, BootstrapError> {
    let mut output = String::from("kind\tid\tname\tdefinition_hash\n");
    for entry in catalog.profile().entries() {
        writeln!(
            output,
            "{}\t{}\t{}\t{}",
            registry_kind_name(entry.kind()),
            entry.id().get(),
            entry.name().as_str(),
            entry.definition_hash()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    Ok(output)
}

pub(crate) fn render_rust_runtime(spec: &BootstrapSpec) -> String {
    format!(
        "// Mounted-runtime adapter skeleton for `{}`.\n//\n// No runtime is mounted by generation. Implement\n// `zeno_fcis_adapter::CallableRuntime` or\n// `zeno_fcis_adapter::JsonLineRuntime`, then require complete normalized-\n// decision parity.\n\n// Intentionally no implementation: runtime authority requires project review.\n",
        spec.package_name()
    )
}

pub(crate) fn render_python_runtime(spec: &BootstrapSpec) -> String {
    format!(
        "\"\"\"Mounted-runtime protocol skeleton for {}.\n\nGeneration does not claim runtime refinement.\n\"\"\"\n\nfrom typing import Protocol\n\n\nclass MountedRuntime(Protocol):\n    def evaluate(self, request_line: str) -> str:\n        \"\"\"Return one strict complete normalized-decision JSON line.\"\"\"\n        ...\n",
        spec.package_name()
    )
}

pub(crate) fn render_migration(catalog: &ProjectCatalog) -> String {
    format!(
        "format = zeno-fcis-migration-stub/1\nproject = {}\nsubsystem = {}\nfrom_profile_version = {}\nstatus = not-specified\nmigration_hash = absent\nactivation = absent\nrollback = absent\nclaim = no-migration-authority\n",
        catalog.profile().project().as_str(),
        catalog.profile().subsystem().as_str(),
        catalog.profile().version()
    )
}

pub(crate) fn render_evidence(catalog: &ProjectCatalog) -> String {
    format!(
        "format = zeno-fcis-evidence-requirements/1\nproject = {}\nsubsystem = {}\ncodec_vectors = required-not-provided\nruntime_refinement = required-not-provided\nproof_checker = required-not-provided\ncounterexamples = required-not-provided\ntoolchain_identity = required-not-provided\npromotion_status = denied\n",
        catalog.profile().project().as_str(),
        catalog.profile().subsystem().as_str()
    )
}

pub(crate) fn render_ci(spec: &BootstrapSpec) -> String {
    format!(
        "name: generated-project-ci\n\non:\n  pull_request:\n  push:\n    branches: [main]\n\npermissions:\n  contents: read\n\nconcurrency:\n  group: generated-project-ci-${{{{ github.ref }}}}\n  cancel-in-progress: true\n\njobs:\n  rust:\n    runs-on: ubuntu-24.04\n    timeout-minutes: 30\n    steps:\n      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10\n        with:\n          persist-credentials: false\n      - run: rustup toolchain install 1.97.1 --profile minimal\n      - run: cargo +1.97.1 fmt --all -- --check\n      - run: cargo +1.97.1 clippy --workspace --all-targets --all-features --locked -- -D warnings\n      - run: cargo +1.97.1 test --workspace --all-features --locked\n      - run: cargo +1.97.1 test --workspace --doc --all-features --locked\n      - run: RUSTDOCFLAGS='-D warnings' cargo +1.97.1 doc --workspace --all-features --locked --no-deps\n# Package identity: {}\n",
        spec.package_name()
    )
}

pub(crate) fn render_architecture(catalog: &ProjectCatalog, spec: &BootstrapSpec) -> String {
    format!(
        "# {} bootstrap architecture\n\nGenerated by `{}` from the reviewed `{}/{}` catalog.\n\n## Authority boundary\n\nThe schema, profile, catalog, stable identifiers, policies, and resource limits are inputs. This package only renders them into inspectable starter artifacts. Runtime execution, migration activation, evidence acceptance, proof claims, promotion, and release remain outside generator authority.\n\nThe generated private-field `GeneratedProject` reconstructs the exact catalog and rechecks its schema, profile, complete catalog, and provider commitments. Its transition entry point accepts the exact schema-admitted root envelope rather than a raw value or caller-supplied catalog.\n\n## Pure transition path\n\n```text\nexact generated catalog + schema-admitted root + command/context commitments\n  -> typed helpers\n  -> CataloguedTransitionBuilder\n  -> catalog validation\n  -> Accept | Reject | CommittedFailure\n  -> candidate-bound CommitBundle\n```\n\n## Explicit nonclaims\n\n- The runtime skeleton is not a mounted runtime.\n- The migration stub authorizes no migration.\n- The evidence manifest contains no satisfied evidence.\n- Exact catalog reconstruction does not prove business-policy correctness.\n- Generation is not a proof or production-readiness claim.\n\n## Deterministic output bounds\n\n- Files: at most {}.\n- Bytes per file: at most {}.\n- Aggregate bytes: at most {}.\n",
        spec.package_name(),
        BOOTSTRAP_GENERATOR_ID,
        catalog.profile().project().as_str(),
        catalog.profile().subsystem().as_str(),
        spec.limits().max_files(),
        spec.limits().max_file_bytes(),
        spec.limits().max_total_bytes()
    )
}

fn registry_kind_name(kind: RegistryKind) -> &'static str {
    match kind {
        RegistryKind::StateType => "state-type",
        RegistryKind::CommandType => "command-type",
        RegistryKind::ContextType => "context-type",
        RegistryKind::Reason => "reason",
        RegistryKind::Effect => "effect",
        RegistryKind::Channel => "channel",
        RegistryKind::Evidence => "evidence",
        RegistryKind::Capability => "capability",
        RegistryKind::Event => "event",
        RegistryKind::Claim => "claim",
        RegistryKind::Migration => "migration",
    }
}
