//! Inspectable project-starter templates derived from one reviewed catalog.

use std::fmt::Write as _;

use zeno_fcis_catalog::{ProjectCatalog, ReasonDisposition};
use zeno_fcis_project::RegistryKind;

use crate::{BOOTSTRAP_GENERATOR_ID, BootstrapError, BootstrapSpec};

pub(crate) fn render_rust_project(
    catalog: &ProjectCatalog,
    _spec: &BootstrapSpec,
) -> Result<String, BootstrapError> {
    let profile = catalog.profile();
    let mut output = String::new();
    writeln!(
        output,
        "// Typed catalog bindings generated by `{BOOTSTRAP_GENERATOR_ID}`."
    )
    .map_err(|_| BootstrapError::Render)?;
    output.push_str("//\n// These helpers construct closed plan values. Catalog validation and\n");
    output.push_str("// candidate sealing remain authoritative.\n\n");
    output.push_str("use zeno_fcis_catalog::ProjectCatalog;\n");
    output.push_str("use zeno_fcis_codec::{CommitmentHasher, Domain, Hash32};\n");
    output.push_str("use zeno_fcis_core::BudgetUsed;\n");
    output.push_str("use zeno_fcis_plan::{Effect, OutboxEntry};\n");
    output.push_str("use zeno_fcis_project::{ProfileError, SemanticId};\n");
    output.push_str("use zeno_fcis_transition::{CataloguedTransitionBuilder, TransitionError, TransitionLimits};\n");
    output.push_str("use zeno_fcis_value::Value;\n\n");
    writeln!(
        output,
        "pub const PROJECT: &str = {:?};",
        profile.project().as_str()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const SUBSYSTEM: &str = {:?};",
        profile.subsystem().as_str()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const PROFILE_ID: u32 = {};",
        profile.profile_id().get()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const PROFILE_VERSION: u32 = {};",
        profile.version()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const STATE_TYPE_ID: u32 = {};",
        profile.state_type().get()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const COMMAND_TYPE_ID: u32 = {};",
        profile.command_type().get()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const CONTEXT_TYPE_ID: u32 = {};",
        profile.context_type().get()
    )
    .map_err(|_| BootstrapError::Render)?;
    writeln!(
        output,
        "pub const DOMAIN_PREFIX: &str = {:?};\n",
        profile.domain_prefix().as_str()
    )
    .map_err(|_| BootstrapError::Render)?;

    output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n");
    output.push_str("pub enum ReasonClass { Reject, CommittedFailure }\n\n");
    render_reason_enum(&mut output, catalog)?;
    render_effect_enum(&mut output, catalog)?;
    render_channel_enum(&mut output, catalog)?;
    render_effect_helpers(&mut output, catalog)?;
    render_channel_helpers(&mut output, catalog)?;

    output.push_str("/// Starts one catalog-aware pure transition.\n");
    output.push_str("pub fn begin_transition<'a, H: CommitmentHasher>(\n");
    output.push_str("    catalog: &'a ProjectCatalog,\n");
    output.push_str("    pre_state: &'a Value,\n");
    output.push_str("    state_domain: Domain<'a>,\n");
    output.push_str("    command_hash: Hash32,\n");
    output.push_str("    context_hash: Hash32,\n");
    output.push_str("    budget_used: BudgetUsed,\n");
    output.push_str("    limits: TransitionLimits,\n");
    output.push_str(") -> Result<CataloguedTransitionBuilder<'a, H>, TransitionError> {\n");
    output.push_str("    CataloguedTransitionBuilder::try_new(\n");
    output.push_str("        catalog, pre_state, state_domain, command_hash, context_hash, budget_used, limits,\n");
    output.push_str("    )\n}\n");

    Ok(output)
}

fn render_reason_enum(output: &mut String, catalog: &ProjectCatalog) -> Result<(), BootstrapError> {
    output.push_str("/// Stable catalogued reason identifiers.\n");
    output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n#[repr(u32)]\n");
    output.push_str("pub enum ReasonId {\n");
    for reason in catalog.manifest().reasons() {
        writeln!(
            output,
            "    /// `{}` at precedence {}.\n    Reason{} = {},",
            reason.name().as_str(),
            reason.precedence(),
            reason.id().get(),
            reason.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("}\n\nimpl ReasonId {\n");
    output.push_str("    pub const fn get(self) -> u32 { self as u32 }\n");
    output.push_str("    pub fn try_semantic_id(self) -> Result<SemanticId, ProfileError> {\n");
    output.push_str("        SemanticId::try_new(self.get())\n    }\n");
    output.push_str("    pub const fn class(self) -> ReasonClass {\n        match self {\n");
    for reason in catalog.manifest().reasons() {
        let class = match reason.disposition() {
            ReasonDisposition::Reject => "ReasonClass::Reject",
            ReasonDisposition::CommittedFailure => "ReasonClass::CommittedFailure",
        };
        writeln!(
            output,
            "            Self::Reason{} => {class},",
            reason.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("        }\n    }\n}\n\n");
    Ok(())
}

fn render_effect_enum(output: &mut String, catalog: &ProjectCatalog) -> Result<(), BootstrapError> {
    output.push_str("/// Stable authoritative-effect identifiers.\n");
    output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n#[repr(u32)]\n");
    output.push_str("pub enum EffectKind {\n");
    for effect in catalog.manifest().effects() {
        writeln!(
            output,
            "    /// `{}`.\n    Effect{} = {},",
            effect.name().as_str(),
            effect.id().get(),
            effect.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("}\n\nimpl EffectKind {\n");
    output.push_str("    pub const fn get(self) -> u32 { self as u32 }\n}\n\n");
    Ok(())
}

fn render_channel_enum(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    output.push_str("/// Stable external-delivery channel identifiers.\n");
    output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n#[repr(u32)]\n");
    output.push_str("pub enum ChannelKind {\n");
    for channel in catalog.manifest().channels() {
        writeln!(
            output,
            "    /// `{}`.\n    Channel{} = {},",
            channel.name().as_str(),
            channel.id().get(),
            channel.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    output.push_str("}\n\nimpl ChannelKind {\n");
    output.push_str("    pub const fn get(self) -> u32 { self as u32 }\n}\n\n");
    Ok(())
}

fn render_effect_helpers(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    for effect in catalog.manifest().effects() {
        let payload = schema_type_name(catalog, effect.payload_type())?;
        writeln!(
            output,
            "/// Constructs catalog effect `{}`.\npub fn effect_{}(\n    ordinal: u32,\n    authority: Hash32,\n    subject: Hash32,\n    payload: &crate::generated::{payload},\n) -> Result<Effect, crate::generated::AdapterError> {{\n    Ok(Effect::new(\n        ordinal,\n        EffectKind::Effect{}.get(),\n        authority,\n        subject,\n        payload.to_value()?,\n    ))\n}}\n",
            effect.name().as_str(),
            effect.id().get(),
            effect.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    Ok(())
}

fn render_channel_helpers(
    output: &mut String,
    catalog: &ProjectCatalog,
) -> Result<(), BootstrapError> {
    for channel in catalog.manifest().channels() {
        let destination = schema_type_name(catalog, channel.destination_type())?;
        let payload = schema_type_name(catalog, channel.payload_type())?;
        writeln!(
            output,
            "/// Constructs catalog channel entry `{}`.\npub fn channel_{}(\n    ordinal: u32,\n    destination: &crate::generated::{destination},\n    payload: &crate::generated::{payload},\n) -> Result<OutboxEntry, crate::generated::AdapterError> {{\n    Ok(OutboxEntry::new(\n        ordinal,\n        ChannelKind::Channel{}.get(),\n        destination.to_value()?,\n        payload.to_value()?,\n    ))\n}}\n",
            channel.name().as_str(),
            channel.id().get(),
            channel.id().get()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    Ok(())
}

fn schema_type_name(
    catalog: &ProjectCatalog,
    id: zeno_fcis_schema::TypeId,
) -> Result<&str, BootstrapError> {
    catalog
        .schema()
        .type_by_id(id)
        .map(|definition| definition.name().as_str())
        .ok_or(BootstrapError::UnknownSchemaType(id))
}

pub(crate) fn render_registry(catalog: &ProjectCatalog) -> Result<String, BootstrapError> {
    let mut output = String::from("kind\tid\tname\tdefinition_hash\n");
    for entry in catalog.profile().entries() {
        writeln!(
            output,
            "{}\t{}\t{}\t{}",
            registry_kind_name(entry.kind()),
            entry.id().get(),
            entry.name().as_str(),
            entry.definition_hash()
        )
        .map_err(|_| BootstrapError::Render)?;
    }
    Ok(output)
}

pub(crate) fn render_rust_runtime(spec: &BootstrapSpec) -> String {
    format!(
        "// Mounted-runtime adapter skeleton for `{}`.\n//\n// No runtime is mounted by generation. Implement\n// `zeno_fcis_adapter::CallableRuntime` or\n// `zeno_fcis_adapter::JsonLineRuntime`, then require complete normalized-\n// decision parity.\n\n// Intentionally no implementation: runtime authority requires project review.\n",
        spec.package_name()
    )
}

pub(crate) fn render_python_runtime(spec: &BootstrapSpec) -> String {
    format!(
        "\"\"\"Mounted-runtime protocol skeleton for {}.\n\nGeneration does not claim runtime refinement.\n\"\"\"\n\nfrom typing import Protocol\n\n\nclass MountedRuntime(Protocol):\n    def evaluate(self, request_line: str) -> str:\n        \"\"\"Return one strict complete normalized-decision JSON line.\"\"\"\n        ...\n",
        spec.package_name()
    )
}

pub(crate) fn render_migration(catalog: &ProjectCatalog) -> String {
    format!(
        "format = zeno-fcis-migration-stub/1\nproject = {}\nsubsystem = {}\nfrom_profile_version = {}\nstatus = not-specified\nmigration_hash = absent\nactivation = absent\nrollback = absent\nclaim = no-migration-authority\n",
        catalog.profile().project().as_str(),
        catalog.profile().subsystem().as_str(),
        catalog.profile().version()
    )
}

pub(crate) fn render_evidence(catalog: &ProjectCatalog) -> String {
    format!(
        "format = zeno-fcis-evidence-requirements/1\nproject = {}\nsubsystem = {}\ncodec_vectors = required-not-provided\nruntime_refinement = required-not-provided\nproof_checker = required-not-provided\ncounterexamples = required-not-provided\ntoolchain_identity = required-not-provided\npromotion_status = denied\n",
        catalog.profile().project().as_str(),
        catalog.profile().subsystem().as_str()
    )
}

pub(crate) fn render_ci(spec: &BootstrapSpec) -> String {
    format!(
        "name: generated-project-ci\n\non:\n  pull_request:\n  push:\n    branches: [main]\n\npermissions:\n  contents: read\n\nconcurrency:\n  group: generated-project-ci-${{{{ github.ref }}}}\n  cancel-in-progress: true\n\njobs:\n  rust:\n    runs-on: ubuntu-24.04\n    timeout-minutes: 30\n    steps:\n      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10\n        with:\n          persist-credentials: false\n      - run: rustup toolchain install 1.97.1 --profile minimal\n      - run: cargo +1.97.1 fmt --all -- --check\n      - run: cargo +1.97.1 clippy --workspace --all-targets --all-features --locked -- -D warnings\n      - run: cargo +1.97.1 test --workspace --all-features --locked\n      - run: cargo +1.97.1 test --workspace --doc --all-features --locked\n      - run: RUSTDOCFLAGS='-D warnings' cargo +1.97.1 doc --workspace --all-features --locked --no-deps\n# Package identity: {}\n",
        spec.package_name()
    )
}

pub(crate) fn render_architecture(catalog: &ProjectCatalog, spec: &BootstrapSpec) -> String {
    format!(
        "# {} bootstrap architecture\n\nGenerated by `{}` from the reviewed `{}/{}` catalog.\n\n## Authority boundary\n\nThe schema, profile, catalog, stable identifiers, policies, and resource limits are inputs. This package only renders them into inspectable starter artifacts. Runtime execution, migration activation, evidence acceptance, proof claims, promotion, and release remain outside generator authority.\n\n## Pure transition path\n\n```text\nimmutable state + command/context commitments\n  -> typed helpers\n  -> CataloguedTransitionBuilder\n  -> catalog validation\n  -> Accept | Reject | CommittedFailure\n  -> candidate-bound CommitBundle\n```\n\n## Explicit nonclaims\n\n- The runtime skeleton is not a mounted runtime.\n- The migration stub authorizes no migration.\n- The evidence manifest contains no satisfied evidence.\n- Generated typed helpers do not replace catalog validation.\n- Generation is not a proof or production-readiness claim.\n\n## Deterministic output bounds\n\n- Files: at most {}.\n- Bytes per file: at most {}.\n- Aggregate bytes: at most {}.\n",
        spec.package_name(),
        BOOTSTRAP_GENERATOR_ID,
        catalog.profile().project().as_str(),
        catalog.profile().subsystem().as_str(),
        spec.limits().max_files(),
        spec.limits().max_file_bytes(),
        spec.limits().max_total_bytes()
    )
}

fn registry_kind_name(kind: RegistryKind) -> &'static str {
    match kind {
        RegistryKind::StateType => "state-type",
        RegistryKind::CommandType => "command-type",
        RegistryKind::ContextType => "context-type",
        RegistryKind::Reason => "reason",
        RegistryKind::Effect => "effect",
        RegistryKind::Channel => "channel",
        RegistryKind::Evidence => "evidence",
        RegistryKind::Capability => "capability",
        RegistryKind::Event => "event",
        RegistryKind::Claim => "claim",
        RegistryKind::Migration => "migration",
    }
}
