#!/usr/bin/env python3
"""Validate and assemble the deterministic ZenoFCIS release-candidate set."""

from __future__ import annotations

import argparse
import copy
import gzip
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import uuid
import zipfile
from pathlib import Path, PurePosixPath
from urllib.parse import quote

import tomllib

import check_generated_application as generated_application

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_SET_PATH = ROOT / "release" / "package-set.toml"
LOCK_PATH = ROOT / "Cargo.lock"
NPM_PACKAGE_PATH = ROOT / "package.json"
NPM_LOCK_PATH = ROOT / "package-lock.json"
PROBITY_CONFIG_PATH = ROOT / "probity.config.ts"
NODE_VERSION_PATH = ROOT / ".node-version"
EXPECTED_NODE_VERSION = "22.23.1"
EXPECTED_PROBITY_VERSION = "1.10.0"
EXPECTED_PROBITY_INTEGRITY = (
    "sha512-tb2eOaE/lugOLm0DzRbW+x4FOQDxDJJldkRiMbybiluCX4AKIMqN6CZ9LQ20K5Y"
    "EBUePD8+S4/kRiqh8K/B0oA=="
)
EXPECTED_NPM_LOCK_CANONICAL_SHA256 = (
    "7de4680ba8603eb93ec3fb08a5b9b0528577b6a44158561058710439185a2518"
)
FIXED_ZIP_TIME = (1980, 1, 1, 0, 0, 0)
RUSTDOC_ARCHIVE_NOTICE = """ZenoFCIS offline rustdoc archive

This archive retains all public crate API and source pages generated by pinned
Rustdoc 1.97.1. The tool's merged cross-crate search.index is intentionally
excluded because independent clean builds do not produce byte-identical search
shards. The generated help.html and settings.html pages are normalized to the
zeno_fcis umbrella crate because Rustdoc otherwise records whichever crate
finishes last.

Use docs.rs or regenerate documentation locally when global search is needed.
This boundary concerns archive reproducibility only; it is not an API or
semantic assurance claim.
"""


class RcError(ValueError):
    """A fail-closed release-candidate validation error."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    subcommands = parser.add_subparsers(dest="command", required=True)
    subcommands.add_parser("check")
    subcommands.add_parser("self-test")
    build = subcommands.add_parser("build")
    build.add_argument("--output", type=Path, required=True)
    verify = subcommands.add_parser("verify-packaged", help="exercise an existing crate set and its generated application")
    verify.add_argument("--packages", type=Path, required=True)
    verify.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def run(
    arguments: list[str],
    *,
    capture: bool = False,
    binary: bool = False,
    environment: dict[str, str] | None = None,
    cwd: Path = ROOT,
) -> str | bytes:
    result = subprocess.run(
        arguments,
        cwd=cwd,
        check=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=None,
        text=not binary,
        env=environment,
    )
    if not capture:
        return b"" if binary else ""
    if binary:
        if not isinstance(result.stdout, bytes):
            raise RcError("binary command returned text")
        return result.stdout
    if not isinstance(result.stdout, str):
        raise RcError("text command returned bytes")
    return result.stdout


def load_toml(path: Path) -> dict[str, object]:
    document = tomllib.loads(path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise RcError(f"{path.relative_to(ROOT)} is not a TOML table")
    return document


def load_json_object(path: Path) -> dict[str, object]:
    document = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise RcError(f"{path.relative_to(ROOT)} is not a JSON object")
    return document


def canonical_json_sha256(document: dict[str, object]) -> str:
    encoded = json.dumps(
        document,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def validate_developer_tooling_documents(
    package: dict[str, object],
    lock: dict[str, object],
    config_text: str,
    node_version: str,
    release_version: str,
) -> None:
    if (
        package.get("name") != "zeno-fcis-development"
        or package.get("private") is not True
    ):
        raise RcError("package.json must describe the private development-tool package")
    if package.get("version") != release_version:
        raise RcError("package.json version does not match the release candidate")
    engines = package.get("engines")
    if not isinstance(engines, dict) or engines.get("node") != EXPECTED_NODE_VERSION:
        raise RcError("package.json does not pin exact Node 22.23.1")
    dependencies = package.get("devDependencies")
    if dependencies != {"@nizos/probity": EXPECTED_PROBITY_VERSION}:
        raise RcError("package.json must pin only Probity 1.10.0 as developer tooling")
    if node_version.strip() != EXPECTED_NODE_VERSION:
        raise RcError(".node-version does not pin exact Node 22.23.1")

    if lock.get("lockfileVersion") != 3:
        raise RcError("package-lock.json must use lockfile version 3")
    if canonical_json_sha256(lock) != EXPECTED_NPM_LOCK_CANONICAL_SHA256:
        raise RcError("package-lock.json complete canonical graph changed")
    packages = lock.get("packages")
    if not isinstance(packages, dict):
        raise RcError("package-lock.json omits the packages map")
    root = packages.get("")
    if not isinstance(root, dict):
        raise RcError("package-lock.json omits the root package")
    if (
        root.get("version") != release_version
        or root.get("devDependencies") != dependencies
        or root.get("engines") != engines
    ):
        raise RcError("package-lock.json root metadata does not match package.json")
    probity = packages.get("node_modules/@nizos/probity")
    if not isinstance(probity, dict):
        raise RcError("package-lock.json omits the Probity package")
    if (
        probity.get("version") != EXPECTED_PROBITY_VERSION
        or probity.get("integrity") != EXPECTED_PROBITY_INTEGRITY
        or probity.get("dev") is not True
    ):
        raise RcError("package-lock.json Probity identity or integrity changed")

    required_config = (
        "rustCommandPolicy",
        "cargo\\s+(?:\\+\\S+\\s+)?update",
        "cargo\\s+(?:\\+\\S+\\s+)?publish",
        "python3\\s+tools\\/atdd\\.py\\s+run\\s+--all",
    )
    for marker in required_config:
        if marker not in config_text:
            raise RcError(f"probity.config.ts omits required marker {marker!r}")
    if "enforceTdd" in config_text:
        raise RcError("probity.config.ts may not enable AI-judged TDD authority")


def validate_developer_tooling(release_version: str) -> None:
    validate_developer_tooling_documents(
        load_json_object(NPM_PACKAGE_PATH),
        load_json_object(NPM_LOCK_PATH),
        PROBITY_CONFIG_PATH.read_text(encoding="utf-8"),
        NODE_VERSION_PATH.read_text(encoding="utf-8"),
        release_version,
    )


def package_set() -> dict[str, object]:
    document = load_toml(PACKAGE_SET_PATH)
    if document.get("format") != "zeno-fcis/package-set/1":
        raise RcError("unsupported package-set format")
    return document


def cargo_metadata(*, complete: bool) -> dict[str, object]:
    arguments = [
        "cargo",
        "+1.97.1",
        "metadata",
        "--format-version",
        "1",
        "--locked",
    ]
    if not complete:
        arguments.append("--no-deps")
    encoded = run(arguments, capture=True)
    if not isinstance(encoded, str):
        raise RcError("cargo metadata did not return text")
    document = json.loads(encoded)
    if not isinstance(document, dict):
        raise RcError("cargo metadata is not an object")
    return document


def require_string(document: dict[str, object], field: str) -> str:
    value = document.get(field)
    if not isinstance(value, str) or not value:
        raise RcError(f"package-set field {field!r} must be a nonempty string")
    return value


def require_string_list(document: dict[str, object], field: str) -> list[str]:
    value = document.get(field)
    if not isinstance(value, list) or not all(
        isinstance(item, str) and item for item in value
    ):
        raise RcError(f"package-set field {field!r} must be a string list")
    return list(value)


def workspace_packages(metadata: dict[str, object]) -> list[dict[str, object]]:
    packages = metadata.get("packages")
    members = metadata.get("workspace_members")
    if not isinstance(packages, list) or not isinstance(members, list):
        raise RcError("cargo metadata omits workspace packages")
    member_ids = set(members)
    selected = [
        package
        for package in packages
        if isinstance(package, dict) and package.get("id") in member_ids
    ]
    if len(selected) != len(member_ids):
        raise RcError("cargo metadata workspace member set is incomplete")
    return selected


def validate_package_documents(
    configured: dict[str, object], metadata: dict[str, object]
) -> tuple[dict[str, object], dict[str, object]]:
    packages = workspace_packages(metadata)
    version = require_string(configured, "version")
    toolchain = require_string(configured, "rust_toolchain")
    if toolchain != "1.97.1":
        raise RcError("release candidates must use pinned Rust 1.97.1")

    order = require_string_list(configured, "publish_order")
    private = require_string_list(configured, "private_packages")
    if len(order) != len(set(order)):
        raise RcError("publish order contains a duplicate")
    if len(private) != len(set(private)):
        raise RcError("private package set contains a duplicate")

    by_name: dict[str, dict[str, object]] = {}
    for package in packages:
        name = package.get("name")
        if not isinstance(name, str) or name in by_name:
            raise RcError("workspace package names are invalid or duplicated")
        by_name[name] = package

    public_actual = {
        name for name, package in by_name.items() if package.get("publish") != []
    }
    private_actual = set(by_name).difference(public_actual)
    if set(order) != public_actual:
        missing = sorted(public_actual.difference(order))
        extra = sorted(set(order).difference(public_actual))
        raise RcError(f"publish set mismatch: missing={missing}, extra={extra}")
    if set(private) != private_actual:
        raise RcError(
            "private package mismatch: "
            f"expected={sorted(private_actual)}, configured={sorted(private)}"
        )

    order_index = {name: index for index, name in enumerate(order)}
    for name, package in by_name.items():
        if package.get("version") != version:
            raise RcError(f"{name}: package version is not {version}")
        if package.get("rust_version") != toolchain:
            raise RcError(f"{name}: rust-version is not {toolchain}")
        for field in ("description", "license", "repository", "readme"):
            value = package.get(field)
            if not isinstance(value, str) or not value:
                raise RcError(f"{name}: missing package metadata {field}")
        manifest_path = package.get("manifest_path")
        if not isinstance(manifest_path, str) or not manifest_path:
            raise RcError(f"{name}: package manifest path is unavailable")
        readme = Path(manifest_path).parent / str(package["readme"])
        if not readme.is_file():
            raise RcError(f"{name}: package README does not exist")

        dependencies = package.get("dependencies")
        if not isinstance(dependencies, list):
            raise RcError(f"{name}: dependency metadata is malformed")
        for dependency in dependencies:
            if not isinstance(dependency, dict):
                raise RcError(f"{name}: dependency metadata is malformed")
            dependency_name = dependency.get("name")
            if dependency_name not in by_name:
                continue
            if dependency.get("req") != f"={version}":
                raise RcError(
                    f"{name}: internal dependency {dependency_name} is not pinned "
                    f"to ={version}"
                )
            if (
                name in order_index
                and dependency_name in order_index
                and order_index[str(dependency_name)] >= order_index[name]
            ):
                raise RcError(
                    f"{name}: dependency {dependency_name} is not earlier in "
                    "publish_order"
                )

    binaries = configured.get("binaries")
    if not isinstance(binaries, list) or not binaries:
        raise RcError("package set must declare at least one binary")
    binary_targets: set[str] = set()
    for binary in binaries:
        if not isinstance(binary, dict):
            raise RcError("binary declaration is malformed")
        package_name = binary.get("package")
        target_name = binary.get("target")
        if (
            package_name not in by_name
            or not isinstance(target_name, str)
            or not target_name
            or not target_name.isascii()
            or any(
                not character.isalnum() and character not in "-_"
                for character in target_name
            )
        ):
            raise RcError("binary package or target is invalid")
        if target_name in binary_targets:
            raise RcError(f"duplicate binary target {target_name}")
        binary_targets.add(target_name)
        targets = by_name[str(package_name)].get("targets")
        if not isinstance(targets, list) or not any(
            isinstance(target, dict)
            and target.get("name") == target_name
            and "bin" in target.get("kind", [])
            for target in targets
        ):
            raise RcError(f"missing binary target {package_name}/{target_name}")

    return configured, metadata


def validate_package_set() -> tuple[dict[str, object], dict[str, object]]:
    configured, metadata = validate_package_documents(
        package_set(), cargo_metadata(complete=False)
    )
    validate_developer_tooling(require_string(configured, "version"))
    return configured, metadata


def run_self_test(configured: dict[str, object], metadata: dict[str, object]) -> None:
    def expect_failure(
        changed_configured: dict[str, object],
        changed_metadata: dict[str, object],
        label: str,
    ) -> None:
        try:
            validate_package_documents(changed_configured, changed_metadata)
        except RcError:
            return
        raise RcError(f"self-test mutation survived: {label}")

    duplicate_configured = copy.deepcopy(configured)
    duplicate_order = require_string_list(duplicate_configured, "publish_order")
    duplicate_order.append(duplicate_order[0])
    duplicate_configured["publish_order"] = duplicate_order
    expect_failure(duplicate_configured, copy.deepcopy(metadata), "duplicate package")

    reversed_configured = copy.deepcopy(configured)
    reversed_configured["publish_order"] = list(
        reversed(require_string_list(reversed_configured, "publish_order"))
    )
    expect_failure(
        reversed_configured, copy.deepcopy(metadata), "invalid publish order"
    )

    dev_order_configured = copy.deepcopy(configured)
    dev_order = require_string_list(dev_order_configured, "publish_order")
    crypto_index = dev_order.index("zeno-fcis-crypto")
    spec_index = dev_order.index("zeno-fcis-spec")
    dev_order[crypto_index], dev_order[spec_index] = (
        dev_order[spec_index],
        dev_order[crypto_index],
    )
    dev_order_configured["publish_order"] = dev_order
    expect_failure(
        dev_order_configured,
        copy.deepcopy(metadata),
        "dev dependency publish order",
    )

    wrong_version_metadata = copy.deepcopy(metadata)
    wrong_version_packages = wrong_version_metadata.get("packages")
    if not isinstance(wrong_version_packages, list) or not wrong_version_packages:
        raise RcError("self-test package set is unavailable")
    first_package = wrong_version_packages[0]
    if not isinstance(first_package, dict):
        raise RcError("self-test package is malformed")
    first_package["version"] = "9.9.9"
    expect_failure(copy.deepcopy(configured), wrong_version_metadata, "package version")

    wrong_rust_metadata = copy.deepcopy(metadata)
    rust_packages = workspace_packages(wrong_rust_metadata)
    rust_packages[0]["rust_version"] = "1.97"
    expect_failure(copy.deepcopy(configured), wrong_rust_metadata, "minimum Rust version")

    missing_readme_metadata = copy.deepcopy(metadata)
    missing_readme_packages = missing_readme_metadata.get("packages")
    if not isinstance(missing_readme_packages, list) or not missing_readme_packages:
        raise RcError("self-test package set is unavailable")
    readme_package = missing_readme_packages[0]
    if not isinstance(readme_package, dict):
        raise RcError("self-test package is malformed")
    readme_package["readme"] = "missing-release-readme.md"
    expect_failure(copy.deepcopy(configured), missing_readme_metadata, "package README")

    package = load_json_object(NPM_PACKAGE_PATH)
    lock = load_json_object(NPM_LOCK_PATH)
    wrong_probity = copy.deepcopy(package)
    wrong_probity["devDependencies"] = {"@nizos/probity": "9.9.9"}
    try:
        validate_developer_tooling_documents(
            wrong_probity,
            lock,
            PROBITY_CONFIG_PATH.read_text(encoding="utf-8"),
            NODE_VERSION_PATH.read_text(encoding="utf-8"),
            require_string(configured, "version"),
        )
    except RcError:
        pass
    else:
        raise RcError("self-test mutation survived: Probity version")

    changed_transitive_lock = copy.deepcopy(lock)
    changed_transitive_packages = changed_transitive_lock.get("packages")
    if not isinstance(changed_transitive_packages, dict):
        raise RcError("self-test npm packages map is unavailable")
    changed_transitive = changed_transitive_packages.get(
        "node_modules/@openai/codex-sdk"
    )
    if not isinstance(changed_transitive, dict):
        raise RcError("self-test could not find a transitive npm package")
    changed_transitive["version"] = "9.9.9"
    changed_transitive["integrity"] = "sha512-hostile-lock-graph-mutation"
    try:
        validate_developer_tooling_documents(
            package,
            changed_transitive_lock,
            PROBITY_CONFIG_PATH.read_text(encoding="utf-8"),
            NODE_VERSION_PATH.read_text(encoding="utf-8"),
            require_string(configured, "version"),
        )
    except RcError:
        pass
    else:
        raise RcError("self-test mutation survived: transitive npm lock graph")

    wrong_pin_metadata = copy.deepcopy(metadata)
    wrong_pin_packages = wrong_pin_metadata.get("packages")
    changed_pin = False
    if isinstance(wrong_pin_packages, list):
        workspace_names = {
            package.get("name")
            for package in wrong_pin_packages
            if isinstance(package, dict)
        }
        for package in wrong_pin_packages:
            if not isinstance(package, dict):
                continue
            dependencies = package.get("dependencies")
            if not isinstance(dependencies, list):
                continue
            for dependency in dependencies:
                if (
                    isinstance(dependency, dict)
                    and dependency.get("name") in workspace_names
                ):
                    dependency["req"] = "*"
                    changed_pin = True
                    break
            if changed_pin:
                break
    if not changed_pin:
        raise RcError("self-test could not find an internal dependency")
    expect_failure(copy.deepcopy(configured), wrong_pin_metadata, "dependency pin")

    hidden_public_metadata = copy.deepcopy(metadata)
    hidden_packages = hidden_public_metadata.get("packages")
    if not isinstance(hidden_packages, list):
        raise RcError("self-test package set is unavailable")
    private_test_package = next(
        (
            package
            for package in hidden_packages
            if isinstance(package, dict)
            and package.get("name") == "zeno-fcis-generated-code-tests"
        ),
        None,
    )
    if private_test_package is None:
        raise RcError("self-test generated-code test package is unavailable")
    private_test_package["publish"] = None
    expect_failure(
        copy.deepcopy(configured), hidden_public_metadata, "hidden public package"
    )

    wrong_binary_configured = copy.deepcopy(configured)
    binaries = wrong_binary_configured.get("binaries")
    if (
        not isinstance(binaries, list)
        or not binaries
        or not isinstance(binaries[0], dict)
    ):
        raise RcError("self-test binary declaration is unavailable")
    binaries[0]["target"] = "missing-binary"
    expect_failure(wrong_binary_configured, copy.deepcopy(metadata), "binary target")

    duplicate_binary_configured = copy.deepcopy(configured)
    duplicate_binaries = duplicate_binary_configured.get("binaries")
    if not isinstance(duplicate_binaries, list) or not duplicate_binaries:
        raise RcError("self-test binary declaration is unavailable")
    duplicate_binaries.append(copy.deepcopy(duplicate_binaries[0]))
    expect_failure(
        duplicate_binary_configured,
        copy.deepcopy(metadata),
        "duplicate binary target",
    )


def run_packaged_layout_self_test() -> None:
    """Planted controls for the consumer build and the cross-package test input manifest."""

    def package(directory: Path, name: str, library: str, test: str | None = None) -> Path:
        (directory / "src").mkdir(parents=True)
        (directory / "Cargo.toml").write_text(
            f'[package]\nname = "{name}"\nversion = "0.1.0"\nedition = "2024"\npublish = false\n',
            encoding="utf-8",
        )
        (directory / "src" / "lib.rs").write_text(library, encoding="utf-8")
        (directory / "data.txt").write_text(f"{name} data\n", encoding="utf-8")
        if test is not None:
            (directory / "tests").mkdir()
            (directory / "tests" / "reads.rs").write_text(test, encoding="utf-8")
        return directory

    def workspace(root: Path, roots: dict[str, Path], environment: dict[str, str]) -> Path:
        manifest = write_packaged_workspace_manifest(root, roots)
        run(["cargo", "+1.97.1", "generate-lockfile", "--manifest-path", str(manifest), "--offline"],
            environment=environment, cwd=root)
        return manifest

    def layout_reads(root: Path, roots: dict[str, Path], environment: dict[str, str]):
        return repository_layout_reads(workspace(root, roots, environment), root, environment)

    def refused(action, label: str) -> None:
        try:
            action()
        except (RcError, subprocess.CalledProcessError):
            return
        raise RcError(f"packaged layout self-test accepted {label}")

    sibling_read = 'pub const DATA: &str = include_str!("../../beta/data.txt");\n'
    test_reads = (
        "#[test]\nfn reads() {\n"
        '    assert!(!include_str!("../../beta/data.txt").is_empty());\n'
        '    assert!(!include_str!("../../../verification/fixture.txt").is_empty());\n}\n'
    )
    fixture = b"reviewed fixture\n"
    with tempfile.TemporaryDirectory(prefix="zeno-fcis-packaged-layout-self-test-") as raw:
        base = Path(raw)

        def environment(name: str) -> dict[str, str]:
            return dict(os.environ, CARGO_TARGET_DIR=str(base / f"target-{name}"),
                        CARGO_INCREMENTAL="0", CARGO_PROFILE_DEV_DEBUG="0", CARGO_PROFILE_TEST_DEBUG="0")

        # Control 1: a library reading a sibling file cannot build from the archives alone.
        isolated = base / "isolated"
        consumer_env = environment("consumer")
        consumer_manifest = workspace(isolated, {
            "alpha": package(isolated / "sources" / "alpha-0.1.0", "alpha", sibling_read),
            "beta": package(isolated / "sources" / "beta-0.1.0", "beta", ""),
        }, consumer_env)
        refused(lambda: run(consumer_build_command(consumer_manifest), environment=consumer_env,
                            cwd=isolated), "a library reading a sibling package file")

        # Repository layout: one test reads a sibling archive file and a verification file.
        layout = base / "layout"
        roots = {"alpha": package(layout / "crates" / "alpha", "alpha", "", test_reads),
                 "beta": package(layout / "crates" / "beta", "beta", "")}
        sibling_digest = hashlib.sha256(b"beta data\n").hexdigest()
        expected = [
            {"package": "alpha", "target": "test:reads", "path": "crates/beta/data.txt",
             "sha256": sibling_digest},
            {"package": "alpha", "target": "test:reads", "path": "verification/fixture.txt",
             "sha256": hashlib.sha256(fixture).hexdigest()},
        ]
        stage_repository_inputs(expected, layout, read_blob=lambda path: fixture)
        messages, observed, non_test = layout_reads(layout, roots, environment("layout"))
        require_packaged_test_inputs(observed, expected, non_test)

        # Control 2: an unlisted cross-package read in a test fails the manifest check.
        refused(lambda: require_packaged_test_inputs(observed, expected[1:], non_test),
                "an unlisted cross-package test read")
        # Control 3: a changed verification fixture fails, whether staged or read.
        refused(lambda: stage_repository_inputs(expected, base / "restaged",
                                                read_blob=lambda path: fixture + b"changed"),
                "a verification input that differs from the manifest")
        (layout / "verification" / "fixture.txt").write_bytes(fixture + b"changed")
        changed, changed_non_test = observed_cross_package_inputs(
            messages, layout, base / "target-layout")
        refused(lambda: require_packaged_test_inputs(changed, expected, changed_non_test),
                "a changed verification fixture")

        # Control 4: a non-test target with any cross-package read fails, even when it compiles.
        mixed = base / "mixed"
        mixed_roots = {"gamma": package(mixed / "crates" / "gamma", "gamma", sibling_read),
                       "beta": package(mixed / "crates" / "beta", "beta", "")}
        _, mixed_observed, mixed_non_test = layout_reads(mixed, mixed_roots, environment("mixed"))
        if not mixed_non_test:
            raise RcError("packaged layout self-test missed a non-test cross-package read")
        refused(lambda: require_packaged_test_inputs(mixed_observed, mixed_observed, mixed_non_test),
                "a non-test cross-package read")


def run_rustdoc_normalization_self_test() -> None:
    with tempfile.TemporaryDirectory(prefix="zeno-fcis-rustdoc-self-test-") as raw:
        doc_root = Path(raw)
        umbrella = doc_root / "zeno_fcis"
        search_index = doc_root / "search.index"
        umbrella.mkdir()
        search_index.mkdir()
        (umbrella / "index.html").write_text("api", encoding="utf-8")
        (search_index / "root.js").write_text("nondeterministic", encoding="utf-8")
        for name in ("help.html", "settings.html"):
            (doc_root / name).write_text(
                '<meta data-current-crate="finishing_crate">', encoding="utf-8"
            )

        normalize_rustdoc_tree(doc_root)

        if search_index.exists():
            raise RcError("rustdoc normalization retained the search index")
        for name in ("help.html", "settings.html"):
            helper = (doc_root / name).read_text(encoding="utf-8")
            if 'data-current-crate="zeno_fcis"' not in helper:
                raise RcError(f"rustdoc normalization did not normalize {name}")
        notice = doc_root / "OFFLINE_SEARCH_DISABLED.txt"
        if notice.read_text(encoding="utf-8") != RUSTDOC_ARCHIVE_NOTICE:
            raise RcError("rustdoc normalization notice is not exact")


def git_text(*arguments: str) -> str:
    value = run(["git", *arguments], capture=True)
    if not isinstance(value, str):
        raise RcError("git returned binary output")
    return value.strip()


def require_clean_commit() -> str:
    commit = git_text("rev-parse", "HEAD")
    if len(commit) != 40 or any(
        character not in "0123456789abcdef" for character in commit
    ):
        raise RcError("HEAD is not a full lowercase Git commit")
    if git_text("status", "--porcelain", "--untracked-files=all"):
        raise RcError("RC assembly requires a clean exact checkout")
    return commit


def write_json(path: Path, document: object) -> None:
    path.write_text(
        json.dumps(document, ensure_ascii=True, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        while chunk := source.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def normalized_tar_info(info: tarfile.TarInfo) -> tarfile.TarInfo:
    info.mtime = 0
    info.uid = 0
    info.gid = 0
    info.uname = ""
    info.gname = ""
    return info


def deterministic_tree_archive(source: Path, destination: Path, prefix: str) -> None:
    with (
        destination.open("wb") as raw,
        gzip.GzipFile(filename="", fileobj=raw, mode="wb", mtime=0) as compressed,
        tarfile.open(
            fileobj=compressed, mode="w", format=tarfile.USTAR_FORMAT
        ) as archive,
    ):
        for path in sorted(source.rglob("*")):
            if path.name == ".lock":
                continue
            relative = path.relative_to(source)
            archive_name = str(Path(prefix) / relative)
            info = normalized_tar_info(archive.gettarinfo(str(path), archive_name))
            if info.isdir():
                info.mode = 0o755
                archive.addfile(info)
            elif info.isfile():
                info.mode = 0o644
                with path.open("rb") as content:
                    archive.addfile(info, content)
            else:
                raise RcError(
                    f"deterministic tree archive rejects {relative}: "
                    "only regular files and directories are supported"
                )


def run_tree_archive_mode_self_test() -> None:
    with tempfile.TemporaryDirectory(prefix="zeno-fcis-archive-self-test-") as raw:
        root = Path(raw)
        sources = [root / "left", root / "right"]
        archives = [root / "left.tar.gz", root / "right.tar.gz"]
        for source in sources:
            nested = source / "nested"
            nested.mkdir(parents=True)
            (nested / "api.html").write_text("same bytes", encoding="utf-8")

        os.chmod(sources[0] / "nested", 0o700)
        os.chmod(sources[0] / "nested" / "api.html", 0o600)
        os.chmod(sources[1] / "nested", 0o775)
        os.chmod(sources[1] / "nested" / "api.html", 0o664)

        for source, archive in zip(sources, archives, strict=True):
            deterministic_tree_archive(source, archive, "docs")
        if archives[0].read_bytes() != archives[1].read_bytes():
            raise RcError("tree archives differ across source permission modes")

        with tarfile.open(archives[0], mode="r:gz") as archive:
            modes = {member.name: member.mode for member in archive.getmembers()}
        expected = {"docs/nested": 0o755, "docs/nested/api.html": 0o644}
        if modes != expected:
            raise RcError(f"tree archive modes are not canonical: {modes}")


def normalize_rustdoc_tree(doc_root: Path) -> None:
    if not (doc_root / "zeno_fcis" / "index.html").is_file():
        raise RcError("public umbrella rustdoc is missing")
    search_index = doc_root / "search.index"
    if not (search_index / "root.js").is_file():
        raise RcError("rustdoc search index is missing before normalization")
    shutil.rmtree(search_index)

    marker = 'data-current-crate="'
    for name in ("help.html", "settings.html"):
        page = doc_root / name
        if not page.is_file():
            raise RcError(f"rustdoc helper page {name} is missing")
        content = page.read_text(encoding="utf-8")
        if content.count(marker) != 1:
            raise RcError(f"rustdoc helper page {name} has an unexpected shape")
        start = content.index(marker) + len(marker)
        end = content.find('"', start)
        if end < 0:
            raise RcError(f"rustdoc helper page {name} has no crate marker terminator")
        page.write_text(content[:start] + "zeno_fcis" + content[end:], encoding="utf-8")

    (doc_root / "OFFLINE_SEARCH_DISABLED.txt").write_text(
        RUSTDOC_ARCHIVE_NOTICE, encoding="utf-8"
    )


def deterministic_binary_archive(binary: Path, destination: Path, prefix: str) -> None:
    members = [
        (binary, binary.name, 0o755),
        (ROOT / "README.md", "README.md", 0o644),
        (ROOT / "LICENSE-APACHE", "LICENSE-APACHE", 0o644),
        (ROOT / "LICENSE-MIT", "LICENSE-MIT", 0o644),
        (ROOT / "docs" / "INSTALLATION.md", "INSTALLATION.md", 0o644),
    ]
    with (
        destination.open("wb") as raw,
        gzip.GzipFile(fileobj=raw, mode="wb", mtime=0) as compressed,
        tarfile.open(
            fileobj=compressed, mode="w", format=tarfile.USTAR_FORMAT
        ) as archive,
    ):
        for source, name, mode in members:
            content = source.read_bytes()
            info = tarfile.TarInfo(str(Path(prefix) / name))
            info.size = len(content)
            info.mode = mode
            normalized_tar_info(info)
            archive.addfile(info, io.BytesIO(content))


def binary_artifact_inventory(
    configured: dict[str, object], version: str, host: str
) -> list[dict[str, str]]:
    binaries = configured.get("binaries")
    if not isinstance(binaries, list):
        raise RcError("binary metadata is malformed")
    inventory: list[dict[str, str]] = []
    archive_names: set[str] = set()
    prefixes: set[str] = set()
    for binary in binaries:
        if not isinstance(binary, dict):
            raise RcError("binary metadata is malformed")
        package_name = binary.get("package")
        target_name = binary.get("target")
        if not isinstance(package_name, str) or not isinstance(target_name, str):
            raise RcError("binary metadata is malformed")
        stem = f"{target_name}-{version}-{host}"
        archive_name = f"{stem}.tar.gz"
        if archive_name in archive_names or stem in prefixes:
            raise RcError(f"duplicate binary artifact path for {target_name}")
        archive_names.add(archive_name)
        prefixes.add(stem)
        inventory.append(
            {
                "package": package_name,
                "target": target_name,
                "archive": archive_name,
                "prefix": stem,
                "command": (
                    "cargo +1.97.1 build --release --locked "
                    f"-p {package_name} --bin {target_name}"
                ),
            }
        )
    return inventory


def run_binary_inventory_self_test(configured: dict[str, object]) -> None:
    version = require_string(configured, "version")
    inventory = binary_artifact_inventory(
        configured, version, "self-test-unknown-linux"
    )
    binaries = configured.get("binaries")
    if not isinstance(binaries, list) or len(inventory) != len(binaries):
        raise RcError("binary inventory omitted a declared target")
    if len({item["archive"] for item in inventory}) != len(inventory):
        raise RcError("binary inventory archive names are not unique")
    if len({item["command"] for item in inventory}) != len(inventory):
        raise RcError("binary inventory provenance commands are not unique")

    with tempfile.TemporaryDirectory(prefix="zeno-fcis-binary-self-test-") as raw:
        root = Path(raw)
        for item in inventory:
            executable = root / item["target"]
            executable.write_bytes(item["target"].encode("ascii"))
            archive_path = root / item["archive"]
            deterministic_binary_archive(executable, archive_path, item["prefix"])
            with tarfile.open(archive_path, mode="r:gz") as archive:
                members = {member.name for member in archive.getmembers()}
            expected_executable = str(Path(item["prefix"]) / item["target"])
            if expected_executable not in members:
                raise RcError(f"binary archive omitted {item['target']}")


def source_archive(destination: Path, prefix: str) -> None:
    content = run(
        ["git", "archive", "--format=tar", f"--prefix={prefix}/", "HEAD"],
        capture=True,
        binary=True,
    )
    if not isinstance(content, bytes):
        raise RcError("git archive did not return bytes")
    with (
        destination.open("wb") as raw,
        gzip.GzipFile(fileobj=raw, mode="wb", mtime=0) as compressed,
    ):
        compressed.write(content)


def cargo_lock_checksums() -> dict[tuple[str, str, str], str]:
    document = load_toml(LOCK_PATH)
    packages = document.get("package")
    if not isinstance(packages, list):
        raise RcError("Cargo.lock has no package set")
    checksums: dict[tuple[str, str, str], str] = {}
    for package in packages:
        if not isinstance(package, dict):
            continue
        name = package.get("name")
        version = package.get("version")
        source = package.get("source")
        checksum = package.get("checksum")
        if all(isinstance(item, str) for item in (name, version, source, checksum)):
            checksums[(str(name), str(version), str(source))] = str(checksum)
    return checksums


def bom_ref(package: dict[str, object]) -> str:
    name = quote(str(package["name"]), safe="-._~")
    version = quote(str(package["version"]), safe="-._~")
    source = package.get("source")
    base = f"pkg:cargo/{name}@{version}"
    if isinstance(source, str):
        return f"{base}?repository_url={quote(source, safe='')}"
    return base


def build_sbom(
    metadata: dict[str, object], commit: str, version: str
) -> dict[str, object]:
    packages = metadata.get("packages")
    resolve = metadata.get("resolve")
    if not isinstance(packages, list) or not isinstance(resolve, dict):
        raise RcError("complete Cargo metadata omits packages or resolution")
    checksums = cargo_lock_checksums()
    by_id = {
        str(package["id"]): package
        for package in packages
        if isinstance(package, dict) and "id" in package
    }
    components = []
    for package in sorted(
        by_id.values(),
        key=lambda item: (
            str(item["name"]),
            str(item["version"]),
            str(item.get("source")),
        ),
    ):
        component: dict[str, object] = {
            "type": "library",
            "bom-ref": bom_ref(package),
            "name": package["name"],
            "version": package["version"],
            "purl": bom_ref(package),
        }
        license_value = package.get("license")
        if isinstance(license_value, str) and license_value:
            component["licenses"] = [{"expression": license_value}]
        source = package.get("source")
        if isinstance(source, str):
            checksum = checksums.get(
                (str(package["name"]), str(package["version"]), source)
            )
            if checksum is not None:
                component["hashes"] = [{"alg": "SHA-256", "content": checksum}]
        if package.get("id") in metadata.get("workspace_members", []):
            component["properties"] = [{"name": "zeno-fcis:workspace", "value": "true"}]
        components.append(component)

    nodes = resolve.get("nodes")
    if not isinstance(nodes, list):
        raise RcError("Cargo resolution nodes are malformed")
    dependencies = []
    for node in nodes:
        if not isinstance(node, dict) or node.get("id") not in by_id:
            continue
        dependency_ids = node.get("dependencies")
        if not isinstance(dependency_ids, list):
            raise RcError("Cargo resolution dependency list is malformed")
        dependencies.append(
            {
                "ref": bom_ref(by_id[str(node["id"])]),
                "dependsOn": sorted(
                    bom_ref(by_id[str(dependency)])
                    for dependency in dependency_ids
                    if str(dependency) in by_id
                ),
            }
        )

    timestamp = git_text("show", "-s", "--format=%cI", commit)
    serial = uuid.uuid5(
        uuid.NAMESPACE_URL, f"https://github.com/TheDarkLightX/ZenoFCIS@{commit}"
    )
    return {
        "bomFormat": "CycloneDX",
        "specVersion": "1.6",
        "serialNumber": f"urn:uuid:{serial}",
        "version": 1,
        "metadata": {
            "timestamp": timestamp,
            "component": {
                "type": "library",
                "bom-ref": f"pkg:cargo/zeno-fcis@{version}",
                "name": "zeno-fcis",
                "version": version,
                "purl": f"pkg:cargo/zeno-fcis@{version}",
            },
            "properties": [
                {"name": "zeno-fcis:source-commit", "value": commit},
                {"name": "zeno-fcis:rust-toolchain", "value": "1.97.1"},
            ],
        },
        "components": components,
        "dependencies": sorted(dependencies, key=lambda item: str(item["ref"])),
    }


def artifact_entries(output: Path, excluded: set[Path]) -> list[dict[str, object]]:
    entries = []
    for path in sorted(item for item in output.rglob("*") if item.is_file()):
        if path in excluded:
            continue
        entries.append(
            {
                "path": path.relative_to(output).as_posix(),
                "sha256": sha256(path),
                "size": path.stat().st_size,
            }
        )
    return entries


def deterministic_bundle(output: Path, destination: Path) -> None:
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_STORED) as archive:
        for path in sorted(item for item in output.rglob("*") if item.is_file()):
            if path == destination:
                continue
            info = zipfile.ZipInfo(path.relative_to(output).as_posix(), FIXED_ZIP_TIME)
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            archive.writestr(info, path.read_bytes())


def extract_checked_crate(archive_path: Path, destination: Path) -> None:
    with tarfile.open(archive_path, mode="r:gz") as archive:
        members = archive.getmembers()
        seen: set[PurePosixPath] = set()
        for member in members:
            relative = PurePosixPath(member.name)
            if (
                relative.is_absolute()
                or not relative.parts
                or relative.parts[0] != archive_path.stem
                or relative in seen
                or ".." in relative.parts
                or member.issym()
                or member.islnk()
                or not (member.isdir() or member.isfile())
            ):
                raise RcError(
                    f"crate archive contains an unsafe member: {archive_path.name}:{member.name}"
                )
            seen.add(relative)
        archive.extractall(destination, members=members, filter="data")


def compiler_environment(environment: dict[str, str]) -> dict[str, str]:
    """Exclude inherited flag, compiler, wrapper, and target overrides."""
    overrides = {
        "RUSTFLAGS", "RUSTDOCFLAGS", "CARGO_ENCODED_RUSTFLAGS", "CARGO_ENCODED_RUSTDOCFLAGS",
        "RUSTC", "RUSTDOC", "RUSTC_WRAPPER", "RUSTC_WORKSPACE_WRAPPER",
        "CARGO_BUILD_RUSTC", "CARGO_BUILD_RUSTDOC", "CARGO_BUILD_RUSTC_WRAPPER",
        "CARGO_BUILD_RUSTC_WORKSPACE_WRAPPER", "CARGO_BUILD_TARGET",
    }
    return {name: value for name, value in environment.items() if name not in overrides}


def remapped_compiler_environment(
    environment: dict[str, str], source: Path, destination: str,
) -> dict[str, str]:
    """Remap source and dependency home paths without inherited flag overrides."""
    result = compiler_environment(environment)
    # Rust uses the last matching remap. Keep the specific source mapping last
    # when a normal checkout is itself under the home directory.
    remaps = [f"--remap-path-prefix={Path.home()}=/zeno-fcis-home",
              f"--remap-path-prefix={source}={destination}"]
    if any("\x1f" in remap or "\0" in remap for remap in remaps):
        raise RcError("staging path cannot be encoded as one compiler argument")
    result["CARGO_ENCODED_RUSTFLAGS"] = "\x1f".join(remaps)
    result["CARGO_ENCODED_RUSTDOCFLAGS"] = "\x1f".join(["-D", "warnings", *remaps])
    return result


def compiler_flag_evidence(environment: dict[str, str], source: Path, label: str) -> dict[str, list[str]]:
    return {key: [flag.replace(str(source), label).replace(str(Path.home()), "<home>")
                  for flag in environment[key].split("\x1f")]
            for key in ("CARGO_ENCODED_RUSTFLAGS", "CARGO_ENCODED_RUSTDOCFLAGS")}


PACKAGED_TEST_INPUTS_PATH = ROOT / "release" / "packaged-test-inputs.json"
PACKAGED_TEST_INPUTS_FORMAT = "zeno-fcis/packaged-test-inputs/1"
# Test inputs that are not in any published archive. They are copied from the
# exact commit and must also appear, with their SHA-256, in the manifest.
REPOSITORY_INPUT_PREFIX = "verification/"
CONSUMER_TARGET_ARGUMENTS = ("--workspace", "--lib", "--bins", "--examples", "--all-features")
PACKAGED_TEST_ARGUMENTS = ("--workspace", "--all-targets", "--all-features")


def load_packaged_test_inputs(path: Path = PACKAGED_TEST_INPUTS_PATH) -> list[dict[str, str]]:
    """Read the reviewed list of files each packaged test target reads outside its package."""

    document = load_json_object(path)
    if set(document) != {"format", "inputs"} or document["format"] != PACKAGED_TEST_INPUTS_FORMAT:
        raise RcError(f"{path.name}: unexpected packaged test input format")
    entries = document["inputs"]
    if not isinstance(entries, list):
        raise RcError(f"{path.name}: inputs must be a list")
    keys = {"package", "target", "path", "sha256"}
    checked: list[dict[str, str]] = []
    hashes: dict[str, str] = {}
    for entry in entries:
        if not isinstance(entry, dict) or set(entry) != keys or not all(
            isinstance(entry[key], str) for key in keys
        ):
            raise RcError(f"{path.name}: malformed input entry")
        relative = PurePosixPath(entry["path"])
        if (
            relative.is_absolute()
            or ".." in relative.parts
            or relative.as_posix() != entry["path"]
            or relative.parts[0] not in ("crates", REPOSITORY_INPUT_PREFIX.rstrip("/"))
            or re.fullmatch(r"[0-9a-f]{64}", entry["sha256"]) is None
        ):
            raise RcError(f"{path.name}: invalid input entry {entry['path']}")
        if hashes.setdefault(entry["path"], entry["sha256"]) != entry["sha256"]:
            raise RcError(f"{path.name}: one path has two digests: {entry['path']}")
        checked.append(dict(entry))
    if checked != sorted(checked, key=packaged_input_key) or len(
        {packaged_input_key(entry) for entry in checked}
    ) != len(checked):
        raise RcError(f"{path.name}: inputs must be sorted and unique")
    return checked


def packaged_input_key(entry: dict[str, str]) -> tuple[str, str, str]:
    return entry["package"], entry["target"], entry["path"]


def git_blob(path: str) -> bytes:
    data = run(["git", "cat-file", "blob", f"HEAD:{path}"], capture=True, binary=True)
    if not isinstance(data, bytes):
        raise RcError("git returned text for a blob")
    return data


def stage_repository_inputs(
    entries: list[dict[str, str]], layout_root: Path, read_blob=git_blob,
) -> list[dict[str, str]]:
    """Copy the listed non-archive inputs from the commit into the repository layout."""

    staged = []
    for path, digest in sorted({(entry["path"], entry["sha256"]) for entry in entries}):
        if not path.startswith(REPOSITORY_INPUT_PREFIX):
            continue
        data = read_blob(path)
        if hashlib.sha256(data).hexdigest() != digest:
            raise RcError(f"repository test input differs from the reviewed manifest: {path}")
        destination = layout_root / path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
        staged.append({"path": path, "sha256": digest})
    return staged


def dep_info_prerequisites(path: Path) -> list[str] | None:
    """Return the prerequisites of a rustc dep-info file, or None for any other dep-info.

    Rustc's own file names itself as its first rule's target and lists only the
    files of that one compilation. Cargo's uplifted dep-info (`target/debug/x.d`)
    names the artifact instead and lists every dependency's sources; it is skipped.
    """

    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        separator = re.search(r"(?<!\\):(?:\s|$)", line)
        if separator is None:
            raise RcError(f"unreadable dep-info rule: {path.name}")
        if Path(line[:separator.start()].replace("\\ ", " ")).name != path.name:
            return None
        return [item.replace("\\ ", " ") for item in re.split(r"(?<!\\)\s+", line[separator.end():].strip()) if item]
    return None


def observed_cross_package_inputs(
    messages: str, layout_root: Path, target_dir: Path,
) -> tuple[list[dict[str, str]], list[str]]:
    """Derive, from rustc dep-info, every file a package target reads outside its package.

    Returns the test-target entries and a list of non-test violations. Files under the
    target directory are build-script output of the package itself.
    """

    test_targets: dict[str, tuple[str, str]] = {}
    for line in messages.splitlines():
        message = json.loads(line)
        if message.get("reason") != "compiler-artifact" or not message["profile"]["test"]:
            continue
        manifest = Path(message["manifest_path"]).resolve()
        if layout_root.resolve() not in manifest.parents:
            continue
        target = message["target"]
        label = f"{target['kind'][0]}:{target['name']}"
        test_targets[Path(message["filenames"][0]).name] = (message["target"]["src_path"], label)
    resolved_target = target_dir.resolve()
    dep_files = [*target_dir.glob("debug/deps/*.d"), *target_dir.glob("debug/examples/*.d"),
                 *target_dir.glob("debug/build/*/*.d")]
    entries: list[dict[str, str]] = []
    violations: list[str] = []
    seen_tests: set[str] = set()
    for dep_file in sorted(dep_files):
        prerequisites = dep_info_prerequisites(dep_file)
        if not prerequisites:
            continue
        root = Path(os.path.normpath(layout_root / prerequisites[0]))
        try:
            relative_root = root.relative_to(layout_root)
        except ValueError:
            continue
        if len(relative_root.parts) < 2 or relative_root.parts[0] != "crates":
            continue
        package = relative_root.parts[1]
        package_root = layout_root / "crates" / package
        test = test_targets.get(dep_file.stem)
        if test is not None:
            seen_tests.add(dep_file.stem)
        label = test[1] if test is not None else f"non-test:{relative_root.as_posix()}"
        for prerequisite in prerequisites:
            read = Path(os.path.normpath(layout_root / prerequisite))
            if read == package_root or package_root in read.parents:
                continue
            if resolved_target == read.resolve() or resolved_target in read.resolve().parents:
                continue
            try:
                relative = read.relative_to(layout_root).as_posix()
            except ValueError:
                relative = read.as_posix()
            if test is None:
                violations.append(f"{package} {label} reads {relative}")
                continue
            if not read.is_file():
                raise RcError(f"dep-info names a missing file: {relative}")
            entries.append({"package": package, "target": label, "path": relative,
                            "sha256": sha256(read)})
    missing = sorted(set(test_targets) - seen_tests)
    if missing:
        raise RcError(f"dep-info is missing for packaged test targets: {', '.join(missing)}")
    unique = {packaged_input_key(entry): entry for entry in entries}
    return [unique[key] for key in sorted(unique)], violations


def require_packaged_test_inputs(
    observed: list[dict[str, str]], expected: list[dict[str, str]], non_test: list[str],
) -> None:
    problems = [f"non-test target has a cross-package read: {item}" for item in non_test]
    expected_rows = {tuple(entry.values()) for entry in expected}
    observed_rows = {tuple(entry.values()) for entry in observed}
    problems.extend(f"unlisted cross-package test input: {' '.join(row)}"
                    for row in sorted(observed_rows - expected_rows))
    problems.extend(f"listed cross-package test input not read as listed: {' '.join(row)}"
                    for row in sorted(expected_rows - observed_rows))
    if problems:
        raise RcError("packaged test inputs differ from release/packaged-test-inputs.json:\n  "
                      + "\n  ".join(problems))


def repository_layout_reads(
    layout_manifest: Path, layout_root: Path, environment: dict[str, str],
) -> tuple[str, list[dict[str, str]], list[str]]:
    """Build every non-test and test target in the repository layout and derive cross-package reads.

    The non-test build comes first so that every library, binary, example and build
    script leaves its own dep-info, even when no test depends on it.
    """

    run(consumer_build_command(layout_manifest), environment=environment, cwd=layout_root)
    messages = run(packaged_test_command(layout_manifest), capture=True,
                   environment=environment, cwd=layout_root)
    if not isinstance(messages, str):
        raise RcError("packaged test build returned binary data")
    observed, non_test = observed_cross_package_inputs(
        messages, layout_root, Path(environment["CARGO_TARGET_DIR"]))
    return messages, observed, non_test


def write_packaged_workspace_manifest(root: Path, package_roots: dict[str, Path]) -> Path:
    workspace_manifest = root / "Cargo.toml"
    workspace_lines = ["[workspace]", 'resolver = "3"', "members = ["]
    for package_root in sorted(package_roots.values()):
        workspace_lines.append(f"  {json.dumps(package_root.relative_to(root).as_posix())},")
    workspace_lines.extend(["]", "", "[patch.crates-io]"])
    for name, package_root in sorted(package_roots.items()):
        workspace_lines.append(f"{json.dumps(name)} = {{ path = {json.dumps(str(package_root))} }}")
    workspace_manifest.write_text("\n".join(workspace_lines) + "\n", encoding="utf-8")
    return workspace_manifest


def consumer_build_command(workspace_manifest: Path) -> list[str]:
    return ["cargo", "+1.97.1", "build", "--manifest-path", str(workspace_manifest),
            *CONSUMER_TARGET_ARGUMENTS, "--locked", "--offline", "--jobs", "1"]


def packaged_test_command(workspace_manifest: Path) -> list[str]:
    return ["cargo", "+1.97.1", "test", "--manifest-path", str(workspace_manifest),
            *PACKAGED_TEST_ARGUMENTS, "--locked", "--offline", "--no-run", "--jobs", "1",
            "--message-format=json-render-diagnostics"]


def packaged_checker_inputs() -> list[dict[str, str]]:
    return [{"path": name, "sha256": sha256(ROOT / name)} for name in (
        "tools/rc_package.py", "tools/check_generated_application.py", "tools/check_synthesis.py",
        "Cargo.lock", "release/package-set.toml", "release/packaged-test-inputs.json",
        "tools/check_v1_compatibility.py",
        "test-data/v1-compatibility/baseline.json",
        "test-projects/external-consumer/src/main.rs", "test-projects/external-consumer/Cargo.toml",
    )]


def verify_packaged_workspace(
    packages_dir: Path,
    version: str,
    build_target: Path,
    environment: dict[str, str],
) -> dict[str, object]:
    build_target.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="packaged-workspace-", dir=build_target) as directory:
        return check_packaged_workspace(packages_dir, version, Path(directory), environment)


def check_packaged_workspace(
    packages_dir: Path, version: str, verification_root: Path, environment: dict[str, str],
) -> dict[str, object]:
    sources = verification_root / "sources"
    sources.mkdir(parents=True)
    commit = git_text("rev-parse", "HEAD")
    inputs = packaged_checker_inputs()
    clean = not git_text("status", "--porcelain", "--untracked-files=all")
    expected = {f"{name}-{version}.crate" for name in require_string_list(package_set(), "publish_order")}
    archives = sorted(packages_dir.glob("*.crate"))
    if {path.name for path in archives} != expected:
        raise RcError("packaged verification requires the exact declared crate set")
    package_roots: dict[str, Path] = {}
    package_evidence = []
    for archive_path in archives:
        extract_checked_crate(archive_path, sources)
        name = archive_path.stem.removesuffix(f"-{version}")
        package_root = sources / f"{name}-{version}"
        if not (package_root / "Cargo.toml").is_file():
            raise RcError(f"unpacked crate is missing Cargo.toml: {archive_path.name}")
        manifest = load_toml(package_root / "Cargo.toml")
        package = manifest.get("package", {})
        if not isinstance(package, dict) or (package.get("name"), package.get("version")) != (name, version):
            raise RcError(f"unpacked crate identity differs from its archive: {archive_path.name}")
        vcs = load_json_object(package_root / ".cargo_vcs_info.json")
        git_info = vcs.get("git")
        if not isinstance(git_info, dict) or git_info.get("sha1") != commit:
            raise RcError(f"crate source commit differs from this checkout: {archive_path.name}")
        dirty = git_info.get("dirty", False)
        if not isinstance(dirty, bool):
            raise RcError(f"crate source status is malformed: {archive_path.name}")
        package_evidence.append({"archive": archive_path.name, "sha256": sha256(archive_path),
                                 "source_clean": not dirty})
        package_roots[name] = package_root

    workspace_manifest = write_packaged_workspace_manifest(verification_root, package_roots)

    check_environment = remapped_compiler_environment(
        environment, verification_root, "/zeno-fcis-package-check",
    )
    target_dir = verification_root / "target"
    check_environment["CARGO_TARGET_DIR"] = str(target_dir)
    check_environment.update(CARGO_BUILD_JOBS="1", CARGO_INCREMENTAL="0",
                             CARGO_PROFILE_DEV_DEBUG="0", CARGO_PROFILE_TEST_DEBUG="0")
    graph = generated_application.resolve_reviewed_graph(
        verification_root,
        {(name, version): root / "Cargo.toml" for name, root in package_roots.items()},
        check_environment,
    )
    # 1. Consumer build, isolated layout: every target a consumer of a published
    #    crate builds (libraries, binaries, examples, build scripts) from the
    #    archives alone.
    run(consumer_build_command(workspace_manifest), environment=check_environment,
        cwd=verification_root)

    # 2. Packaged tests, repository layout: the same archives at crates/<name>/,
    #    plus only the verification files the reviewed manifest names. Every
    #    file a test reads outside its own package must equal that manifest.
    expected_test_inputs = load_packaged_test_inputs()
    layout_root = verification_root / "repository-layout"
    layout_roots = {name: layout_root / "crates" / name for name in package_roots}
    for name, package_root in package_roots.items():
        shutil.copytree(package_root, layout_roots[name])
    repository_inputs = stage_repository_inputs(expected_test_inputs, layout_root)
    layout_manifest = write_packaged_workspace_manifest(layout_root, layout_roots)
    layout_graph = generated_application.resolve_reviewed_graph(
        layout_root,
        {(name, version): root / "Cargo.toml" for name, root in layout_roots.items()},
        check_environment,
    )
    if layout_graph != graph:
        raise RcError("repository-layout graph differs from the isolated packaged graph")
    _, observed_test_inputs, non_test_reads = repository_layout_reads(
        layout_manifest, layout_root, check_environment,
    )
    require_packaged_test_inputs(observed_test_inputs, expected_test_inputs, non_test_reads)
    run(["cargo", "+1.97.1", "build", "--locked", "--offline", "-p", "zeno-fcis-cli",
         "--bin", "zeno-fcis"], environment=check_environment, cwd=verification_root)
    executable = verification_root / "target" / "debug" / ("zeno-fcis.exe" if os.name == "nt" else "zeno-fcis")
    application_root = verification_root / "generated-application"
    application_root.mkdir()
    app = application_root / "counter"
    run([str(executable), "new", str(app), "--template", "durable-counter"],
        environment=check_environment, cwd=application_root)
    application = generated_application.exercise_application(
        app, application_root, package_roots, version, check_environment, [str(executable)],
    )
    prepared_root = verification_root / "prepared-application"
    prepared_root.mkdir()
    prepared_app = prepared_root / "counter"
    run([str(executable), "new", str(prepared_app), "--template", "prepared-counter"],
        environment=check_environment, cwd=prepared_root)
    prepared_application = generated_application.exercise_prepared_application(
        prepared_app, prepared_root, package_roots, version, check_environment, [str(executable)],
    )
    examples = {}
    for template in generated_application.EXAMPLE_TEMPLATES:
        example_root = verification_root / f"{template}-application"
        example_root.mkdir()
        example_app = example_root / "app"
        run([str(executable), "new", str(example_app), "--template", template],
            environment=check_environment, cwd=example_root)
        examples[template] = generated_application.exercise_example_application(
            template, example_app, example_root, package_roots, version, check_environment,
            [str(executable)],
        )
    v1_consumer = generated_application.exercise_v1_consumer(
        verification_root, package_roots, version, check_environment,
    )
    compiler = run(["rustc", "+1.97.1", "-vV"], capture=True)
    if (packaged_checker_inputs() != inputs or git_text("rev-parse", "HEAD") != commit
            or (not git_text("status", "--porcelain", "--untracked-files=all")) != clean):
        raise RcError("checker inputs or source status changed during packaged verification")
    result = {
        "format": "zeno-fcis/packaged-application/1", "status": "passed",
        "source_commit": commit, "checker_source_clean": clean, "checker_inputs": inputs,
        "version": version, "compiler": compiler,
        "compiler_flags": compiler_flag_evidence(check_environment, verification_root, "<verification-root>"),
        "archives": package_evidence, "packaged_workspace_graph": graph,
        "consumer_build": {
            "layout": "sources/<crate>-<version>/, archives only",
            "command": ["cargo", "+1.97.1", "build", "--manifest-path", "<isolated-workspace>/Cargo.toml",
                        *CONSUMER_TARGET_ARGUMENTS, "--locked", "--offline", "--jobs", "1"],
        },
        "packaged_tests": {
            "layout": "crates/<crate>/ from the same archives, plus the listed verification files",
            "command": ["cargo", "+1.97.1", "test", "--manifest-path", "<repository-layout>/Cargo.toml",
                        *PACKAGED_TEST_ARGUMENTS, "--locked", "--offline", "--no-run", "--jobs", "1"],
            "test_inputs_manifest_sha256": sha256(PACKAGED_TEST_INPUTS_PATH),
            "cross_package_inputs": observed_test_inputs,
            "repository_inputs": repository_inputs,
            "standalone_tests": False,
        },
        "generator": {"package": "zeno-fcis-cli", "target": "zeno-fcis", "sha256": sha256(executable),
                      "command": ["<packaged-cli>", "new", "<new-application>", "--template", "durable-counter"]},
        "internal_manifests": [{"name": name, "version": version,
                                "path": (root / "Cargo.toml").relative_to(verification_root).as_posix()}
                               for name, root in sorted(package_roots.items())],
        "application": application,
        "prepared_application": prepared_application,
        "example_applications": examples,
        "v1_consumer": v1_consumer,
        "nonclaims": ["not a registry-only installation check", "not fresh external dependency resolution",
                      "packaged tests are not standalone: they compile only in the repository layout "
                      "with the listed verification files; the whole-repository source archive runs every test",
                      "not an independent review",
                      "not production deployment qualification", "not release authorization"],
    }
    return result


def verify_packaged(packages: Path, output: Path, version: str) -> None:
    output.mkdir(parents=True)
    target = output / ".cargo-target"
    try:
        result = verify_packaged_workspace(packages, version, target, dict(os.environ))
        write_json(output / "PACKAGED-APPLICATION.json", result)
        target.rmdir()
    except BaseException:
        # The exclusive mkdir above establishes ownership before cleanup.
        shutil.rmtree(output)
        raise
    print(f"rc-package: packaged application PASS; receipt: {output / 'PACKAGED-APPLICATION.json'}")


def build(output: Path) -> None:
    configured, _ = validate_package_set()
    version = require_string(configured, "version")
    commit = require_clean_commit()
    run([sys.executable, "tools/check_release_privacy.py", "check"])
    if output.exists() and any(output.iterdir()):
        raise RcError("output directory must not exist or must be empty")
    output.mkdir(parents=True, exist_ok=True)
    packages_dir = output / "packages"
    binaries_dir = output / "binaries"
    docs_dir = output / "docs"
    source_dir = output / "source"
    for directory in (packages_dir, binaries_dir, docs_dir, source_dir):
        directory.mkdir()
    build_target = output / ".cargo-target"
    build_environment = remapped_compiler_environment(
        dict(os.environ), ROOT, "/zeno-fcis-source",
    )
    build_environment["CARGO_TARGET_DIR"] = str(build_target)

    run(
        ["cargo", "+1.97.1", "fetch", "--locked"],
        environment=build_environment,
    )

    source_manifest_text = run(
        ["python3", "tools/release_manifest.py", "--require-clean"], capture=True
    )
    if not isinstance(source_manifest_text, str):
        raise RcError("source manifest returned binary data")
    source_manifest = output / "SOURCE-MANIFEST.json"
    source_manifest.write_text(source_manifest_text, encoding="utf-8")

    package_arguments = [
        "cargo",
        "+1.97.1",
        "package",
        "--workspace",
        "--locked",
        "--no-verify",
    ]
    for private_name in require_string_list(configured, "private_packages"):
        package_arguments.extend(["--exclude", private_name])
    run(package_arguments, environment=build_environment)
    for name in require_string_list(configured, "publish_order"):
        archive = build_target / "package" / f"{name}-{version}.crate"
        if not archive.is_file():
            raise RcError(f"cargo did not create {archive.name}")
        shutil.copyfile(archive, packages_dir / archive.name)
    packaged_application = verify_packaged_workspace(packages_dir, version, build_target, build_environment)
    write_json(output / "PACKAGED-APPLICATION.json", packaged_application)

    rustdoc_environment = remapped_compiler_environment(
        build_environment, build_target, "/zeno-fcis-target",
    )
    rustdoc_arguments = [
        "cargo",
        "+1.97.1",
        "doc",
        "--workspace",
        "--all-features",
        "--locked",
        "--no-deps",
        "--jobs",
        "1",
    ]
    for private_name in require_string_list(configured, "private_packages"):
        rustdoc_arguments.extend(["--exclude", private_name])
    run(rustdoc_arguments, environment=rustdoc_environment)
    if (build_target / "doc" / "zeno_fcis_generated_code_tests").exists():
        raise RcError("private generated-code test crate leaked into public rustdoc")
    normalize_rustdoc_tree(build_target / "doc")
    deterministic_tree_archive(
        build_target / "doc",
        docs_dir / f"zeno-fcis-rustdoc-{version}.tar.gz",
        f"zeno-fcis-rustdoc-{version}",
    )

    verbose_version = run(["rustc", "+1.97.1", "-vV"], capture=True)
    if not isinstance(verbose_version, str):
        raise RcError("rustc version output is binary")
    host_lines = [
        line.removeprefix("host: ")
        for line in verbose_version.splitlines()
        if line.startswith("host: ")
    ]
    if len(host_lines) != 1:
        raise RcError("rustc host target is unavailable")
    host = host_lines[0]
    host_targets = {host}
    binary_inventory = binary_artifact_inventory(configured, version, host)
    for item in binary_inventory:
        package_name = item["package"]
        target_name = item["target"]
        run(
            [
                "cargo",
                "+1.97.1",
                "build",
                "--release",
                "--locked",
                "-p",
                package_name,
                "--bin",
                target_name,
            ],
            environment=build_environment,
        )
        executable_name = f"{target_name}.exe" if os.name == "nt" else target_name
        executable = build_target / "release" / executable_name
        if not executable.is_file():
            raise RcError(f"release binary {executable_name} is missing")
        deterministic_binary_archive(
            executable,
            binaries_dir / item["archive"],
            item["prefix"],
        )
    actual_binary_archives = sorted(path.name for path in binaries_dir.iterdir())
    expected_binary_archives = sorted(item["archive"] for item in binary_inventory)
    if actual_binary_archives != expected_binary_archives:
        raise RcError(
            "assembled binary archive set differs from the declared inventory"
        )
    shutil.rmtree(build_target)

    source_archive(
        source_dir / f"zeno-fcis-{version}-source.tar.gz",
        f"zeno-fcis-{version}",
    )

    complete_metadata = cargo_metadata(complete=True)
    sbom_path = output / "SBOM.cdx.json"
    write_json(sbom_path, build_sbom(complete_metadata, commit, version))
    if require_clean_commit() != commit:
        raise RcError("source commit changed during release assembly")

    provenance_inputs = {
        "format": "zeno-fcis/provenance-inputs/1",
        "version": version,
        "source_commit": commit,
        "rust_toolchain": "1.97.1",
        "host_targets": sorted(host_targets),
        "source_manifest_sha256": sha256(source_manifest),
        "packaged_test_inputs_sha256": sha256(PACKAGED_TEST_INPUTS_PATH),
        "sbom_sha256": sha256(sbom_path),
        "compiler_flags": {
            "native": compiler_flag_evidence(build_environment, ROOT, "<source>"),
            "packaged_application": packaged_application["compiler_flags"],
            "rustdoc": compiler_flag_evidence(rustdoc_environment, build_target, "<target>"),
        },
        "commands": [
            "cargo +1.97.1 fetch --locked",
            " ".join(package_arguments),
            "cargo +1.97.1 metadata --manifest-path <isolated-workspace and repository-layout>/Cargo.toml --offline --format-version 1 (seeded and checked against the reviewed lock)",
            "cargo +1.97.1 build --manifest-path <isolated-workspace>/Cargo.toml --workspace --lib --bins --examples --all-features --locked --offline --jobs 1 (sources/<crate>-<version>/, archives only)",
            "cargo +1.97.1 test --manifest-path <repository-layout>/Cargo.toml --workspace --all-targets --all-features --locked --offline --no-run --jobs 1 (crates/<crate>/ plus the verification files in release/packaged-test-inputs.json; every cross-package read must equal that manifest)",
            "cargo +1.97.1 build --manifest-path <isolated-workspace>/Cargo.toml --locked --offline -p zeno-fcis-cli --bin zeno-fcis",
            "<packaged-cli> new <new-application> --template durable-counter",
            "generated application: archive-only internal sources, reviewed external lock, formatting, Clippy, tests and durable demonstration; see PACKAGED-APPLICATION.json",
            *[item["command"] for item in binary_inventory],
            " ".join(rustdoc_arguments),
        ],
        "nonclaim": "inputs for a future signed attestation; not a signature or SLSA provenance",
    }
    write_json(output / "PROVENANCE-INPUTS.json", provenance_inputs)

    manifest_path = output / "RC-MANIFEST.json"
    checksums_path = output / "SHA256SUMS"
    bundle_path = output / f"zeno-fcis-{version}-rc-bundle.zip"
    entries = artifact_entries(output, {manifest_path, checksums_path, bundle_path})
    write_json(
        manifest_path,
        {
            "format": "zeno-fcis/release-candidate-manifest/1",
            "version": version,
            "source_commit": commit,
            "rust_toolchain": "1.97.1",
            "artifacts": entries,
            "nonclaims": [
                "not a production deployment authorization",
                "not an independent audit",
                "not a signature or SLSA attestation",
            ],
        },
    )
    checksum_files = [
        path
        for path in sorted(item for item in output.rglob("*") if item.is_file())
        if path not in {checksums_path, bundle_path}
    ]
    checksums_path.write_text(
        "".join(
            f"{sha256(path)}  {path.relative_to(output).as_posix()}\n"
            for path in checksum_files
        ),
        encoding="utf-8",
    )
    deterministic_bundle(output, bundle_path)
    run([sys.executable, "tools/check_release_privacy.py", "check", str(output)])
    print(
        f"rc-package: built {len(require_string_list(configured, 'publish_order'))} "
        f"crate packages and {len(entries)} retained artifacts at {commit}"
    )


def main() -> int:
    args = parse_args()
    try:
        configured, _ = validate_package_set()
        if args.command == "check":
            run([sys.executable, "tools/check_release_privacy.py", "check"])
            print(
                "rc-package: PASS "
                f"({len(require_string_list(configured, 'publish_order'))} public, "
                f"{len(require_string_list(configured, 'private_packages'))} private, "
                f"version {require_string(configured, 'version')})"
            )
        elif args.command == "self-test":
            run([sys.executable, "tools/test_release_privacy.py"])
            run_self_test(configured, cargo_metadata(complete=False))
            run_rustdoc_normalization_self_test()
            run_packaged_layout_self_test()
            run_tree_archive_mode_self_test()
            run_binary_inventory_self_test(configured)
            print(
                "rc-package: self-test PASS "
                "(12 hostile mutations rejected; 4 packaged layout controls refused; "
                "rustdoc, archive modes, and binary inventory verified)"
            )
        elif args.command == "verify-packaged":
            verify_packaged(args.packages.resolve(), args.output.resolve(), require_string(configured, "version"))
        else:
            build(args.output.resolve())
        return 0
    except (
        RcError,
        RuntimeError,
        OSError,
        subprocess.CalledProcessError,
        json.JSONDecodeError,
        tomllib.TOMLDecodeError,
        tarfile.TarError,
    ) as error:
        print(f"rc-package: FAIL: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
